[WIP] - feat: added manage tokens table
JoinColony/colonyCDapp pull request #1041
Opened 2023-09-05 12:19 UTC by CzarekDryl

https://tw.auroracreation.com/app/tasks/15536337

![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/2cb59a6d-fbb9-4297-96d2-00287c70892d)

2023-09-22 11:03 UTC, krawczykkatarzyna commented on src/components/v5/shared/SearchSelect/partials/SearchInput/SearchInput.tsx
>          className={styles.input}
please add styles here and remove './SearchInput.module.css' file

2023-09-22 11:03 UTC, krawczykkatarzyna commented on src/components/v5/shared/SearchSelect/partials/SearchItem/SearchItem.tsx
> +import TokenIcon from '~shared/TokenIcon/TokenIcon';
'~shared/TokenIcon';

2023-09-22 12:19 UTC, TomaszChmielPagepro commented on src/components/v5/common/ActionSidebar/partials/TokenSelect/TokenSelect.tsx
> +  };
Can you move this to hook?

2023-09-22 12:20 UTC, TomaszChmielPagepro commented on src/components/v5/common/ActionSidebar/partials/TokenSelect/TokenSelect.tsx
> +      if (!field.value) {
This would not be valid behavior because if the field value is set token should be rendered (line 73)

2023-09-22 12:23 UTC, TomaszChmielPagepro commented on src/components/v5/common/ActionSidebar/partials/TokensTable/hooks.tsx
> +      const shouldShow = shouldShowMenu(data[index]);
Some of the row's cannot be removed (the initial one which are colony tokens)

2023-09-22 13:26 UTC, CzarekDryl commented on src/components/v5/common/ActionSidebar/partials/TokenSelect/partials/TokenStatus/TokenStatus.tsx
> +
Added

2023-09-25 06:58 UTC, CzarekDryl commented on src/components/v5/common/ActionSidebar/partials/TokenSelect/TokenSelect.tsx
> +  const renderButtonContent = () => {
I will have to pass like 5-6 props to this component, I don't know if it's worth

2023-09-25 07:49 UTC, CzarekDryl commented on src/components/v5/common/ActionSidebar/partials/TokenSelect/TokenSelect.tsx
> +  const renderButtonContent = () => {
All logic moved to hook

2023-09-25 07:56 UTC, krawczykkatarzyna approved these changes

2023-09-25 08:01 UTC, joanna-pagepro requested changes

2023-09-25 08:01 UTC, joanna-pagepro commented on src/components/v5/shared/SearchSelect/partials/SearchInput/SearchInput.tsx
>        <input
Can you use `InputBase` here?

2023-09-25 08:01 UTC, joanna-pagepro commented on src/components/v5/shared/SearchSelect/partials/SearchInput/SearchInput.tsx
>          placeholder={formatMessage({ id: 'placeholder.search' })}
formatText

2023-09-25 08:06 UTC, CzarekDryl commented on src/components/v5/common/ActionSidebar/partials/TokensTable/TokensTable.tsx
> +        className="mt-6"
Then it's moving button from form - 
![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/3bd5bb86-e5aa-4ee1-be6f-07dee55e97eb)

2023-09-25 08:12 UTC, CzarekDryl commented on src/components/v5/common/ActionSidebar/partials/TokensTable/TokensTable.tsx
> +      {!!data.length && (
If there is no data then we are not showing table, after clicking it is shown immediately

2023-09-25 08:21 UTC, CzarekDryl commented on src/components/v5/common/ActionSidebar/partials/TokenSelect/hooks.tsx
> +      ) || (
I've fixed this, but for now we don't have possibility to show error state. I will have to talk with Will about this later.

2023-09-25 08:25 UTC, joanna-pagepro commented on src/components/v5/common/ActionSidebar/partials/TokensTable/TokensTable.tsx
> +      {!!data.length && (
If you're able to open it after the transaction is done, then I guess that you will have to fetch the data and a loader would be something nice to have

2023-09-25 09:19 UTC, merged