Fix/15567450
JoinColony/colonyCDapp pull request #1109
Opened 2023-09-27 11:42 UTC by krawczykkatarzyna

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2023-09-27 11:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1109) before we can accept your contribution.<br/><hr/>**krawczykkatarzyna** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1109) it.</sub>

2023-09-27 11:45 UTC, CzarekDryl commented on src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx
> +        'border border-solid rounded-lg flex justify-between min-h-[2.75rem] flex-col md:flex-row md:items-center',
Is `border-solid` class needed?

2023-09-27 11:48 UTC, joanna-pagepro requested changes

2023-09-27 11:48 UTC, joanna-pagepro commented on src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx
> +        [&_button]:hover:no-underline mt-2 md:mt-0 text-4`,
Please add hover on desktop only. You can also add those styles directly to buttons and anchors. Please add className prop if it's missing

2023-09-27 11:48 UTC, joanna-pagepro commented on src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx
> +              'ml-0 md:ml-0 md:self-center': isAlt,
margin classes are not needed here

2023-09-27 11:48 UTC, joanna-pagepro commented on src/components/v5/common/ActionSidebar/partials/DefaultField/DefaultField.tsx
> +          className={clsx('text-xs shrink-0 ml-auto absolute right-0 top-5', {
You should also add a padding to the input, so that the value and this counter won't overlap

2023-09-27 13:44 UTC, CzarekDryl commented on src/components/common/Extensions/NotificationBanner/NotificationBanner.tsx
> +                    })}
`underline md:hover:no-underline`, same under

2023-09-28 07:48 UTC, CzarekDryl approved these changes

2023-09-28 07:50 UTC, merged