prepare modal
JoinColony/colonyCDapp pull request #1181
Opened 2023-10-16 18:09 UTC by krawczykkatarzyna

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2023-10-16 18:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1181) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1181) before we can accept your contribution.<br/><hr/>**krawczykkatarzyna** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1181) it.</sub>

2023-10-20 10:12 UTC, joanna-pagepro requested changes

2023-10-20 10:12 UTC, joanna-pagepro commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable.tsx
> +  } = useActionSidebarContext();
Why are you using sidebar context here?

2023-10-20 10:12 UTC, joanna-pagepro commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable.tsx
> +        <div className="flex sm:flex-row flex-col gap-4 sm:gap-2" />
I guess that this div is redundant here

2023-10-20 10:12 UTC, joanna-pagepro commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable.tsx
> +        <span className="flex text-1">
Please use other HTML tag here

2023-10-20 10:12 UTC, joanna-pagepro commented on src/components/v5/shared/CopyWallet/CopyWallet.tsx
> +const CopyWallet: FC<CopyWalletProps> = ({
Please make this component reusable - don't use `walletAddress` here, just pass the value later, when you will be using it. Please also add it to storybook

2023-10-20 10:12 UTC, joanna-pagepro commented on src/components/v5/shared/CopyWallet/CopyWallet.tsx
> +          {formatText({ id: 'copy.addressCopied' })}
Please add props to set the texts

2023-10-20 10:12 UTC, joanna-pagepro commented on src/components/v5/shared/CopyWallet/CopyWallet.tsx
> +            'flex items-center transition-all duration-normal text-sm text-gray-600 md:hover:text-blue-400',
Please add `text-gray-600` when button is not disabled

2023-11-06 12:25 UTC, KornelKwiatkowski commented on src/components/v5/shared/CopyWallet/CopyWallet.tsx
> +            'flex items-center transition-all duration-normal text-sm text-gray-600 md:hover:text-blue-400',
remove `text-gray-600` from default classes

2023-11-07 13:01 UTC, KornelKwiatkowski approved these changes

2023-11-10 11:20 UTC, melyndav requested changes
Hi @krawczykkatarzyna. Thanks for your work on this PR.

There are some UI fixes that are required.

1. The icon in the top left isn't the correct size as per Figma:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/f7d50c75-b597-4d73-b467-7cc1b0d0b601)


2. Size of the wallet icon next to the address is not centre aligned with the text to the right and is also not the correct size. Figma: 

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/7070ed18-ef75-4757-a301-ccc1d6dca05c)


3. The button has issues:

- not the correct Primary CTA button and has the wrong padding and text size
- Border colour is wrong 

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/be8b5ec7-139c-4584-a8e2-b0b61d11fdda)

4. When I cope the address the text size change, I think this is due to issue #3 above.

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/297e8d7b-d434-451b-a158-56669c1195b5)


5. I don't see the add funds from wallet input and section?

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/5c72c268-60ad-4e96-90c6-1aee4c13f13a)

2023-11-21 09:02 UTC, krawczykkatarzyna commented
@melyndav 
1.  Can you check it again? From what I see size of the icon is the sam as on Figma design.
<img width="1218" alt="Screen Shot 2023-11-20 at 22 45 05" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/59cbdf03-2347-4bc5-944e-ee5b22a10676">
<img width="1206" alt="Screen Shot 2023-11-20 at 22 45 16" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/8a26720e-9896-415d-97d9-660af674a61b">
<img width="346" alt="Screen Shot 2023-11-20 at 22 45 50" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/42a66fb0-3212-427c-a05c-bc0345414b37">
<img width="258" alt="Screen Shot 2023-11-20 at 22 45 56" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/fc280de5-b1ef-4b83-939c-0f25c8d67735">

Other issues fixed.

6. As I spoke with @arrenv today he mentioned that API to create "add funds to wallet" is not ready yet  so we have to hide this section for now.

2023-11-21 09:16 UTC, KornelKwiatkowski submitted a review, later dismissed

2023-11-21 09:40 UTC, melyndav requested changes
Hey @krawczykkatarzyna appreciate the updates. Everything looks good.

Can I request the title 'send funds to the colony' here just above the grey wallet & button be removed? Thank you!

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/26c75e45-b3f3-4148-b7c2-1c2eeb29a3bf)

2023-11-21 10:23 UTC, krawczykkatarzyna commented
@melyndav title removed

2023-11-21 10:34 UTC, KornelKwiatkowski approved these changes

2023-11-21 10:47 UTC, joanna-pagepro approved these changes

2023-11-21 11:30 UTC, melyndav approved these changes
I appreciate that update @krawczykkatarzyna. Thank you!

2023-11-21 11:32 UTC, arrenv approved these changes
Looks good to me, thank you!

2023-11-21 12:05 UTC, merged