Feat/15631447 balance page handling table actions
JoinColony/colonyCDapp pull request #1193
Opened 2023-10-20 09:33 UTC by krawczykkatarzyna

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2023-10-20 09:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1193) before we can accept your contribution.<br/><hr/>**krawczykkatarzyna** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1193) it.</sub>

2023-11-10 12:49 UTC, melyndav requested changes
Hi @krawczykkatarzyna. Nice start on this. There are a few issues that require addressing:

1. Hover states are missing. The text should change on hover.
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/96a6e157-9503-4070-b940-28f50363f617)

2. Icon sizes are in-consistent as you can see in this menu item it is much larger;
<img width="186" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/98c717ca-4a8a-419f-b888-b7f7e923445b">

3. When I select 'view on EthScan' it triggers metamask wallet. 
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/6bac58c5-525d-410a-8d29-b5b9c9b7f165)

Example of it being used currently:

![Animation123](https://github.com/JoinColony/colonyCDapp/assets/82127904/c6480347-aa36-4409-b6e1-ba57aab318c6)

Here is where the code is: 
src/components/shared/TokenInfoPopover/TokenInfo.tsx
L87

2023-11-21 16:30 UTC, jakubcolony requested changes

2023-11-21 16:30 UTC, jakubcolony commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +    if (!selectedToken) return;
This return should be wrapped in curly brackets {} as per
https://github.com/JoinColony/ColonyFrontEndLivingStandard/blob/master/codeQuality/index.md#explicitly-scoping-if-statements

2023-11-21 16:30 UTC, jakubcolony commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Please provide an explanation comment as to why this rule got disabled

2023-11-21 16:30 UTC, jakubcolony commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +            key: 'transfer_fundss',
typo

2023-11-21 16:30 UTC, jakubcolony commented on src/context/TokenContext.tsx
> +import React, {
The only purpose of this context is to pass the selected token address to the new action form, right? If so, can that not be achieved using existing `dispatchGlobalEvent` solution, similarly to how we set the action type? It's one less moving part to worry about

2023-11-22 18:22 UTC, rdig requested changes
![Screenshot from 2023-11-22 20-18-37](https://github.com/JoinColony/colonyCDapp/assets/1193222/efec962b-90d7-41b9-aac8-0cf1e75a4fb7)

In the case of a native token that is `mintable` (see Colony model), the "Add funds" entry should be the same as "Mint Tokens" as that's the most obvious way to add them.

Even more, if the token is also `locked`, that's the **only** way add tokens

- As Mel remarked, clicking "View on <BlockExplorer>" actually triggers the action to import a custom asset into Metamask, which is not correct
![Screenshot from 2023-11-22 20-18-54](https://github.com/JoinColony/colonyCDapp/assets/1193222/f2274930-44da-43a3-a2fd-105adf591322)

2023-12-11 14:02 UTC, krawczykkatarzyna commented
@arrenv @rdig @ArmandoGraterol  reported issues fixed

2023-12-13 10:53 UTC, bassgeta requested changes

2023-12-13 10:53 UTC, bassgeta commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +  data,
could we somehow type these params?

2023-12-13 10:53 UTC, bassgeta commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +export const useBalanceTable = () => {
is this gonna be used in the future, why is it unused?

2023-12-13 10:53 UTC, bassgeta commented on src/components/frame/v5/pages/BalancePage/partials/TokenAvatar/TokenAvatar.tsx
> +          <Tooltip
sadly this will conflict with [this PR](https://github.com/JoinColony/colonyCDapp/pull/1538), we need to keep in mind to use phosphor icons

2023-12-13 10:53 UTC, bassgeta commented on src/components/frame/v5/pages/BalancePage/types.ts
> +export interface TransferFundsProps {
this is unused

2023-12-13 10:53 UTC, bassgeta commented on src/i18n/en.json
> +    "balancePage.burger.label.addFunds": "Add funds",
I know it's an older PR, if you have the time, could you please take these strings into the component where they're being rendered? as per our [standards](https://github.com/JoinColony/ColonyFrontEndLivingStandard/blob/master/codeQuality/index.md#i18n)

2023-12-13 11:47 UTC, krawczykkatarzyna commented
@bassgeta fixed

2023-12-14 09:28 UTC, bassgeta commented
> @bassgeta fixed

Nice one! I'd appreciate if the i18n one gets fixed too, then we're g2g

2023-12-15 09:36 UTC, bassgeta requested changes

2023-12-15 09:57 UTC, krawczykkatarzyna commented on src/components/v5/shared/MeatBallMenu/types.ts
> +  onSelect?: () => void;
@bassgeta  fixed

2023-12-15 10:04 UTC, bassgeta submitted a review, later dismissed

2023-12-15 10:17 UTC, melyndav requested changes
Hey @krawczykkatarzyna thanks for some of the updates. A couple of new issues still remain:

1. Blue hover on the external link. This should be text-gray-900 and not blue.

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/ab91d2cf-ece7-441f-a04b-f5926de14e9c)

 
 2. The 'view on' link above just doesn't go anywhere? URL shows the page I am currently on. 
 
 3. When I select any of the 'transfer funds' options, it should open the 'transfer funds' action panel with THAT token pre-selected.|
 
 Here you can see Gotham Guilder but I open the transfer funds via the dropdown, another token is selected.
 
 
<img width="1277" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ef0ed34e-2307-4401-9916-d8f26f1ab92e">

<img width="404" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2964231c-a0ea-4655-ac19-284175f1febc">

4. Can you reduce the icon in the 'view on' dropdown to be the same size of the others? Currently it looks too big and isn't in proportion with the other icons.

2023-12-15 11:43 UTC, krawczykkatarzyna commented
@melyndav 1,3 issues fixed. 
Regarding point 2:
The link will not work if you try to test it locally, it is implemented in the same way as elsewhere, for example in the dropdown menu on the members page. Under the hood there is functionality that checks the URL to see where you are and redirects you to the right place. It will work when we push this to the production url.

Regarding to point 4:
Every icons have set the same size. The reason why they look different depends on svg files ( these are not phosphor-react icons ). If you'd like to prefer use icons from that library I suggest fix it in separate pull request because we use this dropdown in several places.

<img width="526" alt="Screen Shot 2023-12-15 at 12 28 27" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/be210cff-8b08-4c78-a927-b64c1fd739ec">
<img width="531" alt="Screen Shot 2023-12-15 at 12 28 14" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/1cd005e5-c038-49e3-b5d2-8a206c3349fd">
<img width="518" alt="Screen Shot 2023-12-15 at 12 28 19" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/32fdc37e-16cc-4fb6-a08d-7fb049a4596e">
<img width="537" alt="Screen Shot 2023-12-15 at 12 28 23" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/bb6988c5-6496-4a4e-9bce-e5e0b4af9f01">

2023-12-15 13:35 UTC, melyndav submitted a review, later dismissed
Thanks for your updates on this one @krawczykkatarzyna. Approved.

2023-12-18 11:34 UTC, krawczykkatarzyna commented
@rdig  @ArmandoGraterol @jakubcolony can you check it again please?

2023-12-18 20:35 UTC, jakubcolony requested changes
Thanks for addressing the previous comments, it looks like some things changed in the meantime so it'd be great if you could update the PR as well.

2023-12-18 20:35 UTC, jakubcolony commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +                    toggleActionSidebarOn();
I believe the latest way to do this is to pass the initial values to the `toggleActionSidebarOn` function directly, like here:
<img width="449" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/8232bc30-0c53-47ff-9044-4ae384ea19f6">

2023-12-18 20:35 UTC, jakubcolony commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +              });
It should also be possible to pass the token address directly to `toggleActionSidebarOn`.

2023-12-19 10:16 UTC, jakubcolony requested changes

2023-12-19 10:16 UTC, jakubcolony commented on src/components/v5/common/ActionSidebar/partials/forms/SimplePaymentForm/SimplePaymentForm.tsx
> +  const { selectedTokenAddress } = useSimplePayment(getFormOptions);
As mentioned during our chat in Discord, I don't think it's necessary to pass the token address explicitly, as the `AmountField` can access it directly from the form state.

2023-12-19 10:32 UTC, jakubcolony submitted a review, later dismissed
LGTM 👍

2023-12-19 11:28 UTC, bassgeta submitted a review, later dismissed

2023-12-19 12:13 UTC, rdig commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +  },
This needs to use

2023-12-19 12:26 UTC, rdig requested changes
This is all good, with the exception of the link to the block explorer.

I've left code comments below on how this can be done.

2023-12-19 12:26 UTC, rdig commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +          },
This needs to use the correct name and link for appropriate network the CDapp is deployed to, exactly the same as the members page tooltip uses

https://github.com/JoinColony/colonyCDapp/blob/feat/15631447-balance-page-handling-table-actions/src/components/frame/v5/pages/MembersPage/partials/MembersTabContent/hooks.tsx#L64-L84

2023-12-19 12:26 UTC, rdig commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/hooks.tsx
> +  },
This will no longer be needed, see my comment above

2023-12-19 13:26 UTC, krawczykkatarzyna commented
@rdig @ArmandoGraterol @jakubcolony reported issues have been fixed.

2023-12-19 14:58 UTC, ArmandoGraterol approved these changes
LGTM 👍

2023-12-19 19:40 UTC, rdig approved these changes
All good

2023-12-19 20:44 UTC, jakubcolony approved these changes

2023-12-20 08:51 UTC, merged