Update user registration flow UI
JoinColony/colonyCDapp pull request #1208
Opened 2023-10-24 17:02 UTC by ArmandoGraterol

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #1159

2023-10-26 08:07 UTC, thomassdk requested changes
Good work @ArmandoGraterol :1st_place_medal: left some feedback that is mostly to do with page pro's work but the most salient point is that this needs a rebase onto the latest #1197 which should fix some input problems. I dont think you should need to change anything in those components. All issues should be funnelled back to page pro.

The other thing I noticed is that the component should be centered in the page according to the designs whereas now it is to the left hand side of the document:

![Screenshot from 2023-10-26 10-00-12](https://github.com/JoinColony/colonyCDapp/assets/32598350/a8957ae0-adc7-48fd-886b-6ce00947e9d1)

2023-10-26 08:07 UTC, thomassdk commented on src/components/v5/common/Fields/Input/partials/CharacterNumbers.tsx
Same comment as above

2023-10-26 17:53 UTC, ArmandoGraterol commented on src/components/v5/common/CreateUserForm/CreateUserFormHeader.tsx
> This looks like a duplicate of the `HeaderRow` component in `src/components/v5/common/CreateColonyWizard/shared.tsx` it would probably be best to extract that to somewhere common and reuse it in both wizards

Good one!



> Also it seems the new setup for react-intl is to stick everything in `en.json`

Why? Is that something PagePro decided? The `en.json` file is for messages that are globally used, not for messages that are used in only 1 place.

2023-10-26 17:55 UTC, ArmandoGraterol commented on src/images/icons/colony-icon.svg
Yes, it's not used anywhere in the CDapp, not even in the Dapp which is the "older" version.

2023-10-26 17:58 UTC, ArmandoGraterol commented on src/routes/UserRegistrationRoute/CreateYourColonySidebar.tsx
> +});
That may be the case, as my understanding is that we don't use `en.json` like that. It's for more reusable messages that are used across different places in the CDapp/Dapp.

2023-10-27 09:21 UTC, chmanie commented on src/routes/UserRegistrationRoute/CreateYourColonySidebar.tsx
> +          {/* @TODO: Add logic to change height and color of the line, dots, and text depending on the current step */}
@ArmandoGraterol, please reach out to me regarding this as it'll be a bit fiddly (the sidebar is in a different context and doesn't really know about the steps).

2023-10-30 20:24 UTC, ArmandoGraterol commented
@thomassdk @chmanie just uploaded an approach to the sidebar logic question. The display should be working as expected when traversing between the flows (user and colony creation)

2023-10-31 11:22 UTC, thomassdk submitted a review, later dismissed
Really good work Armando looks good to me.

The only thing that is missing is that the colony logo in the sidebar should be clickable and redirect the user to the landing page

2023-10-31 13:31 UTC, ArmandoGraterol commented
> The only thing that is missing is that the colony logo in the sidebar should be clickable and redirect the user to the landing page

Are we sure about this? I left it like that because of this comment on Figma:
![FireShot Capture 183 - Colony V5 – Figma - www figma com](https://github.com/JoinColony/colonyCDapp/assets/18473896/58babde7-c1ab-423e-ac01-510d50fadc54)

2023-10-31 14:06 UTC, chmanie requested changes
Really nice work! I have a few comments to make things a little more consistent and - to some extend - generic.

2023-10-31 14:06 UTC, chmanie commented on src/routes/UserRegistrationRoute/CreateYourColonySidebar.tsx
Great work with the sidebar! I have some suggestions though:

1) I'd prefer the sidebar content to be dynamic. That means you can pass it an array of `MessageDescriptor`s and it will create the sidebar for a wizard with these steps. That means you can define the steps in a separate file and this layout becomes reusable.
2) Once that is done, I would rename this to something like `WizardSidebar`.

2023-10-31 14:06 UTC, chmanie commented on src/routes/UserRegistrationRoute/CreateYourColonyLayout.tsx
I think this should be renamed to something like `WizardLayout` and re-use the `MainLayout` component (like `ColonyLayout` does already.

2023-10-31 14:06 UTC, chmanie commented on src/routes/UserRegistrationRoute/UserRegistrationRoute.tsx
To be consistent, I think this should be called `Wizard(s)Route` then.

2023-10-31 14:57 UTC, thomassdk commented
> > The only thing that is missing is that the colony logo in the sidebar should be clickable and redirect the user to the landing page
> 
> Are we sure about this? I left it like that because of this comment on Figma: ![FireShot Capture 183 - Colony V5 – Figma - www figma com](https://user-images.githubusercontent.com/18473896/279391125-58babde7-c1ab-423e-ac01-510d50fadc54.png)

hmmm this contradicts something that Arren told me yesterday. @arrenv can you clear this up?

2023-10-31 15:53 UTC, arrenv commented
> hmmm this contradicts something that Arren told me yesterday. @arrenv can you clear this up?

Yes, clicking should go to the app main landing page. I have updated that design annotation with Mel to align.

2023-10-31 19:03 UTC, ArmandoGraterol commented on src/components/shared/Icon/Icon.tsx
> +      )} ${className || ''}`}
Agreed! Otherwise, it's annoying to customize the default styles when we need to

2023-10-31 19:21 UTC, ArmandoGraterol commented on src/routes/UserRegistrationRoute/CreateYourColonyLayout.tsx
I didn't use `MainLayout` because the styles used by it are not the ones in the specs, do you think the reusability is worth it?

2023-11-01 08:55 UTC, chmanie commented on src/routes/UserRegistrationRoute/CreateYourColonyLayout.tsx
You mean because of the wider sidebar? We have that one in other places as well, so maybe it's worth it! What I want to avoid is too many layouts hanging around. We are then setting the wrong affordances for other pages down the line. If it becomes "canonical" to just create a new layout for every page we will be left with inconsistencies. I know it doesn't seem justified in this isolated case but there might be more later.

2023-11-01 08:56 UTC, chmanie commented on src/components/shared/Icon/Icon.tsx
> +      )} ${className || ''}`}
In the past we used this by just `extend`ing css classes but that's not possible anymore with tailwind (or at least it's not straightforward), so yeah, this is definitely the right call to make here :)

2023-11-06 16:26 UTC, chmanie requested changes
This is great! I have a little beef with the inconsistencies with the `CreateColonyWizard` but all in all this is very close to done. Good work :)

2023-11-06 16:26 UTC, chmanie commented on src/components/frame/v5/pages/CreateUserPage/CreateUserPage.tsx
> +const CreateUserPage = () => {
Also I don't think we need the `flex` `main` tag at all. Just add a `mx-auto` to the `article`.

2023-11-06 17:59 UTC, ArmandoGraterol commented on src/components/frame/v5/pages/CreateUserPage/CreateUserPage.tsx
> +        <ActionForm
The final step of the colony creation wizard uses `ActionForm` (`StepConfirmAllInput`).

`ActionForm` is just a wrapper around `Form` that is used specifically when the form is going to submit a redux action, in the case of the colony creation wizard, only the final step needs it as that's the one that dispatches the action with the payload, the other `Forms` before that only advance the wizard step on submit.

2023-11-06 18:00 UTC, ArmandoGraterol commented on src/components/frame/v5/pages/CreateUserPage/CreateUserPage.tsx
> +        <ActionForm
In this case, we create the user in 1 single step so no need to use `Form` to advance steps as the colony creation flow does.

2023-11-07 01:28 UTC, chmanie commented
Armando will be adding a redirect to the user profile after user creation and adjust the sidebar a little bit so people can create users as a "standalone" wizard.

2023-11-08 18:58 UTC, chmanie approved these changes
That's what I'm talkin' about. Let's merge this bad boi :)

2023-11-08 20:24 UTC, rdig approved these changes
Nothing stands out. Good to go.

2023-11-08 20:33 UTC, merged