Updates to calamity banner design
JoinColony/colonyCDapp pull request #1265
Opened 2023-11-07 14:50 UTC by arrenv

## Description

This small PR adds styling updates to the Calamity banner in order to better align it with the design updates and to resolve padding issues.

To test, you will need to force the banner to appear, testing both the `info` and `error` mode.

Resolves #1264

2023-11-07 14:58 UTC, melyndav approved these changes

2023-11-09 09:15 UTC, bassgeta requested changes
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/373ec4ed-ea52-450b-95df-838554ad96f0)
Looks good but the order of `Learn more` and `Upgrade` is switched around on this branch, do we change it in Figma or here?

2023-11-09 10:03 UTC, bassgeta requested changes
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/87fb213b-b89e-447f-b105-38dd3f83e1a0)
Same order issue with the error banner

2023-11-09 14:20 UTC, melyndav commented
@bassgeta all good, we've updated Figma, so it's correct. Nice pick up.

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/025a44df-a1a8-472c-aed7-35e5591603d7)

2023-11-09 14:21 UTC, bassgeta commented
> @bassgeta all good, we've updated Figma, so it's correct so this PR should be good now.
> 
> ![image](https://user-images.githubusercontent.com/82127904/281761369-025a44df-a1a8-472c-aed7-35e5591603d7.png)

good stuff :+1:

2023-11-09 14:22 UTC, bassgeta approved these changes

2023-11-09 15:36 UTC, merged