Fix[15639563]: members dropdown menu issues
JoinColony/colonyCDapp pull request #1272
Opened 2023-11-08 11:48 UTC by KornelKwiatkowski

## Description

Task: https://tw.auroracreation.com/app/tasks/15639563

- Fixed issues with members dropdown menu

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/6e4b7139-be06-4d49-8271-09a5d0c9f1c7)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/baccc9b6-9460-4b64-9bb8-9749b553812f)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/be4bb9d6-9b2f-4d02-8439-9e32a826f84b)

2023-11-08 12:44 UTC, melyndav requested changes
Hi @KornelKwiatkowski 

I made an error with the ticket in Team Work. When the user selects the search input, the text colour should stay as the text-gray-400 which is the placeholder text colour and not change to the text-gray-900 until the user starts typing.

My apologises for the mistake and the extra work. I will update the Team Work ticket.

2023-11-08 13:04 UTC, rdig requested changes
- **Please do a rebase pull, not a merge pull!**
![Screenshot from 2023-11-08 14-59-31](https://github.com/JoinColony/colonyCDapp/assets/1193222/d2c20e7e-70b6-463b-ac17-b1513fb73258)

- List shows incorrect avatars for users
![Screenshot from 2023-11-08 14-26-02](https://github.com/JoinColony/colonyCDapp/assets/1193222/b35c8963-4b1f-4882-a568-482bd8a11287)

- Bottom list padding is wrong
![Screenshot from 2023-11-08 14-26-22](https://github.com/JoinColony/colonyCDapp/assets/1193222/fdbf8c60-b445-4dc6-aec9-2a0d8db95f3b)

- Avatar is misaligned with the username
![Screenshot from 2023-11-08 14-26-25](https://github.com/JoinColony/colonyCDapp/assets/1193222/05d2ff59-8760-4bb7-8cfc-a9b3bda61be3)

- Left list padding is wrong
![Screenshot from 2023-11-08 14-26-30](https://github.com/JoinColony/colonyCDapp/assets/1193222/3022f216-6b40-4901-b8b8-b09db7d06f0c)

- Placeholder text grammar is incorrect (enter vs. add)
![Screenshot from 2023-11-08 14-26-58](https://github.com/JoinColony/colonyCDapp/assets/1193222/750f711f-553c-4c76-92a9-ed8630799b6f)

- Input focus state changes the color of the placeholder text, which is incorrect
![Screenshot from 2023-11-08 14-30-49](https://github.com/JoinColony/colonyCDapp/assets/1193222/6c84befb-d01b-477a-8fea-d8e147971644)

- Entering a non-existent username will show them in the list and allow you to click it
![Screenshot from 2023-11-08 14-32-13](https://github.com/JoinColony/colonyCDapp/assets/1193222/e99a9360-79ac-4634-afdd-218efa481975)

2023-11-08 13:36 UTC, KornelKwiatkowski commented
"Please do a rebase pull, not a merge pull!"
@rdig My apologies, I read your comment in another PR after making this one.

2023-11-08 13:46 UTC, KornelKwiatkowski commented
Thanks for the feedback @rdig. I appreciated this. I see all these issues, but they are out of scope of the task.
Please, check the link from Teamwork: https://tw.auroracreation.com/app/tasks/15639563

@melyndav I changed the placeholder color.

2023-11-08 14:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1272) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1272) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1272) it.</sub>

2023-11-09 14:36 UTC, joanna-pagepro requested changes

2023-11-09 14:36 UTC, joanna-pagepro commented on src/components/v5/common/Fields/InputBase/InputBase.tsx
> +const InputBase = React.forwardRef<HTMLInputElement | null, InputBaseProps>(
I think that `| null` is redundant here

2023-11-09 14:36 UTC, joanna-pagepro commented on src/i18n/en.json
> +}
Please add the missing empty line

2023-11-10 08:54 UTC, KornelKwiatkowski commented on src/components/v5/common/Fields/InputBase/InputBase.tsx
> +const InputBase = React.forwardRef<HTMLInputElement | null, InputBaseProps>(
done

2023-11-10 08:54 UTC, KornelKwiatkowski commented on src/i18n/en.json
> +}
done

2023-11-10 09:07 UTC, krawczykkatarzyna submitted a review, later dismissed

2023-11-10 10:32 UTC, closed without merging