Fix[15629358]: change colors of radio buttons
JoinColony/colonyCDapp pull request #1280
Opened 2023-11-08 15:11 UTC by KornelKwiatkowski

## Description

Task: https://tw.auroracreation.com/app/tasks/15629358

- Changed colors of radio buttons

**Changes** 🏗

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/2d53eb9c-1ca6-4244-9f75-24cac3d0d70a)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/235cfc9e-2d28-4c88-bbc3-0b42fbb2b481)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/73be20f9-d354-4b63-867b-1043db4736e1)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/013447d1-d6d6-43f5-b71b-f9bafb805218)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/fa06149f-4e1a-428b-bf53-06f4ddfb27ff)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/31e1acab-8440-4765-8653-6953e6c55b22)

2023-11-08 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1280) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1280) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1280) it.</sub>

2023-11-09 09:07 UTC, TomaszChmielPagepro submitted a review, later dismissed

2023-11-09 09:08 UTC, CzarekDryl approved these changes

2023-11-09 09:35 UTC, krawczykkatarzyna approved these changes

2023-11-09 11:03 UTC, melyndav requested changes
Hi @KornelKwiatkowski  thanks for your time on this PR.

There's an issue with both buttons when they selected.  There should be no hover on a active state. Both buttons require updating. 

This is the version that needs to be removed: 
<img width="238" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b7a5b570-4ebf-4e9b-bb80-12b036b996cd">

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/f4bb4ed6-ad66-454d-89da-820fc81c82b9)

2023-11-09 12:05 UTC, melyndav approved these changes
Thanks @KornelKwiatkowski for the update! Approved.

2023-11-09 12:07 UTC, arrenv approved these changes
Colors are correct, thank you @KornelKwiatkowski

2023-11-09 12:32 UTC, merged