Fix: forwarding the disabled status for radio buttons
JoinColony/colonyCDapp pull request #1287
Opened 2023-11-09 14:14 UTC by KornelKwiatkowski

## Description

- I noticed that radio buttons aren't disabled when I create a motion, and I don't have enough reputation. It turned out that the 'disabled' state in the component wasn't being passed on. Now it's fixed.

2023-11-09 14:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1287) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1287) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1287) it.</sub>

2023-11-09 14:18 UTC, joanna-pagepro submitted a review, later dismissed

2023-11-09 15:29 UTC, rdig requested changes
I can't get this to work. This is a user without any reputation, yet I am still able to create the motion

![Screenshot from 2023-11-09 17-28-27](https://github.com/JoinColony/colonyCDapp/assets/1193222/6a95e1da-9c59-482c-9dca-17d52b5aec0d)

2023-11-10 08:02 UTC, KornelKwiatkowski commented
@rdig yes, maybe I described it inaccurately. Please check the screen record with issue below:

https://github.com/JoinColony/colonyCDapp/assets/90605528/5065d7dc-f178-4bf1-b86c-8e09504a4eb7

These buttons should be disabled in this case.

2023-11-10 18:51 UTC, ArmandoGraterol approved these changes
LGTM 👍

2023-11-13 11:21 UTC, TomaszChmielPagepro approved these changes

2023-11-15 07:34 UTC, KornelKwiatkowski commented
@rdig could you check it again, please? :)

2023-11-15 11:26 UTC, rdig requested changes
Still doesn't show as disabled for me, even will all my tokens deactivated

![Screenshot from 2023-11-15 13-24-56](https://github.com/JoinColony/colonyCDapp/assets/1193222/fc4db31d-48d3-4d5d-9f91-ecfbaa53c419)

![Screenshot from 2023-11-15 13-25-04](https://github.com/JoinColony/colonyCDapp/assets/1193222/d7fbf24b-b10b-4323-aa29-d028dba3a0ab)

Also, please rebase this branch, as it's quite out of date with the current master.

2023-11-15 13:23 UTC, KornelKwiatkowski commented
Alright, thanks @rdig for the feedback. I will check this case :)

2023-11-15 13:35 UTC, KornelKwiatkowski commented
@rdig I did a rebase and fixed the issue you mentioned above.

2023-11-15 13:43 UTC, TomaszChmielPagepro approved these changes

2023-11-16 15:51 UTC, KornelKwiatkowski commented
Hi @rdig, that's weird. I can't reproduce this issue. My result:

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/cb2422fb-f756-4ded-8af7-38b5221a19da)

Could I do something differently?

2023-11-16 17:24 UTC, ArmandoGraterol approved these changes
Still working for me in the case of not having rep or not having tokens:
![FireShot Capture 229 - Extensions - Colony - - localhost](https://github.com/JoinColony/colonyCDapp/assets/18473896/a510b090-2f18-4e63-9f38-5e85aad4abc5)
![FireShot Capture 230 - Extensions - Colony - - localhost](https://github.com/JoinColony/colonyCDapp/assets/18473896/c5217e47-2312-44eb-a42e-74802c01b089)

2023-11-17 08:32 UTC, KornelKwiatkowski commented
@ArmandoGraterol It works fine for you. Buttons are disabled and this is the expected state

2023-11-17 11:09 UTC, rdig approved these changes
Working now. 

Both with a user with no rep and and no tokens

![Screenshot from 2023-11-17 13-07-00](https://github.com/JoinColony/colonyCDapp/assets/1193222/51296dc9-97f4-425f-b8ff-f769a57f4760)

And both with a user with rep and no active tokens

![Screenshot from 2023-11-17 13-07-50](https://github.com/JoinColony/colonyCDapp/assets/1193222/d2c01e0d-df9b-4c5e-96ea-2d1d328d0f9d)

2023-11-17 11:42 UTC, merged