Feat/15645086 join colony button
JoinColony/colonyCDapp pull request #1300
Opened 2023-11-10 15:04 UTC by CzarekDryl

https://tw.auroracreation.com/app/tasks/15645086

Added join colony button with animation.

2023-11-10 15:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1300) it.</sub>

2023-11-13 11:03 UTC, TomaszChmielPagepro commented on src/components/common/Extensions/UserNavigation/UserNavigation.tsx
> +  const isOnColonyRoute = window.location.pathname.includes('/colony/');
Use `useMatch` instead

2023-11-13 11:42 UTC, rdig requested changes
- Icon is misaligned
![Screenshot from 2023-11-13 13-36-50](https://github.com/JoinColony/colonyCDapp/assets/1193222/2a413d3e-0cbd-429d-8545-3ab66f63434f)

- Join functionality is not triggering correctly, as it needs to fire off the mutation at the start, and run in parallel to the animation, not wait until the animation finishes and then fire it off

- Leaving a colony (unjoin) will bring back the button with the wrong state: text "Joined" (vs. "Join") and the icon being visible

2023-11-13 12:03 UTC, krawczykkatarzyna approved these changes

2023-11-14 09:30 UTC, CzarekDryl commented on src/components/common/Extensions/UserNavigation/UserNavigation.tsx
> +  const isOnColonyRoute = window.location.pathname.includes('/colony/');
`useMatch` used

2023-11-14 09:31 UTC, CzarekDryl commented
@rdig All issue mentioned by you are fixed, please check it once more :)

2023-11-14 13:17 UTC, KornelKwiatkowski approved these changes

2023-11-14 15:22 UTC, rdig requested changes
It's now working (more or less) as expected but has a bit of weird behavior.

- Join a colony
- Leave a colony
- Join a colony again -- triggers an Apollo error

2023-11-14 18:02 UTC, ArmandoGraterol submitted a review, later dismissed
LGTM 👍

2023-11-15 11:31 UTC, CzarekDryl commented
@rdig  it was the same in the old UI, it's only in the case of a new user. I think it's better for someone from your team to check it.

![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/5bfc6842-377f-496c-876e-cefabce92ae2)

2023-11-15 12:19 UTC, rdig commented
>  I think it's better for someone from your team to check it.
?

 I did try it with new users, 3 of them actually.

2023-11-15 12:23 UTC, TomaszChmielPagepro commented
@rdig Didn't just @CzarekDryl say that it only occurs for new users? 😅
This seems to be a problem with the old UI as well and the error suggests that it might be something wrong on the backend side

2023-11-15 17:50 UTC, melyndav requested changes
Hey @CzarekDryl thanks for your work on this!

A minor update:

1. The 16px padding is missing for both the wallet connected and not connected states:
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/1383dd62-474a-4b54-a09d-f9eb50f6a40c)

2023-11-16 09:58 UTC, melyndav approved these changes
Great work @CzarekDryl, works as expected.

2023-11-16 10:25 UTC, arrenv approved these changes
Looks good, thank you @CzarekDryl

2023-11-16 12:31 UTC, merged