Fix[15637084]: dropdown menus
JoinColony/colonyCDapp pull request #1303
Opened 2023-11-13 09:57 UTC by KornelKwiatkowski

## Description

Task: https://tw.auroracreation.com/app/tasks/15637084

**Changes** 🏗

Examples of places that have been corrected:

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/c2029c25-19fa-4a74-be04-9d7c134a461b)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/8c6560c4-c09e-419e-b384-bb8743fc1d1e)

2023-11-13 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1303) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1303) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1303) it.</sub>

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/AdvancedPaymentForm.tsx
> +          cardClassName="md:w-[200px]"
change px to rem

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/BatchPaymentForm/BatchPaymentForm.tsx
> +        cardClassName="md:w-[200px]"
the same

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/CreateDecisionForm/CreateDecisionForm.tsx
> +          cardClassName="md:w-[200px]"
the same

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/CreateNewTeamForm.tsx
> +          cardClassName="md:w-[200px]"
the same

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/EditColonyDetailsForm.tsx
> +          cardClassName="md:w-[200px]"
the same

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/EditTeamForm.tsx
> +          cardClassName="md:w-[200px]"
the same

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/ManageColonyObjectivesForm.tsx
> +          cardClassName="md:w-[200px]"
the same

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx
> +          cardClassName="md:w-[200px]"
the same

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/ManageTokensForm.tsx
> +          cardClassName="md:w-[200px]"
the same

2023-11-13 10:10 UTC, krawczykkatarzyna commented on src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/MintTokenForm.tsx
> +          cardClassName="md:w-[200px]"
the same

2023-11-13 10:44 UTC, KornelKwiatkowski commented on src/components/v5/common/ActionSidebar/partials/forms/AdvancedPaymentForm/AdvancedPaymentForm.tsx
> +          cardClassName="md:w-[200px]"
fixed

2023-11-13 10:44 UTC, KornelKwiatkowski commented on src/components/v5/common/ActionSidebar/partials/forms/BatchPaymentForm/BatchPaymentForm.tsx
> +        cardClassName="md:w-[200px]"
fixed

2023-11-13 10:44 UTC, KornelKwiatkowski commented on src/components/v5/common/ActionSidebar/partials/forms/CreateNewTeamForm/CreateNewTeamForm.tsx
> +          cardClassName="md:w-[200px]"
fixed

2023-11-13 10:44 UTC, KornelKwiatkowski commented on src/components/v5/common/ActionSidebar/partials/forms/EditColonyDetailsForm/EditColonyDetailsForm.tsx
> +          cardClassName="md:w-[200px]"
fixed

2023-11-13 10:44 UTC, KornelKwiatkowski commented on src/components/v5/common/ActionSidebar/partials/forms/EditTeamForm/EditTeamForm.tsx
> +          cardClassName="md:w-[200px]"
fixed

2023-11-13 10:44 UTC, KornelKwiatkowski commented on src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/ManageColonyObjectivesForm.tsx
> +          cardClassName="md:w-[200px]"
fixed

2023-11-13 10:44 UTC, KornelKwiatkowski commented on src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/ManagePermissionsForm.tsx
> +          cardClassName="md:w-[200px]"
fixed

2023-11-13 10:44 UTC, KornelKwiatkowski commented on src/components/v5/common/ActionSidebar/partials/forms/ManageTokensForm/ManageTokensForm.tsx
> +          cardClassName="md:w-[200px]"
fixed

2023-11-13 10:44 UTC, KornelKwiatkowski commented on src/components/v5/common/ActionSidebar/partials/forms/MintTokenForm/MintTokenForm.tsx
> +          cardClassName="md:w-[200px]"
fixed

2023-11-13 10:53 UTC, krawczykkatarzyna submitted a review, later dismissed

2023-11-13 11:00 UTC, TomaszChmielPagepro submitted a review, later dismissed

2023-11-13 11:08 UTC, melyndav requested changes
Hi @KornelKwiatkowski thanks for your work on this.

A number of updates from the Team Work hasn't been made.

Please note that this input that was added in this PR is correct with all correct hover states, height etc - https://github.com/JoinColony/colonyCDapp/pull/1299

1. The search icon isn't the correct grey as per Figma in the default state across all dropdown menus. 
2. The height of all search inputs are too high and should be 34px globally. 
3. I am still seeing the extra padding at the bottom of each dropdown menu. 

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/e356b5c2-1de7-4a9f-bce7-7c91e1640699)

4. The width of the gray hover background doesn't match Figma.
<img width="297" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/537435fe-d0c8-48be-824b-036557d7b25d">

5. The x is missing from the input when input is added by the user
<img width="319" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/09d261a3-9b40-4a70-a61c-0bb62940e239">
 

6. There are padding issues with this model and it does not match FIgma. 
<img width="271" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/e6989128-10f3-4715-b56e-3ccb708fc507">

2023-11-13 12:11 UTC, KornelKwiatkowski commented
Hi @melyndav, thanks for the feedback. I have a few questions.

_3. I am still seeing the extra padding at the bottom of each dropdown menu._

We have 24px padding from the bottom, like on Figma. Did I miss something?

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/d044a973-641b-4cc2-ac91-b08afc31be8c)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/0928b91d-e939-4a6b-a5e0-fb96624b62d0)


_4. The width of the gray hover background doesn't match Figma._

@arrenv and I talked about this case. We decided that the padding will be larger here so that the hover does not overlap the scrollbar. If you have another solution, please let us know :)


1, 2 and 5 are because I didn't update this branch before making PR, I'm very sorry about that.

2023-11-15 13:39 UTC, KornelKwiatkowski commented
Hi @melyndav,  I need your answer here. Please have a look when you have time :)

2023-11-15 16:17 UTC, ArmandoGraterol requested changes
Noticed a couple of things:

![FireShot Capture 220 - Extensions - Colony - - localhost](https://github.com/JoinColony/colonyCDapp/assets/18473896/6248bc3b-ca6a-465e-a73a-113f793ab984)

- The padding in the modal is 24x10 when it should be 24px from all sides like the decision dropdown.
- The avatar looks quite misaligned, especially when you hover over the item

![FireShot Capture 221 - Extensions - Colony - - localhost](https://github.com/JoinColony/colonyCDapp/assets/18473896/2c4fd72a-70b9-42cd-bbb9-db5477a0f369)

- The placeholder are not being highlighted when you have a menu open.

![FireShot Capture 223 - Extensions - Colony - - localhost](https://github.com/JoinColony/colonyCDapp/assets/18473896/e880595e-b746-4196-849f-d13def9adf54)
![FireShot Capture 222 - Extensions - Colony - - localhost](https://github.com/JoinColony/colonyCDapp/assets/18473896/95d6cc2e-f23d-470c-bac3-6262c85504ed)

- The gray hover background is missing from these dropdowns

2023-11-16 08:35 UTC, KornelKwiatkowski commented
@ArmandoGraterol Are you sure, you have the latest changes? I see only these two issues:

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/7bc8c6ae-72e4-4aec-9d98-5048c08bd529)

![image](https://github.com/JoinColony/colonyCDapp/assets/90605528/39f50c6f-408d-4873-bbfa-a73aa30ac880)

I will fix them

2023-11-16 15:17 UTC, KornelKwiatkowski commented
@ArmandoGraterol fixed :)

2023-11-16 18:07 UTC, ArmandoGraterol approved these changes
LGTM 👍 Thank you for the changes!

2023-11-17 07:06 UTC, TomaszChmielPagepro commented on src/components/v5/shared/HoverWidthWrapper/HoverWidthWrapper.tsx
> +        'font-medium text-transparent h-[.0625rem] overflow-hidden invisible',
I wouldn't add `font-medium` here as this style is specific to a certain use case and should be passed trough `hoverClassName`.

2023-11-17 07:08 UTC, TomaszChmielPagepro commented on src/components/v5/shared/HoverWidthWrapper/types.ts
> +  children: ReactNode;
Can you use `PropsWithChildren` instead?

2023-11-17 07:08 UTC, TomaszChmielPagepro commented on src/components/v5/common/ActionSidebar/partials/forms/ManageColonyObjectivesForm/ManageColonyObjectivesForm.tsx
> +          cardClassName="md:w-[12.5rem]"
This may not be needed after adding `HoverWidthWrapper`

2023-11-17 07:10 UTC, TomaszChmielPagepro commented on src/components/v5/common/ActionSidebar/partials/AmountField/AmountField.tsx
> +                            <HoverWidthWrapper hoverElement="span">
Can you please check if wrapping the whole `button` with this component gives the same effect?

2023-11-17 08:19 UTC, KornelKwiatkowski commented
Hi @melyndav, I need you here :) https://github.com/JoinColony/colonyCDapp/pull/1303#issuecomment-1808043430

2023-11-17 08:29 UTC, TomaszChmielPagepro approved these changes

2023-11-17 08:57 UTC, krawczykkatarzyna approved these changes

2023-11-17 09:14 UTC, melyndav approved these changes
This is fine to go @KornelKwiatkowski! Thanks :)

2023-11-17 09:39 UTC, merged