feat: members related actions
JoinColony/colonyCDapp pull request #1312
Opened 2023-11-13 13:13 UTC by joanna-pagepro

https://tw.auroracreation.com/app/tasks/15629286

![image](https://github.com/JoinColony/colonyCDapp/assets/44369011/dee1caac-63ad-471b-bf6c-9884b608212a)

2023-11-13 13:24 UTC, KornelKwiatkowski submitted a review, later dismissed

2023-11-13 14:53 UTC, arrenv requested changes
@joanna-pagepro This seems to work well if no action is open.

Although, I encountered issues if the action modal is already open. I will share directly via chat.

2023-11-14 06:43 UTC, CzarekDryl approved these changes

2023-11-14 13:07 UTC, TomaszChmielPagepro submitted a review, later dismissed

2023-11-14 20:31 UTC, arrenv approved these changes
Great work @joanna-pagepro, works really well!

2023-11-15 06:30 UTC, CzarekDryl approved these changes

2023-11-15 06:33 UTC, merged