Feat/15662312 widget boxes
JoinColony/colonyCDapp pull request #1330
Opened 2023-11-15 09:40 UTC by CzarekDryl

https://tw.auroracreation.com/app/tasks/15662312

Adding horizontal widgets to colony dashboard, other components will be added in other PRs.

![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/55676778-511d-43f5-bdb9-6c06ace994a4)

2023-11-15 09:55 UTC, krawczykkatarzyna commented on src/components/common/ColonyHome/hooks.ts
> +export const useGetHomeWidget = (team?: number) => {
please add return type

2023-11-15 09:55 UTC, krawczykkatarzyna commented on src/components/common/ColonyHome/hooks.ts
> +const setTeamColor = (color?: DomainColor) => {
please move it to consts file

2023-11-15 09:55 UTC, krawczykkatarzyna commented on src/components/v5/shared/UserAvatars/UserAvatars.tsx
> +            'flex items-center justify-center border border-base-white rounded-full bg-gray-50 text-xs font-semibold text-gray-700 -ml-3 z-10',
use `text-5`

2023-11-15 09:55 UTC, krawczykkatarzyna commented on src/hooks/useUserAvatars.ts
> +export const useUserAvatars = (
please add return type

2023-11-15 13:59 UTC, rdig submitted a review, later dismissed
Mostly good, however the Members Widget avatars are not properly aligned

![Screenshot from 2023-11-15 15-54-46](https://github.com/JoinColony/colonyCDapp/assets/1193222/7050fb4c-41a6-4f48-8103-d2381b12ed3d)

2023-11-15 18:33 UTC, ArmandoGraterol requested changes
Looking good! Just a few minor details in the code

2023-11-15 18:33 UTC, ArmandoGraterol commented on src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VoteOutcome/VoteOutcome.tsx
> +import { UserAvatarsItem } from '~v5/shared/UserAvatars/types';
This import should be grouped with the other relative imports

2023-11-15 18:33 UTC, ArmandoGraterol commented on src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VoteOutcome/VoteResults/VoteResults.tsx
> +import { UserAvatarsItem } from '~v5/shared/UserAvatars/types';
Same above

2023-11-15 18:33 UTC, ArmandoGraterol commented on src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VoteOutcome/VoteResults/VoteResultsItem.tsx
> +import { UserAvatarsItem } from '~v5/shared/UserAvatars/types';
Same here

2023-11-15 18:33 UTC, ArmandoGraterol commented on src/components/common/ColonyActions/ActionDetailsPage/DefaultMotion/MotionPhaseWidget/VoteOutcome/VoteResults/VoterAvatars.tsx
> +import { UserAvatarsItem } from '~v5/shared/UserAvatars/types';
Same here

2023-11-15 18:33 UTC, ArmandoGraterol commented on src/components/common/ColonyHome/ColonyHome.tsx
> +import { useGetHomeWidget } from './hooks';
This one should be below the relative imports

2023-11-15 18:33 UTC, ArmandoGraterol commented on src/components/common/ColonyHome/types.ts
> +    | undefined;
We can import `Token` from `~ types` and leave it like this `nativeToken: Token | undefined`. This way if the fields of the `Token` model type are updated in the future, we don't have to come back and manually update this type.

2023-11-15 18:33 UTC, ArmandoGraterol commented on src/components/v5/common/WidgetBoxList/WidgetBoxList.tsx
> +import WidgetBox from '../WidgetBox/WidgetBox';
The extra `WidgeBox` in the import route here shouldn't be needed

2023-11-15 18:33 UTC, ArmandoGraterol commented on src/hooks/useUserAvatars/index.ts
> +import { UseUserAvatarsReturnType } from './types';
These imports need to be rearranged

2023-11-16 08:52 UTC, CzarekDryl commented
@rdig Wdym that members widget is not aligned properly? On design it's aligned to the bottom of texts - 
![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/aaa78135-b575-411a-a2fd-ae95c6d12fbf)

2023-11-16 09:50 UTC, melyndav requested changes
Hey @CzarekDryl,

Great start on this one! 

1. can we update the border width to the following? The border seems a little too thin and not rendering clearly. 

.border {
    border-width: 1.5px;
}

2. Can we update the following to show 4 avatars and remove the last circle with the + 

<UserAvatars maxAvatarsToShow={3} size="xms" items={allMembers} />
to
<UserAvatars maxAvatarsToShow={4} size="xms" items={allMembers} />

2023-11-16 11:40 UTC, arrenv requested changes
Can we please add a "-" instead of a "0" for the initial state while loading.

![default-loading](https://github.com/JoinColony/colonyCDapp/assets/33682027/b517c42f-7169-4f42-979c-bef0fd1ba486)

2023-11-16 12:09 UTC, CzarekDryl commented
@arrenv Added loading and also changed `-` to `0` in total funds box

2023-11-16 13:49 UTC, melyndav submitted a review, later dismissed
Thanks for the fixes @CzarekDryl! Approved from my end.

2023-11-16 14:00 UTC, arrenv commented on src/components/common/ColonyHome/ColonyHome.tsx
> +                <span className="text-1">USD</span>
This should then show the native token symbol. Instead of being hard coded USD.

2023-11-16 14:56 UTC, CzarekDryl commented on src/components/common/ColonyHome/ColonyHome.tsx
> +                    className="text-gray-900"
Changed to `Numeral`

2023-11-17 10:14 UTC, arrenv approved these changes
Works great, thank you @CzarekDryl !

2023-11-17 10:41 UTC, KornelKwiatkowski approved these changes

2023-11-17 10:43 UTC, merged