vertical widgets
JoinColony/colonyCDapp pull request #1353
Opened 2023-11-17 13:37 UTC by krawczykkatarzyna

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2023-11-17 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1353) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1353) before we can accept your contribution.<br/><hr/>**krawczykkatarzyna** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1353) it.</sub>

2023-11-20 14:06 UTC, melyndav requested changes
Hi @krawczykkatarzyna nice start on these widgets. :)  

1. The text should not show as blue on hover. Only the outter border should have a hover state.
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/2a3868ea-2a76-4e39-b8a4-afa61003c51a)

2. The agreement box shouldn't have a hover state since it's not interactable.
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/7b18f607-25b4-441f-ab15-f5df17ad104a)

3. Font weight on the heading in the teams widget doesn't match Figma.
<img width="141" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5da48d23-46c9-41d6-9659-d65474a6b571">

4. Padding doesn't match Figma.
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/f059fda9-4a18-4255-b9db-df294d2dbd07)

5. The widgets need to be handled down to the smallest desktop size (1025px). The forced width is causing issues. 
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/2590fa6d-7f6d-48a5-a612-6869a14eb5a8)

6. When I create a new objective to add it in, the placeholder content from the design is showing and not the correct content. It's showing accuratly on the colony admin page. 
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/870316d3-2c51-4475-907b-cf51d414e970)

7. There is an additional space between the percentage and the % symbol.
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/d929645c-cf9f-4724-b967-ad43afa483a2)

2023-11-20 14:28 UTC, krawczykkatarzyna commented
@melyndav please do not check this pull request, it is not ready yet

2023-11-23 08:32 UTC, CzarekDryl commented on src/components/common/ColonyHome/ColonyHome.tsx
> +                <div className="flex flex-col items-start gap-[0.8rem]">
Is `items-start` needed?

2023-11-23 09:39 UTC, CzarekDryl commented on src/components/v5/common/WidgetBox/WidgetBox.tsx
> +    'transition-all sm:hover:border-gray-900 sm:hover:cursor-pointer';
Is hover needed on `cursor-pointer`?

2023-11-23 09:39 UTC, CzarekDryl commented on src/components/v5/common/WidgetBox/partials/EmptyWidgetState.tsx
> +    <button
I think we have TextButton component, please check if you can use it

2023-11-23 09:39 UTC, CzarekDryl commented on src/components/v5/common/WidgetBox/partials/types.ts
> +  actionTitle: MessageDescriptor;
React.ReactNode

2023-11-23 09:39 UTC, CzarekDryl commented on src/components/v5/shared/Link/types.ts
> +  to?: To;
Why is `to` optional? Link will be without href?

2023-11-23 09:39 UTC, CzarekDryl commented on src/components/v5/shared/ProgressBar/ProgressBar.tsx
> -        <span className="text-3 text-gray-600 ml-1 flex-shrink-0">
Did you check if it's working in all places?

2023-11-23 09:46 UTC, arrenv requested changes
Thank you @krawczykkatarzyna, great work. Some feedback:

1. The hover state seems to stick when switching from one team to another in the chart.

![same-tooltip-showing](https://github.com/JoinColony/colonyCDapp/assets/33682027/45b0f38e-9cc3-45fc-a936-0ef8ea0249d4)


2. The tooltip appears off to the side initial in some cases.

![hover-state-chart](https://github.com/JoinColony/colonyCDapp/assets/33682027/b7bde88a-b703-449c-8e5f-ce2a964b4561)


3. There should be a spacing, i.e. stroke between each segment of the cart.

Design: 
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/dc9ef4ed-908f-4744-b36b-2e831ee15916)


4.  I am getting a re-rendering issue when hovering over each team.

![rerendering-issue](https://github.com/JoinColony/colonyCDapp/assets/33682027/2ef51d56-3218-4a16-bc2f-efb40ec71b5c)

5. The responsiveness in the chart seems to not be working.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/752c4909-af3b-4591-8c91-f7d04e1ef9fd)

6. There seems to be a padding issue at the bottom of the agreement widget at smaller desktop screen sizes. This was found by emulating the widget width with the activity feed in and a screen width at 1025px i.e. just before the breakpoint.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/c1701751-b8e9-41ba-87ea-77657dc6af9f)

2023-11-23 11:30 UTC, rdig submitted a review, later dismissed
- No reputation in any teams (the whole colony) should just show a gray circle, currently it does not show anything
![Screenshot from 2023-11-23 13-28-00](https://github.com/JoinColony/colonyCDapp/assets/1193222/7a672d9b-db93-4315-9cae-f9066ac44611)

- Long domain names break the ui. There needs to be a limit after which an ellipsis kicks in
![Screenshot from 2023-11-23 13-28-55](https://github.com/JoinColony/colonyCDapp/assets/1193222/8ca4e718-c4ac-4bb0-ba50-1ea972ab2ed3)

2023-11-23 13:58 UTC, krawczykkatarzyna commented
@arrenv @rdig all issues fixed

2023-11-23 15:44 UTC, arrenv requested changes
@krawczykkatarzyna Thank you for the updates, great work. A few comments.


1. The design shows the teams aligned vertically in the design.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/91c0af30-7f48-45dd-b577-8f69e5b60e8d)

This is what currently happens:

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/466bc96d-b9e9-4198-bc26-9faa03933c13)


2. There is a padding at the bottom of a team, if there is no `All other`.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/2069a8cb-a4f6-4b36-9db8-369ca59cee88)

2023-11-23 15:44 UTC, arrenv commented on src/components/common/ColonyHome/ColonyHome.tsx
> +                </p>
We can remove the hardcoded default data here.

2023-11-23 15:44 UTC, arrenv commented on src/components/common/ColonyHome/ColonyHome.tsx
> +            href: agreements ? '/' : undefined,
We can use the `COLONY_AGREEMENTS_ROUTE` from `src/routes/routeConstants.ts`.

2023-11-23 15:44 UTC, arrenv commented on src/components/common/ColonyHome/hooks.ts
> +    stroke: '#F2F4F7',
We should be using the Tailwind defined colours here.

2023-11-23 15:44 UTC, arrenv commented on src/components/v5/common/TeamReputationSummary/utils.ts
> +};
Why are we not able to use the defined colours as opposed to defining again here with hexes.

2023-11-23 15:44 UTC, arrenv commented on src/components/v5/common/DonutChart/hooks.tsx
> +              stroke: '#F9FBFC',
Can we avoid using hexes and instead use the defined colour variables.

2023-11-23 15:44 UTC, arrenv commented on src/images/icons/message.svg
Can we use phospher icons library instead of adding a new SVG with a hardcoded colour.

2023-11-23 17:56 UTC, ArmandoGraterol reviewed
I haven't spotted anything codewise but I'll take a closer look once the changes of the other reviews are in 👍

2023-11-23 18:48 UTC, krawczykkatarzyna commented
@arrenv fixed

2023-11-24 11:23 UTC, melyndav approved these changes
@krawczykkatarzyna great work on this. All looks good from a UI standpoint!

2023-11-24 11:23 UTC, arrenv approved these changes
Everything picked up has been resolved, great work @krawczykkatarzyna thank you!

2023-11-24 12:46 UTC, CzarekDryl approved these changes

2023-11-24 13:15 UTC, merged