Fix/15681618 team reputation
JoinColony/colonyCDapp pull request #1408
Opened 2023-11-27 08:03 UTC by CzarekDryl

https://tw.auroracreation.com/app/tasks/15681618

Changes in this PR:
- rounded percentage of teams reputation
- added tooltip on hover to show full percentage value

![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/c77ecf19-db28-46d8-8845-a5be88617133)
![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/b446283b-995c-4eb4-9945-4263cf8450dd)

2023-11-27 12:50 UTC, melyndav approved these changes
Great work on this @CzarekDryl. Approved

2023-11-27 12:51 UTC, arrenv approved these changes
Looks good @CzarekDryl. thank you for update.

2023-11-27 14:48 UTC, rdig requested changes
All good, however the "All Other" entries shows the tooltip rendered to the left, ranther than on top

![Screenshot from 2023-11-27 16-47-56](https://github.com/JoinColony/colonyCDapp/assets/1193222/050bbd2f-cf7d-4dd4-8aab-9939e11f8099)
![Screenshot from 2023-11-27 16-48-00](https://github.com/JoinColony/colonyCDapp/assets/1193222/2713ba4a-ab0a-4495-944c-041146bf7032)

2023-11-28 08:05 UTC, CzarekDryl commented
@rdig Thanks for checking that, I've fixed this issue.

2023-11-28 19:26 UTC, ArmandoGraterol approved these changes
Looks good to me 👍 Thank you for your work

2023-11-28 19:26 UTC, ArmandoGraterol commented on src/components/v5/common/TeamReputationSummary/partials/TeamReputationSummaryRow.tsx
> +import Tooltip from '~shared/Extensions/Tooltip';
Same here

2023-11-28 19:32 UTC, arrenv submitted a review, later dismissed
Looks consistent now, thanks @CzarekDryl

2023-11-29 10:19 UTC, arrenv approved these changes

2023-11-30 14:34 UTC, melyndav submitted a review, later dismissed
Nice work @CzarekDryl! Approved :)

2023-11-30 14:34 UTC, arrenv approved these changes
Thanks @CzarekDryl, looks good to me!

2023-11-30 23:06 UTC, jakubcolony submitted a review, later dismissed
Nice work 👍

2023-12-01 09:16 UTC, arrenv approved these changes

2023-12-01 09:16 UTC, TomaszChmielPagepro approved these changes

2023-12-01 10:31 UTC, jakubcolony approved these changes

2023-12-01 11:28 UTC, merged