Added activity feed on colony dashboard
JoinColony/colonyCDapp pull request #1441
Opened 2023-11-29 18:50 UTC by TomaszChmielPagepro

This PR adds an activity feed table on the colony home page and filtering by team.
Optimized refetch method of `useNetworkMotionStates`, the consumer can now decide which motions ids should be refetched.

![image](https://github.com/JoinColony/colonyCDapp/assets/38806520/41f0d4b0-44c4-4d32-bae5-11f58f694205)
![image](https://github.com/JoinColony/colonyCDapp/assets/38806520/375390d0-62fa-42c1-bfc7-34d58d0063cf)
![image](https://github.com/JoinColony/colonyCDapp/assets/38806520/77de358e-c8a8-48ca-88c0-afe7c549c887)

2023-11-29 20:07 UTC, arrenv requested changes
@TomaszChmielPagepro Thank you adding this is, coming together now!

From my side, we just need to align it better with the design.

1. The bottom of the activity feed should align with the bottom of the widgets:
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/5905ba2d-413c-4617-8e33-000336b17fac)


2. There should be 7 items per page on the dashboard version of the activity feed. The height of each row is 70px as well. This is different to the dedicated activity page where each row is 58px, and there are 10 items per page.


3. When clicking on an item in the activity feed, it re-renders the page changing the team and refetching the list.
![rerender-when-clicking-item](https://github.com/JoinColony/colonyCDapp/assets/33682027/06ee99e0-0d95-4f7b-b5bb-cfee06b96c4e)


4. The width of the widgets does not match the design. The activity feed on the dashboard should have a width of 61% at the max container width.
The design:
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/90544567-e578-4e1f-8c15-9c99de577bbd)
This PR:
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/1bc6b1ec-3057-4145-9e60-c66b7795199c)
It causes the chart in the widget to disappear:
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/370c6297-18d1-4144-bb0d-d6496cd8517c)

2023-11-30 11:05 UTC, TomaszChmielPagepro commented
@arrenv Issues fixed

2023-11-30 12:14 UTC, melyndav requested changes
Hey @TomaszChmielPagepro. Great start on this one.

1. I see the issue Arren raised about the width of the table and it impacting the three left side widgets is still visible.
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/14f13b56-fe50-4c11-900e-278fe6c5e47a)

2. Is it possible to align the bottom of the table with the left side widget
<img width="1001" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/06a1eedf-867e-4b8d-926b-a63fad3dd9b4">

3. Can the skeleton loader also be applied to the avatars to keep it consistent with the activity feed?
![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/6161c121-2443-4836-87d8-fbcd9e86f5b3)

2023-11-30 14:39 UTC, TomaszChmielPagepro commented
@melyndav @arrenv Issues fixed

2023-11-30 15:30 UTC, melyndav submitted a review, later dismissed
Great work @TomaszChmielPagepro! Thank you and approved. :)

2023-11-30 15:48 UTC, arrenv approved these changes
Nice work @TomaszChmielPagepro, looks and works great!

2023-11-30 15:48 UTC, arrenv commented on tailwind.config.js
> +      md: ['0.875rem', '1.25rem'],
This looks to better match the design, we looked in as many places as we could find it was being used and seems to not cause any alignment issues.

2023-11-30 15:49 UTC, merged