fix: 15690133 - external url
JoinColony/colonyCDapp pull request #1448
Opened 2023-11-30 14:12 UTC by krawczykkatarzyna

2023-11-30 14:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1448) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1448) before we can accept your contribution.<br/><hr/>**krawczykkatarzyna** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1448) it.</sub>

2023-11-30 14:16 UTC, TomaszChmielPagepro approved these changes

2023-12-01 12:47 UTC, arrenv requested changes
I still seem to have an issue, the URL is being generated as of the screenshot and going to a 404.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/dc03928e-32b2-46e5-b4d4-e4278c83767e)

Validation in the social links should handle this, but it is still possible to create a different type of link when using the create data script.

Where are you seeing this fix the issue and I can check there as well?

2023-12-12 17:35 UTC, chmanie commented
@arrenv are you saying we should detect it as URLs if someone just gives "example.com" or "www.example.com" (as opposed to "https://www.example.com")

2023-12-14 14:56 UTC, arrenv commented
> @arrenv are you saying we should detect it as URLs if someone just gives "example.com" or "www.example.com" (as opposed to "https://www.example.com")

If possible, yes, otherwise, at least we should hide links that are won't work due being added to the route path.

2023-12-18 12:24 UTC, closed without merging