Fix metatransaction toggle
JoinColony/colonyCDapp pull request #1453
Opened 2023-11-30 23:22 UTC by ArmandoGraterol

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #1422

2023-12-01 15:01 UTC, melyndav requested changes
Hey @ArmandoGraterol nice start on this! One issue I picked up. When switching between tabs on the Account screen, the state of the toggle is reverted. However, on reload it is the correct state.

2023-12-03 18:18 UTC, arrenv approved these changes
Works great @ArmandoGraterol! Created a new user and was set by default, amazing!

2023-12-03 18:20 UTC, rdig commented
I can't check this right now, but metatransactions should be disabled by default on local dev, but enabled by default in production

2023-12-04 11:54 UTC, melyndav submitted a review, later dismissed
Thanks for addressing my point of feedback @ArmandoGraterol! I appreciate your work on this one! :)

2023-12-04 19:37 UTC, arrenv approved these changes

2023-12-05 15:40 UTC, melyndav approved these changes
:)

2023-12-05 15:41 UTC, merged

2023-12-11 11:13 UTC, melyndav commented
@ArmandoGraterol looks like this issue is back due to regressions during launch. I will make a new issue for it and tag you.