Fix/15673692 description not required
JoinColony/colonyCDapp pull request #1461
Opened 2023-12-04 12:02 UTC by CzarekDryl

https://tw.auroracreation.com/app/projects/562144/tasks/15685797

Changes in this PR:
- Description field is no longer required

2023-12-04 15:36 UTC, melyndav requested changes
Hey @CzarekDryl looks great from my end, so thanks for your work on this.

Two requests:

1. Can you please leave the description as required only for the 'Create a decision' action type? The description field is the decision content. 

2. For this 'Create a decision' error states validation copy can the following errors please be updated:

- decisionMethod must be defined > Please select a decision method 
- description must be defined > Please enter a description for your agreement 

Thank you!

2023-12-05 06:56 UTC, CzarekDryl commented
@melyndav Sure thing! I've changed that

2023-12-05 11:06 UTC, thomassdk approved these changes
Looks good to me, just minor issue with imports

2023-12-05 11:06 UTC, thomassdk commented on src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/hooks.ts
> +import { MAX_ANNOTATION_LENGTH } from '~constants';
this needs to go up :point_up:

2023-12-06 18:31 UTC, ArmandoGraterol approved these changes
Looks good to me! Descriptions are indeed, no longer required 👍

2023-12-08 06:36 UTC, merged