disable fields; add correct styles
JoinColony/colonyCDapp pull request #1462
Opened 2023-12-04 12:21 UTC by krawczykkatarzyna

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2023-12-04 12:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1462) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1462) before we can accept your contribution.<br/><hr/>**krawczykkatarzyna** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1462) it.</sub>

2023-12-04 15:31 UTC, melyndav submitted a review, later dismissed
Sorry, I left a comment on the wrong PR. Please ignore.

2023-12-04 19:33 UTC, arrenv requested changes
Thank you @krawczykkatarzyna!

I noticed these things while reviewing.

1. This should only work if the `VotingReputation` extension is been `Enabled`. At the moment, it is only checking if the extension has been installed. 

2. The 'Permission' Decision method is not possible at all with this Action type at the moment, so, the dropdown should only support 'Reputation'.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/3b9f3835-d5d8-4a02-90dd-e73d130079c2)


4. I noticed this error in the console when creating an Agreement.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/86939ef6-e995-4bcd-8de1-0618bcb5459a)

5. After creating an agreement with the Reputation decision method I don't see the description of the Agreement or the title.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/82d414ff-147a-4fd4-832f-147a3df18199)

6. Likely out of scope of this PR, but I also noticed that the Agreement dashboard widget did not update after creating an agreement.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/b590d577-d757-4230-8cb4-93bd142a46e7)

2023-12-13 11:52 UTC, bassgeta requested changes
Good work! Dropped just a few minor comments

2023-12-13 11:52 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/consts.tsx
> +export const useCreateActionTypeNotification = (
can this be a component? it's a hook returning JSX inside a file that should containt constants
Seeing how it's used, we can just replace this codesnip
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/297ff66c-99a9-45ed-8065-96c653137c8a)
with a component called `ActionTypeNotification` which can then just render the banner conditionally

2023-12-13 11:52 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/partials/ActionButtons.tsx
> +  useDisableFields,
hope it's not too nitpicky, but `useDisableFields` makes it sound like it's going to disable fields, maybe rename to `useIsFieldDisabled`

2023-12-13 11:52 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
> +import { noop } from 'lodash';
you can use noop from our utils

2023-12-13 11:52 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
> +            <>
probably no need for a fragment here

2023-12-13 11:52 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/partials/ActionSidebarContent/partials/SidebarBanner.tsx
> +  const getProperty = (obj, key, defaultValue) => {
this looks like a useful util! maybe we can already put it to `utils/objects` already :)

2023-12-22 13:41 UTC, bassgeta requested changes

2023-12-22 13:41 UTC, bassgeta commented on src/components/v5/shared/ActionTypeNotification/ActionTypeNotification.tsx
> +            {actionTypeNotificationTitle()}
we can reuse notificationTitle here

2023-12-22 13:41 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/partials/hooks.ts
> +  const isExtenstionEnabled =
isExtensionEnabled

2023-12-22 13:49 UTC, bassgeta approved these changes

2023-12-22 15:08 UTC, ArmandoGraterol requested changes
Nice work with this! The only gripe I could find is that the description is not aligned when it's not expanded on the summary side panel after submit:
![FireShot Capture 265 - Transaction - 0xa592ab98a4a8fadc87acb2205aad6849000ce7dd893f0f8e17f4b_ - localhost](https://github.com/JoinColony/colonyCDapp/assets/18473896/df242e77-5c24-4a6d-bf45-a7cfbad474dc)

2024-01-24 13:27 UTC, iamsamgibbs requested changes
This is looking great! Description alignment is fixed. I've only noticed one very minor thing on my end. The "enter a description" button still has a hover state when disabled. I've added a comment where this is occurring.

![Screenshot 2024-01-24 at 13 08 50](https://github.com/JoinColony/colonyCDapp/assets/34915414/1881b572-270d-492b-acbb-ecdbdb71c777)

2024-01-24 13:27 UTC, iamsamgibbs commented on src/components/v5/shared/RichText/RichText.tsx
> +                  'sm:hover:text-blue-400': !isDisabled,
```suggestion
                className={clsx('transition text-left', {
                  'text-gray-900': characterCount,
                  'text-gray-400': !characterCount,
                  'sm:hover:text-blue-400': !isDisabled,
```

sm:hover:text-blue-400 should no longer be applied by default as it is now applied only when !isDisabled.

2024-01-24 15:58 UTC, iamsamgibbs approved these changes
Looks good to me!

2024-01-25 15:40 UTC, ArmandoGraterol submitted a review, later dismissed
Looking good to me 👍 Thank you for the changes

2024-01-25 16:52 UTC, iamsamgibbs submitted a review, later dismissed
Looks good to me!

2024-01-26 12:07 UTC, arrenv approved these changes
Looks good to me, thank you @CzarekDryl.

Out of scope of this PR, put just noting that Creating an Agreement is unfortunately not working for me.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/8f8fa24e-60e7-4ad9-b982-b92aca52d39d)

2024-01-26 14:26 UTC, iamsamgibbs approved these changes

2024-01-30 15:52 UTC, arrenv submitted a review, later dismissed
Still good!

2024-01-30 16:00 UTC, ArmandoGraterol requested changes
It's working as expected as far as I can tell! Noticed some small things that we could change/improve but other than that, this should be good to go

2024-01-30 16:00 UTC, ArmandoGraterol commented on src/components/v5/shared/ActionTypeNotification/ActionTypeNotification.tsx
> +  const actionTypeNotificationTitle = (): string | undefined => {
I think this name doesn't reflect that this is a function. Perhaps something like `getNotificationTitle` would be better

2024-01-30 16:00 UTC, ArmandoGraterol commented on src/components/v5/shared/ActionTypeNotification/ActionTypeNotification.tsx
> +    return title;
We don't need `let title` here. We can directly return the title in each case:
```
  const actionTypeNotificationTitle = (): string | undefined => {
    switch (selectedAction) {
      case ACTION.UNLOCK_TOKEN:
        return formatText(
          isNativeTokenUnlocked ? MSG.unlockedToken : MSG.unlockedTokenError,
        );
      case ACTION.ENTER_RECOVERY_MODE:
        return formatText(MSG.enterRecoveryModeError);
      case ACTION.CREATE_DECISION:
        return isFieldDisabled
          ? formatText(MSG.createDecisionError)
          : undefined;
        break;
      default:
        return undefined;
    }
  };

  const notificationTitle = actionTypeNotificationTitle();
```

2024-02-01 16:21 UTC, ArmandoGraterol submitted a review, later dismissed
LGTM 🆗

2024-02-02 09:17 UTC, iamsamgibbs approved these changes
All looks good to me!

2024-02-02 10:27 UTC, iamsamgibbs approved these changes

2024-02-02 13:00 UTC, KornelKwiatkowski approved these changes

2024-02-02 13:01 UTC, merged