Motion styling fixes #2
JoinColony/colonyCDapp pull request #1487
Opened 2023-12-05 21:58 UTC by arrenv

## Description

Adds various style fixes to motions as listed out here https://github.com/JoinColony/colonyCDapp/issues/1480 including an additional fix for the 0 appearing when the voting threshold progress bar loads.

Resolves #1480

2023-12-07 15:51 UTC, chmanie submitted a review, later dismissed
Looks reasonable to me!

2023-12-08 16:25 UTC, jakubcolony requested changes
Looks good, just a small request regarding the enum

2023-12-08 16:25 UTC, jakubcolony commented on src/components/v5/shared/ProgressBar/ProgressBar.tsx
> +  if (threshold == null || threshold === 0) {
Why non-strict equality? If you want to cover null, undefined and 0 you could consider `!threshold`, unless of course you want to allow empty strings

2023-12-15 13:17 UTC, melyndav submitted a review, later dismissed
Nice work on this @arrenv! Approved.

2023-12-18 22:08 UTC, jakubcolony approved these changes
LGTM 👍

2023-12-20 15:44 UTC, rdig approved these changes
All good here

2023-12-20 15:44 UTC, rdig commented
Since @arrenv is off, I'm going to take over this, fix @jakubcolony 's code suggestion then merge this

2023-12-20 15:56 UTC, merged