Add "Not enough funds" error to finalize step
JoinColony/colonyCDapp pull request #1499
Opened 2023-12-06 21:07 UTC by ArmandoGraterol

The logic was already there, althought a bit wrong as it was considering the motion domain instead of `fromDomain` which actually has the domain from which the funds are going to be extracted.

Besides that, now you should see this error whenever you create a simple payment or transfer funds motion with an amount that by the time the motion is ready to be finalized, is larger than the domain's balance:

![FireShot Capture 256 - Transaction - 0x8c79399a21594e2c41e7eee957c3cbcf1fa725bda8503970f04ba_ - localhost](https://github.com/JoinColony/colonyCDapp/assets/18473896/9e830f9e-8645-4f59-bbd4-0414e1570da4)

Resolves #1482

2023-12-08 18:22 UTC, jakubcolony approved these changes
LGTM!

2023-12-15 11:01 UTC, melyndav requested changes
Hey @ArmandoGraterol,

1. I tested this on a failed motion that had no stakes and the error is showing but it shouldn't because nothing was staked, and the motion failed and couldn't be finalised.

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/1bc4d648-6178-439f-8404-0eb292b75fb3)

2. This is also showing incorrectly as there was enough funds in root.

2023-12-20 13:54 UTC, jakubcolony submitted a review, later dismissed
👍

2023-12-20 16:33 UTC, rdig submitted a review, later dismissed
Nice work!

2024-01-10 11:58 UTC, melyndav commented
Can you rebase this one @ArmandoGraterol ? Ta. :)

2024-01-10 16:27 UTC, ArmandoGraterol commented
@melyndav Done!

2024-01-11 17:58 UTC, jakubcolony submitted a review, later dismissed

2024-01-12 09:10 UTC, rdig submitted a review, later dismissed

2024-01-16 16:19 UTC, melyndav requested changes
Hey @ArmandoGraterol,

Did another check of this just doing the normal flow (not the no stakes flow) and I see that something's changed with the finalized button compared to the original screenshots.

<img width="351" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/0e8abd35-a7d8-4c9c-acae-9e875cc4db76">

Can we get this fixed?

2024-01-18 17:31 UTC, ArmandoGraterol commented
@melyndav 
> Did another check of this just doing the normal flow (not the no stakes flow) and I see that something's changed with the finalized button compared to the original screenshots.

Fixed!

> Also, I'm still seeing my original error where there was no staking at all on the motion, but it's showing the no funds error.

I wasn't able to replicate this but I've tweaked logic related to cover other cases anyway so it should be working as expected.

FYI this is how it looks to me when I don't stake in a motion after fixing the submit button issue you mentioned:
![Screenshot 2024-01-18 at 14 30 46](https://github.com/JoinColony/colonyCDapp/assets/18473896/55625eb0-6ba8-4699-bbf0-cacc502ff5dc)

2024-01-23 12:44 UTC, iamsamgibbs commented
@ArmandoGraterol can you rebase this branch now that #1771 has been merged as it'll make it easier to test with the staking issue resolved?

2024-01-23 15:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1499) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1499) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1499) it.</sub>

2024-01-23 15:18 UTC, ArmandoGraterol commented
@iamsamgibbs Done!

2024-01-23 15:53 UTC, rdig submitted a review, later dismissed
Working, as expected, however it did require a refresh to get to the correct state _(the again, in real life this won't be such a big issue)_

Available funds
![Screenshot from 2024-01-23 17-51-28](https://github.com/JoinColony/colonyCDapp/assets/1193222/91a74b9d-16fe-4c05-9127-e6fa8a9add7e)

Finalize with more funds then available:
![Screenshot from 2024-01-23 17-51-19](https://github.com/JoinColony/colonyCDapp/assets/1193222/e9e3b4ac-6b1e-48f0-b33b-89d0fa6adff5)

2024-01-23 16:16 UTC, iamsamgibbs submitted a review, later dismissed
This looks good to me! Looks as expected when there are insufficient funds, and when the motion has no stakes.

![Screenshot 2024-01-23 at 16 13 46](https://github.com/JoinColony/colonyCDapp/assets/34915414/140b4ed4-4d42-4ac0-81c5-0fb3458ae8bd)

![Screenshot 2024-01-23 at 16 13 52](https://github.com/JoinColony/colonyCDapp/assets/34915414/c319c85a-980c-4e34-8e55-4ade5be11f52)

2024-01-30 16:42 UTC, iamsamgibbs approved these changes

2024-01-31 15:01 UTC, ArmandoGraterol commented
@melyndav May I get a re-review of this PR, please?

2024-01-31 15:54 UTC, rdig approved these changes
Re-approved

2024-02-06 14:36 UTC, merged