fix: colony details styles, new native token pill
JoinColony/colonyCDapp pull request #1516
Opened 2023-12-08 12:27 UTC by bassgeta

## Description

Fix styles according to the issue.
Added a new native token pill so we can reuse it between the details page and the dashboard header.

**New stuff** ✨

* `NativeTokenPill` component which displays a tooltip 

**Changes** 🏗

* Use the new component instead of doing it twice

Resolves  #1389

2023-12-13 09:51 UTC, chmanie commented on src/components/v5/common/NativeTokenPill/NativeTokenPill.tsx
> +    <div className="h-[1.875rem] flex flex-row items-center px-[.375rem] border border-gray-200 rounded-lg bg-base-white text-gray-900">
0.375rem is `px-1.5`

2023-12-13 09:52 UTC, chmanie commented on src/components/v5/common/NativeTokenPill/NativeTokenPill.tsx
> +          <LockKey size={12} className="ml-[.125rem] -translate-x-px" />
0.125rem is `ml-0.5`

2023-12-14 10:38 UTC, melyndav requested changes
Hey @bassgeta,

You've changed the desktop styling of the native token pill. This shouldn't match, they have different styling. 

Link to dashboard: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=11846-72482&mode=design&t=j9QKipjvSqXI1GXM-4

Also, double check in figma the padding between the text and the icon inside the pill. It's looking a little small.

2023-12-14 16:36 UTC, rdig approved these changes
code wise I'm good with this. As long as Mel's UI updates are covered, this is good to go

2023-12-15 14:41 UTC, melyndav approved these changes
You know the drill, get this one shipppppped! Nice work @bassgeta, I appreciate you working on the UI fixes as requested.

2023-12-15 14:45 UTC, merged