fix: native token in table popup
JoinColony/colonyCDapp pull request #1538
Opened 2023-12-12 10:23 UTC by bassgeta

## Description

Changed the icon so it fits the designs, also had to use a different popup.
Our table rows had `scale(1)` which brought them to the very forefront of our app, thus displaying over the popup.
The hack was introduced due to Safari not handling `position: relative` on table rows, but I think we shouldn't be relying on those, our popups are mostly on single cells or components in there.

**Changes** 🏗

* new icon and tooltip for the native token popup
* removed the scale transform on the entire table row

Resolves #1523

2023-12-13 16:52 UTC, chmanie approved these changes
Yup, that's much nicer.

2023-12-14 10:35 UTC, melyndav requested changes
Hey @bassgeta thanks so much for working on this issue.

My only feedback is with the tool tip. Can this be more inline with the component styling so there is consistency across all tooltips? So making it wider and extend out to the right instead of down covering the other tokens in the table. 

Figma component for styling: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-V5?type=design&node-id=834-186119&mode=design&t=j9QKipjvSqXI1GXM-4

2023-12-14 13:21 UTC, CzarekDryl commented on src/components/frame/v5/pages/BalancePage/partials/TokenAvatar/TokenAvatar.tsx
> +            <LockKey size={14} className="mt-[1px]" />
Please do `mt-px`

2023-12-14 16:45 UTC, rdig approved these changes
I'm good here, however please be more descriptive when composing your commit messages:

![Screenshot from 2023-12-14 18-40-34](https://github.com/JoinColony/colonyCDapp/assets/1193222/6e3ed6a2-3cc3-4228-b2f2-bc5312b3e74e)

As the last one you did to address review comments isn't descriptive at all, and a year down the line when you look at this commit through some git blame, you will have no idea what Code Review this commit is mentioning.

2023-12-15 14:36 UTC, melyndav approved these changes
Thanks for the updates @bassgeta! Approved from my side. :)

2023-12-15 14:38 UTC, merged