Add currency conversion menu
JoinColony/colonyCDapp pull request #1572
Opened 2023-12-18 11:58 UTC by willm30

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2023-12-29 17:19 UTC, ArmandoGraterol submitted a review, later dismissed
LGTM 👍

2024-01-02 17:31 UTC, arrenv approved these changes
Nice one @willm30, regarding the order, no big issue with it as it is for the moment as long as it is consistent.

Is there anyway to fix the issue with the edges getting cut off.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/54ca5040-d2e3-44ec-9f2b-c56fb48b4bf2)

2024-01-03 16:17 UTC, rdig submitted a review, later dismissed
Minor naming nitpick, all good otherwise

2024-01-03 16:17 UTC, rdig commented on src/images/icons.json
> +    "india"
Maybe prepend theses with `flag-`. Ie: `flag-us`, `flag-japan`

2024-01-05 13:27 UTC, ArmandoGraterol submitted a review, later dismissed

2024-01-10 11:32 UTC, melyndav submitted a review, later dismissed
A quick check of this one and all looks good @willm30! Nice work.

2024-01-10 12:21 UTC, rdig approved these changes
All good again

2024-01-10 13:13 UTC, rdig submitted a review, later dismissed

2024-01-10 13:25 UTC, rdig submitted a review, later dismissed

2024-01-10 14:05 UTC, ArmandoGraterol submitted a review, later dismissed

2024-01-10 18:58 UTC, ArmandoGraterol submitted a review, later dismissed

2024-01-11 11:45 UTC, arrenv requested changes
@willm30 All looks to be functioning well, nice!

Only thing I noticed was doesn't the new env variable `COINGECKO_API_KEY` need to also be added to the `Dockerfile`? - https://github.com/JoinColony/colonyCDapp/blob/cc2baf5affd5ea57f364a169215d26b75d61a79d/Dockerfile#L76

2024-01-11 14:56 UTC, rdig approved these changes

2024-01-11 14:56 UTC, merged