add missing banner; purple border on mobile;
JoinColony/colonyCDapp pull request #1619
Opened 2023-12-22 14:47 UTC by krawczykkatarzyna

https://tw.auroracreation.com/app/tasks/15660303
https://tw.auroracreation.com/app/tasks/15678862

<img width="802" alt="Screen Shot 2023-12-22 at 15 34 56" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/802c2498-0960-4b80-98b4-a8b4fc1c25dd">
<img width="497" alt="Screen Shot 2023-12-22 at 15 35 13" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/4690fcd7-13c7-4621-8462-510978f8b936">
<img width="864" alt="Screen Shot 2023-12-22 at 15 47 13" src="https://github.com/JoinColony/colonyCDapp/assets/119587095/63bb5f92-c4f0-4cdc-8aa4-c7c62779c497">

2023-12-22 14:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1619) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1619) before we can accept your contribution.<br/><hr/>**krawczykkatarzyna** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1619) it.</sub>

2023-12-28 16:27 UTC, ArmandoGraterol requested changes
Good work so far! I've noticed that the banner is missing in some other instances of the popover:
![Screenshot 2023-12-28 at 13 14 06](https://github.com/JoinColony/colonyCDapp/assets/18473896/ef8bb364-2f7e-4993-9694-6bafc144702a)

- On the extension page, when you click on the user that installed the extension
- On the action side panel's overview of what member executed the action with what permission

2024-01-09 16:36 UTC, ArmandoGraterol reviewed
The "Not verified" banner is still missing in this popover:
![Screenshot 2024-01-09 at 13 34 42](https://github.com/JoinColony/colonyCDapp/assets/18473896/ac952726-14a3-4f74-83b3-4b565440ea0e)

2024-01-09 16:36 UTC, ArmandoGraterol commented on src/components/v5/shared/UserAvatarPopover/UserAvatarPopover.tsx
> +        additionalContent || (!isVerified && showVerifiedBox) ? (
If every place where the user popover is used must look the same (according to what Product wrote in the task at least), then I don't think we need this `showVerifiedBox` as the verified box should always show if the user is not verified.

2024-01-11 15:22 UTC, rdig requested changes
Code-wise this seems fairly good, however not all the banners show up _(see Armando's comments)_

Once those are addressed, I'll re-review this.

2024-01-15 14:22 UTC, ArmandoGraterol approved these changes
Looks good to me 👍 All popovers seem to be appearing as expected

2024-01-23 10:15 UTC, jakubcolony commented
@CzarekDryl can you please rebase on latest master to fix the `build` check, after which it should be good to merge.

2024-01-23 13:37 UTC, merged