Fix pending colony metadata not appearing on side panel
JoinColony/colonyCDapp pull request #1774
Opened 2024-01-22 20:00 UTC by ArmandoGraterol

This PR addresses the pending colony metadata not appearing on the motion side panel.

The data wasn't appearing before because the auth proxy was blocking the request: https://github.com/JoinColony/colonyCDappAuthProxy/pull/7

![Screenshot 2024-01-22 at 16 56 58](https://github.com/JoinColony/colonyCDapp/assets/18473896/f522641f-3b53-43a6-a2e6-d9e0da6818ab)

Resolves #1560

2024-01-23 09:39 UTC, bassgeta submitted a review, later dismissed

2024-01-23 09:41 UTC, iamsamgibbs submitted a review, later dismissed
Approved! Tested this with colonyCDappAuthProxy#7 and works as expected

2024-01-23 10:22 UTC, rdig requested changes
Note that I've rejected this just because I've rejected https://github.com/JoinColony/colonyCDappAuthProxy/pull/7 as the fix needs to happen at the source, not in the auth proxy

2024-01-23 12:02 UTC, jakubcolony submitted a review, later dismissed
All looks good on this PR, left a comment on the proxy one 👍

2024-01-31 11:21 UTC, iamsamgibbs submitted a review, later dismissed
Tested and this is working well for me now!

(I assume you're already aware as you mention the mess of the action version, but when done with permissions the completed action component shows "manage colony objective" instead of "edit colony details" - if this isn't a known issue we can make a new ticket)

2024-01-31 14:56 UTC, ArmandoGraterol commented
> I assume you're already aware as you mention the mess of the action version, but when done with permissions the completed action component shows "manage colony objective" instead of "edit colony details" - if this isn't a known issue we can make a new ticket

That's correct, this is the PR that fixes that: https://github.com/JoinColony/colonyCDapp/pull/1490

2024-01-31 16:02 UTC, jakubcolony submitted a review, later dismissed

2024-01-31 20:25 UTC, rdig approved these changes
This all works, as the metadata now shows up properly



However

2024-02-14 10:18 UTC, arrenv commented
@ArmandoGraterol Is this one able to be merged?

2024-02-14 22:14 UTC, ArmandoGraterol commented
@arrenv It should be, now :)

2024-02-15 08:17 UTC, iamsamgibbs approved these changes
All still good!

2024-02-15 09:40 UTC, jakubcolony approved these changes

2024-02-15 13:34 UTC, merged