I have replaced alll the as const objects with string enums
JoinColony/colonyCDapp pull request #1791
Opened 2024-01-25 19:00 UTC by malcyb123

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-01-25 19:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1791) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1791) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1791) it.</sub>

2024-01-26 10:19 UTC, jakubcolony requested changes
Hi @malcyb123, thanks for your first PR, your help is much appreciated!

Your PR looks good, I just left you two comments before I can approve. Thanks

2024-01-26 10:19 UTC, jakubcolony commented on src/components/v5/common/ActionSidebar/partials/consts.tsx
> +export enum DISTRIBUTION_METHOD {
Please could you ensure the casing in the names of enums and their members is exactly as in the issue description? This enum should become `DistributionMethod`

2024-01-26 10:19 UTC, jakubcolony commented on src/components/v5/common/ActionSidebar/partials/consts.tsx
>    (typeof DISTRIBUTION_METHOD)[keyof typeof DISTRIBUTION_METHOD];
This is wholly on me for not being specific enough in the issue but the idea behind switching to `enum`s was that we can ditch those types. Could you replace those types with newly added enums everywhere?

2024-01-26 10:45 UTC, chmanie commented
Thank you so much for your work! I just have one little comment and that's on the PR description. We'd really like you to use the template and for you to write a very brief sentence about what you changed. Thanks again ❤️

2024-01-26 17:48 UTC, rdig requested changes
Mostly good, but please revert the package updates first.

After that, I'll approve it.

2024-01-26 17:48 UTC, rdig commented on package.json
> +    "@types/jest": "^26.0.24",
Please revert the package updates, as they are not relevant to this PR

2024-01-26 17:48 UTC, rdig commented on package.json
> +    "uuid": "^9.0.1",
Please revert the package updates, as they are not relevant to this PR

2024-02-08 12:32 UTC, jakubcolony commented
Hi @malcyb123, are you still interested in finishing this PR? Thanks.

2024-02-10 02:47 UTC, malcyb123 commented
> Hi @malcyb123, are you still interested in finishing this PR? Thanks.

Hello, I am sorry I don't think i will be able to complete it due to some emergencies. Thanks

2024-02-12 11:38 UTC, rdig commented
Closing this as no longer having any activity. I've also unassigned #1768 so it's now up for grabs again

2024-02-12 11:38 UTC, closed without merging