feat: add dumb saga and mock component for testing purposes
JoinColony/colonyCDapp pull request #1817
Opened 2024-01-30 10:49 UTC by bassgeta

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves  #1729

2024-01-30 10:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1817) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1817) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1817) it.</sub>

2024-01-31 11:08 UTC, jakubcolony approved these changes
LGTM, nice work! 

Just a heads up the `build` check is failing on this PR

2024-01-31 11:51 UTC, iamsamgibbs commented on src/redux/sagas/actions/addVerifiedMembers.ts
> +    );
I believe this should be replaced with `waitForTxResult` (#1018 currently in progress to replace these globally)

2024-01-31 11:51 UTC, iamsamgibbs requested changes
Looks good to me! Just one minor change request, have left a comment.

2024-01-31 15:38 UTC, iamsamgibbs approved these changes
Thanks for the update! Looks great!

2024-01-31 17:20 UTC, ArmandoGraterol approved these changes
LGTM 👌

2024-02-01 08:55 UTC, merged