Fix: Blockies placeholder during colony creation onboarding flow
JoinColony/colonyCDapp pull request #1867
Opened 2024-02-07 12:41 UTC by iamsamgibbs

## Description

Previously when creating a colony, you would get shown two different blockies when creating the native token. This PR replaces the temporary blockie with a placeholder graphic.

## Testing

1. Generate a new beta invite code.
```
mutation MyMutation {
  createPrivateBetaInviteCode(input: {}) {
    id
  }
}
```
2. Go to: http://localhost:9091/create-colony/{beta-invite-code}
3. Follow the onboarding flow, when creating the token there should be a placeholder image (unless you upload your own image).
4. When completing the onboarding flow a new blockie will be generated for the colony as before.

## Diffs

**Changes** 🏗

* Temporary blockie replaced with placeholder

![Screenshot 2024-02-07 at 12 41 03](https://github.com/JoinColony/colonyCDapp/assets/34915414/45625a45-1359-49b0-a79e-3cd8b143f455)

![Screenshot 2024-02-07 at 12 41 09](https://github.com/JoinColony/colonyCDapp/assets/34915414/b685e13f-4143-4403-95c1-c9dec6ae9bee)

Resolves #1532

2024-02-07 12:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1867) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1867) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1867) it.</sub>

2024-02-07 18:29 UTC, rdig requested changes
I think I found a issue. Granted, it's an edge case.

- Create a new colony + token, make sure to set an image to that token on creation
- Copy that colony's token address
- Create a second new colony, existing token, but use the first colony's token address (the one you copied above)
- In the final step of the creation wizard you'll see the blockies rather than the image

First token created
![Screenshot from 2024-02-07 20-23-17](https://github.com/JoinColony/colonyCDapp/assets/1193222/2f933849-ca06-4a9a-94ff-02bdf86a4a7c)

![Screenshot from 2024-02-07 20-26-44](https://github.com/JoinColony/colonyCDapp/assets/1193222/eb5a63ce-28b6-4b17-abec-7b0f29e3b341)

Second colony, with the first colony's token created
![Screenshot from 2024-02-07 20-23-17](https://github.com/JoinColony/colonyCDapp/assets/1193222/220ea4b1-da8a-4956-948f-862bf98e3cf1)

Also, as a side note, on the above screen, I think the text "Native Token" needs to be replaced with "Existing Token", since you're no longer creating a new, native token, but rather using an existing, external one.

But maybe check with @arrenv about that nomenclature though

2024-02-08 14:47 UTC, iamsamgibbs commented
![Screenshot 2024-02-08 at 14 43 21](https://github.com/JoinColony/colonyCDapp/assets/34915414/15c71546-49fd-4f67-ac25-3b3810d0eb31)

Thanks for picking this up @rdig - I've made the changes to get this working.

2024-02-08 16:55 UTC, rdig submitted a review, later dismissed
All good now.

2024-02-08 17:23 UTC, iamsamgibbs commented
Just clarified the "Native token" naming with @arrenv and it should stay as "Native token" so have reverted that change.

2024-02-09 10:22 UTC, melyndav approved these changes
Looks great @iamsamgibbs! Thanks for picking up my issue and working with me on a fix. Appreciate the effort 👍

2024-02-09 13:12 UTC, rdig approved these changes

2024-02-09 13:38 UTC, merged