Add "complete action" support for missing actions
JoinColony/colonyCDapp pull request #1880
Opened 2024-02-08 18:03 UTC by ArmandoGraterol

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #1826

2024-02-20 10:01 UTC, bassgeta requested changes
Just checked the code for now, looks really great, nice job unifying the rows :D! 
dropped a few comments which are minor. 
I just have another question/proposal. Should we unify these title strings to use the ones from `en-actions.ts` like we use em [here](https://github.com/JoinColony/colonyCDapp/blob/master/src/components/v5/common/ActionSidebar/partials/ActionSidebarDescription/partials/CreateDecisionDescription.tsx) ?

2024-02-20 20:57 UTC, ArmandoGraterol commented on src/components/v5/common/CompletedAction/partials/rows/TeamFrom.tsx
> +          id: 'actionSidebar.tooltip.simplePayment.from',
What's the typo? :ˆ)

2024-02-20 21:06 UTC, ArmandoGraterol commented on src/components/v5/common/CompletedAction/partials/UpgradeColonyObjective/UpgradeColonyObjective.tsx
> +const displayName = 'v5.common.CompletedAction.partials.EditColonyDetails';
Serves me right for being lazy and copy-pasting stuff :)

2024-02-20 21:08 UTC, ArmandoGraterol commented on src/components/v5/common/CompletedAction/partials/rows/PermissionsTable.tsx
> +  if (!role) {
True! It's probably a leftover from when I was adapting the form permission table

2024-02-20 21:12 UTC, ArmandoGraterol commented on src/components/v5/common/CompletedAction/partials/rows/hooks.tsx
> +export const getCustomPermissionsTableColumns = (
I don't mind changing the name of this file to something else as there are no hooks being used here anymore but why `tableFixtures`? (I had to search what `fixtures` is :P) as opposed to something like `consts` or `utils`?

2024-02-21 08:59 UTC, bassgeta commented on src/components/v5/common/CompletedAction/partials/rows/TeamFrom.tsx
> +          id: 'actionSidebar.tooltip.simplePayment.from',
ah you're right this one is intended, I thought we need a generic from, resolving this comment

2024-02-21 08:59 UTC, bassgeta commented on src/components/v5/common/CompletedAction/partials/EditColonyDetails/EditColonyDetails.tsx
> +      <SocialLinksTable socialLinks={actionColonyMetadata?.externalLinks} />
yeah maybe we just not render the component if we have undefined data and the component can always operate with the fact that data is defined :+1:

2024-02-21 09:00 UTC, bassgeta commented on src/components/v5/common/CompletedAction/partials/rows/hooks.tsx
> +export const getCustomPermissionsTableColumns = (
I used fixtures due to me naming it so in another project, but I am not opinionated on the naming (i suck at naming after all). so we can rename it to a utils.tsx for the moment or whatever you feel is best

2024-02-22 09:03 UTC, bassgeta approved these changes
all good now, great job, tested out some actions and works like a charm :+1:

2024-02-22 10:46 UTC, iamsamgibbs commented on src/components/v5/common/ActionSidebar/partials/forms/ManagePermissionsForm/consts.tsx
> +    createdIn: number().defined(),
I think this change is preventing the form from being submitted when using the permissions decision method.

![Screenshot 2024-02-22 at 10 45 44](https://github.com/JoinColony/colonyCDapp/assets/34915414/65d62b6e-a34c-4ce1-8331-d180e5d0a004)

2024-02-22 10:55 UTC, iamsamgibbs requested changes
Great work on this! All the code changes look great and working as expected.

I've left one code comment where a validation change is preventing the manage permissions form from submitting with permissions.

The completed view for "manage colony objective" is also missing the percentage sign after the number.

![Screenshot 2024-02-22 at 10 26 32](https://github.com/JoinColony/colonyCDapp/assets/34915414/ff1add87-2a15-4573-8794-4016b8d16672)

(Unrelated to this issue, but I also noticed the "edit team" action is missing the description field, but it looks like the completed action view would show this correctly if it were there - not sure if that is quick and easy for you to add in with this PR, or can open as a new issue)

![Screenshot 2024-02-22 at 10 24 37](https://github.com/JoinColony/colonyCDapp/assets/34915414/3e1a0976-99a1-4a3c-a31d-e2d83921f32c)

2024-02-22 17:12 UTC, ArmandoGraterol commented
@iamsamgibbs 
> I've left one code comment where a validation change is preventing the manage permissions form from submitting with permissions.

> The completed view for "manage colony objective" is also missing the percentage sign after the number.

Fixed!

> (Unrelated to this issue, but I also noticed the "edit team" action is missing the description field, but it looks like the completed action view would show this correctly if it were there - not sure if that is quick and easy for you to add in with this PR, or can open as a new issue)

This was fixed when I did the rebase but yeah, the fix was gonna be easy and could have been included in this PR :)

2024-02-23 09:09 UTC, iamsamgibbs approved these changes
Works great now, thanks for the changes! 🎉

2024-02-23 13:35 UTC, warrencolliver approved these changes
working fine for me! great work

2024-02-26 09:24 UTC, iamsamgibbs approved these changes

2024-02-26 11:18 UTC, bassgeta approved these changes

2024-02-26 14:11 UTC, merged