Fix: Completed action rich text description formatting
JoinColony/colonyCDapp pull request #1887
Opened 2024-02-09 15:34 UTC by iamsamgibbs

## Description

Rich text should be formatted correctly in both the creation and completed state.

Previously the HTML from the description input field was being stripped out as part of the error validation, as such it was not being properly submitted. This has been replaced with a custom yup test.

[TODO: format completed action description)

## Testing

1. Write a rich text description in an action.
2. Create a Simple payment action with a description.
3. Complete the action and view the description in the completed state.

## Diffs

**Changes** 🏗

* `ACTION_BASE_VALIDATION_SCHEMA` description max length validation replaced with custom yup test.

## TODO

- [ ] Fix completed action formatting

Resolves #1776

2024-02-09 15:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1887) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1887) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1887) it.</sub>

2024-02-09 17:39 UTC, arrenv requested changes
Nice one @iamsamgibbs, this is looking much better.

I am still not able to get Reputation decision method working locally, so could not test them.

The one thing I noticed is that empty lines seem to get ignored. Is there something where we can limit it to 1, but not allow more then 2 empty lines?

Having one seems to make it easier to ready, but allowing infinite means that people can just submit big empty descriptions.

### Before
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/326a473d-c8e2-4121-b248-5b23f5617757)

### After
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/4b662b0f-c06f-4c87-a8d4-536ead4131c9)

2024-02-12 09:53 UTC, iamsamgibbs commented
Thanks for testing @arrenv and picking up the spacing issue, I've pushed up a fix for this so it now matches the action sidebar description editor.

The way the editor handles new lines is to just make new paragraph tags, so I think if we want to restrict to just 2 lines of empty space, then it would be better to add this restriction on the action sidebar editor rather than on the completed view. This will ensure the styling on the completed action accurately reflects how the description was entered in the editor.

![Screenshot 2024-02-12 at 09 42 15](https://github.com/JoinColony/colonyCDapp/assets/34915414/1fd23092-ad47-466d-8f39-947945124d0a)

Can also confirm the permissions completed action uses the same description component and looks the same.

2024-02-12 19:50 UTC, rdig approved these changes
Working as expected. Nice job!

![Screenshot from 2024-02-12 21-46-24](https://github.com/JoinColony/colonyCDapp/assets/1193222/7410d6db-f100-4b89-b541-04cdc7950b5b)

Not related to this specifically, but I did found that if you try to write a code block, you do run into some "weird" interactions

[Screencast from 2024-02-12 21-48-30.webm](https://github.com/JoinColony/colonyCDapp/assets/1193222/d02499de-6a31-4d31-92c2-4f014096a3fc)

2024-02-12 20:50 UTC, arrenv requested changes
The spacing works much better, thanks for that @iamsamgibbs.

> The way the editor handles new lines is to just make new paragraph tags, so I think if we want to restrict to just 2 lines of empty space, then it would be better to add this restriction on the action sidebar editor rather than on the completed view. This will ensure the styling on the completed action accurately reflects how the description was entered in the editor.

Do you have an example of this?

This is what we are trying to avoid.

#### Creation
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/ddf08db8-31ee-4138-9a06-15b224e4a26d)

#### Completed default (collapsed)
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/599c4826-d10a-44d1-aae8-bf616e2473d0)

#### Completed (expanded)
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/4aee2849-1fcf-45bf-a509-f4b29a9d3786)

2024-02-13 14:34 UTC, iamsamgibbs commented
@arrenv Ah, I was suggesting having the editor handle it as a possible solution rather than work I’ve actually implemented.

I’ve had a bit of a look today at how feasible it would be to limit the editor input to only allow a maximum of 2 lines of empty space and I think it would be doable and still the best solution but it would be best to create a new issue for this.

2024-02-13 15:09 UTC, merged