fix: styles on mobile for main nav
JoinColony/colonyCDapp pull request #1895
Opened 2024-02-13 11:55 UTC by CzarekDryl

https://tw.auroracreation.com/app/tasks/15787761

![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/722f339b-75c3-4119-85a9-805c52a5efae)

## Description

- Fixed UI styles for colony switcher on mobile

Resolves [1893](https://github.com/JoinColony/colonyCDapp/issues/1893)

2024-02-13 14:10 UTC, warrencolliver submitted a review, later dismissed
Looks good to me - icons are now 18px and the padding sizes have been resolved.
![Screenshot 2024-02-13 at 14 10 38](https://github.com/JoinColony/colonyCDapp/assets/155957480/f5839f1a-8c63-406d-831c-f902923f2f3e)

2024-02-13 14:18 UTC, melyndav requested changes
Hey @CzarekDryl thanks for picking up my issue. Everything looks good, just one minor change, can you match the user avatar height to the others in the top header?Should be 18px and looks like it's still 16px. Thanks! 

<img width="295" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/410daf0f-ed29-4061-bb6f-1018ea2565bb">

2024-02-14 10:11 UTC, melyndav approved these changes
Perfect @CzarekDryl! Smashed it. Approved from my side 👍

2024-02-14 14:00 UTC, warrencolliver approved these changes
Looks good - re approving

2024-02-14 15:46 UTC, ArmandoGraterol approved these changes
LGTM 👍

2024-02-15 09:13 UTC, merged

2024-02-15 15:46 UTC, rdig commented on src/components/common/Extensions/UserNavigation/partials/HeaderAvatar/HeaderAvatar.tsx
> +      <UserAvatar user={user || wallet?.address} showUsername size="xss" />
@CzarekDryl This change broke the user name display on the landing page

![Screenshot from 2024-02-15 17-40-30](https://github.com/JoinColony/colonyCDapp/assets/1193222/52d584d9-ddb1-43d8-8667-fe68bb56539b)
![Screenshot from 2024-02-15 17-44-41](https://github.com/JoinColony/colonyCDapp/assets/1193222/2bacbc52-8931-4d6a-80ed-1b1d0c54d1ae)

However, it does work fine when you're on a colony's home / dashboard

![Screenshot from 2024-02-15 17-40-35](https://github.com/JoinColony/colonyCDapp/assets/1193222/9faeb4a9-f9d5-459b-9e5f-a18c937db245)

Please open a separate PR to fix this.