Fix/1629 paragraph input fields within action types
JoinColony/colonyCDapp pull request #1907
Opened 2024-02-14 14:51 UTC by KornelKwiatkowski

## Description

Fields for entering text in the action form are now unified.

## Testing

The tests consist in checking whether the "Objective description", "Description" and "Colony description" fields work in the same way.

Instructions for testing this branch:

* Step 1. Create "Edit Colony details" or "Manage Colony objective" action
* Step 2. Check if "Objective description", "Description" and "Colony description" fields work in the same way

## Diffs

**Changes** 🏗

- From now on, the text does not overflow outside the component.
- The missing icons have been added to the fields (chevron arrows)
- The validation for the fields 'Colony description' and 'Objective description' has been fixed.

Resolves: https://github.com/JoinColony/colonyCDapp/issues/1629

2024-02-14 14:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1907) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1907) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1907) it.</sub>

2024-02-14 16:56 UTC, warrencolliver requested changes
Thanks for your work on this, However I did pick up on 2 small things

1. when submitting a action, the description field isn't displayed in the action summary once submitted (this happens on both tasks)
![Screenshot 2024-02-14 at 16 52 20](https://github.com/JoinColony/colonyCDapp/assets/155957480/1d2a1726-455b-41de-a25c-3fbed615e91c)

2.  If I use one long single word (no breaks) and contract the field the same issue occurs where the text doesn't wrap and continues off screen.
![no wrap on no break](https://github.com/JoinColony/colonyCDapp/assets/155957480/abd8d937-e331-4cf9-a619-34b4a0e43e36)

2024-02-15 10:29 UTC, melyndav requested changes
Hey @KornelKwiatkowski this PR is introducing a lot of unintended issues including changing the main description field, adding elements that aren't intended to be in this field etc. 

What we want is:

1. The objective description works as exactly the same as the Colony description in the 'Edit Colony details' action. I.e the content should wrap and the chevron should be ignored. 

All other changes should be reverted.

2024-02-15 14:32 UTC, KornelKwiatkowski commented
@melyndav done :)
If you can, please update the task: https://github.com/JoinColony/colonyCDapp/issues/1629

2024-02-16 18:34 UTC, ArmandoGraterol approved these changes
Looking good! They both work the same

2024-02-19 09:41 UTC, iamsamgibbs approved these changes
This looks good to me! (Although I couldn't test how it looks in the motion state as the edit colony details motion isn't pulling through the data properly)

2024-02-19 10:16 UTC, melyndav approved these changes
Thanks @KornelKwiatkowski for making the changes to the scope, much appreciated. Works much better now. 👍

2024-02-27 12:23 UTC, warrencolliver approved these changes
Good work on the changes

2024-03-06 12:53 UTC, merged