feat: added permissions page filter
JoinColony/colonyCDapp pull request #1913
Opened 2024-02-15 12:34 UTC by CzarekDryl

https://tw.auroracreation.com/app/tasks/15763226

## Description

- Added filters to permissions page
- Added permissions and agreements pages to be visible on prod

Resolves [1824](https://github.com/JoinColony/colonyCDapp/issues/1824), [1908](https://github.com/JoinColony/colonyCDapp/issues/1908)

2024-02-15 16:48 UTC, ArmandoGraterol requested changes
I've noticed this warning appears every time I open the permission types popover:
![Screenshot 2024-02-15 at 13 47 19](https://github.com/JoinColony/colonyCDapp/assets/18473896/3d6bf28f-7987-4aef-8e9f-1e96a121d851)

2024-02-15 16:48 UTC, ArmandoGraterol commented on src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageFilter.tsx
> +              <>
This empty bracket is not needed

2024-02-15 16:48 UTC, ArmandoGraterol commented on src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageFilter.tsx
> +              <>
Same here

2024-02-15 16:48 UTC, ArmandoGraterol commented on src/components/frame/Extensions/pages/PermissionsPage/partials/PermissionsPageFilter.tsx
> +                            <span className="text-4 text-gray-400 px-3.5 uppercase">
Same here

2024-02-16 15:56 UTC, warrencolliver submitted a review, later dismissed
all looks good to me! 

filter checklist & search filter work fine and the empty permission types are hidden.

2024-02-16 19:05 UTC, ArmandoGraterol submitted a review, later dismissed
Nice work! Thank you for addressing the requested changes :)

2024-02-19 09:27 UTC, iamsamgibbs requested changes
This is looking really good so far, but I've noticed a few issues.

The main issue is that users with custom permissions do not show at all on the members page.

I assume the Reputation Weighted extension should not show if it is not installed / enabled? May need @arrenv to confirm.

When just the "custom" filter type is selected, there is no active filter shown.

https://github.com/JoinColony/colonyCDapp/assets/34915414/381abf96-d6ab-48fc-8a8e-1289fe457c42

On mobile, when opening the filters modal, I get the `Each child in a list should have a unique "key" prop.` error in the console.

The entire page shifts when opening the user popover.

https://github.com/JoinColony/colonyCDapp/assets/34915414/9296323c-58ef-4a8f-954a-dd8a1a445bea

2024-02-19 09:56 UTC, arrenv commented
> I assume the Reputation Weighted extension should not show if it is not installed / enabled? May need @arrenv to confirm.

Basically, if it has permissions then it should show on the permissions page. If it does not have permissions, which is likely if not installed, or possible if not enabled, then correct, it should not appear.

2024-02-19 10:03 UTC, melyndav requested changes
Hey @CzarekDryl great start on this! Some feedback points:

1. Icon should be 18x18px as per the design system component - 
<img width="166" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f24ba0c2-63e3-4e38-89b1-5121c8034950">
 
 https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1782-13112&mode=design&t=WFM99rbhmm6YoSHO-4
 
 2. The two buttons next to each other have different heights. They are both a secondary button and should be the same. Check the design system link in Figma above to check both buttons to sure they are correct. 
 
<img width="167" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/4435cd02-6cb5-4f3b-8356-9a91c7874f2c">

3. The active pill design should match the one @joanna-pagepro has in her activity feed PR #1914 since this is the correct stysling (x icon and padding are incorrect)
<img width="153" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2b99ba45-88a9-4bae-b7e7-8e92fc965b98">

4. Search input has the incorrect placeholder copy in the input
<img width="550" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/01fe3471-c602-4623-b300-50d596c9f292">

5. There are alignment problems inside the filter pill on mobile when a filter is active
<img width="142" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/246a70c2-7a61-459f-9d92-2abf5b8ff855">

6. Mobile needs to be updated with the correct copy in both places
<img width="410" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/9fca126c-72b9-4892-a328-ac5460bd4f82">

7. The size of the X inside the input when content is added doesn't match Figma on desktop and mobile.
<img width="248" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/1e79dd53-5ae8-4aff-972a-b140b82ae5da">

2024-02-19 14:47 UTC, CzarekDryl commented
@arrenv and @iamsamgibbs Issue with showing not installed extensions will be handled in other task - [1872](https://github.com/JoinColony/colonyCDapp/issues/1872)

2024-02-20 15:50 UTC, iamsamgibbs submitted a review, later dismissed
This is looking better, thanks for addressing those UI issues!

2024-02-21 15:12 UTC, melyndav submitted a review, later dismissed
Hey @CzarekDryl thanks again for your continued work on the PR.

1. There seems to be an issue with the counting. Here you can see I have 4 filters active in the UI but it's showing as 10 (second screenshot).

It's because when you de-select the custom option, it doesn't de-select all of the sub options under custom and still counts them. But I can only see 4 (on mobile) unless I re-select the custom option to view the others.

Please implement: If custom is deselected in the top level at any point, all child options should deselect as well. Thanks! 

<img width="394" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/101a5136-9837-412b-a564-23736225bf3b">

<img width="200" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/522bb3ab-e2c0-4df2-92e7-66e0a8999e6f">

Desktop 
<img width="1025" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f1a398f5-0eb8-46e8-9aa4-e26a35d9d685">


2. Chevron arrow on mobile is the wrong colour token and should be the gray 900.

3. Can we get the correct filter & sort heading added in?

<img width="644" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ce30e7ac-dd9e-41a6-9b3c-dad9952d0a58">

4. For searching empty states, can we match the styling of every other no search result component with the border and padding? All the text etc should remain the same, but just make it consistent with the other filters you're implementing for desktop and mobile.

<img width="1318" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d1c743d9-8173-486f-b7ec-acd8d3f01fba">

2024-02-26 09:20 UTC, iamsamgibbs requested changes
Thanks for the changes, the requests Mel requested are looking all resolved except for the mobile filtering showing an incorrect count.

https://github.com/JoinColony/colonyCDapp/assets/34915414/5456fd7e-b3e3-439b-a646-c780d5e8b0c9

2024-02-26 10:09 UTC, iamsamgibbs approved these changes
Perfect, thanks for the fix!

2024-02-26 17:30 UTC, ArmandoGraterol approved these changes
Thank you for the changes! Looks good to me 👌

2024-02-27 15:03 UTC, rdig approved these changes
Approving so we can get this merged

2024-02-28 07:43 UTC, merged