Feature: Advanced Payments
JoinColony/colonyCDapp pull request #1922
Opened 2024-02-16 09:57 UTC by jakubcolony

## Description

Advanced Payments feature branch

2024-03-01 16:07 UTC, iamsamgibbs requested changes
Seems like this is mostly still intact! Just a few notes:

#1924 - There was a recent commit to remove decisionMethod field from expenditures - so assume this is no longer required?

#1918 - expenditure balances in the query did not update after finalising (balance on the balance page did update correctly though)

#1958 - unable to test as the create staked expenditure button returns this gasEstimation error in the console: `colony-token-locking-insufficient-deposit`

(I also had to run block-ingestor#176 separately as I was having weird gas estimation issues otherwise, but the commit hash looks correct, so probably just a weird issue with my dev environment)

2024-03-04 22:07 UTC, jakubcolony commented
Hey @iamsamgibbs, thanks for your thorough review!

> https://github.com/JoinColony/colonyCDapp/pull/1924 - There was a recent commit to remove decisionMethod field from expenditures - so assume this is no longer required?

That's right, it was supposed to keep track of the user's preferences when it came to funding an expenditure, but the designs have been updated and it's no longer needed.

> https://github.com/JoinColony/colonyCDapp/pull/1958 - unable to test as the create staked expenditure button returns this gasEstimation error in the console: colony-token-locking-insufficient-deposit

Sounds like you don't have enough active tokens - have you activated some before attempting to stake?

> https://github.com/JoinColony/colonyCDapp/pull/1918 - expenditure balances in the query did not update after finalising (balance on the balance page did update correctly though)

Great spot, should be fixed now.

> (I also had to run block-ingestor#176 separately as I was having weird gas estimation issues otherwise, but the commit hash looks correct, so probably just a weird issue with my dev environment)

Not something I could reproduce but give me a shout if you run into those again.

2024-03-05 16:09 UTC, iamsamgibbs commented
> Sounds like you don't have enough active tokens - have you activated some before attempting to stake?

🤦‍♂️ You're completely right, I missed that step in the testing instructions. That all works fine, however I wasn't able to cancel and punish an expenditure. Everything else is good though!

2024-03-06 20:59 UTC, jakubcolony commented
> That all works fine, however I wasn't able to cancel and punish an expenditure.

Another great spot, the saga was getting stuck due to wrong order of calls, fixed!

2024-03-11 14:08 UTC, iamsamgibbs requested changes
Left a comment which is preventing 'Cancel and punish' from working (works fine when reordered), otherwise all good!

2024-03-11 14:08 UTC, iamsamgibbs commented on src/redux/sagas/expenditures/cancelDraftExpenditure.ts
> +      yield initiateTransaction({ id: cancelAndReclaimStake.id });
initiateTransaction needs to be moved to above takeFrom

2024-03-11 14:08 UTC, iamsamgibbs commented on src/redux/sagas/expenditures/cancelStakedExpenditure.ts
> +    yield initiateTransaction({ id: cancelStakedExpenditure.id });
And here too

2024-03-12 21:31 UTC, jakubcolony commented
@iamsamgibbs fixed

2024-03-13 08:46 UTC, iamsamgibbs approved these changes
All good now! 🎉

2024-03-13 14:12 UTC, ArmandoGraterol submitted a review, later dismissed
LGTM 👌

2024-03-20 22:30 UTC, merged