Advanced Payments: Store selected decision method for an expenditure
JoinColony/colonyCDapp pull request #1924
Opened 2024-02-16 12:02 UTC by iamsamgibbs

## Description

The UI requires storing the selected decision method for an expenditure for later reference.

This PR:
- Modifies the `createExpenditure`, `createStakedExpenditure` sagas to accept a decision method parameter
- Modifies the schema (`ExpenditureMetadata` model) to add a field storing the selected method 

## Testing

There is a temporary button to create an expenditure from root domain to the currently logged in user with one payout of 10 ETH in colony's native token with the 'Permissions' decision method.

You can then run the following query to confirm the decision method has been saved correctly: (If you have previously ran the create-data script there will be a bunch of expenditures without metadata, but the newly created expenditure should be correct)

```
query ListExpenditures {
  listExpenditures {
    items {
      metadata {
        decisionMethod
      }
    }
  }
}
```

## Diffs

**Changes** 🏗

* `createExpenditure`, `createStakedExpenditure` sagas now accept a decision method parameter
- `ExpenditureMetadata` model now has a decisionMethod field 

Resolves #1878

2024-02-16 12:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1924) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1924) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jakubcolony<br/>:x: iamsamgibbs<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1924) it.</sub>

2024-02-16 16:13 UTC, rdig approved these changes
Tested. Does exactly what it says on the tin. Nice work!

![Screenshot from 2024-02-16 18-11-39](https://github.com/JoinColony/colonyCDapp/assets/1193222/d0f79192-3139-4c7f-a996-a2d7391999ad)
![Screenshot from 2024-02-16 18-13-04](https://github.com/JoinColony/colonyCDapp/assets/1193222/3a1a7f84-2a0d-42b0-a6ca-a5f479c6bd92)

2024-02-16 17:58 UTC, warrencolliver approved these changes
Looks good. all working fine for me

2024-02-16 23:16 UTC, ArmandoGraterol approved these changes
Good to go 🎉

2024-02-19 14:12 UTC, jakubcolony requested changes
Great work @iamsamgibbs, the functionality works as intended, I was just wondering if you could make the new enum more expenditures-specific? Thanks!

2024-02-19 16:17 UTC, jakubcolony approved these changes
All looking good now! 👍

2024-02-19 17:13 UTC, merged