[Advanced payments] feat: add annotation support to all expenditure sagas
JoinColony/colonyCDapp pull request #1941
Opened 2024-02-19 14:55 UTC by bassgeta

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs
Resolved #1043

2024-02-20 18:52 UTC, rdig requested changes
The expenditure creates successfully but the metadata gets a "forbidden" message when trying to send the mutation

![Screenshot from 2024-02-20 20-49-37](https://github.com/JoinColony/colonyCDapp/assets/1193222/5a1ca7ba-ba90-4e34-880e-3ae520ea220a)
![Screenshot from 2024-02-20 20-49-52](https://github.com/JoinColony/colonyCDapp/assets/1193222/454d8141-e14b-42aa-a342-c67ec37a2632)
![Screenshot from 2024-02-20 20-49-56](https://github.com/JoinColony/colonyCDapp/assets/1193222/133093be-dd26-48f0-bde8-f779d5400213)

Is this expected? And/or the issue we've spoken about during Monday's team meeting ?

Also, I think the base feature branch needs to be rebased from `master` as it seems quite out of data

2024-02-21 10:03 UTC, jakubcolony requested changes
Thanks for your work on this PR @bassgeta, annotations part looks good but custom titles are out of scope of the issue and as @rdig pointed out, they don't work anyway (as the auth proxy check for them requires the underlying action to exist). Moreover, custom titles will only be relevant for create expenditure/create staked expenditure sagas (other sagas will not trigger an action).

Could you please remove all custom title references?

2024-02-23 14:41 UTC, jakubcolony requested changes
Thanks for removing custom titles, all looks good other than missing tx channel closing step

2024-02-23 14:41 UTC, jakubcolony commented on src/redux/sagas/expenditures/cancelDraftExpenditure.ts
I think you still need to close the channels, have a look at `createExpenditure` to see how to do that with mulitple channels.

2024-02-23 14:41 UTC, jakubcolony commented on src/redux/sagas/expenditures/cancelStakedExpenditure.ts
>    return null;
Same here

2024-02-26 11:34 UTC, jakubcolony approved these changes
Smashing work @bassgeta 👌

2024-02-26 21:29 UTC, rdig approved these changes
Seems all good now. Nice work! :+1:

2024-02-27 10:02 UTC, merged