Fix: Inconsistent versions of colony network and extensions
JoinColony/colonyCDapp pull request #1966
Opened 2024-02-21 17:02 UTC by iamsamgibbs

## Description

There are various inconsistencies with Colony network versions and extension versions that are shown or are being picked up in the UI.

Previously, the action sidebar new version was hardcoded to be +1 from the current version. This PR gets the correct version from the context.

Previously, the extensions page would show the latest available version even if an older version was installed, this would result in inconsistencies with the extension details page which shows the current version. This PR shows the currentVersion if the extension is enabled.

Please someone suggest a better approach to this as it feels bad. extension.isEnabled feels like the better thing to check against, but typescript will complain that extension.currentVersion does not exist on AnyExtensionData as it only exists on the InstalledExtensionData and not on InstallableExtensionData.
```
                  version={
                    'currentVersion' in extension
                      ? extension.currentVersion
                      : extension.availableVersion
                  }

```

## Testing

This is a bit hard to properly test as it would require installing older versions of the colony network and extensions, it should be possible to verify by looking at the code.

Create an action to upgrade the colony, the new version row and action description should both show the correct latest version (14).

Extensions page will now show current version if installed rather than the latest available version

## Diffs

**Changes** 🏗

* Action sidebar now correctly shows latest colony contract version
* Extensions page now shows current version if installed rather than available version

![Screenshot 2024-02-21 at 15 37 00](https://github.com/JoinColony/colonyCDapp/assets/34915414/14aaf333-1473-469c-bd7e-4aebc35b53f0)

Resolves #1838

2024-02-21 17:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1966) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=1966) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=1966) it.</sub>

2024-02-22 09:43 UTC, bassgeta submitted a review, later dismissed
Code looks like it makes sense, if you want to rewrite the version value, you can extract it into a function `getExtensionVersion` which would check if extension is installed and if available version exists, but I don't have any qualms with the approach you've used here :D

2024-02-22 14:10 UTC, jakubcolony submitted a review, later dismissed
Great work @iamsamgibbs, looks like that'll fix all the issues, I left you a comment on how you could improve the `'currentVersion' in extension` check

2024-02-22 14:10 UTC, jakubcolony commented on src/components/frame/Extensions/pages/ExtensionsPage/ExtensionsPage.tsx
> +                  }
`isInstalledExtensionData` type guard will help you here

2024-02-23 09:51 UTC, bassgeta approved these changes
nice one :sunglasses:

2024-02-23 15:31 UTC, rdig requested changes
Versions show up correctly in the UI, both colony and extensions

![Screenshot from 2024-02-23 17-24-04](https://github.com/JoinColony/colonyCDapp/assets/1193222/e21a96e1-e9b7-4e13-a1a0-b5c6d0921adc)
![Screenshot from 2024-02-23 17-24-13](https://github.com/JoinColony/colonyCDapp/assets/1193222/9a166a48-a787-443e-8abd-402a5a4d5749)
![Screenshot from 2024-02-23 17-25-08](https://github.com/JoinColony/colonyCDapp/assets/1193222/140d24e5-9983-4a85-be7f-eda9b9ce4acc)
![Screenshot from 2024-02-23 17-25-24](https://github.com/JoinColony/colonyCDapp/assets/1193222/c836f0cb-a5cd-47b3-a3f6-887da11049f5)
![Screenshot from 2024-02-23 17-25-30](https://github.com/JoinColony/colonyCDapp/assets/1193222/647468ee-ee5e-4e85-8337-538b6c62b180)
![Screenshot from 2024-02-23 17-29-32](https://github.com/JoinColony/colonyCDapp/assets/1193222/3ddcab44-dd3c-4e80-af36-03472928b549)
![Screenshot from 2024-02-23 17-26-05](https://github.com/JoinColony/colonyCDapp/assets/1193222/fa01e4e3-bae4-41c8-aaa7-aeae326db6d1)
![Screenshot from 2024-02-23 17-26-12](https://github.com/JoinColony/colonyCDapp/assets/1193222/eb50e246-2b03-4262-b3b3-aef59ce1cca7)


However, I cannot / am not allowed to upgrade extensions at all. Upgrade button disabled by default.

![Screenshot from 2024-02-23 17-26-57](https://github.com/JoinColony/colonyCDapp/assets/1193222/4b42298d-8205-457f-b1a3-9ec3ef382340)

So this needs further investigation.

2024-02-26 17:39 UTC, iamsamgibbs commented
@rdig I think it is not possible to upgrade to version 7 of OneTxPayment here because the disabled button check calls `isExtensionCompatible` from `@colony/colony-js` which checks if the version is included in the [oneTxPaymentIncompatibilityMap](https://github.com/JoinColony/colonyJS/blob/22179035ed7b28e0604dc5d06863755f248d97e5/packages/core/src/versions/OneTxPayment.ts#L15) If I've understood correctly, upgrading from version 5 to 6 should be possible, so I don't believe this to be a bug.

2024-02-26 18:30 UTC, rdig commented
@iamsamgibbs I'm incline to believe you, since I did indeed "fake" the version number.

I am however remembering this not working correctly in production, so I'll test again just to be sure.

2024-02-26 20:49 UTC, rdig approved these changes
You were indeed correct Sam! :100: 

If I use a "proper" version number the upgrade button seems to be working / behaving as expected

![Screenshot from 2024-02-26 22-48-51](https://github.com/JoinColony/colonyCDapp/assets/1193222/80f114be-3292-4de9-bc8b-2746efb4a7a4)

Nice work!

2024-02-27 08:59 UTC, iamsamgibbs commented
Thanks for looking into that and confirming!

2024-02-27 09:00 UTC, merged