Connect expenditures with actions model
JoinColony/colonyCDapp pull request #1969
Opened 2024-02-21 23:28 UTC by jakubcolony

## Description

Advanced payments feature requires displaying payments in the activity feed. This PR introduces relations between expenditures and actions model so that there's a corresponding action created for each expenditure.

## Testing

TBC...

Resolves #1102

2024-02-23 10:52 UTC, bassgeta approved these changes
works, nice one :+1: 
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/36f3d627-9f35-432f-b728-b83d6a286ac8)
it even shows up in the UI :D!

2024-02-23 11:53 UTC, iamsamgibbs approved these changes
Tested and all working as expected!

2024-02-23 12:03 UTC, iamsamgibbs requested changes
Oh scratch that, this seems to have created issues with creating simple payments via the action sidebar (403 response).

2024-02-23 16:42 UTC, jakubcolony commented
Good spot @iamsamgibbs, this is part of a bigger issue that we now have with distinguishing between simple and advanced payments (they all use expenditures under the hood!). This needs a product discussion, so putting this PR on hold.

2024-03-14 21:06 UTC, jakubcolony commented
@bassgeta @iamsamgibbs I've reworked this PR and it's ready for another review

2024-03-15 17:07 UTC, ArmandoGraterol approved these changes
Working as expected for me 👌

2024-03-17 17:01 UTC, merged