Fix: change not enough reputation error message
JoinColony/colonyCDapp pull request #1986
Opened 2024-02-26 21:41 UTC by warrencolliver

## Description

This PR changes the error message a user gets when they don't have enough reputation to contribute to a stake decision

## Testing

1. Create a motion in a team using the Reputation Decision method (I created an agreement).
2. View the decision from a user without any reputation in the team
3. Correctly, you won't be able to stake on the action and you will get an error message.

## Diffs

**Changes** 🏗

New error message can be seen here:
![Screenshot 2024-02-26 at 21 37 44](https://github.com/JoinColony/colonyCDapp/assets/155957480/7a4be1d1-3b82-4af2-a1df-26ad73344ea4)

I've added some code to get the user's team / domain name to display it in the error message, however it feels messy, if someone has a better suggestion on how to get the team name please let me know.

Resolves #1940

2024-02-27 10:06 UTC, iamsamgibbs requested changes
Looks like this will always return `General` as the team regardless of which team the motion was created in. You should be able to get the correct team from `motionAction.motionData.motionDomain.metadata?.name`

2024-02-27 18:09 UTC, ArmandoGraterol approved these changes
LGTM 👍 Nice job Warren!

2024-02-28 11:05 UTC, iamsamgibbs approved these changes
Looks good to me now! 🎉 Changes for the change

<img width="329" alt="Screenshot 2024-02-28 at 11 04 37" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/564f54b2-7b7a-43f8-84b4-ec3537e80f39">

2024-02-28 18:39 UTC, rdig approved these changes
All good.

Sorry I'm adding a third review on a PR that has enough already, but I actually ran out of things to review :)

2024-02-29 10:37 UTC, merged