fix: team reputation summary and agreements widget
JoinColony/colonyCDapp pull request #1987
Opened 2024-02-27 09:45 UTC by joanna-pagepro

Agreement widget:
Before:
![image](https://github.com/JoinColony/colonyCDapp/assets/44369011/38a9cd74-0992-4f93-8aff-f7507269de4b)
After: 
![image](https://github.com/JoinColony/colonyCDapp/assets/44369011/bae75da8-7da8-4954-8286-45131ef5106d)

Team reputation Summary widget:
https://github.com/JoinColony/colonyCDapp/issues/1935
Does not show `M` when not needed
![image](https://github.com/JoinColony/colonyCDapp/assets/44369011/a75fb4d3-6389-471c-935f-ad00a4569a74)

2024-02-27 11:31 UTC, warrencolliver submitted a review, later dismissed
looks good to me

2024-02-27 11:50 UTC, iamsamgibbs requested changes
Thanks for fixing this up. Reputation summary looks good. I'm not 100% sure as it isn't clear from the figma design, but I think the agreements widget should show the unformatted description (it is unformatted on the agreements page so makes sense to make that it should be consistent). Currently it shows the formatted description.

Widget:
<img width="485" alt="Screenshot 2024-02-27 at 11 43 44" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/ee993b8e-2733-4f17-935d-d53989a6e0b6">

Page:
<img width="611" alt="Screenshot 2024-02-27 at 11 48 36" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/f4f7f071-88be-4e48-9234-197afa31ba3f">

Would be good to get @melyndav to confirm before making this change.

2024-02-27 11:59 UTC, joanna-pagepro commented
@iamsamgibbs good catch, thanks!
I've checked the requirements here: https://github.com/JoinColony/colonyCDapp/issues/1789 and it shouldn't be formatted.
![image](https://github.com/JoinColony/colonyCDapp/assets/44369011/bb70f1f7-8df2-46d6-be86-c7867209a72e)

2024-02-27 18:31 UTC, ArmandoGraterol approved these changes
LGTM 👍

2024-02-28 08:06 UTC, joanna-pagepro commented
@iamsamgibbs I need an approval from you :)

2024-02-28 10:59 UTC, iamsamgibbs approved these changes
All looks good, thank you for the change!

<img width="443" alt="Screenshot 2024-02-28 at 10 57 52" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/a7678acc-a11f-4265-a237-d005096db55c">

2024-02-28 11:10 UTC, merged