Feat/15704056 filter pills
JoinColony/colonyCDapp pull request #1993
Opened 2024-02-28 09:22 UTC by CzarekDryl

[tw task](https://tw.auroracreation.com/app/tasks/15704056)

## Description

- Added filters to funding page

Acceptance criteria

- user should see a pills for Active Filters
- user should be able to close pills and by that reset filter

2024-02-28 14:33 UTC, CzarekDryl commented
@iamsamgibbs I've missed one place when renaming variables 😢

2024-02-28 16:15 UTC, ArmandoGraterol requested changes
Nice job! I only noticed 1 thing.

I unmarked the `Custom` filter, yet the "subfilters" were still active:
![Screenshot 2024-02-28 at 13 11 12](https://github.com/JoinColony/colonyCDapp/assets/18473896/10f0af0a-a524-4a7a-ba53-47cc9f440302)

2024-02-29 07:39 UTC, CzarekDryl commented
@ArmandoGraterol I think you've checked wrong page. Filters that I added are on `/incoming` page.

2024-02-29 08:53 UTC, iamsamgibbs requested changes
Good work on this so far, almost ready to go.

I feel like the 'Token status' filter should work similarly to the 'User status' filter on the members page where it can be either option or off to show both. Currently when neither option is selected you get no results at all.

![Screenshot 2024-02-29 at 08 46 16](https://github.com/JoinColony/colonyCDapp/assets/34915414/38d686c5-9dd8-42f6-9b61-c09d5ba0f8db)

This also leads to inconsistent behaviour as 'approved' can be deselected from the menu, but the filter tag cannot be cleared.

2024-02-29 13:09 UTC, jakubcolony requested changes
Thanks for your work @CzarekDryl, I'm also noticing the issue Sam raised.

Also, the pill for status filter doesn't appear initially, but after you change it to something else and back to the default value, the pill appears but it's impossible to remove it:

https://github.com/JoinColony/colonyCDapp/assets/112586815/2e6e4333-175b-48fd-be42-742b6bd943b5

2024-03-01 13:57 UTC, CzarekDryl commented on src/components/frame/v5/pages/FundsPage/partials/FundsTable/FundsTable.tsx
> +      }
At the beginning, pills with the default value should not be shown, only after any change do we show the pills. So I think that I need this state to check that.

![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/d2a89743-c22f-45df-a7a8-5d40af8beb3e)

2024-03-04 09:17 UTC, iamsamgibbs requested changes
Thanks for the improvements, it's very nearly there!

I've noticed this issue with the filters. `ƓƓƓ` is approved, so it shouldn't show with this selection of filters.

![Screenshot 2024-03-04 at 09 14 48](https://github.com/JoinColony/colonyCDapp/assets/34915414/bd8b7956-1a97-44d2-aae0-3ca85f761bf0)

2024-03-04 16:37 UTC, ArmandoGraterol reviewed
Sorry! I was indeed looking at the wrong page.

- If I apply both status filters, only the approved is shown, is this intentional?
![Screenshot 2024-03-04 at 13 27 49](https://github.com/JoinColony/colonyCDapp/assets/18473896/12144a67-cb99-4795-9c36-e95e537b7366)

2024-03-05 09:16 UTC, CzarekDryl commented
@iamsamgibbs @ArmandoGraterol Filtering should work as expected now, please check it again :)

2024-03-05 14:15 UTC, iamsamgibbs requested changes
Good work! Filters are working great now. I just noticed on the figma design that "Token type" should appear before "Token status" in the menu, if you could swap those over then we're all good to go!

![Screenshot 2024-03-05 at 14 13 56](https://github.com/JoinColony/colonyCDapp/assets/34915414/fc823da2-0fce-4a92-916e-249f793e759d)

2024-03-05 14:56 UTC, ArmandoGraterol submitted a review, later dismissed
Looking good to me 👍 Thank you for the changes

2024-03-05 16:15 UTC, jakubcolony submitted a review, later dismissed
Looks like all the previous issues are now resolved, nice work @CzarekDryl!

2024-03-06 12:43 UTC, warrencolliver approved these changes
Nice work on this. tested the changes and I can't find any problems

2024-03-06 13:34 UTC, merged