feat: added filters on balance page
JoinColony/colonyCDapp pull request #2007
Opened 2024-02-29 14:40 UTC by CzarekDryl

https://tw.auroracreation.com/app/projects/562144/tasks/15577548

## Description

- Added filters to balance page

## Out of scope

- Sorting

(Resolves | Contributes to) #31415

2024-02-29 21:03 UTC, rdig approved these changes
Can't find much to point at, so nice  work. :+1: I left a comment that I want you to address before merging though

![Screenshot from 2024-02-29 22-23-46](https://github.com/JoinColony/colonyCDapp/assets/1193222/5b483e79-1e43-4bfa-b31c-4aa909e25e28)

2024-02-29 22:09 UTC, warrencolliver approved these changes
looks good to me, happy to re-approve if needed after Raul's comments

2024-03-01 10:36 UTC, CzarekDryl commented on src/components/frame/v5/pages/BalancePage/partials/BalanceTable/Filters/partials/filters/AttributeFilters/consts.ts
> +  // },
Yup, I've added TODO for this

2024-03-01 10:51 UTC, iamsamgibbs reviewed
Great work on this issue, all looks great. I just wanted to confirm this is intended for the filtering, the 'Native' attribute in effect overrides the token type? With these filters selected I would have expected no results:

![Screenshot 2024-03-01 at 10 49 31](https://github.com/JoinColony/colonyCDapp/assets/34915414/b800547e-7639-4c4c-b76a-62b52beeabc3)

2024-03-02 01:09 UTC, rdig requested changes
Good pickup @iamsamgibbs. I totally missed that.

You are correct in expecting having that table empty with those filter selected. Filter order / hierarchy is something that definitely needs to be addressed

2024-03-04 09:44 UTC, iamsamgibbs approved these changes
Thanks for the fix, all working as expected! 🎉

2024-03-04 12:26 UTC, warrencolliver submitted a review, later dismissed

2024-03-05 16:36 UTC, melyndav requested changes
Hey @CzarekDryl! Nice work on this one.

Two minor change requests.

1. The input in the active state has funky border radius which has been an issue before - 

![image](https://github.com/JoinColony/colonyCDapp/assets/82127904/3de6090b-8345-4879-bb40-0b676644ac31)


2. On mobile, the search title in the search pop up should be 'SEARCH BALANCE ACTIVITY'

Thank you!

2024-03-05 19:40 UTC, rdig approved these changes
This works as expected now. Nice work! :100: 

![Screenshot from 2024-03-05 21-39-32](https://github.com/JoinColony/colonyCDapp/assets/1193222/c9acbca8-963c-454d-9930-53755ab243fa)

2024-03-06 08:46 UTC, iamsamgibbs approved these changes

2024-03-06 13:51 UTC, melyndav approved these changes
Thanks for the changes @CzarekDryl. Approved from my side.

2024-03-06 13:55 UTC, merged