Feat: Implement edit locked expenditure motion saga
JoinColony/colonyCDapp pull request #2021
Opened 2024-03-05 12:05 UTC by iamsamgibbs

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-03-05 12:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=2021) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=2021) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=2021) it.</sub>

2024-03-05 18:25 UTC, ArmandoGraterol approved these changes
Nice work Sam! Working as expected for me 👍

2024-03-05 20:16 UTC, rdig approved these changes
All good codewise, can't run this manually however.

I managed to get around the block ingestor by starting it manually from it's own repo, but then the amplify image won't build.

![Screenshot from 2024-03-05 22-14-29](https://github.com/JoinColony/colonyCDapp/assets/1193222/45fbd2ad-45cb-456e-b7e9-1fe1abd8e59d)

Seems like npm is either responding slowly or just down completely.

I'm actually surprised GH's UI still works.

At any rate, nice work here!

2024-03-06 12:27 UTC, jakubcolony requested changes
Hey @iamsamgibbs, great work so far!

I finalized the motion but the values in the DB are not 100% correct (claim delay for new slot is null, the recipient address is wrong):
<img width="667" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/f460767c-76ef-42c2-a14e-b03137ff1a9b">


I also noticed there's still one requirement that needs addressing:
> The changes proposed via a motion should be stored and made available to the UI.

According to designs (https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3615-356361&mode=design&t=iPwrs8mSpxlkFqFa-0), we need to store all changes that the motion is proposing to make.

Feel free to drag me into a call and we can discuss this in more detail.

2024-03-06 12:27 UTC, jakubcolony commented on src/redux/sagas/motions/expenditures/editLockedExpenditureMotion.ts
> +  const resolvedPayouts: ExpenditurePayoutFieldValue[] = [];
Could all this logic be extracted into a helper considering it's very similar to edit expenditure via permissions?

2024-03-06 12:27 UTC, jakubcolony commented on src/redux/sagas/motions/expenditures/editLockedExpenditureMotion.ts
> +  const batchId = 'motion-edit-locked-expenditure';
Could you align this saga with the fixes I did in #2020 (e.g. https://github.com/JoinColony/colonyCDapp/pull/2020/files#diff-5097462c62b8afbf61c34f5ba821182563002e86f110568703f0e0b762948b4d) - especially around the batch ID and `createGroupTransaction` params?

2024-03-11 22:47 UTC, jakubcolony approved these changes
Really nice work @iamsamgibbs, tested different cases and all seems to be working great 👌 

Before finalizing:
<img width="653" alt="Screenshot 2024-03-11 at 22 37 15" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/2b404350-3346-48fc-9e1f-d04904103020">

After: 
<img width="597" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/048cb132-5e56-4e5f-9cc5-42271d4630dd">

Deleting a slot also works fine, only the modified (deleted) slot is stored for the motion:
<img width="618" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/543f3c15-ee89-4124-977c-64de1809d238">

And the payouts update correctly after finalization:
<img width="586" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/2c4cf7d1-2cce-4592-a615-82330109372c">

2024-03-12 14:36 UTC, ArmandoGraterol approved these changes

2024-03-12 21:35 UTC, jakubcolony approved these changes
LGTM 👍

2024-03-14 21:15 UTC, jakubcolony commented
Are we good to merge this PR @iamsamgibbs?

2024-03-14 21:32 UTC, merged