Feat/15828803 action fields
JoinColony/colonyCDapp pull request #2039
Opened 2024-03-12 13:39 UTC by CzarekDryl

https://tw.auroracreation.com/app/tasks/15828803

**New stuff** ✨

* Added fields to created action - draft mode and completed action

## TODO

- Custom action title

## Out of scope

- Right side of action sidebar

2024-03-12 21:18 UTC, jakubcolony commented
@arrenv @AdrianDudko are we missing a corresponding Github issue? I'm not sure of the scope of this ticket and can't access the aurora creation link.

2024-03-13 07:00 UTC, CzarekDryl commented
@jakubcolony We do have issue but it applies to the whole task, not just part of it, because we make the subtasks ourselves.[https://github.com/JoinColony/colonyCDapp/issues/2005](https://github.com/JoinColony/colonyCDapp/issues/2005)

2024-03-13 08:59 UTC, arrenv commented
> @jakubcolony We do have issue but it applies to the whole task, not just part of it, because we make the subtasks ourselves.#2005

@CzarekDryl It would be good to copy the relevant acceptance criteria into it's own issue that can be referenced.

2024-03-14 07:08 UTC, CzarekDryl commented
@arrenv @jakubcolony New issue added

2024-03-14 22:50 UTC, jakubcolony requested changes
Thanks for adding the related issue @CzarekDryl.

It looks like this PR needs rebasing but I ran some high-level functional testing. A few things I noticed:

- Action type is `Generic` instead of `Payment builder`:
<img width="1078" alt="Screenshot 2024-03-14 at 22 30 03" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/05715ec4-6ba8-4fd7-9d93-652157158154">

- It is possible to crash the app when you create a payment with some specific amounts (e.g. `5342534`) which is most likely due to JS float precision, we need to be able to handle it though:


https://github.com/JoinColony/colonyCDapp/assets/112586815/2e369ba7-b6da-4084-a0a7-adf03fd67d12

2024-03-15 13:55 UTC, CzarekDryl commented
@jakubcolony I think that I've fixed that issue with decimals, please check it again.

2024-03-15 18:14 UTC, jakubcolony requested changes
Thanks for your work @CzarekDryl, left a couple of comments in code.

2024-03-15 18:14 UTC, jakubcolony commented on src/components/v5/common/ActionSidebar/hooks/useGetActionData.ts
> +            );
Can also use the `getSelectedToken` here

2024-03-15 18:14 UTC, jakubcolony commented on src/components/v5/common/ActionSidebar/ActionSidebar.tsx
> +  );
This hook seems to be called in `useGetActionData` as well, so maybe whatever data you need here could be exported from that hook instead?

2024-03-15 18:14 UTC, jakubcolony commented on src/components/v5/common/ActionSidebar/hooks/useGetExpenditureData.ts
> +  });
The query shouldn't just run with an empty id, please make sure to specify `skip` option to avoid unnecessary requests

2024-03-18 11:13 UTC, melyndav requested changes
Hey @CzarekDryl thanks for your work on this PR.

Every time I try a new transaction to test I just get caught in this loading state. I've tried opening it again using the transaction URL and get the same loading state. It was using permissions.

<img width="1762" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d7abd872-d516-4883-852b-a02efa0079ef">

If I try using reputation, I can't get past the pending state. 

<img width="1229" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/7f162d24-89d3-43b2-907f-ffc075a4ccc9">

Maybe I'm not doing something correctly here?

2024-03-18 13:31 UTC, jakubcolony requested changes
Looking very solid @CzarekDryl, thanks for your changes.

I left some comments in code, and also noticed the following:

- The table breaks quite a bit shortly before going mobile, also notice how the description breaks into multiple lines but `leela` stays aligned to the right:
<img width="878" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/16ac7da4-7d2c-4277-819b-9607b6cf1311">

- Overlapping issue on larger screen width with longer amounts:
<img width="567" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/1e5e2a0f-bb57-4c45-a837-3a486cdffa2e">

- Neither the recipients nor the tokens are clickable which feels inconsistent with every other instance of user/token link that opens a popover. But I'm not sure what the requirements say about this so one for @melyndav to confirm maybe? 🙂 

- I also thought I saw the payments table load without any rows but I wasn't able to replicate that - noting it here though in case anyone else spots it.

2024-03-18 13:31 UTC, jakubcolony commented on amplify/backend/api/colonycdapp/schema.graphql
> +  TEMP_ADVANCED_PAYMENT
Looks like you've pulled my changes from #1969 - that means `TEMP_ADVANCED_PAYMENT` isn't needed anymore

2024-03-18 14:48 UTC, melyndav requested changes
Hey @CzarekDryl thanks for helping me fix my issue.

I got it to work and have some feedback.

1. When I'm only paying 1 user, the metadata is showing 'multiple recipients and tokens' which isn't accurate. It should show the number here when only 1 member is being paid.
<img width="726" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/616dee5b-dec4-4a21-809f-d93fe5240cdf">

2. The table looses it's styling in the completed state.
<img width="726" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/dc66ea91-08e5-40ef-abc3-5913ca441298">

There should be NO horizontal rules between members at any stage (during the action creation and completed states) but only between the last row and the total field as per Figma below: 

<img width="874" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/df98acec-8293-428a-b6d2-84ac7afb7ccf">


3. The mobile total field at the bottom of the table has padding issues:
<img width="410" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2c6d8f9c-f802-4e55-ad20-eab3a81f1934">
 
 Figma showing correct padding:
 
<img width="628" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8fb82f35-b420-49b4-af14-561d683bf7e7">

4. Unverified members are missing their alert icon showing in the table.
<img width="192" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/bc618290-6f97-40eb-8ef8-8fbbc0d5ccdd">


5. Size of the verified icon and the padding after the username should match Figma on desktop and mobile - it should match the same size as the building state before the CTA is selected.
<img width="192" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/fe7bfb8b-175d-4ec1-9b0b-73c3ea59f0f6">

Link to example: https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=3643-417416&mode=design&t=GU7PGCjsxu5u5B0A-4

2024-03-19 10:42 UTC, iamsamgibbs requested changes
Thanks for your work so far! I've noticed a couple of issues:

It isn't possible to change the token type on mobile.

https://github.com/JoinColony/colonyCDapp/assets/34915414/3556a530-8c49-488a-a825-fa809de6bc96

On the completed view, the horizontal rules should continue the entire way across. The total number of tokens should also be right aligned.

<img width="555" alt="Screenshot 2024-03-19 at 10 36 24" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/2a5cb107-4619-4952-8a94-0091c47eb88d">

Figma:

<img width="387" alt="Screenshot 2024-03-19 at 10 36 36" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/b7d043ec-e90f-48fb-a3b1-734d6daed8bd">

2024-03-19 12:57 UTC, CzarekDryl commented
@iamsamgibbs First one is out of scope because in this issue I'm taking care of completed action.

2024-03-19 19:05 UTC, jakubcolony requested changes
Codewise it looks good 👍 

I'm still able to cause some overlay issues however, and there is a weird horizontal scrollbar in the user popover (which doesn't happen elsewhere this component is used):

<img width="853" alt="Screenshot 2024-03-19 at 18 57 10" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/f05d5c26-9e28-4531-84ce-42367c0d399d">

<img width="373" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/f08db68a-fc45-41f6-b74b-1a4deb6d971d">

2024-03-20 07:48 UTC, CzarekDryl commented
@jakubcolony Currently, I have no idea how to improve the table, it would be best if Melynda came up with something. Can we merge it into a feature branch and then fix it, because we are seriously blocked by this task.

2024-03-20 09:28 UTC, arrenv commented
Adding a comment here regarding the table at table view, the solution to this can just be to toggle the mobile version of the table at this size.

I think this is worth it's own issue though, so, I have created an issue here https://github.com/JoinColony/colonyCDapp/issues/2072 and this PR, so that this PR can be completed without including this fix.

2024-03-20 09:30 UTC, melyndav requested changes
@CzarekDryl all looks good to go, I've approved it. :)

2024-03-20 09:53 UTC, jakubcolony approved these changes
LGTM code-wise, good to merge once Mel's comments are addressed 👍

2024-03-20 11:45 UTC, iamsamgibbs approved these changes

2024-03-20 12:01 UTC, merged