fix: Not able to finalize agreements
JoinColony/colonyCDapp pull request #2040
Opened 2024-03-12 18:29 UTC by warrencolliver

## Description

This PR fixes the issue which was occuring when trying to finalize an agreement / decision action. 

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-03-14 09:23 UTC, iamsamgibbs requested changes
This looks good and all works as expected! Just one small change: would be better if `formatText` took in an id from `src/il8n/en.json`

2024-03-14 12:27 UTC, iamsamgibbs approved these changes

2024-03-14 13:39 UTC, bassgeta requested changes
Works like a charm, just dropped a comment if we may want to wrap some if statements into variables for more readability. Not necessary tho, just some QoL improvements :)

2024-03-14 13:39 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
> +    actionData.type === ColonyActionType.CreateDecisionMotion
maybe we could put this (perhaps some other too) into boolean variables for improved readability

2024-03-14 18:42 UTC, ArmandoGraterol requested changes
Nice job Warren! Just left a nitpick but after that this should be good to go from my side

2024-03-14 18:42 UTC, ArmandoGraterol commented on src/components/v5/common/ActionSidebar/partials/Motions/steps/FinalizeStep/FinalizeStep.tsx
> +                        }
A small nitpick but this way we avoid repetition:
```
formatText({ id: isMotionAgreement ? 'motion.finalizeStep.returnStakes' : buttonTextId })
```

2024-03-15 17:35 UTC, ArmandoGraterol submitted a review, later dismissed
LGTM 👍 Thank you for the changes

2024-03-19 08:56 UTC, iamsamgibbs approved these changes
Looks good to me!

2024-03-19 10:41 UTC, merged