Feature/1372 consolidate avatar components
JoinColony/colonyCDapp pull request #2066
Opened 2024-03-19 15:05 UTC by bassgeta

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #1372

2024-03-26 11:47 UTC, iamsamgibbs requested changes
Great job on this, the avatar components look so much nicer to work with now 🎉

I've only noticed a few regressions (and you even fixed some whilst I was reviewing!)

The chain icon isn't being properly overlaid on the colony avatar.

<img width="116" alt="Screenshot 2024-03-26 at 11 38 36" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/b3b686f2-8fde-430e-ae96-24314694c8b2">

The token avatar on the incoming balance page should be 26px.

<img width="472" alt="Screenshot 2024-03-26 at 10 37 20" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/c0e36068-8117-4f11-a931-4c93067ef8e4">

2024-03-26 11:47 UTC, iamsamgibbs commented on src/components/v5/shared/Avatar/Avatar.tsx
> +        alt={alt ?? `Avatar of ${address}`}
Should we be using i18n for alt text?

2024-03-26 13:06 UTC, melyndav requested changes
Hey @bassgeta nice start on this. Recommend a bit more sanity checking first before requesting a review since there a lot of issues that could have been picked up just from an initial check.

**All of these issues related to desktop, tablet and mobile sizes.**

1. Members widget on the dashboard has some issues.

<img width="1304" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/29ba04cf-9423-4e19-b1a8-e2fa193b6582">

On mobile:
<img width="412" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/30b8a9c4-0bf7-4ab2-bfe8-5e7b49630ea9">
 
 
 2. The colours of the circles around the avatars should match the component in Figma and match the correct contributor colour type.
 
<img width="1069" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f5a65f59-a095-4fe6-90ea-5990f1ef76eb">


3. Same problem with the pop-over colours.
<img width="274" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b5324926-22fd-4b37-959d-6ff5bdc49e92">
 
 
 4. The placement of the avatars on within the team cards have shifted. They should align with the team name title as per the Figma component below. 
 
<img width="594" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ee661515-63d8-4aa9-a227-6febabe1397b">

5. Avatars within the team card are missing their white border.
<img width="62" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/03cce1c8-56e4-4154-8a61-71804c3ec4cf">

As per Figma:
<img width="155" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/e41c17f8-007b-4dbb-bdcb-8133e0cbcbc6">
 
 6. Size of the avatars in filter components look to have been impacted from 18x18px 
 
<img width="258" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f1119815-082c-4811-9655-56626c565c91">

 As per Figma:
 
<img width="388" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2b341fca-5561-46b6-b887-218e185989d8">


7. Avatars in table rows specifically balance and incoming funds should match Figma.
<img width="326" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/0d013964-4d6a-4675-9826-c3435bad50d1">
 
 
 As per Figma:
 
<img width="186" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/7ce6c87e-ecc5-4271-870b-8530f642418f">


8. User account profile avatar should be 60x60
<img width="393" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5e1c0703-10e8-4ed0-b088-afc44ee66974">


9. Avatars across all member dropdowns and token dropdowns should match Figma.
<img width="417" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/aec7085c-a41c-4de7-8537-1c17f8b19e84">

As per Figma:
<img width="445" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5dc3ca4e-4773-465d-a436-d2d0964aba08">
 
 Token dropdowns:
 
<img width="354" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f88a5e8d-c5c6-41c7-b4e3-2db5d37b499e">

10. Problems on mobile navigation:
<img width="482" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8f0ad93a-68cd-4625-8f99-70715da9678c">
 
11. Problems with the currency switcher with the updates.
<img width="385" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/81b2222a-4978-4340-b7e7-e727556941b2">

Mobile:
<img width="479" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/c099cd25-929d-4016-9f18-dcd25f060d42">


How it should look:
<img width="524" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/31848e07-5f84-4bd7-abb2-be05f1ea1419">



I can't get any actions to show in the activity feed to test the avatar sizing here?

2024-03-26 13:19 UTC, iamsamgibbs commented
(Just a note, 11 is an issue on master just opened a ticket for it: #2091)

2024-03-26 13:20 UTC, melyndav commented
> (Just a note, 11 is an issue on master just opened a ticket for it: #2091)

Nice pick up, thanks @iamsamgibbs

2024-03-26 19:00 UTC, rdig requested changes
Wow this one was big. Amazing work Kerry both in quality and size.

This was not a easy thing to refactor, and you deserve all the credit.

I've just reviewed it codewise, with just minor pick-ups, so in that sense, job well done.

I'll refrain from doing a functional review since Mel and Sam already pointed out a bunch, so I avoid reporting the same issue.

2024-03-27 09:07 UTC, bassgeta commented on src/components/v5/common/MemberSignature/partials/MemberAvatar/MemberAvatar.tsx
> +          'border-blue-400 ': userStatus === 'dedicated' && hasAvatarDecor,
this is actually a currently unused component, so I will probably just end up reworking props to receive `contributorType` instead, nice catch

2024-03-27 10:41 UTC, bassgeta commented on src/components/frame/v5/pages/MembersPage/types.ts
> +  reputation?: number;
this is just something I've moved, not built from scratch, so I went ahead and double checked
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/1df2b4ac-5dae-49a4-a030-3c06ddbb0597)
this value is 
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/699c4e8d-5ab5-4591-9678-8b18eb14e470)
the `reputationPercentage` property of a colony contributor. So I guess it's fine like this or should I cast it to string in the `getMemberList` helper?

2024-03-28 08:15 UTC, rdig commented on src/components/frame/v5/pages/MembersPage/types.ts
> +  reputation?: number;
If it's just a percentage then we're all good. 

The improvement here would be renaming the prop to avoid confusion in the future.

2024-03-28 08:39 UTC, rdig approved these changes
Most of my concerns were addressed. Nicely done.

We discussed the `enum` sizes issue separately and came to the conclusion that it's not feasible to do just yet.

Tested the most obvious places where avatars get rendered, and nothing out of the ordinary stood out _(this is by no means exhaustive)_

![Screenshot from 2024-03-28 10-30-11](https://github.com/JoinColony/colonyCDapp/assets/1193222/c82484f7-531d-4961-85a6-c6e82ae5dbd4)
![Screenshot from 2024-03-28 10-30-18](https://github.com/JoinColony/colonyCDapp/assets/1193222/de110251-8ff5-4357-977a-eede72b4842c)
![Screenshot from 2024-03-28 10-30-28](https://github.com/JoinColony/colonyCDapp/assets/1193222/d49dbe27-25e0-47b5-bb77-90982db2ee9a)
![Screenshot from 2024-03-28 10-30-40](https://github.com/JoinColony/colonyCDapp/assets/1193222/d4735be4-aff6-477a-b0c6-21ad381e321e)
![Screenshot from 2024-03-28 10-30-57](https://github.com/JoinColony/colonyCDapp/assets/1193222/46e38626-c6a7-47eb-b2dc-ba7e89c1afda)
![Screenshot from 2024-03-28 10-31-34](https://github.com/JoinColony/colonyCDapp/assets/1193222/5e54177f-9543-44c9-80e5-214cde0327c1)

As I said last time, this was a massive refactor, which you've seen to completion. Kudos :100:

2024-04-03 08:47 UTC, melyndav requested changes
Hey @bassgeta super work on all the updates! Appreciate all the fixes. A couple of pick ups - 

1. The 'new' contributor is missing the correct colour around the avatar 
<img width="327" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/57635ddb-8e80-44e9-9a2c-1e6a22489b25">

https://www.figma.com/file/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?type=design&node-id=1784-15145&mode=design&t=HoBOeMkdWFybVCey-4

2. Also needs to be updates on the popover as well
<img width="358" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/206bdcda-8b36-44d5-a624-483282adffaa">


3. The balance table should have an avatar size of 26x26px as per Figma below.
<img width="310" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/3224f52f-c113-4a37-a72c-1408281cb4de">

4. Blockie avatar is broken in the members dropdown in an action when adding the address:
<img width="360" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/3409272f-4020-49f6-adef-6114f8d8dbdc">

<img width="357" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/9b68184a-3102-4a18-8f82-442e9109d4ff">

And then again when it's showing in the member list
<img width="386" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/6f64dcce-f09f-429a-9dcc-8c41b458e503">
 

5. Colony avatar is breaking in the completed state for Colony details 
<img width="695" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d65ebec9-782a-4c1c-954f-0d4759dbad47">

2024-04-03 15:55 UTC, iamsamgibbs submitted a review, later dismissed
Great work on this, everything is looking just as it did before!

Can see that Mel's issues have been addressed. New contributor has the correct outline colour.

<img width="372" alt="Screenshot 2024-04-03 at 16 53 19" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/aacf69b5-f887-477d-8139-339732528538">

Balance table icon is the correct size.

<img width="334" alt="Screenshot 2024-04-03 at 16 30 06" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/18592eac-aa2f-496b-8708-7fa7ba94e3d9">

Blockie avatar showing as expected.

<img width="440" alt="Screenshot 2024-04-03 at 16 34 24" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/9e20adeb-b409-484c-884c-520d8edc7e99">

Colony avatar also showing correctly on completed action screen.

<img width="361" alt="Screenshot 2024-04-03 at 16 32 06" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/a64060a9-e9a1-458b-bf46-328137731c5b">

Nice one! 💯

2024-04-04 14:25 UTC, rdig submitted a review, later dismissed
Approving from my end as well, so you can get closed to merging this :+1:

2024-04-04 14:56 UTC, chmanie commented on src/components/common/ColonyActionsTable/partials/ActionDescription/ActionDescription.tsx
> +          userName={user?.profile?.displayName ?? undefined}
Personally I don't like this fallback to undefined. I think the component should handle this case

2024-04-04 17:32 UTC, ArmandoGraterol requested changes
Looking good! I couldn't notice a place in the UI that needed to change but I did find a small conditional that can be simplified

2024-04-05 09:32 UTC, melyndav requested changes
Hey @bassgeta! Again, super nice work ont his one. A couple of picks ups.

1. Full addresses aren't showing truncated on the contributors and members cards.

On master:
<img width="409" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/75c5c6e4-df4a-49be-ae40-c6f23cae861b">

On this branch:
<img width="430" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d7936281-95ad-4d45-ae25-a26076425559">

<img width="576" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d6935bfc-774b-486b-8ad3-fd55f54c5d8c">

Mobile:
<img width="574" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/1fbbb739-b96b-4a88-b91d-807fb4d10b0f">



2. I changed Leela's avatar in the user account area, but it doesn't update on the member and contributor tabs despite it showing in other places within the UI

<img width="1638" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/6acf6023-d2d4-4244-9bf6-47fd536aae42">

<img width="1639" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8d2265e8-238c-4238-b115-f6b59ec9feb8">

Here it is showing correctly in the activity feed:
<img width="1622" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/e8bd7058-2b12-447d-bd3d-b22399167ce9">


3. Also, I don't see any skeleton loaders happening in the members section now especially on the all members tab? Even when throttling, nothing is showing where previously it was. Has this been removed to resolve the impact to skeleton loaders I raised previously?

2024-04-08 12:23 UTC, bassgeta commented
> Hey @bassgeta! Again, super nice work on this one. A couple of picks ups.
> 
>     1. Full addresses aren't showing truncated on the contributors and members cards.
> 
> 
> On master: <img alt="image" width="409" src="https://private-user-images.githubusercontent.com/82127904/319930541-75c5c6e4-df4a-49be-ae40-c6f23cae861b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzkyMjAsIm5iZiI6MTcxMjU3ODkyMCwicGF0aCI6Ii84MjEyNzkwNC8zMTk5MzA1NDEtNzVjNWM2ZTQtZGY0YS00OWJlLWFlNDAtYzZmMjNjYWU4NjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NDUyYTE5ZDRiMjNlZDhmNGZhYzJkODNjYzIwNTcwN2YwN2Q1NTQyZTliYTZmZjEwMGQ4MWRmOTM2ZjIxNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6FxaxViUL7qIUEViogPr4R_zuujSCikXoiWAnPICWRU">
> 
> On this branch: <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/82127904/319932596-d7936281-95ad-4d45-ae25-a26076425559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzkyMjAsIm5iZiI6MTcxMjU3ODkyMCwicGF0aCI6Ii84MjEyNzkwNC8zMTk5MzI1OTYtZDc5MzYyODEtOTVhZC00ZDQ1LWFlMjUtYTI2MDc2NDI1NTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYzc5NGU2MTdkYTI4OTBiZDQ4NmI0MjBmNGUzNDg3ZDU2Y2I1Y2RmZWE4YjNhZTk2NzA4MTc5NzBkY2VjM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fAtNLpBDU7vJXEcsqHQhCAGVqqbuuJhyrl78BIDLKUA">
> <img alt="image" width="576" src="https://private-user-images.githubusercontent.com/82127904/319933340-d6935bfc-774b-486b-8ad3-fd55f54c5d8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzkyMjAsIm5iZiI6MTcxMjU3ODkyMCwicGF0aCI6Ii84MjEyNzkwNC8zMTk5MzMzNDAtZDY5MzViZmMtNzc0Yi00ODZiLThhZDMtZmQ1NWY1NGM1ZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOGFiOWI1OTMzMzEyNDYzZjcyNGMxMTRkZTRhNmExNWY1NTI2OTFlMDdiM2Q3NmEyMmY2YzM5NTdkODdlODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CAxmVTCEM6m-rcG6UYPHL9LJn19WjDMdy0XNiXOte3g">
> 
> Mobile: <img alt="image" width="574" src="https://private-user-images.githubusercontent.com/82127904/319935584-1fbbb739-b96b-4a88-b91d-807fb4d10b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzkyMjAsIm5iZiI6MTcxMjU3ODkyMCwicGF0aCI6Ii84MjEyNzkwNC8zMTk5MzU1ODQtMWZiYmI3MzktYjk2Yi00YTg4LWI5MWQtODA3ZmI0ZDEwYjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMDg5MTZhOGNjNjFlYWExNmZlZDA4YWFlM2Q3ODZlZDQ5MDEzM2I4NDVjY2Y1NDFmMzFmZDc1ZGE5Mzg2Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d2KYFHYoM72CMyKLi6O1puoQuHMXwmr5Szax-yP_-lY">
> 
>     2. I changed Leela's avatar in the user account area, but it doesn't update on the member and contributor tabs despite it showing in other places within the UI
> 
> 
> <img alt="image" width="1638" src="https://private-user-images.githubusercontent.com/82127904/319934736-6acf6023-d2d4-4244-9bf6-47fd536aae42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzkyMjAsIm5iZiI6MTcxMjU3ODkyMCwicGF0aCI6Ii84MjEyNzkwNC8zMTk5MzQ3MzYtNmFjZjYwMjMtZDJkNC00MjQ0LTliZjYtNDdmZDUzNmFhZTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTA0MThhZTg0ZTQ3NGUzNTQ0NTEwYTIxNWFmZDc5OGJkZDc3YTA5MGRkZTY1MmY1MmUzMzU0NzIwNzgzMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hX5tSTYCWlriqhBf6sDNWd7YVdYpm54PT3Bxr03I-Ic"> <img alt="image" width="1639" src="https://private-user-images.githubusercontent.com/82127904/319935013-8d2265e8-238c-4238-b115-f6b59ec9feb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzkyMjAsIm5iZiI6MTcxMjU3ODkyMCwicGF0aCI6Ii84MjEyNzkwNC8zMTk5MzUwMTMtOGQyMjY1ZTgtMjM4Yy00MjM4LWIxMTUtZjZiNTllYzlmZWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZGE4NDAwMzk4MTBjOWZkZGIxYWZjNzBiYzE5NmU2NGM1MjdkNmEyMGNiYjYxYzRlMmViNWJjZjJhYjRlNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dK_1TXoKK1D0-txlBc05tGd91FO4g0XzaaeZS5J2BVs">
> 
> Here it is showing correctly in the activity feed: <img alt="image" width="1622" src="https://private-user-images.githubusercontent.com/82127904/319935188-e8bd7058-2b12-447d-bd3d-b22399167ce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzkyMjAsIm5iZiI6MTcxMjU3ODkyMCwicGF0aCI6Ii84MjEyNzkwNC8zMTk5MzUxODgtZThiZDcwNTgtMmIxMi00NDdkLWJkM2QtYjIyMzk5MTY3Y2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YzU3MjgxNDg1MDQ4ZDdlZDU0ODU4MmI0MDU1YTQzMTJjYzI3MDg4MTg1ZmNjZTZiODlhMjlmYWMwNDYzOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7kwep0EFu6wIASCmA--yZYAxDXpfr1sizvzpjodwXx8">
> 
>     3. Also, I don't see any skeleton loaders happening in the members section now especially on the all members tab? Even when throttling, nothing is showing where previously it was. Has this been removed to resolve the impact to skeleton loaders I raised previously?

Opened an issue for bug number 2 at #2173 , and I actually get the spinner on `master` too. Not sure if there's something janky on my dev environment, but if we wanna show skeletons, I can open up a new issue so we can get this chonky PR out of the way ASAP :D

2024-04-08 20:52 UTC, ArmandoGraterol approved these changes
LGTM 👍 Tested various instances and it seems to be working as expected! Also, I see that the member page issues have been solved.

2024-04-09 10:32 UTC, melyndav approved these changes
SHIPPPPPPPPP IT!!!! 💯 Solid effort on this @bassgeta, thanks for all your work!

2024-04-09 10:34 UTC, rdig approved these changes
Finally you get to merge this!!1 Nicely done! :tumbler_glass:

2024-04-09 11:31 UTC, merged