feat: added release modal
JoinColony/colonyCDapp pull request #2090
Opened 2024-03-26 08:53 UTC by CzarekDryl

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-03-27 12:45 UTC, jakubcolony requested changes
Great work @CzarekDryl, I was able to finalize once I locked and funded the expenditure using testing UI. I left a comment regarding permissions validation, otherwise LGTM.

2024-03-27 12:45 UTC, jakubcolony commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/ReleasePaymentModal/consts.ts
> +    userPermissions.includes(ColonyRole.Arbitration);
It's sufficient just to check if the user has `Arbitration` permission but it must take into account the domain of the expenditure. You can replace it with a single check using `addressHasRoles`:
```ts
addressHasRoles({
  address: user.walletAddress,
  colony,
  requiredRoles: [ColonyRole.Arbitration],
  requiredRolesDomains: [expenditure.nativeDomainId] // will need to pass expenditure as prop
})
```

2024-03-27 17:50 UTC, melyndav requested changes
Hey @CzarekDryl nice start on this.

1. The modal is missing the icon and styling to match Figma.

<img width="453" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/279e9147-1d43-49cf-9e53-87a68d08961e">

2. The input and dropdown have the same styling issues from #2085 - 3, 4, 5, 6 and 7 
https://github.com/JoinColony/colonyCDapp/pull/2085#pullrequestreview-1957545540

2024-03-27 18:10 UTC, ArmandoGraterol reviewed
According to the design on figma, there should be an icon at the top:
![Screenshot 2024-03-27 at 15 01 35](https://github.com/JoinColony/colonyCDapp/assets/18473896/ec32935e-5dc2-4846-af93-5c85225bd329)

Dialog in this PR:
![Screenshot 2024-03-27 at 15 02 05](https://github.com/JoinColony/colonyCDapp/assets/18473896/f484305d-cb7a-4686-ac97-e4f279265f91)

Has this changed?

EDIT: I didn't see Mel review pointing out the same thing

2024-03-28 07:15 UTC, CzarekDryl commented
@melyndav Did you check it? Because it was all fixed here in this PR

2024-03-28 11:12 UTC, bassgeta approved these changes
Looking good, very nice and readable, LGTM :ship:

2024-03-28 12:01 UTC, melyndav requested changes
Hey @CzarekDryl thanks for the update on the icon.

1. The main CTA shouldn't be disabled at anytime. It should be left active, but an error state should show if no option is selected as per Figma here. 

https://www.figma.com/file/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?type=design&node-id=22199-239208&mode=design&t=5gViKhxqOZqOTwev-4

2. Button placement on mobile should be consistent and be stickied to the bottom to stay consistent with every other mobile modals.
<img width="491" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/9c35cfcc-76f4-455a-be13-07d654ef91ac">

2024-03-29 07:51 UTC, CzarekDryl commented
@jakubcolony @ArmandoGraterol @bassgeta I had to modify this modal and add a form, because now there is validation on onSubmit whether an item has been selected in select.

2024-03-29 09:18 UTC, melyndav approved these changes
Thanks for your work on all the requested updates @CzarekDryl - approving this one from my side.

2024-03-29 11:39 UTC, jakubcolony approved these changes

2024-03-29 12:35 UTC, merged