Update Change Action modal logic
JoinColony/colonyCDapp pull request #2095
Opened 2024-03-26 20:26 UTC by ArmandoGraterol

With these changes, now the modal should show only when you edit any fields other than the action type and title. Otherwise, it should never show when you change from one action type to another, for example.

Resolves #2089

2024-03-27 11:35 UTC, iamsamgibbs requested changes
Great work on this, so much nicer switching between action types now! I've only noticed one very minor issue with the amount field:

https://github.com/JoinColony/colonyCDapp/assets/34915414/75947571-a9ed-4de5-a237-2c8a8a2d7268

(Happens on any action type with the amount field, enter an amount, change action type, you will be prompted as expected, change again to any other action and you will be incorrectly prompted despite making no changes)

2024-03-27 13:44 UTC, jakubcolony requested changes
Nice start @ArmandoGraterol, however I'm also seeing the issue with fields being "left over" from the previously selected actions.

2024-03-27 13:44 UTC, jakubcolony commented on src/components/v5/common/ActionSidebar/ActionTypeSelect.tsx
> +  const title = watch('title');
Could also use `TITLE_FIELD_NAME`

2024-03-27 13:44 UTC, jakubcolony commented on src/components/v5/common/ActionSidebar/ActionTypeSelect.tsx
> +                  if (hasMadeChanges && actionType) {
It's a bit manual now that we have to specify the "common" fields here, and then make sure we're also setting them in `onConfirm`. Could those be stored in a config somewhere that we could iterate over?

2024-03-28 09:02 UTC, iamsamgibbs approved these changes
This is great, all working as expected, and I like the addition of NON_RESETTABLE_FIELDS.

No longer experiencing the previous issue 🎉

https://github.com/JoinColony/colonyCDapp/assets/34915414/721bcd64-3619-4765-8482-20e87955a99d

2024-03-28 10:38 UTC, bassgeta approved these changes
Works, nice one :muscle:

2024-03-28 13:22 UTC, jakubcolony approved these changes
LGTM, works like a charm now 👌

2024-03-29 09:11 UTC, melyndav approved these changes
OMG thank you for picking up this issue @ArmandoGraterol. It's a small but huge UX improvement. It was so frustrating to get that modal anytime I wanted to explore actions so thank you for picking up my issue.

2024-04-03 16:21 UTC, merged