Fix: Restore UserNavigation submenu classes
JoinColony/colonyCDapp pull request #2100
Opened 2024-03-27 12:29 UTC by iamsamgibbs

## Description

This PR restores the UserNavigation submenu classes that were accidentally removed as part of the vite refactor.

## Testing

Check each of the usernavigation submenus are styled as expected.

## Diffs

**Changes** 🏗

* Created new submenu.styles.ts file for shared tailwind classes
* Restored the classes to each of the submenus.

Resolves #2091

<img width="413" alt="Screenshot 2024-03-27 at 12 27 22" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/269a115b-8cf1-4de0-a2e7-8fc4c25992f1">

<img width="423" alt="Screenshot 2024-03-27 at 12 27 27" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/58ea517f-0c05-4e12-9e78-4fb92c0d923a">

2024-03-27 12:37 UTC, rdig submitted a review, later dismissed
Can confirm that it's restored to it's original style / layout. Nice job Sam!

![Screenshot from 2024-03-27 14-36-39](https://github.com/JoinColony/colonyCDapp/assets/1193222/69fa6b3c-dafd-4d00-beaa-e24bc2acde2d)
![Screenshot from 2024-03-27 14-36-45](https://github.com/JoinColony/colonyCDapp/assets/1193222/f431c467-60de-4958-8075-8f5b7b228acf)
![Screenshot from 2024-03-27 14-36-52](https://github.com/JoinColony/colonyCDapp/assets/1193222/649eb467-288f-444d-a47b-e6c0cc942566)

2024-03-27 19:05 UTC, ArmandoGraterol requested changes
Nice job! The only thing I could find is that the hover state on the left side in the base currency menu doesn't have space with the item on the right:
![Screenshot 2024-03-27 at 16 03 06](https://github.com/JoinColony/colonyCDapp/assets/18473896/13c486d2-237c-4206-b657-3afe49f5ef42)

On red so it's more noticeable :P
![Screenshot 2024-03-27 at 16 04 56](https://github.com/JoinColony/colonyCDapp/assets/18473896/676d43ff-4cf8-4cff-a807-a4c2f246fa45)

2024-03-27 22:57 UTC, iamsamgibbs commented
Oh good catch! I imagine this was an existing issue as I just restored the styles exactly as they were, but I've fixed this up anyway. 👍

2024-03-28 09:22 UTC, melyndav submitted a review, later dismissed
Nice one @iamsamgibbs! Thanks for fixing this! 👍

2024-04-02 08:25 UTC, bassgeta approved these changes
Works good, looks good :sunglasses: Left a minor comment which you can address, but nobody's gonna lose sleep if you don't :D

2024-04-02 11:11 UTC, bassgeta approved these changes

2024-04-02 11:17 UTC, rdig approved these changes
Re-approving so you can merge

2024-04-03 19:08 UTC, ArmandoGraterol approved these changes
Looks good to me 👍

2024-04-03 19:37 UTC, merged