feat: release overview content
JoinColony/colonyCDapp pull request #2101
Opened 2024-03-28 09:00 UTC by CzarekDryl

## Description

- Opens the Release payment modal with the users possible decision methods
- If funded, the owner can release the funds for the payment, starting the claim delay.
- If any claim delays are 0, then those payments will happen immediately on release and also release the creators stake if present.
- Alternatively, users can use available decision methods, including "Admin" tiered permissions or higher (Arbitration on the contracts)

2024-03-28 09:31 UTC, AdrianDudko commented
Waiting for https://github.com/JoinColony/colonyCDapp/issues/2086

2024-03-28 09:33 UTC, jakubcolony commented
@AdrianDudko #2086 has just been merged. On a side note, once a PR is up, the work dependent on it can be started as long as it's checked out from that branch, without waiting for a merge.

2024-03-30 16:46 UTC, rdig requested changes
Mostly good, however the code inside `isExpenditureFullyFunded` needs to be refactored some.

![Screenshot from 2024-03-30 18-45-31](https://github.com/JoinColony/colonyCDapp/assets/1193222/ca8604c1-b3c0-43a3-8440-e7c234048e3d)

Also, I am guessing this PR doesn't actually bring in the content, just creates a placeholder for it _(based on what I'm seeing inside the Release step)

2024-03-30 16:46 UTC, rdig commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/utils.ts
> +  );
This is improper use of `reduce`. There no case where you actually modify or increment the accumulator, you always return the the same object.

This is at best a use case for `map` rather.

2024-03-30 16:46 UTC, rdig commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/utils.ts
> +          amounts[payout.tokenAddress] = BigNumber.from(
Please be mindful of our eslint rules

In this case a better approach would have been to just declare a new variable which would hold the value you need

2024-04-03 07:49 UTC, CzarekDryl commented
@rdig I've fixed content inside release overview box. Please check it once again.

2024-04-03 09:19 UTC, bassgeta requested changes
Nice start on this! I would like it if we somehow simplify the slot amount checking logic so it's more readable (if possible) :)

2024-04-03 09:19 UTC, bassgeta commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/utils.ts
> +  const amountsByToken = expenditure.slots.map((slot) => {
nitpicky, but could we name this something like `slotAmountsByToken`? `amountsByToken` sounds like an object with token addresses as keys and amounts as values tbh :D

2024-04-03 09:19 UTC, bassgeta commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/utils.ts
> +    const [tokenAddress] = Object.keys(token);
I am not sure I am a fan of this, could we construct the object differently so we don't have to take the first key and then checking the amount?

2024-04-03 10:37 UTC, bassgeta approved these changes
Reads much nicer now, thanks for the quick update!

2024-04-03 18:30 UTC, rdig approved these changes
Good from my side as well. Nice work!

2024-04-03 22:59 UTC, jakubcolony approved these changes
Looks good @CzarekDryl 👍 

<img width="1076" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/5603a2e5-647e-4229-af45-689e5d28f4c4">

2024-04-04 05:57 UTC, merged