feat: remove reputation decision method from payment builder form
JoinColony/colonyCDapp pull request #2123
Opened 2024-04-03 09:25 UTC by joanna-pagepro

## Description

- Removed reputation decision method from payment builder form

## Testing

* Step 1. Check if you have the `Reputation Weighted` extension installed and enabled
* Step 2. Open Action sidebar
* Step 2. Select `Payment builder` action type
* Step 3. Open `Decision method` dropdown - `Reputation` option shouldn't be on the list

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* `filterOptionsFn` prop added to `DecisionMethodField`
* `filterOptionsFn` prop used on `DecisionMethodField` component in `PaymentBuilderForm` to filter Reputation decision method

**Deletions** ⚰️

* 

Contributes to https://github.com/JoinColony/colonyCDapp/issues/2005

2024-04-04 07:26 UTC, joanna-pagepro commented
@iamsamgibbs can you check if it's ok now?

2024-04-04 08:52 UTC, iamsamgibbs requested changes
Still looking the same for me I'm afraid!

<img width="711" alt="Screenshot 2024-04-04 at 09 51 25" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/58f633aa-3d1c-4e28-99ab-cef330feb8e8">

2024-04-08 12:22 UTC, CzarekDryl commented
@iamsamgibbs Could you please check it once more? It's working for me on amy without any permissions
![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/768d732d-665b-48b1-8d7a-fc546a194715)

2024-04-08 14:06 UTC, iamsamgibbs requested changes
Thanks for the update on this, when the "Reputation Weighting" extension isn't install, I can see the "You don't have the right permissions" error message as Amy when attempting to create this action - which is great:

<img width="681" alt="Screenshot 2024-04-08 at 15 00 58" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/e52ebed3-1188-4897-900a-309021ed5cd1">

However, when the extension is installed this error message doesn't show and I can interact with the form. The same error message should show when the extension is installed:
<img width="675" alt="Screenshot 2024-04-08 at 15 01 58" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/28390414-b23b-4943-a651-152418645de2">

2024-04-09 16:11 UTC, ArmandoGraterol commented
@joanna-pagepro This branch needs to be rebased :)

2024-04-11 08:06 UTC, joanna-pagepro commented
@ArmandoGraterol branch rebased :)

2024-04-11 10:12 UTC, joanna-pagepro commented
@iamsamgibbs can you check if it's ok now?

2024-04-11 10:34 UTC, iamsamgibbs requested changes
Thanks for the changes, this is getting closer!

The error message is now showing correctly, but I can still interact with the "Fund from" field and the payments table.
 
<img width="679" alt="Screenshot 2024-04-11 at 11 30 25" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/ba203322-fe40-4a4f-bc38-0b6a68720d3e">

Compared to other actions where you cannot interact with any fields if you don't have valid permissions:
<img width="676" alt="Screenshot 2024-04-11 at 11 31 48" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/5a1f55dd-9ad3-4597-8d2f-31a226a44471">

2024-04-11 11:33 UTC, iamsamgibbs approved these changes
Amazing, thanks for all the changes, this is working perfectly now! 🎉 

<img width="676" alt="Screenshot 2024-04-11 at 12 29 28" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/e7cbd6e7-3685-491a-8115-2bee566aeb12">

(And still working as expected when you do have permissions with the extension installed)

<img width="677" alt="Screenshot 2024-04-11 at 12 33 09" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/75cf4900-49b3-4039-ab54-5cd69baef757">

2024-04-11 13:10 UTC, rdig approved these changes
Seems all good now. Nice work!

2024-04-12 05:43 UTC, merged