fix: copy tooltips
JoinColony/colonyCDapp pull request #2201
Opened 2024-04-10 10:52 UTC by CzarekDryl

## Description

- Added tooltip dedicated for copying
- Copy tooltip should hide after 2 seconds or on mouse leave/clicked outside
- Changed old component to new one in all places that it was used

Resolves [https://github.com/JoinColony/colonyCDapp/issues/2142](https://github.com/JoinColony/colonyCDapp/issues/2142)

2024-04-10 14:57 UTC, jakubcolony requested changes
The colony address copy tooltip works as intended and it closes on mouse leave/click:
<img width="437" alt="Screenshot 2024-04-10 at 15 52 51" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/1a055fbb-09b5-4eb9-a4be-e0c580a3bdd4">
03bf41

But it looks like the one on extensions page got broken:

https://github.com/JoinColony/colonyCDapp/assets/112586815/d81fb779-5f5a-46bf-95de-533c031d18f4

2024-04-10 14:57 UTC, jakubcolony commented on src/components/v5/shared/CopyTooltip/CopyTooltip.tsx
> +      document.addEventListener('mousemove', handleMouseLeave);
please rename the handler to match the event

2024-04-10 14:57 UTC, jakubcolony commented on src/components/v5/shared/CopyTooltip/types.ts
> +  selectTriggerRef?: (ref: HTMLElement | null) => HTMLElement | null;
This could extend the generic tooltip props

2024-04-11 07:55 UTC, bassgeta requested changes
On top of what Jakub already mentioned, would it be an option that this component wraps around or existing `Tooltip`? It's the same component with custom colors and a bit more elaborate logic for closing it.

2024-04-11 07:55 UTC, bassgeta commented on src/components/v5/shared/CopyTooltip/CopyTooltip.tsx
> +          'w-full': isFullWidthContent,
i would maybe just ditch this prop since we can pass w-full in the className if need be

2024-04-11 09:13 UTC, melyndav submitted a review, later dismissed
Hey @CzarekDryl thanks for working on improving this component.

Everything looks great. The only issue I have is that every tooltip has an ! added to the copy which is not wanted or in Figma. But I'll log this for another day.

2024-04-25 20:23 UTC, ArmandoGraterol submitted a review, later dismissed
LGTM 👍 From what I can see even the one in the extension page is working like it should now, nice job!
![Screenshot 2024-04-25 at 17 22 45](https://github.com/JoinColony/colonyCDapp/assets/18473896/454a00cc-e46c-440a-83a1-4c18279f9f58)

2024-04-29 09:24 UTC, jakubcolony submitted a review, later dismissed
LGTM, thanks for the changes @CzarekDryl 👍

2024-05-06 12:44 UTC, CzarekDryl commented
@bassgeta Please take a look at this one

2024-05-06 15:00 UTC, arrenv requested changes
@CzarekDryl Thank you for updating this. I should have been more specific in the spec, the mouseleave and onclick close should be on the tooltip, not on the icon.

2024-05-19 16:39 UTC, jakubcolony approved these changes

2024-05-20 09:11 UTC, iamsamgibbs requested changes
I'm now experiencing this bug with the tooltip where the usual hover tooltip stays visible after clicking and moving the cursor away.


https://github.com/JoinColony/colonyCDapp/assets/34915414/eb459294-9dc5-4c37-8352-4b8919f7f207

2024-06-10 10:21 UTC, arrenv commented
@CzarekDryl Are we able to close this out?

2024-08-14 09:39 UTC, closed without merging