Add Manage Whitelist dialog
JoinColony/colonyCDapp pull request #221
Opened 2023-01-24 23:30 UTC by ArmandoGraterol

Added manage whitelist dialog and updated some of the related components like `CSVUploader`.

![FireShot Capture 796 - Colony CDapp - localhost](https://user-images.githubusercontent.com/18473896/214444044-f58f523f-21d3-49ac-8877-bc4359d2a065.png)
![FireShot Capture 797 - Colony CDapp - localhost](https://user-images.githubusercontent.com/18473896/214444047-668f47a9-b157-46dd-b8e5-3dd235fb245f.png)
![FireShot Capture 798 - Colony CDapp - localhost](https://user-images.githubusercontent.com/18473896/214444049-a038f16d-3bc5-4f15-8a3d-1bc08b10ce80.png)

Contributes to #58

2023-01-29 23:30 UTC, rdig approved these changes
Besides component names, this is mostly good, however I'm still unsure how are we going to handle Whitelist with the database backend.

For now feel free to leave it in.

2023-01-29 23:30 UTC, rdig commented on src/components/common/Dialogs/ManageWhitelistDialog/ManageWhitelistDialog.tsx
> +const displayName = 'common.ColonyHome.ManageWhitelistDialog';
This should be under `Dialogs` not `ColonyHome` here as well

2023-01-29 23:30 UTC, rdig commented on src/components/common/Dialogs/ManageWhitelistDialog/NoWhitelistedAddressesState/NoWhitelistedAddressesState.tsx
> +  'common.ColonyHome.ManageWhitelistDialog.NoWhitelistedAddressesState';
This should be in `Dialogs` too

2023-01-29 23:30 UTC, rdig commented on src/components/common/Dialogs/ManageWhitelistDialog/WhitelistedAddresses/WhitelistedAddresses.tsx
> +  'common.ColonyHome.ManageWhitelistDialog.WhitelistedAddresses';
Same here about being in `Dialogs`

2023-02-17 03:10 UTC, Julianahlk requested changes
I am seeing a few issues after uploading a .csv

- The confirm button is still disabled, I would either expect it to be enabled or display an error message explaining what is wrong
- The back button is displayed as "button.back"
- If you switch tabs to Address Book then return back to the Add Address tab, the state in the UI of the uploaded csv is not saved.

<img width="515" alt="Screen Shot 2023-02-16 at 10 02 18 PM" src="https://user-images.githubusercontent.com/71563622/219539018-29ff3cf1-bfeb-4e95-9a7e-f5e3ade7820d.png">


- Uploading the template.csv that does not contain any whitelisted addresses triggers an uncaught exception

<img width="615" alt="Screen Shot 2023-02-16 at 10 09 44 PM" src="https://user-images.githubusercontent.com/71563622/219539907-d3b4a1fc-a2e6-4f70-946a-ca5aac71a050.png">

2023-02-17 10:09 UTC, jakubcolony requested changes
@ArmandoGraterol I'm seeing similar issues to Juliana with the back button, but more importantly, when I tried to drop the unmodified template, I got stuck in render loop:
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/112586815/219614382-dea9b683-de33-4461-8c54-bc9d69d99ef7.png">

When I tried to replicate it however, all I was seeing is the same error that Juliana already reported.

Does it make sense for the textarea to be shown when there are no addresses in the book?
<img width="519" alt="image" src="https://user-images.githubusercontent.com/112586815/219614783-e9853ed2-e32e-4f8a-9b3f-9154c98f60cc.png">

I'll re-review once the above is addressed

2023-03-07 17:16 UTC, ArmandoGraterol commented on src/components/common/Dialogs/ManageWhitelistDialog/ManageWhitelistActiveToggle.tsx
> +const displayName = `common.ManageWhitelistDialog.ManageWhitelistDialogForm.ManageWhitelistActiveToggle`;
If by path you mean the folder path, that's correct, but this component is only used inside `ManageWhitelistDialogForm`. It's like `NetworkFee` in that sense, it's not used on `CreatePaymentDialog` directly but in the form of the dialog.

2023-03-07 18:33 UTC, ArmandoGraterol commented on src/components/common/Dialogs/ManageWhitelistDialog/ManageWhitelistActiveToggle.tsx
> +      You are deactivating your colony’s address book.
Sounds good to me x2

2023-03-08 19:05 UTC, ArmandoGraterol commented
@Julianahlk @jakubcolony Added some changes to could solve the issues that you guys are having, please let me know if it works! Working on this CSV uploader is a bit of a hassle.
 
> * If you switch tabs to Address Book then return back to the Add Address tab, the state in the UI of the uploaded csv is not saved.

That's intentional per line 114 in `ManageWhitelistDialogForm`. Do you think that it would be best that we don't reset the form when we change tabs? I don't have a strong opinion on it :)

2023-03-09 15:41 UTC, jakubcolony approved these changes
LGTM, all seems to work 👍 Nice job!

2023-03-10 04:23 UTC, Julianahlk approved these changes
Working much better and approving for now.

Regarding saving the state when switching between the add address and address book tabs, in an ideal world it would be nice if the state saved because if you upload a csv then switch tabs, you need to upload it again.

2023-03-20 17:22 UTC, merged