Fix: Colony creation failure handling
JoinColony/colonyCDapp pull request #2225
Opened 2024-04-11 16:21 UTC by iamsamgibbs

## Description

This PR addresses an issue (#2128) - if something goes wrong when joining a colony, it will cause the joined colonies list to be empty.

The issue occurs because a ‘colonyContributor’ is created in the database very early on in the create colony flow. If the `createUniqueColony` lambda fails then  the `colony` doesn’t actually get created in the database. This means the ‘colonyContributor’ will be in the database but not actually linked to a colony, so the query to fetch the colonies for the colony switcher will fail.

This PR addresses this by moving the logic from the `createUniqueColony` lambda to block-ingestor. If the colony does not get added to the database, then the `colonyContributor` entry is deleted from the database.

Moving the `createUniqueColony` lambda to block-ingestor has a few other niceties - we no longer add listeners to colonies which are not correctly created, and ethereal metadata is deleted if a colony is not correctly created.

## Testing

TODO

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Remove the now unused `createUniqueColony` lambda
- [ ] Is there anything else that should be deleted if a colony fails to create?
- [ ] Is this actually the best way to handle this? Or should we be retrying parts of the process?

Resolves #2128

2024-04-15 14:58 UTC, rdig requested changes
All good, but since you moved the lambda logic into the block ingestor, the lambda itself has not purpose, so please remove it.

Otherwise, stellar work! :100:

2024-04-15 17:03 UTC, ArmandoGraterol requested changes
I'm having problems creating colonies as I'm getting this error:

![Screenshot 2024-04-15 at 13 57 44](https://github.com/JoinColony/colonyCDapp/assets/18473896/b819a081-8bfe-48a6-9a72-b44fe3236a40)

Any thoughts?

2024-04-16 15:40 UTC, iamsamgibbs commented
> I'm having problems creating colonies as I'm getting this error:
> 
> Any thoughts?

I don't get this error when running block-ingestor separately, but I am getting this error when it is running in docker - I'm also getting the same error on master, so I don't think it is being introduced here - looking into it.

2024-04-16 16:50 UTC, ArmandoGraterol reviewed
Yeah, it is still happening to me :( Also, it seems like a `.DS_Store` file was committed to the branch, is that intentional?

2024-04-17 13:51 UTC, iamsamgibbs commented
> Yeah, it is still happening to me :( Also, it seems like a `.DS_Store` file was committed to the branch, is that intentional?

Issue should be resolved now thanks to help from Jakub!

2024-04-17 14:30 UTC, iamsamgibbs commented
> Why is this also removing the `setCurrentVersion` lambda ?
> 
> Like I know Jakub removed it, but why does it show up in here? Does the branch need to be rebased or something ?

Jakub identified the colony version issue as the cause for the issue Armando and I have been experiencing with colony creation failing, so he helped cherry pick his commits into this branch (and relevant block-ingestor branch too) to apply the fix here and get things working.

2024-04-17 16:23 UTC, ArmandoGraterol submitted a review, later dismissed
Thank you for the changes, Sam! LGTM 👌

2024-04-17 16:23 UTC, ArmandoGraterol commented on .DS_Store
Is this file needed?

2024-04-18 12:45 UTC, jakubcolony commented on .DS_Store
interesting that the `.gitignore` didn't prevent it from being commited

2024-04-18 12:46 UTC, rdig submitted a review, later dismissed
Right. Well in that case, I'll approve it :)

2024-04-18 15:52 UTC, iamsamgibbs commented on .DS_Store
Strange! It is not needed! Looks like it was accidentally added about 8 months ago and it let my accidental changes get committed. Will remove it here.

2024-04-18 15:52 UTC, iamsamgibbs commented
Just removed accidental .DS_Store commit

2024-04-18 17:30 UTC, ArmandoGraterol approved these changes

2024-04-22 08:27 UTC, rdig approved these changes

2024-04-22 08:32 UTC, merged