Fix: Improvements to transaction errors
JoinColony/colonyCDapp pull request #2257
Opened 2024-04-18 15:48 UTC by iamsamgibbs

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #2222

2024-04-22 08:02 UTC, bassgeta requested changes
Code-wise looks good, I can confirm that the first 5 issues are all resolved!
However, I am getting this error for issue 6:
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/4160a137-f505-4da5-928f-c4f5762d24f5)

2024-04-22 23:45 UTC, jakubcolony requested changes
LGTM overall, just spotted one thing around issue 3

**Issue 1:**

All good here:

https://github.com/JoinColony/colonyCDapp/assets/112586815/59162b15-c4e1-4f21-8b16-ca6be527240a

**Issue 2:**

I think that looks right:

<img width="440" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/6a4f1e40-0163-4fa4-b80d-7a6e684fd386">

**Issue 3:**
The font-weight looks different in Figma:
<img width="440" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/9a52d994-5dc8-4666-b902-738db8055791">
<img width="502" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/b5fbd3ad-d23d-4a11-9507-9762a5a69699">

Issues 4, 5 and 6 all seem to be resolved.

Great work @iamsamgibbs!

2024-04-23 09:50 UTC, iamsamgibbs commented
Thanks for the review Jakub! Issue 3 is looking okay to me on my end?

<img width="444" alt="Screenshot 2024-04-23 at 10 48 08" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/f1e995a6-699b-4a51-a3f8-17ef20763b7a">

2024-04-23 23:51 UTC, jakubcolony approved these changes
Must've been a stale cache or something - all looks good now:

<img width="444" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/dc030f91-f01c-470a-ab24-bdd27c5f1381">

2024-04-29 16:25 UTC, chmanie commented on src/components/common/Extensions/UserHub/partials/TransactionsTab/partials/GroupedTransactionContent.tsx
> +          <TransactionStatus status={status} hasError={!!error} />
I have some reservations about passing in a separate error here, but I think it's necessary for now. I will handle this in my refactor.

2024-04-29 16:26 UTC, chmanie commented
Thank you @iamsamgibbs, this was important, at least to re-establish that functionality. I will address the extra error in my refactoring

2024-04-29 16:26 UTC, chmanie approved these changes
Thank you @iamsamgibbs, this was important, at least to re-establish that functionality. I will address the extra error in my refactoring

2024-04-30 14:49 UTC, merged