Fix: Created in field should only show current team or general
JoinColony/colonyCDapp pull request #2263
Opened 2024-04-19 16:29 UTC by davecreaser

## Description

* The created in field (in action forms) should be filtered based on the currently selected team.
* You should only be able to select to create the motion in the selected team, or general.
* You should not have the option to select any other team.
* Changing the team above it should update the created in field to match it.
* If the team above has not been selected and the created in field is changed, then any team can be chosen, but it should also change the team field above it to match, which in turn then filters the created in options.

https://github.com/JoinColony/colonyCDapp/assets/38098203/8ee06a8b-d1df-490f-995b-ab7e1cd2785d

## Testing

* Ensure you have voting reputation installed.
* Create an action with the Reputation Decision method in a team.
* Click on the created in field and check that the team options available to you is correct, based on the description above.

Test that the created in field is correctly filtered in the following places:

* Manage permissions
* Transfer funds
* Simple payment
* Edit a team

## Diffs

**New stuff** ✨

* New hook in the ActionSidebar folder to apply the same filtering logic in multiple places.

**Changes** 🏗

* Filter the action forms created in field options in the correct way.

Resolves #2223

2024-04-19 19:05 UTC, ArmandoGraterol reviewed
I'm not 100% sure about this but it I think it shouldn't be possible to create a upgrade colony version motion in any other domain other than Root/General, as after all, you are updating a whole-ass colony. It's not something domain specific:

![Screenshot 2024-04-19 at 15 53 03](https://github.com/JoinColony/colonyCDapp/assets/18473896/e4ab54d0-4afc-4f4d-b196-b58417e1471f)

2024-04-22 08:19 UTC, iamsamgibbs requested changes
Nice work on this so far! All the code looks great, but I've got a couple of very minor nitpicky issues that are definitely more quality of life improvements.

This isn't an issue introduced by this PR, but can quickly resolve it here - as Armando noticed, the 'Created in' field for 'Upgrade Colony version' should be read only.

<img width="618" alt="Screenshot 2024-04-22 at 09 05 07" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/59525336-d812-42c6-8fc9-d520ca469e21">

The 'Created in' field behaves a bit differently on 'Simple payment' compared to 'Transfer funds'. I think this is due to 'Transfer funds' having 'General' as the default team, whereas 'Simple payment' doesn't have a default. This means the 'Created in' field only shows 'General' as an option. It would be nice if these behaved consistently.

 Simple payment
<img width="611" alt="Screenshot 2024-04-22 at 09 01 41" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/1c78fbb8-36fb-4465-b7fd-c3311df32b44">

Transfer funds
<img width="626" alt="Screenshot 2024-04-22 at 09 01 49" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/2a6926e4-fbd3-4a35-86c3-b2ba3d88cc9c">

The 'Created in' field on 'Manage reputation' is also behaving slightly differently than the other actions. On the other actions, if you have selected a team and 'Created in' is set to 'General', when you change the team, the 'Created in' field will change from 'General' to the new team. On 'Manage reputation' it is staying on 'General'. Would be nice to either make all the other actions behave the same way as 'Manage reputation', or make 'Manage reputation' behave the same way as the others.


https://github.com/JoinColony/colonyCDapp/assets/34915414/72759d5b-8469-4991-a1b7-34675125935d

2024-04-22 10:29 UTC, davecreaser commented
Cheers guys, should be all consistent now! And I've made the Upgrade Colony Version createdIn field readonly too. 📈

2024-04-22 11:39 UTC, melyndav approved these changes
I've checked all the actions types and everything is working perfectly. Nice home run on this one @davecreaser! 🥇

2024-04-22 14:04 UTC, merged