Feat/#2228 update default root domain colour
JoinColony/colonyCDapp pull request #2269
Opened 2024-04-22 14:02 UTC by davecreaser

## Description

- Add a colour to the DomainColor enum called 'Root' which will be used as the default colour for the root domain (general) when a new colony is created.
- This colour should not be selectable when editing or creating a colony.
- If you edit the general domain to have a different colour, you should not be able to go back to the default colour.

Note: This PR is related to changes in the Block Ingestor here: https://github.com/JoinColony/block-ingestor/pull/208

## Testing

For this PR specifically, just check that the root colour (blue) is not selectable when editing or creating a team. There should only be 16 colours available to choose from, not 17.

If you want to test the full flow, you'll need to run block ingestor locally using this branch: https://github.com/JoinColony/block-ingestor/tree/feat/%232228-update-default-root-domain-colour

## Diffs

**New stuff** ✨

* Add a colour to the DomainColor enum called 'Root' which will be used as the default colour for the root domain (general) when a new colony is created.

Contributes to #2228

2024-04-22 22:59 UTC, jakubcolony requested changes
Changes look great, nice work @davecreaser, good to go as soon as the generated file is updated 👍

2024-04-22 22:59 UTC, jakubcolony commented on src/graphql/generated.ts
> +
Hmm, I think this is a leftover from before #2225, you might have to restart your dev and run codegen again.

2024-04-23 08:40 UTC, iamsamgibbs requested changes
Nice work on this so far @davecreaser 🎉

I can only see 16 colours as expected in the team colour picker and can confirm other teams cannot select the root colour.

<img width="426" alt="Screenshot 2024-04-23 at 09 23 42" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/ea791a08-d26c-4adf-afca-33c872c6c0c8">

I've found if you change the 'General' team colour to any other colour, then it makes it impossible to change back to the default colour - not sure if this is the intended behaviour or not.

<img width="459" alt="Screenshot 2024-04-23 at 09 24 22" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/b528ccbb-cdb9-47f9-ac74-8607bd9425a9">

And as Jakub mentioned, looks like codegen needs a re-run.

You could also add the most recent commit hash of your block-ingestor PR to the `colony-cdapp-dev-env-block-ingestor` docker file to get docker to build with that commit.

2024-04-23 09:28 UTC, melyndav commented
> I've found if you change the 'General' team colour to any other colour, then it makes it impossible to change back to the default colour - not sure if this is the intended behaviour or not.

FYI @iamsamgibbs it's intended. Default is the primary blue and then if they customize it's just the standard team option colours.

2024-04-23 10:05 UTC, davecreaser commented
Codegen has been rerun, looks cleaner now ;)

2024-04-23 10:16 UTC, iamsamgibbs approved these changes
Looks good to me now!

2024-04-23 11:35 UTC, melyndav approved these changes
Appreciate your work on this fix @davecreaser! 💯

2024-04-24 08:15 UTC, merged