Feat: Cancel streams using permissions
JoinColony/colonyCDapp pull request #2321
Opened 2024-05-03 15:10 UTC by iamsamgibbs

## Description

Users should be able to cancel streaming payments.

This PR implements a new saga and a block-ingestor handler.

## Testing

1. Install the streaming payments extension
2. Create a new streaming payment using the temporary UI on the dashboard
3. Run this query and note the end time of the streaming payment

```
query MyQuery {
  listStreamingPayments {
    items {
      endTime
      startTime
      nativeId
    }
  }
}
```

4. Using the temporary dashboard UI, cancel the streaming payment (ids start at 1)
5. Run the query again and notice the endTime change
6. Verify a new colony action was created by running this query. The latest action should have a streamingPaymentId.

```
query MyQuery {
  listColonyActions {
    items {
      streamingPaymentId
      id
      streamingPayment {
        id
        endTime
        createdAt
      }
    }
  }
}
```

## Diffs

**New stuff** ✨

* Cancel streaming payment saga

**Changes** 🏗

* Colony action now accepts streaming payment ID

Resolves #2215

2024-05-06 18:39 UTC, ArmandoGraterol approved these changes
LGTM! Replicated the instructions and I was able to check that the action is being created:
![Screenshot 2024-05-06 at 15 39 14](https://github.com/JoinColony/colonyCDapp/assets/18473896/f9bd94dc-a733-4402-9bd2-516df5a2f7b9)

2024-05-07 13:56 UTC, jakubcolony requested changes
Great start on this PR @iamsamgibbs! Everything seems to be working well, including annotations:
<img width="494" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/6217118f-2069-4961-8bcf-dd4e3b0782f5">

The only problem I spotted is that messages seem to be missing for cancel transactions:
<img width="459" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/fc12e1f2-6879-4309-9b8c-934999dbb025">

I have 2 more requests which have not been specifically covered in the issue but would appreciate if they could be added:
 - Link between `StreamingPayment` and `ColonyActions` model, ie. `actions` field on the streaming payment that would contain all actions related to the stream (currently just `CANCEL_STREAMING_PAYMENT`)
 - A field on the `StreamingPayment` model to indicate that the stream was cancelled - I think a boolean flag will suffice for now

2024-05-07 13:56 UTC, jakubcolony commented on amplify/backend/backend-config.json
I don't think this should be committed

2024-05-08 13:57 UTC, iamsamgibbs commented
Made those changes / additions as requested @jakubcolony

2024-05-08 21:11 UTC, jakubcolony approved these changes
LGTM, thanks for making the changes 👍 

<img width="630" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/46006de1-8466-4324-89c2-f89052a23f07">

2024-05-09 13:18 UTC, rdig approved these changes
Nicely done! :100:

2024-05-09 13:42 UTC, merged