Create claim streaming payment saga
JoinColony/colonyCDapp pull request #2323
Opened 2024-05-03 16:31 UTC by davecreaser

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-05-07 17:11 UTC, ArmandoGraterol reviewed
looking good to me! Just 1 question... I've followed the testing instructions and seems like I was able to claim successfully and see the change reflected on my balance, however, the `Amount claimed to date` is still `0`. Is this expected?
![Screenshot 2024-05-07 at 14 10 12](https://github.com/JoinColony/colonyCDapp/assets/18473896/b6f516f7-b9b7-4a9f-ab92-112b54ba938f)

I would expect this amount to change to the 7k I just claimed

2024-05-07 17:15 UTC, davecreaser commented
> looking good to me! Just 1 question... I've followed the testing instructions and seems like I was able to claim successfully and see the change reflected on my balance, however, the `Amount claimed to date` is still `0`. Is this expected? ![Screenshot 2024-05-07 at 14 10 12](https://private-user-images.githubusercontent.com/18473896/328614239-b6f516f7-b9b7-4a9f-ab92-112b54ba938f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDIyODIsIm5iZiI6MTcxNTEwMTk4MiwicGF0aCI6Ii8xODQ3Mzg5Ni8zMjg2MTQyMzktYjZmNTE2ZjctYjliNy00YTlmLWFiOTItMTEyYjU0YmE5MzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE3MTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTlkYzBkNzk2YjNkNDliMGI1YmU5YWQ4NWNkODQ3OTNmYTY3ZDc0NTk4MTliZTM5ZmUwYjEzODFhMjUxNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GH8ODcwef0U6vyLdR9EhEFdLxakheFJ1aY2m9Yq9B4E)
> 
> I would expect this amount to change to the 7k I just claimed

Hmm, not expected! Is it still 0 after refreshing the page? (I haven't put in any auto updating of that number since it's just a temporary UI, but after a refresh it should be updated)

2024-05-07 17:17 UTC, davecreaser commented
Okay cool cool, definitely a bug then! I'll look into it, thanks :)

2024-05-07 21:31 UTC, jakubcolony requested changes
Gotta say I love the new UI! 💯 

I left a few comments but it's a very solid piece of work, especially considering it's your first "proper" issue - so well done @davecreaser.

Functionally everything seems to be on point, but after pulling latest changes I still can't get the "claimed to date" amount to work:
<img width="418" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/bc3b32da-38c2-492c-b2f9-48496deeec5a">

It seems like no claims are being created in the DB:
<img width="507" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/237526ba-68d5-4172-9fbe-710f7ff2bfc5">

Happy to jump on a call tomorrow to debug (unless of course I'm doing something wrong?)

2024-05-07 21:31 UTC, jakubcolony commented on src/hooks/useStreamingPaymentAmountsLeft.ts
> +          .div(BigNumber.from(10).pow(18));
I was going to make a comment about using hardcoded 18 as token decimals but upon further reading further on this I suppose it's a good representation of how solidity does multiplication - https://github.com/dapphub/ds-math?tab=readme-ov-file#wmul. Nice work figuring this out 👍

2024-05-08 08:34 UTC, davecreaser commented
@jakubcolony and @ArmandoGraterol could you please try again and see if the amount claimed to date is now correct? I realised that I never updated the block ingestor hash in the docker files so unless you ran the block ingestor separately then it wouldn't have worked :) It is updated now though, so npm run dev should be enough!

2024-05-08 09:01 UTC, davecreaser commented on src/hooks/useStreamingPayments.ts
Oh yeah, hadn't spotted that. Added it now!

2024-05-08 19:10 UTC, jakubcolony requested changes
Thanks for the changes @davecreaser, just one tiny detail before you merge - we seem to be missing i18n messages for claim transaction - could you please have a look at the `en.json` file? While you're there, it'd be great if you could also add one for create stream transaction, I must have missed it the first time!

<img width="458" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/e71f392f-8fc8-4fa5-ae9e-efbcb332abcf">

2024-05-09 10:20 UTC, iamsamgibbs approved these changes
Nice job on this one, everything is working great.

<img width="1114" alt="Screenshot 2024-05-09 at 11 15 55" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/e891cc43-c2eb-4326-801a-6328524145d9">

Balance is updating correctly.

<img width="659" alt="Screenshot 2024-05-09 at 11 16 17" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/7fa95eff-3f97-4fc8-beb5-dc510c2ed2e1">

il8n messages look good.

<img width="674" alt="Screenshot 2024-05-09 at 11 16 24" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/1b5364ce-7678-4f0e-a899-a5307428f0bb">

And available amount to claim is working as expected.

<img width="1107" alt="Screenshot 2024-05-09 at 11 16 39" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/273a9ca3-c8e2-42f5-8415-5d5d41646e88">

Nice job!

2024-05-09 22:25 UTC, jakubcolony approved these changes
LGTM, great work 👍

2024-05-10 07:24 UTC, iamsamgibbs approved these changes
All looks good! Thanks for dealing with the rebase!

2024-05-10 09:11 UTC, merged