Strip headers in minimised descriptions
JoinColony/colonyCDapp pull request #2359
Opened 2024-05-10 14:32 UTC by davecreaser

## Description

- Ensure that in descriptions in a collapsed state (actions and agreements) do not show header elements.

Details here: https://github.com/JoinColony/colonyCDapp/issues/2273

## Testing

- Open any action type
- Use the WYSIWYG or markup to add headings into the description field and add a regular block of content
- Complete the action
- View the description field in the collapsed state and check that the headings don't show

- Open the agreement action type
- Use the WYSIWYG or markup to add headings into the description field and add a regular block of content
- Save it as a draft or complete the agreement flow
- Visit the agreements page and view the draft or completed agreement card, and check that the headings don't show

## Diffs

**New stuff** ✨

* New strings util `stripAndremoveHeadingsFromHTML`

**Changes** 🏗

* Remove headings from collapsed descriptions

Resolves #2273

2024-05-10 14:59 UTC, melyndav requested changes
Hey @davecreaser nice start on this one.

While testing payments, the description box seems to be working as expected with handling headings.

However, when testing agreements, the 'save draft' option on this action type isn't working in this branch but seems to be working on master just fine. I get the console error when selecting the save draft button.

<img width="1351" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/06ccdc40-cc18-461e-ae7e-40c26f52ad89">

2024-05-11 11:49 UTC, SandipGyawali commented
@davecreaser how did you setup the project i am having trouble in it can you help me ??

2024-05-11 23:21 UTC, chmanie commented
@SandipGyawali feel free to send me a mail, I might be able to help: chris@colony.io :)

2024-05-13 10:11 UTC, davecreaser commented
> Hey @davecreaser nice start on this one.
> 
> While testing payments, the description box seems to be working as expected with handling headings.
> 
> However, when testing agreements, the 'save draft' option on this action type isn't working in this branch but seems to be working on master just fine. I get the console error when selecting the save draft button.
> 
> <img alt="image" width="1351" src="https://private-user-images.githubusercontent.com/82127904/329624131-06ccdc40-cc18-461e-ae7e-40c26f52ad89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTM0OTAsIm5iZiI6MTcxNTU5MzE5MCwicGF0aCI6Ii84MjEyNzkwNC8zMjk2MjQxMzEtMDZjY2RjNDAtY2MxOC00NjFlLWFlN2UtNDBjMjZmNTJhZDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA5Mzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMDI4OWNmMTQzMDBlNzg1M2M2ZWJjM2ExMDJjYjkyNzI1ZjI1NmFlYWY3MWE5Y2Q2OTRiODhkMzg2YjUxYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qHN_dpgJcZEAza8F2-28rb6zNZtGT9kQDCarX6vhfLU">

Thanks @melyndav!

Very strange that it didn't work for you - the error seems to be unrelated, and really weird since it's a 403 (forbidden) from Amplify 🤔 

I've rebased the branch on master and tested it again locally (screen recording below). Maybe it works for you now after the rebase? If not, we'll have to dive in a bit deeper and see what's happening!

https://github.com/JoinColony/colonyCDapp/assets/38098203/f1ec4232-9a11-4aa6-ac44-7f2d79b25460

2024-05-13 11:18 UTC, melyndav approved these changes
Something funky was going on there @davecreaser, but we're back to regular programming 👍 

<img width="1362" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/e9ec8d42-15eb-46cd-b8a7-9daabe32615a">

Everything is looking as it should. Thanks for your work on this issue!

2024-05-13 14:20 UTC, rdig approved these changes
Nicely done! :100:

2024-05-13 14:58 UTC, merged