Feat/#2200 allow modifying stake fraction
JoinColony/colonyCDapp pull request #2386
Opened 2024-05-16 15:01 UTC by davecreaser

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-05-17 15:14 UTC, iamsamgibbs requested changes
Nice work on this Dave! All working as expected 👍 

<img width="319" alt="Screenshot 2024-05-17 at 16 12 33" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/e82cc2ac-ca55-4b27-8f5c-6affcde2ffa0">

Just looks like a couple of unrelated commits got accidentally mixed into this, once those are resolved should be good to go!

2024-05-17 15:18 UTC, iamsamgibbs commented
Some code snippets to add to `TmpAdvancedPayments.tsx` for the sake of anyone else who wants to test:

`import { type SetStakeFractionPayload } from '~redux/sagas/expenditures/setStakeFraction.ts';`

```
  const setStakeFraction = useAsyncFunction({
    submit: ActionTypes.SET_STAKE_FRACTION,
    error: ActionTypes.SET_STAKE_FRACTION_ERROR,
    success: ActionTypes.SET_STAKE_FRACTION_SUCCESS,
  });

  const handleModifyStakeFraction = async () => {
    const payload: SetStakeFractionPayload = {
      colonyAddress: colony.colonyAddress,
      stakeFraction: '50',
    };

    await setStakeFraction(payload);
  };
  ```
  
  ` <Button onClick={handleModifyStakeFraction}>Modify stake fraction</Button>`

2024-05-17 15:33 UTC, davecreaser commented
> Nice work on this Dave! All working as expected 👍
> 
> <img alt="Screenshot 2024-05-17 at 16 12 33" width="319" src="https://private-user-images.githubusercontent.com/34915414/331647654-e82cc2ac-ca55-4b27-8f5c-6affcde2ffa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjAyNzgsIm5iZiI6MTcxNTk1OTk3OCwicGF0aCI6Ii8zNDkxNTQxNC8zMzE2NDc2NTQtZTgyY2MyYWMtY2E1NS00YjI3LThmNWMtNmFmZmNkZTJmZmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE1MzI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYThiZmQyZTVhMDY2YThjZmUyNWNhODM5YmZlMmNiY2UyOTRkMzBmNzM0ODJhOWY3NDgwYTIxMzg3N2YyN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nSOVb6UXOA541JVJHhhix_KFszqCH85m6N3-Fe_2L7U">
> Just looks like a couple of unrelated commits got accidentally mixed into this, once those are resolved should be good to go!

Cheers Sam! And thanks for catching those commits, I've rebased and removed them :)

2024-05-17 15:37 UTC, iamsamgibbs approved these changes

2024-05-20 17:22 UTC, rdig approved these changes
Nicely done!

2024-05-20 21:19 UTC, jakubcolony approved these changes
Changes look and work great, nice job @davecreaser 👍 

Considering it's resolving the first part of the issue, would you mind opening another one for the other subtask?

2024-05-20 21:19 UTC, jakubcolony commented on src/i18n/en.json
> +    "transaction.ColonyClient.installExtension.description": "Install extension",
Nice catch!

2024-05-21 08:11 UTC, davecreaser commented
> Changes look and work great, nice job @davecreaser 👍
> 
> Considering it's resolving the first part of the issue, would you mind opening another one for the other subtask?

@jakubcolony No problem. You mean opening another issue or another PR?

2024-05-21 10:21 UTC, merged