[Multi-sig] Cancel MultiSig Motion as Owner
JoinColony/colonyCDapp pull request #2454
Opened 2024-05-29 08:55 UTC by iamsamgibbs

## Description

[See block-ingestor counterpart](https://github.com/JoinColony/block-ingestor/pull/229)

As a *user that created a multi-sig motion*, I want to be able to cancel it.

This PR adds a new `cancelMultiSig` saga and `MotionCanceled` event handler to block-ingestor. A new `MultiSigMeatballMenu` component has been added to the `MintTokens` completed action screen. (The same component will need adding to the other completed action screens as multisig is implemented across the other action types).

## Testing

* Step 1 - Install the multisig extension
* Step 2 - Create a new Mint Tokens action using the multisig permission type
* Step 3 - Run the following query to check the `isRejected` status of the multisig motion

```
query MyQuery {
  listColonyMultiSigs {
    items {
      action {
        type
        multiSigData {
          nativeMultiSigId
          isRejected
        }
      }
    }
  }
}

```

* Step 4 - From the completed action meatball menu, select `Reject action`
* Step 5 - Run the query again to confirm the flag has updated

## Diffs

**New stuff** ✨

* `cancelMultiSig` saga added
* `MotionCanceled` handler added
* `MultiSigMeatballMenu` added

<img width="1059" alt="Screenshot 2024-05-29 at 09 49 26" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/43fc304a-4db3-4b9d-a9c1-85872e742826">
<img width="319" alt="Screenshot 2024-05-29 at 09 49 58" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/fe9462d2-fd06-415e-9a45-796a6e71415b">

Resolves #2159

2024-05-29 10:35 UTC, marcocolony approved these changes
@iamsamgibbs Nice job, everything is working well 🙌 
![Export-1716978730839](https://github.com/JoinColony/colonyCDapp/assets/165801260/793d343a-1e91-4d27-95c5-6e13afdf34d3)

2024-05-29 13:24 UTC, bassgeta requested changes
Great job, everything works as it should smooth as butter!
A typo is left, plus 
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/a21691d9-c5f3-4931-9509-4e01fa2c8e74)
if we can make multi-sig rejected motions have the same `Failed` pill on the top left as voting reputation
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/c249d304-3ae3-4ea0-97c6-6ad6dfdf18b2)
would be perfect :ok_hand:

2024-05-29 21:49 UTC, jakubcolony requested changes
Looking good apart from a few bits, nice work 👍

2024-05-29 21:49 UTC, jakubcolony commented on src/redux/sagas/multiSig/cancelMultiSig.ts
> +      ActionTypes.MULTISIG_SET_THRESHOLDS_ERROR,
Same here

2024-05-30 08:19 UTC, iamsamgibbs commented
Thanks Jakub, those should all be resolved now!

2024-05-30 13:03 UTC, bassgeta approved these changes
Still works like a charm, nice one :+1:

2024-05-30 17:32 UTC, jakubcolony approved these changes
LGTM 👍

2024-05-31 11:00 UTC, merged