Fix: Team colour picker mobile view UI adjustments
JoinColony/colonyCDapp pull request #2477
Opened 2024-06-04 18:25 UTC by rumzledz

## Description

It's not pixel perfect compared to the [Figma designs](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-177&t=I6SkwLY4baMEi24f-4) when it comes to non-mobile phone specific viewports below the 768px width breakpoint but hopefully this satisfies the AC when it comes to actual phone dimensions like the iPhone SE or the iPhone 14 Pro Max.

As a side note, this `SearchItem` component seems to manage various scenarios, resulting in a couple of conditional and shared styles that can be challenging to maintain over time. Ideally, in the future, we should create a dedicated component specifically for the colour picker.

| Before (iPhone SE) | (Now) iPhone SE |
| ---- | ---- |
| ![Screenshot 2024-06-04 at 19 18 24](https://github.com/JoinColony/colonyCDapp/assets/50642296/384ff2a4-769e-4e12-b9e1-7152affc5c47) | ![Screenshot 2024-06-04 at 18 56 18](https://github.com/JoinColony/colonyCDapp/assets/50642296/5f556cf8-80d3-4bb2-b7a4-ee129f1def7e) |

| Before (iPhone 14 Pro Max) | After (iPhone 14 Pro Max) |
| ---- | ---- |
| ![Screenshot 2024-06-04 at 19 21 18](https://github.com/JoinColony/colonyCDapp/assets/50642296/1603dcff-08ef-4cbc-bc71-b3d236a3c678) | ![Screenshot 2024-06-04 at 18 56 30](https://github.com/JoinColony/colonyCDapp/assets/50642296/b0d45199-a533-4ae7-be1a-fae8bff85d56) |

## Testing

1. Set your browser to mobile view i.e. iPhone 14 Pro
2. Open the 'Create team' or 'Edit team' action form
3. Click the 'Team colour' field
4. Verify that the colour picker layout matches the [Figma designs](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-177&t=I6SkwLY4baMEi24f-4). I do remember @melyndav telling me that the aim is not to be super pixel perfect so hopefully that's all right as far as the actual mobile viewport goes.

Resolves #2417

2024-06-04 20:04 UTC, rdig approved these changes
Tested and seems to resemble the designs. Nicely done.

![Screenshot from 2024-06-04 23-01-48](https://github.com/JoinColony/colonyCDapp/assets/1193222/3e03c9a5-a10b-45e7-9a5c-fd12406d911f)
![Screenshot from 2024-06-04 23-03-26](https://github.com/JoinColony/colonyCDapp/assets/1193222/00bb1801-683a-472d-9db3-fa493427a78a)

2024-06-05 07:39 UTC, iamsamgibbs requested changes
Nice work on this, the spacing looks a lot better. One issue I've noticed is that if the team colour field is too close to the bottom of the page, then the popover will open off the page and won't be possible to get to the bottom row of colours as it isn't scrollable. The colours also overflow the popover in this scenario.

![Screenshot 2024-06-05 at 08 26 33](https://github.com/JoinColony/colonyCDapp/assets/34915414/99cc20f1-27b6-402b-ba2a-844d6b02c698)

https://github.com/JoinColony/colonyCDapp/assets/34915414/7563bee8-0b8e-4096-bc4d-5b9f874ee457

2024-06-05 10:00 UTC, rumzledz commented
> Nice work on this, the spacing looks a lot better. One issue I've noticed is that if the team colour field is too close to the bottom of the page, then the popover will open off the page and won't be possible to get to the bottom row of colours as it isn't scrollable. The colours also overflow the popover in this scenario.

I thought I was safe because this is already a production issue but not mentioned in the bug ticket!!! 😭😂 But yep! I'll try to figure something out 👌

2024-06-05 10:13 UTC, iamsamgibbs commented
Can always open this issue as a separate ticket if you feel like it is out of scope here :) It might require quite a bit of digging to resolve

2024-06-05 11:10 UTC, rumzledz commented
> Can always open this issue as a separate ticket if you feel like it is out of scope here :) It might require quite a bit of digging to resolve

@iamsamgibbs pushed! 🚀 

![2417_bonus](https://github.com/JoinColony/colonyCDapp/assets/50642296/d69a46f6-3135-41e3-b6e4-7022c0b3b664)

2024-06-05 13:41 UTC, iamsamgibbs approved these changes
Thanks for the fix, tested and looking good now!

![Screenshot 2024-06-05 at 14 37 54](https://github.com/JoinColony/colonyCDapp/assets/34915414/e4d5edef-b1b2-4e81-835a-9cf2fc0132e4)

2024-06-05 18:14 UTC, rdig approved these changes
Re-approved

2024-06-06 09:25 UTC, merged