Fix: Handle transactions that don't exist
JoinColony/colonyCDapp pull request #2479
Opened 2024-06-05 11:07 UTC by davecreaser

## Description

- Properly handle the case in the action sidebar when opening an action that doesn't exist.
- Two cases are covered:
  - When the transaction hash is incorrect
  - When the transaction can't be found in the db

## Testing

- Navigate to the following URL: `http://localhost:9091/planex/activity?tx=0x`
- The action panel should load with a 404 message.

- Navigate to the following URL: `http://localhost:9091/planex/activity?tx=0xfd44e904a267f7c1377486f03020effc50139df775007be4efb7f5bf102b8a7b`
- The action panel should try to load the action for 20 seconds, before throwing a 404 (with a retry button).

## Diffs

**New stuff** ✨

* New reusable 404 message component. The 404 page now uses this too.

**Changes** 🏗

* Update the action sidebar to handle not found actions.
* Update the 404 page to use a reusable component.

## TODO

- [ ] Check with @arrenv and @melyndav about the retry button for the second case, since it's different functionality from the original issue / designs. It came about from conversation with some dev team members as a nice feature to include, since an action might take some time to be created in the db, so it being missing might just be a time issue. This change can easily be removed if it's not wanted however.

Resolves #2335

2024-06-06 08:14 UTC, iamsamgibbs requested changes
Nice work! Code changes look good to me, both testing examples working as expected and 404 page is unaffected.

![Screenshot 2024-06-06 at 08 57 22](https://github.com/JoinColony/colonyCDapp/assets/34915414/b9f0be16-ca3e-42a6-967a-bef4d0eca84e)
![Screenshot 2024-06-06 at 09 05 32](https://github.com/JoinColony/colonyCDapp/assets/34915414/c0fc00a4-8124-4b4c-9512-50a4e5ac3717)
![Screenshot 2024-06-06 at 09 10 03](https://github.com/JoinColony/colonyCDapp/assets/34915414/7ff1670a-4025-4211-b160-6c9cec04b5cb)

However it seems to have affected the staking stage of motions:

https://github.com/JoinColony/colonyCDapp/assets/34915414/3647cf48-3eee-4389-b4e5-60628adde0de

2024-06-06 09:14 UTC, bassgeta requested changes
Nice work on this, a nice and sane solution! I am getting the same issue Sam spotted and dropped a comment for composing stuff in instead of passing in objects.

2024-06-06 09:14 UTC, bassgeta commented on src/components/v5/common/FourOFourMessage/FourOFourMessage.tsx
> +  primaryLinkButton,
could we maybe just compose these in? so we just render the `primaryLinkButton` as passed next to the report button.
The links are a bit trickier, but I think it makes sense to just compose them in and have the parent component control if the link is external or internal. It's a bit tricky to get the styles in (maybe we could wrap each of them in a div and apply the styles there, or try CSS selectors from this component).

2024-06-06 17:36 UTC, davecreaser commented
Cheers @iamsamgibbs and @bassgeta - issues are now fixed and I've switched the props to use composition 🚀

2024-06-07 08:43 UTC, iamsamgibbs submitted a review, later dismissed
All good now! Motion flow is restored.

2024-06-07 10:52 UTC, bassgeta approved these changes
Calm and composed :sunglasses: 
Nice one, the bug has been fixed so it's time to :ship:

2024-06-07 11:38 UTC, arrenv commented
I think the enhancement is an good.

I would suggest updating the copy to be more relevant in this case:

"The transaction you're looking for could not be loaded or does not exist. Please check the link is correct, retry, or look for the transaction on the activity page."

2024-06-07 14:30 UTC, davecreaser commented
Thanks @arrenv, copy is now updated! We are now merging after three approvals, so feel free to add yours here if you would like it to be merged 😆 

@iamsamgibbs and @bassgeta - a reapproval is required if you please 😄

2024-06-10 09:14 UTC, iamsamgibbs approved these changes
Still working and new copy is in. 👍 

<img width="1728" alt="Screenshot 2024-06-10 at 10 13 04" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/fdfb6f61-c547-4886-ac86-b3aa851a487b">

2024-06-10 11:38 UTC, arrenv approved these changes
Thanks @davecreaser, all working as expected for me.

Regarding the description, I should have not added "in this case", as I had meant for the updated description to be used for all cases :)

However, I think the conditional copy is fine.

2024-06-12 11:11 UTC, davecreaser commented
@arrenv @bassgeta @iamsamgibbs I had to rebase and it wiped all the approvals I'm afraid 🙃 Could I steal them back please?

2024-06-12 13:40 UTC, bassgeta approved these changes
re-base, re-approve, let's get this one shipped :ship:

2024-06-12 15:23 UTC, iamsamgibbs approved these changes

2024-06-12 15:51 UTC, arrenv reviewed
All looks good still!

2024-06-12 15:51 UTC, arrenv approved these changes

2024-06-12 15:52 UTC, merged