[Multi-sig] feat: uninstallation of multi-sig extension
JoinColony/colonyCDapp pull request #2488
Opened 2024-06-06 13:57 UTC by bassgeta

## Description

- [] TODO write description
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/236)

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-06-13 11:28 UTC, iamsamgibbs requested changes
Nice work on this! Left a couple of tiny notes on the block-ingestor PR.

As expected, whilst the extension is deprecated, I am still able to approve and finalize multisig motions but not create new ones, and roles are still preserved in the database.

<img width="701" alt="Screenshot 2024-06-13 at 11 43 09" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/4d8ba9c1-ffe3-435f-a1c8-745e7ebcb874">

<img width="700" alt="Screenshot 2024-06-13 at 11 43 13" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/0e2346a2-d863-4ed3-b560-5aa808b7adfa">

When uninstalled, I receive the message as expected, the motions remain in the database and the roles are gone.

<img width="1052" alt="Screenshot 2024-06-13 at 11 45 46" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/67d4a421-6d03-44b8-8fb9-ee89d68b5ccd">

<img width="704" alt="Screenshot 2024-06-13 at 11 46 09" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/748088bd-d42a-4631-b73d-83e9a18d749f">

<img width="528" alt="Screenshot 2024-06-13 at 11 46 15" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/f2b326e1-e020-4ca1-a7b7-3cb9e939adc0">

I've noticed the nativeMultiSigId is always reset to 1 after uninstalling and installing the extension, I'm not sure if this is likely to cause us any issues anywhere?

<img width="573" alt="Screenshot 2024-06-13 at 12 23 46" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/d4e24693-d581-48ef-b1ad-0df7de9d6691">

I'm also experiencing an issue where the roles are sometimes not automatically assigned when installing the extension. I've experiencing this twice, but not sure on the exact steps to recreate, just seems to happen sometimes after uninstalling and reinstalling.

https://github.com/JoinColony/colonyCDapp/assets/34915414/f93f287d-2b51-4ea9-980f-943e7772751f

2024-06-14 09:45 UTC, bassgeta commented
> Nice work on this! Left a couple of tiny notes on the block-ingestor PR.
> 
> As expected, whilst the extension is deprecated, I am still able to approve and finalize multisig motions but not create new ones, and roles are still preserved in the database.
> <img alt="Screenshot 2024-06-13 at 11 43 09" width="701" src="https://private-user-images.githubusercontent.com/34915414/339338282-4d8ba9c1-ffe3-435f-a1c8-745e7ebcb874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTg0NzcsIm5iZiI6MTcxODM1ODE3NywicGF0aCI6Ii8zNDkxNTQxNC8zMzkzMzgyODItNGQ4YmE5YzEtZmZlMy00MzVmLWExYzgtNzQ1ZTdlYmNiODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MWRhNTA2MjExZGMzNGVmMTliNmNjOGY1N2Q4YjgwZTkwMWI5MTRmNDc3MWM1NThjZGJkZDUwMTJhMWIxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YfxPY-fsEwCzXB3cBsAxWOq42oIEDcciPLkjpeYclxE"> <img alt="Screenshot 2024-06-13 at 11 43 13" width="700" src="https://private-user-images.githubusercontent.com/34915414/339338296-0e2346a2-d863-4ed3-b560-5aa808b7adfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTg0NzcsIm5iZiI6MTcxODM1ODE3NywicGF0aCI6Ii8zNDkxNTQxNC8zMzkzMzgyOTYtMGUyMzQ2YTItZDg2My00ZWQzLWI1NjAtNWFhODA4YjdhZGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMzc0NzJiZjE2YjMwZDBkOGJhOWQ3M2FlNWNjZjZjNmI2ZWFhMDE1NmIxMTM1NTRiN2RhZTE0NDhkNmJiMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.igIxwvAbJKo_nVwRF2a4StsEC-MqV_yWqfJAjcLMk-w">
> 
> When uninstalled, I receive the message as expected, the motions remain in the database and the roles are gone.
> <img alt="Screenshot 2024-06-13 at 11 45 46" width="1052" src="https://private-user-images.githubusercontent.com/34915414/339338707-67d4a421-6d03-44b8-8fb9-ee89d68b5ccd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTg0NzcsIm5iZiI6MTcxODM1ODE3NywicGF0aCI6Ii8zNDkxNTQxNC8zMzkzMzg3MDctNjdkNGE0MjEtNmQwMy00NGI4LThmYjktZWU4OWQ2OGI1Y2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkN2QzOWM2OTMwMmRkODdlNGI2MGM2NGU0ZmM3YTFjYjZjNmYyNDI2ZWY5NzQ1NDc5ZTIyZmU2YWIxMzA4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxdgCC8_gcXs5K8J4stijARaydCgIp0dnXS8Fijjigg"> <img alt="Screenshot 2024-06-13 at 11 46 09" width="704" src="https://private-user-images.githubusercontent.com/34915414/339338712-748088bd-d42a-4631-b73d-83e9a18d749f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTg0NzcsIm5iZiI6MTcxODM1ODE3NywicGF0aCI6Ii8zNDkxNTQxNC8zMzkzMzg3MTItNzQ4MDg4YmQtZDQyYS00NjMxLWI3M2QtODNlOWExOGQ3NDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZDY3NTZjZDcwZmNiNDkyZjVmMWIwY2ZkYzAwNTNlNDIyM2MzMjIxYjU2M2VlMjczM2VmMmVmMDA3OGEzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZGN8f2plZ2Iwk3Fpuev7giuUXEKT-63ZgbAI_JRq8aI"> <img alt="Screenshot 2024-06-13 at 11 46 15" width="528" src="https://private-user-images.githubusercontent.com/34915414/339338715-f2b326e1-e020-4ca1-a7b7-3cb9e939adc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTg0NzcsIm5iZiI6MTcxODM1ODE3NywicGF0aCI6Ii8zNDkxNTQxNC8zMzkzMzg3MTUtZjJiMzI2ZTEtZTAyMC00Y2ExLWE3YjctM2NiOWU5MzlhZGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0M2FmYmVkMWUwNDc2OWE5NzA2Y2VmNzAwNTNjOTA0MzYwOTBmMTcyNTM0YjcxMDZkOTYxOTFkYmE4YTM1ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UmyxcrHgwgj3KxjLcZ1ZBtH1ABn2AsDVUOI6TA9OANc">
> 
> I've noticed the nativeMultiSigId is always reset to 1 after uninstalling and installing the extension, I'm not sure if this is likely to cause us any issues anywhere?
> <img alt="Screenshot 2024-06-13 at 12 23 46" width="573" src="https://private-user-images.githubusercontent.com/34915414/339340125-d4e24693-d581-48ef-b1ad-0df7de9d6691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTg0NzcsIm5iZiI6MTcxODM1ODE3NywicGF0aCI6Ii8zNDkxNTQxNC8zMzkzNDAxMjUtZDRlMjQ2OTMtZDU4MS00OGVmLWIxYWQtMGRmN2RlOWQ2NjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA5NDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MTRiYWM2OGEzMTY2YWJmNGRmOTBjZmNiNzM5ODUwOGFiYjc2MDQwMjIzZDZlZDkzODgyOGJhYjNiNjNlNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G2AE1tU_SIlMF05MiDbAhdR9UK-wsplwTk0_jm1Iss0">
> 
> I'm also experiencing an issue where the roles are sometimes not automatically assigned when installing the extension. I've experiencing this twice, but not sure on the exact steps to recreate, just seems to happen sometimes after uninstalling and reinstalling.
> Screen.Recording.2024-06-13.at.12.00.58.mov
> 
> I've rejected the PR for the moment until the installation issues are resolved, but if you'd rather handle that in another issue I can approve this one.

Nice catch with the native id, it shouldn't pose an issue, since it's database ID is combined with the extension address, which changes upon installation. The extension "resets" so it won't double execute motions. We need to be mindful when querying though.

I will resolve installation roles in this issue, I thought I got em, but apparently not :)

2024-06-20 12:12 UTC, jakubcolony approved these changes
Great job despite the the issues you encountered with cached (?) uninstalled client! All seems to work as expected.

a)

https://github.com/JoinColony/colonyCDapp/assets/112586815/f17b1708-18fc-4217-9836-6d860ae650ae

<img width="986" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/bdf014c3-e9be-46b1-92c3-c7d05dccadea">

b)

<img width="1078" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/ca66c5bc-7f25-492a-84ee-6043c9af80fa">

Permissions have been wiped:
<img width="205" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/2466b107-d76e-4a56-9395-6ae244473461">

Multi-sig has been rejected:

<img width="683" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/112586815/704fd8bc-e9c5-4bab-92b8-a38bfcd5d719">

2024-06-21 11:38 UTC, iamsamgibbs approved these changes
🎉  Working perfectly! Nice job fixing the caching issue.

2024-07-01 08:34 UTC, merged