Fix: remove comments number from agreement
JoinColony/colonyCDapp pull request #2554
Opened 2024-06-18 09:06 UTC by mmioana

Remove comments number from colony home agreement card

## Description

- Remove comments number from colony home agreement card
- Add TODO to re-enable the comment number once this feature is implemented

## Testing

TODO: Check is comments number still shows for an agreement on the colony home page

* Step 1. Create an agreement
* Step 2. Go to colony dashboard
* Step 3. Check agreements section

Resolves #2505

2024-06-18 09:41 UTC, melyndav requested changes
Hi @mmioana! Great start on this one! The comment is no longer showing and all looks good. 👯

2024-06-18 09:43 UTC, melyndav submitted a review, later dismissed

2024-06-18 15:21 UTC, davecreaser submitted a review, later dismissed
Good idea to just comment it out for now. Problem solved :)

2024-06-18 15:39 UTC, bassgeta submitted a review, later dismissed
Nice and straightforward :sunglasses:

2024-06-19 18:12 UTC, rdig submitted a review, later dismissed
Can confirm the comment no longer shows. Thanks for removing the leftover code :)

![Screenshot from 2024-06-19 21-10-56](https://github.com/JoinColony/colonyCDapp/assets/1193222/e76a59bc-26d5-4a35-922f-1190725d180a)
![Screenshot from 2024-06-19 21-11-03](https://github.com/JoinColony/colonyCDapp/assets/1193222/443b0bc8-63a8-4fff-94cf-9a7ddfe42c71)

2024-06-19 18:12 UTC, rdig commented on src/components/v5/frame/ColonyHome/partials/Agreements/Agreements.tsx
> +                {/* <MessageNumber message={1} /> */}
Normally, I'd say to remove this altogether since we can always restore this from `git` history

2024-07-01 11:58 UTC, bassgeta approved these changes
No agreement comments shown on my end, so let's get this nice fix off to master! :tada:

2024-07-01 16:33 UTC, rumzledz commented
No default comment count has dared to show itself on this branch. Merge it! 🚀 
![image](https://github.com/JoinColony/colonyCDapp/assets/50642296/1a547be4-e513-4213-a6db-119b515b1f67)

2024-07-01 16:33 UTC, rumzledz approved these changes

2024-07-01 18:27 UTC, merged