fix: User avatar shrinks on mobile when action is submitting
JoinColony/colonyCDapp pull request #2559
Opened 2024-06-18 11:04 UTC by Nortsova

## Description
Fix user avatar shrinks on mobile when action is submitting

## Testing
* Step 1. Set screen size to mobile
* Step 2. Create a new action and submit
* Step 3. See that user avatar is visible
<img width="380" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/60089753-4724-40d8-8032-0dfa1dfaf79b">

Resolves #2546

2024-06-18 11:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=2559) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=2559) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=2559) it.</sub>

2024-06-18 15:26 UTC, davecreaser submitted a review, later dismissed
Good stuff, all tested and the avatar stays visible!

<img width="549" alt="Screenshot 2024-06-18 at 16 25 15" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/77ea4c70-1790-40d1-9292-f497d44694c7">

2024-06-18 16:03 UTC, rumzledz approved these changes
Looking brill @Nortsova ✨

![Screenshot 2024-06-18 at 17 01 55](https://github.com/JoinColony/colonyCDapp/assets/50642296/0117a5ad-6d08-4e4c-9a9e-18e554823e1d)

2024-06-18 16:18 UTC, iamsamgibbs requested changes
Congratulations on your first PR @Nortsova 🎉 

The fix does indeed solve the issue:

https://github.com/JoinColony/colonyCDapp/assets/34915414/80f47a09-6b9c-4060-ad0a-75c76ceb772c

However, I think this change is unnecessary and is affecting a different part of the header:

<img width="362" alt="Screenshot 2024-06-18 at 17 13 11" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/07ab54c6-88bf-4f4c-a535-9b0cb99d2a9b">

And `flex` is already included in the button component and doesn't need to be included again here:
 
<img width="1595" alt="Screenshot 2024-06-18 at 17 11 47" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/8d7878fa-f791-4a56-af2e-12b13cb76403">

Nice job identifying the components involved and making the fix though! I'll review again after these changes.

2024-06-18 16:18 UTC, iamsamgibbs commented on src/components/common/Extensions/UserHubButton/UserHubButton.tsx
> +          ' flex min-w-[3rem] md:hover:!border-blue-400',
I'm being incredibly nitpicky, but there is an unnecessary space at the start of this line.

2024-06-18 16:18 UTC, iamsamgibbs commented on src/components/common/Extensions/UserHubButton/UserHubButton.tsx
> +          ' flex min-w-[3rem] md:hover:!border-blue-400',
I also don't think flex is needed here as it is already included in the button component.

2024-06-18 16:18 UTC, iamsamgibbs commented on src/components/v5/frame/NavigationSidebar/NavigationSidebar.tsx
> +          <div className="flex gap-3 md:flex-col md:gap-9">
This change affects a different part of the header.

2024-06-19 09:16 UTC, iamsamgibbs approved these changes
Looks good to me now! Thanks for making the changes :)

<img width="454" alt="Screenshot 2024-06-19 at 10 15 46" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/9f87ab0a-6e39-44bd-8451-d752de80f24a">

2024-06-21 08:26 UTC, rumzledz approved these changes

2024-06-21 08:27 UTC, mmioana approved these changes
Avatar no longer shrinks

<img width="441" alt="Screenshot 2024-06-21 at 10 25 23" src="https://github.com/JoinColony/colonyCDapp/assets/32430018/ea7c4746-3fe6-4684-84c9-3c4389d13257">


Great work @Nortsova! 🥳

2024-06-21 08:27 UTC, merged