Fix: prevent same permission updates
JoinColony/colonyCDapp pull request #2565
Opened 2024-06-18 14:19 UTC by rumzledz

## Description

![same permissions](https://github.com/JoinColony/colonyCDapp/assets/50642296/5d1bc9ae-862d-4b45-99ba-69846cf3db99)

## Testing

1. Enter a title
2. Set the Action Form to "Manage permissions"
3. Select "Amy"
4. Select the "General" team
5. Select an "Authority" value if applicable
6. Select the "Permissions" decision method
7. Submit the form
8. Verify that you can see an error message that says: "This user already has these permissions" 
![image](https://github.com/JoinColony/colonyCDapp/assets/50642296/5d00e37e-183b-40d6-b544-552fccbb2894)

## Diffs

**New stuff** ✨

* A new form validation for making sure we're not updating a user's permissions using the same set of permissions that they already have.

Resolves #2549

2024-06-18 20:52 UTC, rdig approved these changes
All good from a logic perspective and I really like your validation schema _(albeit a tad hard to read)_

![Screenshot from 2024-06-18 23-48-04](https://github.com/JoinColony/colonyCDapp/assets/1193222/aca3d54c-2ba9-4102-b3bd-0c0207775777)

Could we have the submit button disabled while the action / form has errors ? (I realize this might be harder due to the original implementation, however I still think it's worth investigating)

So I'm just rejecting because of that. Everything else is good.

2024-06-19 04:24 UTC, rumzledz commented
> Could we have the submit button disabled while the action / form has errors ? (I realize this might be harder due to the original implementation, however I still think it's worth investigating)
> 
> So I'm just rejecting because of that. Everything else is good.

What would my Colony experience be without these challenges! 😄 I like your suggestion and made the necessary updates. Because of how our action form is wired up, this will also apply to all other action forms. However I think that's fine because it makes sense to me to disable when errors are present 🤔 Can you please have a look again when you get the chance @rdig? Thank you!

2024-06-19 09:51 UTC, iamsamgibbs requested changes
Nice work on this, thanks for picking up the issue!

<img width="677" alt="Screenshot 2024-06-19 at 10 36 01" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/54246747-c325-46ef-9ec6-ddb40fb2215d">

And correctly lines up with custom permissions too:

<img width="664" alt="Screenshot 2024-06-19 at 10 37 49" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/29394ad6-7aeb-4544-92d7-e8472534c1e5">

Also works when redoing the action - you have to click submit before the validation message will appear, but I don't think this is a big issue, and you experience the same behaviour when first selecting a member who already has permissions.

https://github.com/JoinColony/colonyCDapp/assets/34915414/149c1b8d-56a7-4a7f-99ef-85422166df4d

The disabled submit button is causing issues on other actions where the error validation doesn't occur until the form is submitted.

https://github.com/JoinColony/colonyCDapp/assets/34915414/6c119ed6-c87f-4f9f-a8dd-fbbd2ef7a533

https://github.com/JoinColony/colonyCDapp/assets/34915414/e451ccb4-b397-444c-bfe7-a4d462344378

2024-06-19 12:21 UTC, rumzledz commented
Hey @iamsamgibbs , I just wanna say that it's because those forms you've shown are configured differently and this behaviour is already present on `master`. You'll find that if you did the same things on `master`, the validation isn't re-triggering onChange for those forms fields. What should really happen is that, the validations should go away when a user addresses the required fields like how they're already happening with the following forms:
- Create new team
- Transfer funds
- Unlock token
- And many others

So for example, if you bring up the Create new team form and you:
1. Click the "Create team" button
2. Check that you see the validation messages
3. Start entering a title
4. Check that the title error message goes away without the needed for another submit button click

In a way, this PR has brought those issues into the light 😂 There's a lack of coherence with form validations at the moment 🤔 But sure! I'll try to fix those forms in the process. I'll allot some time to go through each form we have and I'll see if I can fix those under this PR so that everyone is happy! 😄

CC @rdig

2024-06-19 12:27 UTC, iamsamgibbs commented
@rumzledz Yeah those forms are setup differently. I believe with Payment Builder there was a big lag issue when dealing with many payments at once, so the validation was set to only update on submit as a work around for this. Not sure if there is an explicit reason why manage verified members only has validation on submit. It might be a bit job to update these forms.

2024-06-19 14:37 UTC, rumzledz commented
> @rumzledz Yeah those forms are setup differently. I believe with Payment Builder there was a big lag issue when dealing with many payments at once, so the validation was set to only update on submit as a work around for this. Not sure if there is an explicit reason why manage verified members only has validation on submit. It might be a bit job to update these forms.

Oh right if it's for optimisation features, I can't argue with that! What I'll do is create a ticket for it, something for us to look at in the future. The one-liner that disables the button when form errors are present is:

![image](https://github.com/JoinColony/colonyCDapp/assets/50642296/45567106-49c8-4865-8729-7c96a878f87b)

If we want to conditionally enable this "button disabling" feature on a per-form basis, maybe we can modify this hook and retrieve this in `ActionSidebarFormContent`

```js
useActionFormBaseHook({
    disableSubmitButtonOnError: true, // <<-- Maybe add something like this 👀 
    getFormOptions,
    validationSchema,
    actionType:
      decisionMethod === DecisionMethod.Permissions
        ? ActionTypes.ACTION_USER_ROLES_SET
        : ActionTypes.MOTION_USER_ROLES_SET,
    defaultValues: useMemo<DeepPartial<ManagePermissionsFormValues>>(
      () => ({
        createdIn: Id.RootDomain,
      }),
      [],
    ),
    transform: useCallback(
      pipe(
        mapPayload((values: ManagePermissionsFormValues) => {
          return getManagePermissionsPayload(colony, values);
        }),
      ),
      [colony, user, navigate],
    ),
  });
```

OR  modify `AdditionalFormOptionsContextProvider` to handle this option.. something along those lines! 😂  I'll add these deets the issue.

For now, I will be reverting the submit button behaviour change in this PR @iamsamgibbs @rdig if that's okay?

2024-06-20 11:20 UTC, rumzledz commented
Hey @iamsamgibbs! I've just reverted the changes for disabling the form submit button when errors are present. Can you have a look again when you're free? Thank you!

2024-06-20 13:36 UTC, rdig commented
> For now, I will be reverting the submit button behaviour change in this PR @iamsamgibbs @rdig if that's okay?

Go for it :)

2024-06-27 10:16 UTC, iamsamgibbs approved these changes
Looks good to me, still working as expected! Thanks for rolling back the submit button changes, the other actions are functioning again and this can be addressed properly later.

<img width="663" alt="Screenshot 2024-06-27 at 11 15 24" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/4c67131a-f1bd-4135-8640-dbc03962add0">

2024-07-08 09:14 UTC, iamsamgibbs submitted a review, later dismissed
Still working as expected.

<img width="674" alt="Screenshot 2024-07-08 at 10 12 50" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/0d1aa217-e924-411c-80bb-d94a15dd94d3">

<img width="677" alt="Screenshot 2024-07-08 at 10 13 19" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/886ee333-ec2e-4e7e-a52c-f34becd23a3e">

2024-07-08 12:32 UTC, Nortsova submitted a review, later dismissed
Great work, @rumzledz! 💫

I can confirm that validation works properly now:

<img width="679" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/77c0389f-adc2-4877-b3a2-56465873bef3">
<img width="686" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/f25ce7e7-8fd7-4c96-b198-aa482a367f7a">

2024-07-09 11:47 UTC, iamsamgibbs requested changes
Tested and all still working as expected!

<img width="681" alt="Screenshot 2024-07-09 at 12 44 39" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/312be770-7eda-4616-a646-f0dd08848ea9">

<img width="674" alt="Screenshot 2024-07-09 at 12 47 03" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/3fdb6cd8-17bf-4c42-95c4-f53f2453fcc8">

2024-07-09 11:47 UTC, iamsamgibbs approved these changes

2024-07-10 19:16 UTC, rumzledz commented
Hey @melyndav 👋 When you get the chance, could you please have a look at the updates I made for this PR? As per our last conversation, the validation should now trigger automatically without requiring a form submission first. Thank you 😄

2024-07-11 10:36 UTC, melyndav requested changes
Hey @rumzledz! Appreciate the new updates. I've done a check and one improvement is the consistency of the validation state.

If you see in the recording, once I select a team (in this case General) the owner permission is applied by default and throws the validation. 

However, if I change the permission to 'Custom' the styling is different. The permissions field isn't red (incorrect) and the table border has the red outline (correct behaviour).

In any error case, the validation should remain consistent and match the other action errors, including table styling. 

![Export-1720694047497](https://github.com/JoinColony/colonyCDapp/assets/82127904/d6b1ec39-3142-4b38-8a36-3f95b7cfcffb)


Also, when I start fresh with a new action and select a user I know doesn't have any existing users, as soon as I select the team field, it throws an error before I've been had a chance to complete the field. This shouldn't throw and error here. 

Example:

<img width="674" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/146e477d-4e8e-4855-81de-e8610fba45ea">

2024-07-11 11:16 UTC, rumzledz commented
> Hey @rumzledz! Appreciate the new updates. I've done a check and one improvement is the consistency of the validation state.
> 
> If you see in the recording, once I select a team (in this case General) the owner permission is applied by default and throws the validation.
> 
> However, if I change the permission to 'Custom' the styling is different. The permissions field isn't red (incorrect) and the table border has the red outline (correct behaviour).
> 
> In any error case, the validation should remain consistent and match the other action errors, including table styling.
> 
> ![Export-1720694047497](https://private-user-images.githubusercontent.com/82127904/347784251-d6b1ec39-3142-4b38-8a36-3f95b7cfcffb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTY3MDksIm5iZiI6MTcyMDY5NjQwOSwicGF0aCI6Ii84MjEyNzkwNC8zNDc3ODQyNTEtZDZiMWVjMzktMzE0Mi00YjM4LThhMzYtM2Y5NWI3Y2ZjZmZiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNWFiZWQ4MTNmYzQ2MmNlNDdlMDM3ZWE4MmU5NGM1MDNhZDdlOTlkMjgyNmM5YWY3NTcyNGMxODQ4MDViMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xHmOh_OfmwGSQlIb-W86K50B116dPqSYZRB9KIIOwc0) [ ![Export-1720694047497](https://private-user-images.githubusercontent.com/82127904/347784251-d6b1ec39-3142-4b38-8a36-3f95b7cfcffb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTY3MDksIm5iZiI6MTcyMDY5NjQwOSwicGF0aCI6Ii84MjEyNzkwNC8zNDc3ODQyNTEtZDZiMWVjMzktMzE0Mi00YjM4LThhMzYtM2Y5NWI3Y2ZjZmZiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNWFiZWQ4MTNmYzQ2MmNlNDdlMDM3ZWE4MmU5NGM1MDNhZDdlOTlkMjgyNmM5YWY3NTcyNGMxODQ4MDViMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xHmOh_OfmwGSQlIb-W86K50B116dPqSYZRB9KIIOwc0) ](https://private-user-images.githubusercontent.com/82127904/347784251-d6b1ec39-3142-4b38-8a36-3f95b7cfcffb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTY3MDksIm5iZiI6MTcyMDY5NjQwOSwicGF0aCI6Ii84MjEyNzkwNC8zNDc3ODQyNTEtZDZiMWVjMzktMzE0Mi00YjM4LThhMzYtM2Y5NWI3Y2ZjZmZiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNWFiZWQ4MTNmYzQ2MmNlNDdlMDM3ZWE4MmU5NGM1MDNhZDdlOTlkMjgyNmM5YWY3NTcyNGMxODQ4MDViMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xHmOh_OfmwGSQlIb-W86K50B116dPqSYZRB9KIIOwc0) [ ](https://private-user-images.githubusercontent.com/82127904/347784251-d6b1ec39-3142-4b38-8a36-3f95b7cfcffb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTY3MDksIm5iZiI6MTcyMDY5NjQwOSwicGF0aCI6Ii84MjEyNzkwNC8zNDc3ODQyNTEtZDZiMWVjMzktMzE0Mi00YjM4LThhMzYtM2Y5NWI3Y2ZjZmZiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNWFiZWQ4MTNmYzQ2MmNlNDdlMDM3ZWE4MmU5NGM1MDNhZDdlOTlkMjgyNmM5YWY3NTcyNGMxODQ4MDViMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xHmOh_OfmwGSQlIb-W86K50B116dPqSYZRB9KIIOwc0)
> 
> Also, when I start fresh with a new action and select a user I know doesn't have any existing users, as soon as I select the team field, it throws an error before I've been had a chance to complete the field. This shouldn't throw and error here.
> 
> Example:
> 
> <img alt="image" width="674" src="https://private-user-images.githubusercontent.com/82127904/347784566-146e477d-4e8e-4855-81de-e8610fba45ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTY3MDksIm5iZiI6MTcyMDY5NjQwOSwicGF0aCI6Ii84MjEyNzkwNC8zNDc3ODQ1NjYtMTQ2ZTQ3N2QtNGU4ZS00ODU1LTgxZGUtZTg2MTBmYmE0NWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDExMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNDM5Mzg5ODdmOWE5YTNiOWQwM2E4NjYwMzJjNWQ2NTcwM2ZjYzFmMzkwYTA0YTU2NTI0M2ZlMDJjODJiOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pp2MG9wHFxVbSuTLlE3L9sa1pfZy00rN8PBuDnI412E">

Oh wait, I was under the assumption that because the focus is on the permissions table when you set it to "Custom", then the table should receive the error highlight. I'm clearing the "Permissions" row at that point because it's just a row that's saying "Custom" and is behaving as more of a toggle for the actual set of fields you're required to modify. But all right, that's an easy fix @melyndav 👌

2024-07-11 11:18 UTC, rumzledz commented
> Also, when I start fresh with a new action and select a user I know doesn't have any existing users, as soon as I select the team field, it throws an error before I've been had a chance to complete the field. This shouldn't throw and error here.

I thought this is what we agreed on 🤔 I'll call you to discuss, I'm confused now 😂 @melyndav

2024-07-11 14:48 UTC, melyndav requested changes
Hey @rumzledz! Super close on this one, and I appreciate your patience as we work on all the variations with the logic. Two final and very minor updates:

### Table styling during the error states

So here I'm testing a user with existing permissions. Everything is perfect on the logic front. 

The only update needed is that the red border is showing on the custom table, but not on the 'owner' table. 

The red border should show on all tables for each permission if there is an error. You can see here when I switch between the two permission types:

![Export-1720708353661](https://github.com/JoinColony/colonyCDapp/assets/82127904/b8860c0d-f8fb-48ff-ad94-7abc73e1f7e5)


### Update the error copy in the notification banner

Can you please kindly update "You have to select at least one permission" to "You have to enable at least one permission" within the notification banner when the custom table is shown and no permissions enabled? 

Changing select to enable lines up with the table header column, so the user knows to enable at least one toggle. 

### Notes

BTW, your testing steps are great and very easy to follow! Nice work on these 🎉

2024-07-11 15:43 UTC, melyndav submitted a review, later dismissed
If I could smash a big red approval button on this, I would @rumzledz! Great work on this and great communication throughout the process over Discord while we worked through the various user flows here. Everything looks great from my side of things!  🎉

2024-07-11 19:37 UTC, Nortsova submitted a review, later dismissed
Wow! Thank you, @rumzledz, for the great work and the amazing testing guide! ⭐️⭐️⭐️  It is awesome ✨ Everything works as expected

2024-07-12 09:56 UTC, iamsamgibbs requested changes
> I found that a couple of issues when redoing the action. The same permissions validation is missing.

> And the placeholder styling is missing when redoing the action and changing users:

I didn't even know we had a "Redo" action..

2024-07-12 11:02 UTC, iamsamgibbs commented
Reuploading videos:

Filling out the form in the wrong order:
https://github.com/user-attachments/assets/dfc054c3-4316-4b0a-9759-ddaea344a8e9

Redoing action - should have same permissions error:
https://github.com/user-attachments/assets/802a2a93-9f53-40b3-a629-7fb0b4d911e9

Redoing action and changing user:
https://github.com/user-attachments/assets/0baa75af-fe13-4b74-9020-ba59673d8ba3

2024-07-15 14:37 UTC, iamsamgibbs requested changes
This issue with the placeholder styling when redoing an action is still happening:

https://github.com/user-attachments/assets/eacecd86-7a78-4b7d-b47e-3633d5583247

2024-07-16 08:15 UTC, iamsamgibbs approved these changes
Thanks for fixing these tiny edge case issues! Great work on this issue. The redo placeholder styling issue is resolved:

https://github.com/user-attachments/assets/3081b792-4365-4c5d-a4e3-e911f190ae0c

I retested all the testing steps to ensure nothing has broken, and all still working as expected.

Whilst testing, I noticed these field names are lacking the proper formatting in this error message, but this is a problem for another day - just noting it here.

<img width="573" alt="Screenshot 2024-07-16 at 09 13 10" src="https://github.com/user-attachments/assets/19bf7dc1-1932-461a-8e58-67ad3ee1a58c">

2024-07-16 17:19 UTC, Nortsova approved these changes
Thank you @rumzledz ! ✨ Everything work as expected!

2024-07-17 13:24 UTC, melyndav approved these changes
Nice work again on a long and complex PR @rumzledz. I appreciate all your communication throughout the PR and all the attempts to go above and beyond to cover as much as possible here and to make the UX make sense. Great work all round 🥇 

Side note for @iamsamgibbs I've already got a backlog ticket in the design kanban for improving the error copy. They are not great, but something I hope to pick up this Q (if I can squeeze it in!). 👍

2024-07-17 13:26 UTC, merged