Fix/15955924 funding step
JoinColony/colonyCDapp pull request #2585
Opened 2024-06-21 08:10 UTC by CzarekDryl

## Description

- Multiple funding step fixes, all descriptions are in issues

## Testing

* Ensure Reputation decision method is active.
* Create a Payment builder action.
* In funding step use reputation method

Resolves:
[2562](https://github.com/JoinColony/colonyCDapp/issues/2562)
[2561](https://github.com/JoinColony/colonyCDapp/issues/2561)
[2558](https://github.com/JoinColony/colonyCDapp/issues/2558)
[2557](https://github.com/JoinColony/colonyCDapp/issues/2557)
[2556](https://github.com/JoinColony/colonyCDapp/issues/2556)

2024-06-21 15:46 UTC, arrenv requested changes
@CzarekDryl Thank you picking up all these issues.


https://github.com/JoinColony/colonyCDapp/issues/2556: I now longer have the permissions option showing when I don't have permissions.

https://github.com/JoinColony/colonyCDapp/issues/2557: Timer is appearing right away now.

https://github.com/JoinColony/colonyCDapp/issues/2558: Loader is no longer triggering the scrollbar.

https://github.com/JoinColony/colonyCDapp/issues/2561: Motion auto-failed and allowed me to fund again.

https://github.com/JoinColony/colonyCDapp/issues/2562: It is much smoother, however, it still showed the wrong information.

1. The finalize and outcome card shows the incorrect title.
   - In this case the title should have been "Action has passed and has been executed." as it had passed and been finalized.
   - If you return to the screen it shows the first screenshot, however, if you click one of the items in the card above, then it updates the second screenshot.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/00993bb9-4d96-4a59-847a-f1c65c58e127)
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/45d232e6-6f9b-4da5-87c6-629392754e38)

2. The staking over card is showing no funds to claim, despite the user having staked and participated in the voting and should have received a reward.

2024-06-26 14:03 UTC, CzarekDryl commented
@arrenv I don't know but I'm not able to reproduce this bug:
<img width="341" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/76940796/e3181785-a01f-4fe8-be12-7c585a87d904">
<img width="376" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/76940796/4f355b9f-b3c8-4c19-b314-6d37961f0256">
<img width="739" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/76940796/35d3e757-1698-4748-b1da-d731495904c9">

2024-07-02 16:25 UTC, arrenv requested changes
@CzarekDryl I have tried testing this scenario a few times and always get the same result with no stakes or rewards showing, I even tried reloading and restarting my dev environment a couple of times.

Could you explain how you are going about getting it to work.

I would also be interested if any one else @JoinColony/developers get the stakes to show up.

2024-07-03 07:53 UTC, CzarekDryl commented
@arrenv I just restarted the environment `npm run dev`, `node script...`. It will be good if someone else could check this. Here's my video:

https://github.com/JoinColony/colonyCDapp/assets/76940796/dabdeebf-55a8-41d6-98a3-549068a60482

2024-07-04 10:36 UTC, arrenv requested changes
@CzarekDryl Thank you, I have been testing this more and found these issues.

1. The custom title is not working, I have tested in production, and it is working there.
![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/dec4d339-a0a8-4277-9ef5-0bf51c7c7682)

   In production
   ![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/871ebee1-baf5-4382-adb8-c22ddba18f73)

2. I was able to replicate the 0 values in the staking overview with these steps.
   - Create it with leela
   - Fully support and oppose with leela
   - Switch to Amy and vote support
   - Switch to leela and vote support
   - Reveal vote as leela
   - Switch to Amy and reveal vote
   - Finalize
   - Return to the Funding step and the values are 0, despite Amy having received a reward for voting

   ![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/e83fc20e-e8b9-4132-a9b7-af5f5c5ed153)

2024-07-09 07:39 UTC, CzarekDryl commented
@arrenv I did it step by step as you described, but for the 'mint tokens' action, and got 0 in every row.
![image](https://github.com/JoinColony/colonyCDapp/assets/76940796/fefe407d-e667-4554-a868-2773d13df353)

So this problem occurs in all actions, I think it is best to create a new issue with this error.

2024-07-10 11:04 UTC, davecreaser commented
Hey @CzarekDryl, nice work on this!

A couple of the issues are fixed for me but a couple of them I still see when testing locally:

https://github.com/JoinColony/colonyCDapp/issues/2556: **Fixed** The permissions option is disabled when i'm a user without permissions. @arrenv just to check - is disabled okay, or should it not appear at all?
<img width="1920" alt="Screenshot 2024-07-10 at 11 07 52" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/b420e05c-c35e-4170-92d2-ccc67c32f705">

https://github.com/JoinColony/colonyCDapp/issues/2558: **Fixed** No scrollbars showing.

https://github.com/JoinColony/colonyCDapp/issues/2562: **Fixed** Fixed, apart from what Arren has already covered in comments and new issues.

https://github.com/JoinColony/colonyCDapp/issues/2557: **Not fixed** I don't see any timer, see video.

https://github.com/JoinColony/colonyCDapp/issues/2561: **Not fixed** I had to refresh to see that it had failed. I tried multiple times with different times set in the extension settings. See video.

https://github.com/JoinColony/colonyCDapp/assets/38098203/e55510e4-ed60-46d5-937a-09f91ac4a23f

2024-07-10 11:08 UTC, davecreaser requested changes
Looking good code-wise, and most things are fixed, just a couple of things which seem to still be an issue when I was testing. Maybe you could take a look at my comment and video to confirm. Thanks!

2024-07-10 12:42 UTC, CzarekDryl commented
@davecreaser I've tried to reproduce bug with timer and it's working for me everytime:

https://github.com/JoinColony/colonyCDapp/assets/76940796/cdf64f3b-3707-47ba-8657-fb0ad88cd945

2024-07-10 13:44 UTC, CzarekDryl commented
@davecreaser I could reproduce it but it happened once in ~10 tries 😄 I've changed key for timer, and now it's working for me every time. Could you please test it once more?

2024-07-10 14:09 UTC, iamsamgibbs approved these changes
All looks good to me!

#2556 appears resolved.

<img width="603" alt="Screenshot 2024-07-10 at 14 36 24" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/b19b4449-ba63-412f-9157-88b6c43f7617">

#2561 looks good to me.

https://github.com/JoinColony/colonyCDapp/assets/34915414/9bce9921-6bab-40f7-8d27-732623eb1006

#2557 appears resolved.

<img width="372" alt="Screenshot 2024-07-10 at 14 48 48" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/da9e98e3-230d-4aed-812c-fa58457f3a66">

#2558 appears resolved.

#2562 appears resolved.

<img width="357" alt="Screenshot 2024-07-10 at 15 08 04" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/2aabc36e-d2f7-4594-9ecc-3d075b13e2ac">

2024-07-10 16:43 UTC, davecreaser commented
All good @CzarekDryl - I found out that there was a problem with the lambdas in my local environment. I solved that and everything is now working!

Timer shows:
<img width="1728" alt="Screenshot 2024-07-10 at 17 41 02" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/9bd56a62-ff56-4177-aaa5-c23d1f01e10e">

And it auto fails:
https://github.com/JoinColony/colonyCDapp/assets/38098203/911816d3-5d87-43ce-8bc9-e3ddf298a68a

Nice job, thank you!

2024-07-10 16:44 UTC, davecreaser approved these changes

2024-07-11 06:21 UTC, merged