feat: wip
JoinColony/colonyCDapp pull request #2641
Opened 2024-07-02 15:12 UTC by bassgeta

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-07-10 12:17 UTC, mmioana reviewed
Amazing job @bassgeta 👏 

And really cool testing steps
![Screenshot 2024-07-10 at 13 47 37](https://github.com/JoinColony/colonyCDapp/assets/32430018/a1b983f0-77bb-489b-8be0-43a9dcc59059)
![Screenshot 2024-07-10 at 13 48 32](https://github.com/JoinColony/colonyCDapp/assets/32430018/5838b87b-cb9a-4e6b-b86a-567475a2c11a)
![Screenshot 2024-07-10 at 13 50 05](https://github.com/JoinColony/colonyCDapp/assets/32430018/d6d12b8e-8305-4567-9549-fc326fea7478)
![Screenshot 2024-07-10 at 13 50 39](https://github.com/JoinColony/colonyCDapp/assets/32430018/25f90b52-9646-425c-a537-f9526ebae04f)
![Screenshot 2024-07-10 at 13 53 19](https://github.com/JoinColony/colonyCDapp/assets/32430018/89640ed4-891e-4316-ae2d-ef1a911d6e60)
![Screenshot 2024-07-10 at 14 10 30](https://github.com/JoinColony/colonyCDapp/assets/32430018/a5e79dfd-4cc5-43f0-b15e-8a10bdbd64b6)
<img width="1053" alt="Screenshot 2024-07-10 at 14 11 50" src="https://github.com/JoinColony/colonyCDapp/assets/32430018/1c7dfba0-5939-44df-b05a-0a7ab96de98f">


The only thing that I have noticed is that Fry has 3 votes shown in the pill before approving/rejecting an action. Is this as intended?

<img width="337" alt="Screenshot 2024-07-10 at 14 16 41" src="https://github.com/JoinColony/colonyCDapp/assets/32430018/c34ab5c9-f0ca-4a1f-bc12-91c87125982f">

2024-07-10 12:19 UTC, bassgeta commented
> Amazing job @bassgeta 👏
> 
> And really cool testing steps ![Screenshot 2024-07-10 at 13 47 37](https://private-user-images.githubusercontent.com/32430018/347394387-a1b983f0-77bb-489b-8be0-43a9dcc59059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTQxODIsIm5iZiI6MTcyMDYxMzg4MiwicGF0aCI6Ii8zMjQzMDAxOC8zNDczOTQzODctYTFiOTgzZjAtNzdiYi00ODliLThiZTAtNDNhOWRjYzU5MDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZDFkNzkyOGNiOGJkMmI3ZjJjNWViZTZkNWZmYWIwZTVlZDFhZDIyMzIzMTA5OGRiYWI2N2ViYzhjODJjNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QfkVi8E29Np_WXs-eouXWp_eSX_oRCdiYw-RhqoAadQ) ![Screenshot 2024-07-10 at 13 48 32](https://private-user-images.githubusercontent.com/32430018/347394439-5838b87b-cb9a-4e6b-b86a-567475a2c11a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTQxODIsIm5iZiI6MTcyMDYxMzg4MiwicGF0aCI6Ii8zMjQzMDAxOC8zNDczOTQ0MzktNTgzOGI4N2ItY2I5YS00ZTZiLWI4NmEtNTY3NDc1YTJjMTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NzlkNGRkY2I2ZTgyOTZkMjg4NzdlMTY3OWIxMGZjNDRjM2E5YzAzNTZlYmY3YzFkNmVkOWE2YjVkMjY0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tqB9mkgmozCjhj517b4bSqrF8C_ivfd8N2FcyQiDoHg) ![Screenshot 2024-07-10 at 13 50 05](https://private-user-images.githubusercontent.com/32430018/347394488-d6d12b8e-8305-4567-9549-fc326fea7478.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTQxODIsIm5iZiI6MTcyMDYxMzg4MiwicGF0aCI6Ii8zMjQzMDAxOC8zNDczOTQ0ODgtZDZkMTJiOGUtODMwNS00NTY3LTk1NDktZmMzMjZmZWE3NDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNjkyZGRmZmVkZjllNjAxOGM3ZmMzMDE3MjM3MDJiYjY4MDMwYjI1MjAyMjkyNDUxZTIxNDYyMjc0YmI5MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EwRVDKDYd4-cMCL6bxvB-mGbbBoy2Pd5-46dU4tttbw) ![Screenshot 2024-07-10 at 13 50 39](https://private-user-images.githubusercontent.com/32430018/347394540-25f90b52-9646-425c-a537-f9526ebae04f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTQxODIsIm5iZiI6MTcyMDYxMzg4MiwicGF0aCI6Ii8zMjQzMDAxOC8zNDczOTQ1NDAtMjVmOTBiNTItOTY0Ni00MjVjLWE1MzctZjk1MjZlYmFlMDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMDVhYjk0MzFjNDMxODExNDNmMWUwNWJlZjdhMjg1MDZkZjc3MDZiM2U0NzExMmFlNDcxZmEzNjE4N2M1MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cYxgZuxYYLftQj7mcramyUJjI3CkRn3z-yWnOp1SlUY) ![Screenshot 2024-07-10 at 13 53 19](https://private-user-images.githubusercontent.com/32430018/347394606-89640ed4-891e-4316-ae2d-ef1a911d6e60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTQxODIsIm5iZiI6MTcyMDYxMzg4MiwicGF0aCI6Ii8zMjQzMDAxOC8zNDczOTQ2MDYtODk2NDBlZDQtODkxZS00MzE2LWFlMmQtZWYxYTkxMWQ2ZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyOTU3ODA0ZjNlNzBhZjcwNDU3NzBlY2Y0ODk1MTdjOTZiZjQ4NDRjZTVhOWQyYWFkMDVjYjc4ZGIwYWFhOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PB35F8GlUcEDUMhNhWSFPW2jAuRYUnB-lWnw7QQQDvI) ![Screenshot 2024-07-10 at 14 10 30](https://private-user-images.githubusercontent.com/32430018/347394643-a5e79dfd-4cc5-43f0-b15e-8a10bdbd64b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTQxODIsIm5iZiI6MTcyMDYxMzg4MiwicGF0aCI6Ii8zMjQzMDAxOC8zNDczOTQ2NDMtYTVlNzlkZmQtNGNjNS00M2YwLWIxNWUtOGExMGJkYmQ2NGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMGM5NGE2N2IwMzZkN2UwMmE0ODRmNzVkM2RiNTEyMTk5OWQ4MWU1MWZkODgxY2ZmOTU3ZGQ2ZTg2MWYwOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zKz7Cb8SoaYCZxqTAPjrlO5gzlghqEuIZIz9K7vbBKc) <img alt="Screenshot 2024-07-10 at 14 11 50" width="1053" src="https://private-user-images.githubusercontent.com/32430018/347394698-1c7dfba0-5939-44df-b05a-0a7ab96de98f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTQxODIsIm5iZiI6MTcyMDYxMzg4MiwicGF0aCI6Ii8zMjQzMDAxOC8zNDczOTQ2OTgtMWM3ZGZiYTAtNTkzOS00NGRmLWIwNWEtMGE3YWI5NmRlOThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxN2RhMDhhM2EwOTdkYjU0ODUwMGMwZTJlNWJkYTk3MjgzNWE1ZjM4Mjc3YWEzYjJjNDhlYjg1YTM0NjEwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1UL3MlHwroWr5ymHB1D3kGwPicbHeH8hXzyT8u-cGDU">
> 
> The only thing that I have noticed is that Fry has 3 votes shown in the pill before approving/rejecting an action. Is this as intended?
> <img alt="Screenshot 2024-07-10 at 14 16 41" width="337" src="https://private-user-images.githubusercontent.com/32430018/347395144-c34ab5c9-f0ca-4a1f-bc12-91c87125982f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTQxODIsIm5iZiI6MTcyMDYxMzg4MiwicGF0aCI6Ii8zMjQzMDAxOC8zNDczOTUxNDQtYzM0YWI1YzktZjBjYS00YTFmLWJjMTItOTFjODcxMjU5ODJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEyMTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NzYwOTBkMzk3OWI1YmMxZGE4ZmQzN2JlOGU3NmJkODc5MWZkZWE4OTFhODI3NTA4ZWIxZTY0MTdiY2U5MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UquE9xvtzDVFYFNP1JZVotaWceQ7VAdvL8C0ro4QWws">

Ah I forgot to note, the `Awaiting 3` part isn't working here, so I just have a placeholder in place, we need to rework how we fetch eligible signees, and then pass the roles they're holding into this new component. I felt it was a bit out of scope, so I just stubbed it in this PR

2024-07-10 12:27 UTC, mmioana commented
@bassgeta Also I have noticed the action type appears as generic in the sidebar, I think en-action.ts needs to be updated
<img width="433" alt="Screenshot 2024-07-10 at 14 26 57" src="https://github.com/JoinColony/colonyCDapp/assets/32430018/2d454c68-b433-406d-8dd0-4c9255c54abc">

2024-07-12 08:31 UTC, iamsamgibbs requested changes
Great work on this so far @bassgeta 🎉 Some great work in here. Nice job adding the role to the voting.

I followed the nice and detailed testing steps:

<img width="1064" alt="Screenshot 2024-07-12 at 08 27 08" src="https://github.com/user-attachments/assets/567c8a33-ac9a-4803-97e8-2a9fff7951a0">

<img width="766" alt="Screenshot 2024-07-12 at 08 27 43" src="https://github.com/user-attachments/assets/7e4d20d4-f4fa-4572-9683-c2f207c14e84">

<img width="767" alt="Screenshot 2024-07-12 at 08 32 11" src="https://github.com/user-attachments/assets/c51e7552-2a97-4d07-8ddf-44e461928589">

<img width="363" alt="Screenshot 2024-07-12 at 08 44 03" src="https://github.com/user-attachments/assets/cd673f60-64b5-4b75-a203-0d352d9d1e69">

<img width="358" alt="Screenshot 2024-07-12 at 08 44 18" src="https://github.com/user-attachments/assets/d1ef1060-0c26-49a4-a164-4fb65ed5371d">

 I've found one tiny issue with the tooltip.
 
<img width="384" alt="Screenshot 2024-07-12 at 08 30 38" src="https://github.com/user-attachments/assets/dfa522db-e08e-4104-a61d-af9bb5b12db5">

I've hit a few issues with the permissions notice when a user only has multi-sig permissions in a sub-domain. At one point the multi-sig decision method even stopped showing all together.

<img width="1346" alt="Screenshot 2024-07-12 at 08 37 28" src="https://github.com/user-attachments/assets/76897d34-3429-4e3f-94d3-cac655f70ea1"> 

https://github.com/user-attachments/assets/6ec40b10-000f-4eaf-9063-f3e6db86fb94

The notice seems to be checking the `from` field rather than the `createdIn` field.

https://github.com/user-attachments/assets/5e54a7f0-9e67-4c09-b7a4-90c0b61bca3d

I think it is accurate that the contracts require you to have all 3 permissions in the same domain to create the multi-sig motion, but the permissions notice should catch this before the saga.

https://github.com/user-attachments/assets/2314eb60-fb38-4c25-9fc7-095fc2f040eb

Also noting the same `Generic` action issue, but also the `Created in` field is missing.
 
<img width="1048" alt="Screenshot 2024-07-12 at 08 44 56" src="https://github.com/user-attachments/assets/ae969ef4-be0e-4ad2-9a50-269297fbcf91">

I think if the permissions notice issues are only affecting this action, these could be addressed in a separate issue as to not hold this one up, but if it is going to cause issues elsewhere better to resolve them here. (Should be able to tell more easily after a rebase now that some other actions are in the feature branch! 🎉 )

Unfortunately seem to be some issues introduced to the reputation motions. I tried creating one as a user with no permissions.

https://github.com/user-attachments/assets/ad691db3-8246-415a-b108-3594d688e1b2

And then had a different issue as a user with permissions:

https://github.com/user-attachments/assets/aba6ce2c-fff4-418d-8166-4453a9e42ea9

Overall though some great work, nice to see the multiple roles voting working!

2024-07-12 15:51 UTC, iamsamgibbs commented
I'm running into issues with the permissions error on another branch, so I don't think any of those are specific to this PR.

2024-07-17 11:07 UTC, davecreaser approved these changes
Very nice work! This was for sure a complicated one 😄 I've just left a couple of tiny comments, not super important things though.

Also tested with your instructions and all looks good! Here's a bunch of screenshots from that:
<img width="1075" alt="Screenshot 2024-07-17 at 11 22 25" src="https://github.com/user-attachments/assets/0e3c6ec4-2bf6-4019-9db2-046acc0a1956">
<img width="1075" alt="Screenshot 2024-07-17 at 11 22 56" src="https://github.com/user-attachments/assets/0515082d-8476-4390-a660-3cdc1682d3b9">
<img width="1075" alt="Screenshot 2024-07-17 at 11 24 17" src="https://github.com/user-attachments/assets/2d7c7e57-bcb6-40cf-b35a-523653ce3563">
<img width="1075" alt="Screenshot 2024-07-17 at 11 25 28" src="https://github.com/user-attachments/assets/809a195b-58da-462c-a8ad-560c76437bb6">
<img width="1075" alt="Screenshot 2024-07-17 at 11 26 43" src="https://github.com/user-attachments/assets/00ccef0e-c311-4f97-93e3-5ded0770d1e6">
<img width="1075" alt="Screenshot 2024-07-17 at 11 27 19" src="https://github.com/user-attachments/assets/5b70ff7b-46fc-49ed-b76f-adb660432c74">
<img width="1075" alt="Screenshot 2024-07-17 at 11 28 58" src="https://github.com/user-attachments/assets/0296688c-7389-463d-b7b8-4d9e9244ba23">
<img width="1075" alt="Screenshot 2024-07-17 at 11 30 11" src="https://github.com/user-attachments/assets/0510555d-37f0-4dfd-915f-028abc5c4d66">
<img width="1075" alt="Screenshot 2024-07-17 at 11 32 26" src="https://github.com/user-attachments/assets/dd1aba76-2991-480f-97e2-08733411a403">
<img width="1075" alt="Screenshot 2024-07-17 at 11 35 09" src="https://github.com/user-attachments/assets/98857043-c0f9-40f6-82c8-3e72320e875e">

2024-07-17 14:30 UTC, iamsamgibbs approved these changes
Great work on this! All working nicely for me. Just the tiny issues Dave already raised.

Both issues I raised previous are resolved:

<img width="271" alt="Screenshot 2024-07-17 at 15 21 39" src="https://github.com/user-attachments/assets/bc97e286-eaca-4d02-aa1c-c138e1a39d8d">

<img width="524" alt="Screenshot 2024-07-17 at 15 22 16" src="https://github.com/user-attachments/assets/55a187f1-9f2a-4619-ae0f-cc439bfd0f67">

I tested all the steps again to ensure nothing has broken:

<img width="367" alt="Screenshot 2024-07-17 at 15 17 55" src="https://github.com/user-attachments/assets/aeb013d8-090c-4363-82b4-f55611bd1198">

<img width="1329" alt="Screenshot 2024-07-17 at 15 20 22" src="https://github.com/user-attachments/assets/cdd03ce0-3288-4354-97b2-655687d12591">

<img width="472" alt="Screenshot 2024-07-17 at 15 21 08" src="https://github.com/user-attachments/assets/6e70d2ff-b0c1-414c-83b7-144d41594970">

2024-07-17 14:30 UTC, iamsamgibbs commented on src/redux/sagas/motions/paymentMotion.ts
> +          methodName: 'createMotion',
Could be `TRANSACTION_METHODS.CreateMotion`

2024-07-17 14:30 UTC, iamsamgibbs commented on src/redux/sagas/motions/paymentMotion.ts
> +        methodName: 'createMotion',
Could be `TRANSACTION_METHODS.CreateMotion`

2024-07-17 14:30 UTC, iamsamgibbs commented on src/redux/sagas/motions/paymentMotion.ts
> +    yield fork(createTransaction, createMotion.id, transactionParams);
Could be `TRANSACTION_METHODS.AnnotateTransaction`

2024-07-17 19:31 UTC, mmioana approved these changes
Amazing work @bassgeta and really throughout testing steps! 🚀 

<img width="875" alt="Screenshot 2024-07-17 at 21 14 14" src="https://github.com/user-attachments/assets/6f4a39ef-ff35-4175-b61c-793a0c4f1593">
<img width="1052" alt="Screenshot 2024-07-17 at 21 14 53" src="https://github.com/user-attachments/assets/095b85da-9980-4d2c-9103-191f5c9dcd89">
<img width="659" alt="Screenshot 2024-07-17 at 21 16 08" src="https://github.com/user-attachments/assets/b98b6a76-9316-4f30-99b1-f957163399a5">
<img width="890" alt="Screenshot 2024-07-17 at 21 16 55" src="https://github.com/user-attachments/assets/24397cf6-621b-414d-9899-9e57d0285b7e">
<img width="1057" alt="Screenshot 2024-07-17 at 21 17 29" src="https://github.com/user-attachments/assets/5d34d62e-6e53-497d-93ea-3fdc41be29fd">
<img width="1066" alt="Screenshot 2024-07-17 at 21 17 40" src="https://github.com/user-attachments/assets/8b64e929-c3b4-4542-9cfd-9904b5891f07">
<img width="702" alt="Screenshot 2024-07-17 at 21 18 03" src="https://github.com/user-attachments/assets/38d69a6e-7585-40ae-8219-f8f222054f2c">
<img width="907" alt="Screenshot 2024-07-17 at 21 19 05" src="https://github.com/user-attachments/assets/2e511016-c82d-4ef1-b3be-38cdc9858702">
<img width="1067" alt="Screenshot 2024-07-17 at 21 19 37" src="https://github.com/user-attachments/assets/fd483737-6cde-4c3a-b81b-eba7ebf27281">
<img width="1059" alt="Screenshot 2024-07-17 at 21 20 02" src="https://github.com/user-attachments/assets/78f73a78-9381-4c7e-bbf7-07551f9bbc08">
<img width="882" alt="Screenshot 2024-07-17 at 21 20 43" src="https://github.com/user-attachments/assets/d8e45f35-0869-4baa-a974-67ce18874860">
<img width="1054" alt="Screenshot 2024-07-17 at 21 21 12" src="https://github.com/user-attachments/assets/f0607b80-5b51-43c2-a7fb-081e7fcfafad">
<img width="1048" alt="Screenshot 2024-07-17 at 21 23 09" src="https://github.com/user-attachments/assets/ac489b95-24ef-4eb9-91ba-b3eda7211b64">
<img width="1054" alt="Screenshot 2024-07-17 at 21 23 29" src="https://github.com/user-attachments/assets/b836b119-a230-480a-adfe-5b59db142bfb">
<img width="907" alt="Screenshot 2024-07-17 at 21 29 32" src="https://github.com/user-attachments/assets/3a575aa5-40bf-4fd9-ada8-d7da52d2395e">

2024-07-18 08:34 UTC, merged