fix: changed userpopover font-size
JoinColony/colonyCDapp pull request #2648
Opened 2024-07-03 13:41 UTC by CzarekDryl

## Description

- Changed font-size for usernames in permission cards
- Paddings of motion cards seems to be fixed in some other PR
<img width="370" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/76940796/3a644306-5025-45d3-b467-e647e27e8348">

## Testing

* Create any action using permissions

Resolves [https://github.com/JoinColony/colonyCDapp/issues/2337](https://github.com/JoinColony/colonyCDapp/issues/2337)

2024-07-04 11:08 UTC, arrenv approved these changes
@CzarekDryl Nice and quick one, looks good to me!

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/20a35f73-1e6c-44b7-865b-fc796eaf71c3)

2024-07-04 11:10 UTC, arrenv requested changes
@CzarekDryl Apologies, I have just run into an issue with the U`serPopover` though on click. The username jumps to the left.

![image](https://github.com/JoinColony/colonyCDapp/assets/33682027/880a626c-9c69-430a-84c9-52cefbf8f1e1)

2024-07-04 11:27 UTC, melyndav requested changes
Hey @CzarekDryl nice work on this! I see the same issue as Arren.

<img width="502" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/bee901be-b206-4860-a033-b2e4d8c73abb">

2024-07-10 08:17 UTC, melyndav approved these changes
I reviewed this yesterday but didn't hit the approve button @CzarekDryl 😮‍💨 

The previous issue is resolved and all looks good for this one! Thanks for your work on this PR!

2024-07-11 14:38 UTC, Nortsova approved these changes
Great work @CzarekDryl ! ✨

I can confirm that the sizes now fit the design, and there are no bugs when clicking the username:
<img width="380" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/635e94ec-ac20-4e0a-a9c5-1644fcbc8a0b">
<img width="362" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/6f7f4025-64b7-404f-a885-81c104b581ad">

2024-07-16 07:50 UTC, iamsamgibbs approved these changes
Looks good to me! No issue with the popover.

<img width="422" alt="Screenshot 2024-07-16 at 08 49 52" src="https://github.com/user-attachments/assets/e0a80e7a-e031-4dd9-b8c3-73f8b8a5f4f8">

2024-07-16 09:01 UTC, arrenv approved these changes
Thank you @CzarekDryl, all looks good now!

2024-07-17 06:20 UTC, merged