Fix/2496 multi sig user token cards
JoinColony/colonyCDapp pull request #2649
Opened 2024-07-04 07:12 UTC by mmioana

## Description

Add domain color to ContributorReputation and ContributorRoles fragments
Update styling for user popover
Update styling for token popover

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. Go to colony members
* Step 2. Check the user card styling for each type of member (Top/Dedicated/Verified/Unverified etc) - 
  * scrollable Teams section with a maximum of 4 teams displayed 
  * team pills in upper section have a tooltip if text is truncated
* Step 3. Go to colony finance
* Step 4. Check the token card styling - different width for tablet/desktop

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-07-04 07:18 UTC, mmioana commented
@iamsamgibbs @melyndav I have opened another PR for https://github.com/JoinColony/colonyCDapp/issues/2496 containing all needed styling changes requested in PR #2586 as I rebased the wrong branch

2024-07-04 11:15 UTC, melyndav requested changes
Hey @mmioana - continuing comments from (so I have a record) #2586 

1. I'm getting some issues with the different contributor card types: 

<img width="469" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/4fc6bf4c-84ba-4228-8952-21d26aa0b251">

<img width="446" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/afd4b0e9-be97-4fa7-a66e-7592eba341b6">

<img width="559" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/a05b2ef0-6a80-4623-8134-a0f9b6f30392">

<img width="555" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/26d6cb51-8ca1-4c82-8a7b-c23a18fb4b8f">

However, this issue seems to be local to the 'Contributor' tab and not members since the other tab is showing fine. 

<img width="530" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/98d420d3-4b1f-409e-afa7-c55eea0256a5">

<img width="471" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/9977954a-515b-463d-ba61-dad5410edb3d">


2. Also it seems the about section has been set with a fixed height on desktop only but hasn't been carried over to mobile. Please remove this since max height since we have a max char limit set in the user account area. This long text is only for the dev env. 

<img width="469" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/ad79bb75-91fe-41fa-ab72-c9e00d883e6a">


3. Mobile is missing padding at the bottom of the cards, clipping into the team section:

<img width="436" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/0aaad979-0ad1-42c8-9783-dfa2191f9b6c">

2024-07-04 12:58 UTC, Nortsova commented on src/components/v5/common/Pills/PillsBase.tsx
> +      {...rest}
Hi there, thanks for your PR! Just a quick note: I noticed something about props spreading and types that we could improve. There are some props in the type that aren't being extracted from props, which means they might end up as attributes in the <span> element by accident.

Here are the props that could be spread into <span>:

```
export interface PillsProps {
  mode?: ExtensionStatusBadgeMode | UserStatusMode;
  iconSize?: IconSize;
  isIconVisible?: boolean;
}
```

2024-07-05 04:36 UTC, mmioana commented
@melyndav @Nortsova I did the requested changes, if you want please to have another check 🚀 💮

2024-07-05 09:51 UTC, melyndav requested changes
Hi again @mmioana - looks like we're getting closer with this, however, some further changes are needed.

It seems the content container is not matching Figma in regard to width and as a result is truncating the team name. These boxes were designed to handle the max char on team names without truncation needing to happen.

<img width="430" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/450b48fa-93e9-4191-b224-8e4696308673">

Even with longer rep values, the team should not truncate.

<img width="632" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8b8e962f-34b9-4ecd-804d-222f3e02d06c">
 
Be sure to check all card variants to ensure they don't truncate as it's happening not just on the top contributor.

<img width="436" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/afa420c5-be9e-45c7-ade4-dfdfcc22c2ca">

It could be caused by the scroll, however the internal contain container width does not match Figma's px by 2. 

<img width="703" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/218e1372-9b70-4c3a-9da0-1f7bcbf31bd9">

2024-07-05 14:35 UTC, melyndav requested changes
Thanks for the continued updates @mmioana.

1. I'm still getting truncation on team names, as per my previous comment.

<img width="383" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/b418168b-443d-4fc0-9d31-3bef7bc9eba2">

It seems this team container is smaller than the content container when in Figma it's the same.

Currently:
<img width="462" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/a86b9a39-3896-48a3-ba34-fd47d53f8e67">

Figma:
<img width="366" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/a7f46d50-106b-4bfd-a93c-8c3f09db453f">



2. For the token pop over, can you add the missing horizontal rule that's in Figma.

<img width="402" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/d4e4a910-ae52-4302-ba16-b4de56c6e4b3">


<img width="648" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f29cf979-44c4-4858-b479-ac420b6e1400">

3. Also missing is the native token text for the native token in the Colony.

<img width="402" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/14f002d8-eebc-4133-a65c-8b9c0b0c94a4">

2024-07-08 12:09 UTC, mmioana commented
@melyndav amazing eyes, I have definitely missed the token horizontal rule and text! 👀 
Hope now everything is in place, if you can please re-check 💮

2024-07-09 09:25 UTC, melyndav requested changes
Hey @mmioana 

1. Scroll bars have been introduced to modals in this PR -

<img width="542" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/5aee0d1d-7ea6-4d88-81e3-784b9ef496ee">

On production and master (screenshot below) these are not showing.

<img width="557" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/7278be6b-5581-4518-9447-5e465469a63b">


2. I'm still seeing the teams being truncated when a second permission is applied. Since the container width remains the same with as per my previous comment. 

<img width="370" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/2106a8e2-8eed-4582-bbc8-3040e8e2c980">

3. The native token pop over styling is still missing from my previous comment, including the HR and the copy.

<img width="446" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/8b6466db-b714-43f8-b2cf-dfcb92fd9913">

If you can kindly double-check everything before requesting the next review and also doing a quick sanity check of the app, that would be helpful with reducing the time of the PR review process.

2024-07-09 11:23 UTC, iamsamgibbs commented
Just a note to say I am experiencing this issue on master (and on the multi-sig branches) so if you come across it, it hasn't been introduced by a change here. (I am opening a new issue for it)

<img width="460" alt="Screenshot 2024-07-09 at 12 22 15" src="https://github.com/JoinColony/colonyCDapp/assets/34915414/d76f4235-d9ec-478c-bd1b-92ea386a865f">

2024-07-10 21:08 UTC, rdig commented
What's the state here? Can this be reviewed or are we waiting to fix it on `master` then bring over the changes ?

Or are we just fixing everything, including stuff not relevant to the current issue in here ?

2024-07-11 06:25 UTC, mmioana commented
@rdig I put it in draft state only to re-check if all needed changes for this issue are in place.
For the bug Sam discovered, there is another issue https://github.com/JoinColony/colonyCDapp/issues/2676

2024-07-12 13:04 UTC, melyndav requested changes
Hey @mmioana, I'm unable to test this any more. No matter how many times I restart with a fresh env, I just can't get to a test Colony. I have no problems on other branches or master etc. Any thoughts on what this could be? 

![Export-1720789406248](https://github.com/user-attachments/assets/ec78adf9-57bd-4ba3-9210-76a9a7934256)

2024-07-12 14:21 UTC, rdig commented
@melyndav this is definitely a issue on your end, as I just tested this branch and everything is working fine.

What's the error you're getting in the console when the page crashes ?

Also try the following:
- remove the branch locally (`git branch -D <branch-name>`)
- pull the fresh branch again (`git fetch origin <branch-name> && git checkout <branch-name>`)
- remove node modules (`rm -R node_modules`)
- reinstall modules (`npm ci`)
- re-run the dev environment (`npm run dev`)

I'll submit my review in a bit, where you can see me actually being able to run this branch without issues

2024-07-12 14:24 UTC, rdig approved these changes
Tested all the cases I could think of, and all that were mentioned in the original issue, and as far as I can tell everything is as expected.

![Screenshot from 2024-07-12 17-13-50](https://github.com/user-attachments/assets/c4e338ed-de4f-40d6-94ba-cb390ce82031)
![Screenshot from 2024-07-12 17-15-58](https://github.com/user-attachments/assets/fb572dbd-3bff-4cf9-bf04-aa8840158191)
![Screenshot from 2024-07-12 17-16-04](https://github.com/user-attachments/assets/e5718178-ead4-4c0d-8f3c-e7a0c3cf6b98)
![Screenshot from 2024-07-12 17-16-19](https://github.com/user-attachments/assets/1d6dc389-1c57-4ab6-a45d-33e1027d9f3b)
![Screenshot from 2024-07-12 17-16-23](https://github.com/user-attachments/assets/bf9cb6c0-a766-4276-9f04-e8d5071bcf8a)
![Screenshot from 2024-07-12 17-16-51](https://github.com/user-attachments/assets/6ee164c8-cd60-45b4-84fd-efc06d856963)
![Screenshot from 2024-07-12 17-17-02](https://github.com/user-attachments/assets/18edaffc-b386-40b9-b4a4-19c5e462f24f)
![Screenshot from 2024-07-12 17-17-49](https://github.com/user-attachments/assets/7ee06a88-9851-46cb-b4be-0070e1ed1559)
![Screenshot from 2024-07-12 17-17-52](https://github.com/user-attachments/assets/d95bb52d-98f7-443d-b708-85479fcef0b9)
![Screenshot from 2024-07-12 17-18-04](https://github.com/user-attachments/assets/daeb6ccc-a7c3-4c3b-baac-e0267cfcd0a2)
![Screenshot from 2024-07-12 17-18-08](https://github.com/user-attachments/assets/078398f1-9f4b-4f60-ac7b-7e26b8a79c76)

As for the environment not working, here's a short video of me running this locally

[Screencast from 2024-07-12 17-22-11.webm](https://github.com/user-attachments/assets/f09df2cb-617b-4a84-852f-01ae42505f08)

2024-07-15 21:49 UTC, jakubcolony approved these changes
I was able to run this branch without issues.

Nice work on this @mmioana, all the cases I tested look good:
<img width="449" alt="image" src="https://github.com/user-attachments/assets/5ead49cb-39a0-4b83-ac44-60a71a32dc22">

<img width="440" alt="image" src="https://github.com/user-attachments/assets/4299611c-7330-47bc-82b4-95dfa7073383">

<img width="407" alt="image" src="https://github.com/user-attachments/assets/52975043-477f-4318-8890-06eac347d04e">

<img width="385" alt="image" src="https://github.com/user-attachments/assets/8d2d9bc7-1693-4cdd-b6a8-9413332d7354">

<img width="398" alt="image" src="https://github.com/user-attachments/assets/6682a758-fc8c-436a-a539-8b737d33a212">

<img width="383" alt="image" src="https://github.com/user-attachments/assets/c451593d-c451-4210-b533-3f5f54c12bcf">

<img width="407" alt="image" src="https://github.com/user-attachments/assets/bd5b7fdc-3862-4474-b42a-c4bcd250c6fd">

<img width="598" alt="image" src="https://github.com/user-attachments/assets/bfa894f7-ee0c-443c-b945-a18c22c4f19a">

----

The only problem I spotted is the reputation being shown in the wrong units in the tooltip. However, this is also present in `master`, so I opened #2706 to track.
<img width="405" alt="image" src="https://github.com/user-attachments/assets/a6b52837-af35-4799-9f52-142f80dff2b8">

2024-07-16 09:42 UTC, iamsamgibbs approved these changes
Amazing work on this @mmioana ! Fantastic job covering all these cases. All previously raised issues have been resolved. I check the user popovers in as many places as I could find, with different variations of permissions and teams. Checked the token popover too.

<img width="428" alt="Screenshot 2024-07-16 at 10 14 45" src="https://github.com/user-attachments/assets/3557b2e6-2be0-44a8-9f2b-85b55fa4d8d4">

<img width="442" alt="Screenshot 2024-07-16 at 10 14 59" src="https://github.com/user-attachments/assets/63f8a101-9cf2-478a-adab-19b6afd49add">

<img width="451" alt="Screenshot 2024-07-16 at 10 15 26" src="https://github.com/user-attachments/assets/794448b7-0abd-4516-b37e-9028975704f4">

<img width="387" alt="Screenshot 2024-07-16 at 10 20 47" src="https://github.com/user-attachments/assets/f2e29cf4-68b2-4adb-9eda-75121bc14671">

Nice job implementing this "click to open tooltip".

https://github.com/user-attachments/assets/dfa89b91-ccc4-4c33-a487-275f26392e3c

<img width="467" alt="Screenshot 2024-07-16 at 10 26 36" src="https://github.com/user-attachments/assets/b0b02fb4-aa62-492a-9b03-0cab5660f6e9">

<img width="445" alt="Screenshot 2024-07-16 at 10 27 39" src="https://github.com/user-attachments/assets/3605649f-dd52-4f46-8154-14e2de75f598">

<img width="404" alt="Screenshot 2024-07-16 at 10 28 02" src="https://github.com/user-attachments/assets/6355da52-9a8c-495f-aab5-a3de631d6c0e">

<img width="516" alt="Screenshot 2024-07-16 at 10 28 27" src="https://github.com/user-attachments/assets/2584fedc-17b3-4f1d-a033-355bbd8e8362">

<img width="534" alt="Screenshot 2024-07-16 at 10 32 27" src="https://github.com/user-attachments/assets/cf536b19-305d-4e83-b6eb-7daf3fe93341">

I think I've seen this raised on another PR, but the 'verified' icon here should actually be the 'lock' icon. (@melyndav correct me if I'm wrong if it needs to be changed here)

<img width="463" alt="Screenshot 2024-07-16 at 10 31 12" src="https://github.com/user-attachments/assets/65da76ce-7f78-4a06-8a3e-10c28c20d3e1">

<img width="343" alt="Screenshot 2024-07-16 at 10 42 14" src="https://github.com/user-attachments/assets/5cc82ce4-1bfd-435b-9d0f-180fe333b3d0">

2024-07-16 10:08 UTC, iamsamgibbs commented
Ah yep, the locked icon is being tracked in #2667 so no need to fix here :)

2024-07-16 19:03 UTC, rdig commented
@mmioana can you please rebase this ?

2024-07-17 06:36 UTC, mmioana commented
@rdig on my way 🚀

2024-07-17 16:23 UTC, rdig commented
@melyndav do want to review this still?

Otherwise I'll merge it since it's been open for quite a while

2024-07-18 09:35 UTC, melyndav approved these changes
Hey @mmioana! Was able to review this one again and everything now looks aligned with Figma. Nice work on a long PR! Appreciate your effort 🌼

2024-07-18 10:50 UTC, merged