Fix: Edit colony description and objective for multi-sig
JoinColony/colonyCDapp pull request #2654
Opened 2024-07-04 14:37 UTC by mmioana

## Description

- Create and finalize a multi-sig edit colony details and manage colony objective motions.

- [X] The edit colony details multi-sig motion can be created
- [X] The manage colony objective multi-sig motion can be created
- [X] The edit colony details motion can be finalized
- [X] The manage colony objective motion can be finalized
- [X] Only users with [adequate permissions](https://www.notion.so/colony/Multi-sig-Permissions-6aaf0b95309f4754a243d54e8d9c4189?pvs=4#fec3699a5fd241a2925bd2809494b157) can create them

## Testing

Check Edit Colony details motion and Manage objective motion can be created with both Multi-Sig and Permissions decision method.

### Edit Colony details action
* Step 1. Install Multi-Sig extension
* Step 2. Create new action - Edit Colony details 
* Step 3. Select Multi-Sig decision method
* Step 4. Update Colony description field
* Step 5. Create action
* Step 6. Check colony description was updated on dashboard
* Step 7. 🔁 Repeat above steps for the Permissions decision method 🔁

### Manage objective action
* Step 1. Install Multi-Sig extension
* Step 2. Create new action - Manage objective
* Step 3. Select Multi-Sig decision method
* Step 4. Update Objective description field
* Step 5. Create action
* Step 6. Check colony objective was updated on dashboard
* Step 7. 🔁 Repeat above steps for the Permissions decision method 🔁

[Block ingestor PR](url)
Resolves [#2191](https://github.com/JoinColony/colonyCDapp/issues/2191)

2024-07-05 15:45 UTC, Nortsova requested changes
Thanks for your PR, @mmioana!

I can confirm that after the "Edit colony" action is created with a "Multi-sig" motion, changes are not applied by default.

![video-1-before-approve](https://github.com/JoinColony/colonyCDapp/assets/15706494/f76a6503-259f-4299-9339-64a500b44ae7)

After finalizing this action, the changes apply to the colony description:

![video-2-after-approve](https://github.com/JoinColony/colonyCDapp/assets/15706494/ffb2cea0-6a40-4c28-a0b2-182394fe9e7d)
 
I can also confirm that the "Edit colony" action created with a "Permissions" motion has changes applied instantly:

![video-3-edit-permissions](https://github.com/JoinColony/colonyCDapp/assets/15706494/fe2082a2-541a-4b0a-993c-24a5b7676816)

The "Manage objective" action created with "Multi-sig" motion is not applied instantly (before finalization):

![objective-1-not-finalize](https://github.com/JoinColony/colonyCDapp/assets/15706494/763f8334-4c7c-407e-ac5d-63edec595aaf)

It is applied after the action is finalized:

![objective-2-finalized](https://github.com/JoinColony/colonyCDapp/assets/15706494/d29f7436-6b12-4603-b468-a4e7e31c0f6b)

However, for the "Manage objective" action with "Permissions," the app crashes with this error after submission:

<img width="1536" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/12239ad1-e7c0-4902-b254-1f838d90e1c2">

Also I found an error with the description field where the max length is 200, but a colony has already been created with more than 3k symbols. I'm not sure where this mistake originates, but is it possible to solve it easily? 😊

<img width="679" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/15706494/6384df7f-75ed-4716-a203-d4d44d67b1d8">

Thank you! ✨

2024-07-08 09:33 UTC, mmioana commented
Hi @Nortsova thank you for taking the time to review this PR. 💟 

You are right! With muti-sig changes should be visible only after the action is finalised - I will update the testing steps.

For the 'Manage objective' with permissions seems there was a bug, but now it should be solved ✨ 

Regarding the colony description/objective description length I have already updated the create-data script on master to truncate the saved values. If it helps, I can cherry-pick it into this branch.

2024-07-08 14:13 UTC, mmioana commented
@Nortsova you were right! Actually the colony description character limit was relying on the objective description char limit, so in the create-data script I completely omitted it.
Now there should be a MAX_COLONY_DESCRIPTION which ensures the colony description is not larger than 200 chars also for the test data

2024-07-09 08:28 UTC, rumzledz requested changes

2024-07-09 09:47 UTC, rumzledz commented
@mmioana I only found out about this, you should also update the `en-actions.ts` file to include a translation entry for your multi-sig action so it doesn't end up as "Generic action..." in the `Latest activity` table and "Generic" in the action type field in the Completed Action component:

![image](https://github.com/JoinColony/colonyCDapp/assets/50642296/1f3fb6d0-5176-4b34-8640-3d63845afcbe)

![image](https://github.com/JoinColony/colonyCDapp/assets/50642296/936808cd-61e1-443d-9757-e782ac03c4a8)

2024-07-09 20:23 UTC, rumzledz approved these changes

2024-07-10 10:18 UTC, Nortsova requested changes
Hey @mmioana , thank you for the updates :) 

The "Manage Objectives with Permissions" feature is working now, thanks! 💫

However, I found a small issue: after using "Manage Objectives with Multi-Sig," the company description gets removed (social links as well, I didn't show it on video):

![manage-objective-bug](https://github.com/JoinColony/colonyCDapp/assets/15706494/b6b181a7-6266-4a9c-8e00-d55d7532c5e2)

And another thing: I'm not sure if this was mentioned to be done, but right now I can submit "Edit Colony Details" and "Manage Objectives" even if the form hasn't been changed.

So for now, I am rejecting only due to the bug where the description and links are removed after the "Manage Objective" motion with multi-sig is called. ✨

2024-07-10 15:06 UTC, bassgeta requested changes
Nice work on this :ok_hand: 
I was able to edit details via Multi-sig
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/dd6231b1-623c-499a-bf73-e08c07a11c96)
and I can confirm that other stuff doesn't get wiped anymore
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/d80a7cec-f0bb-4f23-8c16-0ff4364dee8f)
Managing an objective also works!
![image](https://github.com/JoinColony/colonyCDapp/assets/23449297/0ad69c0d-7286-450f-83e9-1641b8304b98)

Maybe we can just rework how voting reputation gets the child index, so we use the local helpers and after that it's good to go in my book!

2024-07-12 06:56 UTC, mmioana commented on src/redux/sagas/motions/editColonyMotion.ts
> +      const childSkillIndex = yield call(
"If we don't need the permissions domain ID (we don't in this case, edit colony always happens in root)"
"As long as the parentDomainId and domainId match, there's no network call. Child skill index, as far as I know, is just a number that relates two domains together so if 2 domains are the same, it's always that MaxUint256"

2024-07-12 09:21 UTC, iamsamgibbs approved these changes
Great work on this! It is all working great, and all the code looks great. Nice job! 🎉 

<img width="1069" alt="Screenshot 2024-07-12 at 10 17 35" src="https://github.com/user-attachments/assets/2e7f5218-4352-4840-8919-898db1742c29">

<img width="1060" alt="Screenshot 2024-07-12 at 10 17 41" src="https://github.com/user-attachments/assets/a61a0ae5-b6b4-45a2-a057-fdc80de130f7">

<img width="639" alt="Screenshot 2024-07-12 at 10 03 15" src="https://github.com/user-attachments/assets/2698e61d-3eb8-4ceb-a9f4-47884c49e5c9">

<img width="742" alt="Screenshot 2024-07-12 at 10 04 09" src="https://github.com/user-attachments/assets/e18ec10e-95de-465b-a5d8-25e7409964ee">

<img width="1381" alt="Screenshot 2024-07-12 at 10 05 25" src="https://github.com/user-attachments/assets/6037456c-9b13-4d18-b866-d768c65c3aa1">

<img width="511" alt="Screenshot 2024-07-12 at 10 05 59" src="https://github.com/user-attachments/assets/fa82e65e-920e-4af3-a727-368570d57b66">

<img width="534" alt="Screenshot 2024-07-12 at 10 07 40" src="https://github.com/user-attachments/assets/a45ce6d4-77a5-4537-b503-fd299addb85f">

2024-07-12 09:21 UTC, iamsamgibbs commented on src/components/v5/common/CompletedAction/CompletedAction.tsx
>          // @NOTE: Enabling those 2 above temporarily
Tiny tiny note, but it would be better to have this two lines higher as it now makes the comment incorrect.

2024-07-12 09:21 UTC, iamsamgibbs commented on src/i18n/en-actions.ts
Nice extra pickups here :)

2024-07-12 11:04 UTC, davecreaser approved these changes
Nice job! 🎉 

Code looks all good, and works as expected when testing:

<img width="1920" alt="Screenshot 2024-07-12 at 12 03 16" src="https://github.com/user-attachments/assets/df480eab-ee68-41c9-b9a0-7ff1807bcade">

2024-07-12 12:11 UTC, merged