Feat/2186 upgrade colony version via multi sig
JoinColony/colonyCDapp pull request #2696
Opened 2024-07-11 17:06 UTC by rumzledz

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-07-18 08:35 UTC, iamsamgibbs requested changes
Amazing job on this @rumzledz ! 🎉  I know it was a pain pulling this all together, but it's looking great.

I was able to deploy version 17 and use the create-data script to create colonies on version 16. I was able to install the multi-sig extension and create a version upgrade action using the multi-sig decision method.

<img width="1362" alt="Screenshot 2024-07-18 at 09 15 01" src="https://github.com/user-attachments/assets/2c8ccb72-7482-4428-8f0b-e58cf2e01154">

Approved and executed without issue.

<img width="1363" alt="Screenshot 2024-07-18 at 09 17 44" src="https://github.com/user-attachments/assets/618582df-7d22-454a-a6aa-5a8f59472144">

<img width="309" alt="Screenshot 2024-07-18 at 09 17 48" src="https://github.com/user-attachments/assets/65800c9e-e02f-4e33-a152-46e2a23a5fd8">

Activity list looks good:

<img width="744" alt="Screenshot 2024-07-18 at 09 15 59" src="https://github.com/user-attachments/assets/93c684b7-3c27-47da-a538-a9d6f8604af8">

The only minor pick up is the missing `CreatedIn` field from the completed action screen:

<img width="689" alt="Screenshot 2024-07-18 at 09 15 28" src="https://github.com/user-attachments/assets/ed4be7f3-2439-4da1-9746-ede70a83418b">

I also noticed this mistake I made with the create-data script change, could you fix it here? If `usePreviousColonyVersionArg` is true, then we shouldn't console log line 1488.

<img width="901" alt="Screenshot 2024-07-18 at 09 09 12" src="https://github.com/user-attachments/assets/b2810d12-f67c-4e08-a6b4-ed990f941501">

Is the `[colonyAddress]` -> `[AddressZero]` a breaking change? I think the other motions which use it will need updating too: editColonyMotion, managePermissionsMotion, manageReputationMotion, cancelMultiSig, finalizeMultiSig, setThreshold, voteOnMultiSig. (Manage Permissions will need a block-ingestor change `const isMultiSig = actionTarget !== colonyAddress;` to make this AddressZero too).

If it isn't a breaking change then we could leave this for the QoL issue.

The misalignment caused by the upgrade banner is fun too, I'll raise a separate issue for this:

<img width="1346" alt="Screenshot 2024-07-18 at 09 12 42" src="https://github.com/user-attachments/assets/32119a83-9d73-4366-80c5-e654cbf5050d">

2024-07-18 10:21 UTC, rumzledz commented
Thanks for reviewing this @iamsamgibbs! I'm just gonna re-post the message here for others who are curious as well:

The colonyAddress -> addressZero change (which is not viewable on my PR anymore since the `feat/multi-sig` branch has these updates already) is a required change because on the contract side, it now goes:

If you're making a motion targeting the colony, use address zero.

Which should now be in line with how reputation motions work.

I've updated the Completed Action for to show the CreatedIn field:

![Screenshot 2024-07-18 at 11 19 13](https://github.com/user-attachments/assets/d9754c97-3bf8-41b1-8b1d-33e55c958979)

And updated the create-data script copy:

![Screenshot 2024-07-18 at 11 19 33](https://github.com/user-attachments/assets/cfb2f2bb-5544-4eb2-8c81-76ed3508acbf)

2024-07-19 08:04 UTC, bassgeta approved these changes
Thank you for the detailed testing steps, got the banner to show up :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/75aacd23-8cf9-44dd-9804-275083bf5030)

The header is a bit hilarious, but it's not your fault :D
![image](https://github.com/user-attachments/assets/1e319fc4-2aa5-47d8-bb8b-f9c6c8db6196)
![image](https://github.com/user-attachments/assets/86455e87-098c-4cef-9da3-c6293f1dbd67)

Nice going, let's merge this!

2024-07-22 10:42 UTC, davecreaser approved these changes
Great work @rumzledz! I bet it was a lot of fun when you first picked this up trying to figure out how to even start developing this 🤣 Really nice job. Code is all good, and it works great when testing (barring the banner misalignment that Sam has already pointed out, but that's not part of this PR's remit).

Here's my testing, showing that it worked flawlessly:
<img width="1920" alt="Screenshot 2024-07-22 at 11 35 09" src="https://github.com/user-attachments/assets/839d1660-d36e-4447-81ec-5ffc3a140b40">
<img width="1920" alt="Screenshot 2024-07-22 at 11 37 33" src="https://github.com/user-attachments/assets/b343ea6b-8daa-4214-9277-71f8cb6dcd76">
<img width="1920" alt="Screenshot 2024-07-22 at 11 38 04" src="https://github.com/user-attachments/assets/22fa076d-b292-4a8b-998d-305d2737b41d">
<img width="1920" alt="Screenshot 2024-07-22 at 11 38 32" src="https://github.com/user-attachments/assets/03ded8a8-bbe7-41ef-b71f-fb8589459fe1">
<img width="1920" alt="Screenshot 2024-07-22 at 11 38 55" src="https://github.com/user-attachments/assets/e14e7eec-654c-436c-a8dd-bb9e989fca66">
<img width="1920" alt="Screenshot 2024-07-22 at 11 39 13" src="https://github.com/user-attachments/assets/166c873c-8f15-412d-a6a2-8f4f70b3d667">

2024-07-22 19:06 UTC, rumzledz commented
> I bet it was a lot of fun when you first picked this up trying to figure out how to even start developing this

It was quite the adventure! These two emojis are pretty much summing it up 😭 😂

2024-07-23 08:18 UTC, iamsamgibbs approved these changes
Nice job! My previous issues have been addressed, get it merged!

<img width="1318" alt="Screenshot 2024-07-23 at 09 16 49" src="https://github.com/user-attachments/assets/9e3dba0b-c220-4ae4-b219-f77599e51f8f">

<img width="748" alt="Screenshot 2024-07-23 at 09 15 59" src="https://github.com/user-attachments/assets/9320051b-3fdf-4cff-9ffa-d222d8aeafea">

<img width="1055" alt="Screenshot 2024-07-23 at 09 15 54" src="https://github.com/user-attachments/assets/a7d1ebc5-a47e-4e55-896c-7102dd539ad7">

2024-07-23 09:52 UTC, merged