Feat: Manage Reputation via Multi-Sig
JoinColony/colonyCDapp pull request #2697
Opened 2024-07-11 17:40 UTC by davecreaser

## Description

- Allow users to manage reputation using a multi-sig action.

Block Ingestor changes [here](https://github.com/JoinColony/block-ingestor/pull/253)

## Testing

**First**: Restart your dev env so that you have the correct block ingestor version running. Also visit http://0.0.0.0:3001/reputation/monitor/toggle (make sure you do this only once [or three times, or five...]! - this is explained [here](https://www.notion.so/colony/Reputation-in-development-c05b7a1f79fc4465a220c2806792e4a7)) so that reputation updates happen in dev.

* Step 1. As Leela, install Multi Sig Extension, and set the threshold to 2 (then refresh the page).
* Step 2. Create an action to give Amy multi-sig permissions (then refresh the page).
<img width="1920" alt="Screenshot 2024-07-11 at 17 28 11" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/bf44122b-18ab-4bf4-aa99-c8d61a2876b5">

* Step 3. Navigate to the Contributors tab, and make a note of Fry's reputation. Here you can see it is 3.12%.
<img width="1920" alt="Screenshot 2024-07-11 at 17 31 22" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/18c73931-527e-49ec-b4e6-faeb5fd8bab5">

* Step 4. As Leela, create an action to award Fry some reputation using multi-sig as the decision method.
<img width="1920" alt="Screenshot 2024-07-11 at 17 32 15" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/c4bbc696-b42e-4c83-ada8-ddb9e711c480">

* Step 5. As Amy (I suggest an incognito window), navigate to the above action, and using the sidebar approve and finalise the motion.
<img width="1920" alt="Screenshot 2024-07-11 at 17 32 52" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/33ba0bf1-e548-43b6-9f21-9dc7bbe112c8">

* Step 6. Go back to the Contributors tab from step 3, and refresh the page (you may need to wait a few seconds or refresh a couple of times because of the way the hook / lambda is currently set up to fetch reputation updates). You should see that Fry's reputation has changed reflecting your action.
<img width="1920" alt="Screenshot 2024-07-11 at 17 34 13" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/793a60de-668a-4dfc-87f5-1bdf889e0f49">

* Step 7. Repeat steps 4, 5 and 6, however this time try to _remove_ reputation from Fry, instead of awarding it.
<img width="1920" alt="Screenshot 2024-07-11 at 17 35 47" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/9c813562-fc2e-4480-822a-e28e2f3568c7">
<img width="1920" alt="Screenshot 2024-07-11 at 17 36 06" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/066d9fcb-5e6e-4584-9ef8-34e6603398c9">
<img width="1920" alt="Screenshot 2024-07-11 at 17 37 27" src="https://github.com/JoinColony/colonyCDapp/assets/38098203/57010098-5888-47d1-bf23-1363657f8879">

* Optional Step 8. Repeat steps 3, 4, 5 and 6, but this time do everything in a sub domain. This means checking the current reputation percentage in the Contributors tab after first changing the current team at the top of the page to a sub domain, then creating the remove reputation action in that sub domain instead of General. Things should still work the same way!

## Diffs

**Changes** 🏗

* Edited the Manage Reputation Motion saga to handle multi sig.

Resolves #2190

2024-07-12 08:09 UTC, mmioana requested changes
Awesome job on this one @davecreaser! 🚀 

I managed to award Fry reputation
![Screenshot 2024-07-12 at 10 03 27](https://github.com/user-attachments/assets/57e57ebb-30ca-4ab4-bbab-ef92e005a91a)
![Screenshot 2024-07-12 at 10 03 50](https://github.com/user-attachments/assets/b2640fec-6b82-4344-a76d-3b47ebe061b5)
![Screenshot 2024-07-12 at 10 04 05](https://github.com/user-attachments/assets/9b7537e0-9798-48d6-9e0d-83bb1ac1784b)

However, when trying to remove Fry's reputation I noticed in the action sidebar the current reputation value remains 0. Can you please re-check this?
![Screenshot 2024-07-12 at 10 05 14](https://github.com/user-attachments/assets/141a4c17-4e7b-444f-a72e-d1d7dda6203b)

2024-07-12 10:10 UTC, davecreaser commented
> Awesome job on this one @davecreaser! 🚀
> 
> I managed to award Fry reputation ![Screenshot 2024-07-12 at 10 03 27](https://private-user-images.githubusercontent.com/32430018/348175708-57e57ebb-30ca-4ab4-bbab-ef92e005a91a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzUxNTEsIm5iZiI6MTcyMDc3NDg1MSwicGF0aCI6Ii8zMjQzMDAxOC8zNDgxNzU3MDgtNTdlNTdlYmItMzBjYS00YWI0LWJiYWItZWY5MmUwMDVhOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MGE4NGIxYzk2ZTUwMDFiYzI0NWI2Y2QyZWRjM2EwMWI1YmU5YzRhZjk0YjgxYjA0NDdkNTE4NGUxNTgxMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KZZGYlwo5nufNwcXP_0AJso1vgxfupwPoTqJNOtaD5Q) ![Screenshot 2024-07-12 at 10 03 50](https://private-user-images.githubusercontent.com/32430018/348175835-b2640fec-6b82-4344-a76d-3b47ebe061b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzUxNTEsIm5iZiI6MTcyMDc3NDg1MSwicGF0aCI6Ii8zMjQzMDAxOC8zNDgxNzU4MzUtYjI2NDBmZWMtNmI4Mi00MzQ0LWE3NmQtM2I0N2ViZTA2MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjODI4YzAxOGM2OWQ4MzdiZTgxYzc2OTVjZmQzNjY3MmYyYmYyNzRlODZiODI2NmVjNDQxYjVmMzcxNzc2YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AhNXMdEdrA1WTb4WEtzJ4TDY3yWE_KZSnh7K3TT1mfc) ![Screenshot 2024-07-12 at 10 04 05](https://private-user-images.githubusercontent.com/32430018/348175878-9b7537e0-9798-48d6-9e0d-83bb1ac1784b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzUxNTEsIm5iZiI6MTcyMDc3NDg1MSwicGF0aCI6Ii8zMjQzMDAxOC8zNDgxNzU4NzgtOWI3NTM3ZTAtOTc5OC00OGQ2LTllMGQtODNiYjFhYzE3ODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMDc1NWQ1YzE2YThiOTc4YjcwY2RlMGJmODliZTY4ZDliMzQ3MjNjNGVhYmFmOTljY2E1ZjAwZTUxODc1NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IcOAGpxvj92GGdtNU81U74RScq4xVmq0kbjR-hVzQdw)
> 
> However, when trying to remove Fry's reputation I noticed in the action sidebar the current reputation value remains 0. Can you please re-check this? ![Screenshot 2024-07-12 at 10 05 14](https://private-user-images.githubusercontent.com/32430018/348176174-141a4c17-4e7b-444f-a72e-d1d7dda6203b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzUxNTEsIm5iZiI6MTcyMDc3NDg1MSwicGF0aCI6Ii8zMjQzMDAxOC8zNDgxNzYxNzQtMTQxYTRjMTctNGU3Yi00NDRmLWE3MmUtZDFkN2RkYTYyMDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMmU2ZDQzNDZkMzc4N2Q5YjA2YzBjMDcyOGViZGI2YjM0MjUyOTBlN2VhY2NmMWE4ZWRiNThmNTcyZTNmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1oVkgED0cXUf0CC8xWtFGZ9NpimTaBXdVDFGThyk6A)

Hey @mmioana! Thanks for the review. It looks like reputation might be broken in general on your dev env - I see in the screenshots that in the user hub button in the top right it doesn't show any reputation percentage, which means that the reputation likely isn't being loaded properly anywhere. Could you restart your dev env and try again? You'll need to see a percentage at the top right (in the testing instructions first screenshot you can see Leela has 89.08% rep for example). Thanks!

2024-07-12 10:11 UTC, davecreaser commented on src/components/v5/common/ActionSidebar/partials/forms/ManageReputationForm/utils.ts
> +    colonyDomains: extractColonyDomains(colony.domains),
Oh very nice! I hadn't seen that. I'll keep an eye on that PR and update this when it's merged. Nice one! 🎉

2024-07-12 11:56 UTC, mmioana approved these changes
After fixing my environment, @davecreaser I can confirm awarding and removing reputation works as expected 🎉 

Starting reputation of fry
![Screenshot 2024-07-12 at 13 44 27](https://github.com/user-attachments/assets/e6432559-89ae-4edf-b378-7c384c495678)

Awarding Reputation
![Screenshot 2024-07-12 at 13 47 24](https://github.com/user-attachments/assets/94ab7bcd-b761-44e0-9c6a-8fe96d664682)
![Screenshot 2024-07-12 at 13 47 50](https://github.com/user-attachments/assets/45cc2160-5cc8-4409-8a93-5fad1c4ea09f)
![Screenshot 2024-07-12 at 13 50 27](https://github.com/user-attachments/assets/cbc334d8-dab0-4ea7-b4d8-3bb07d8c15ae)

Removing reputation
![Screenshot 2024-07-12 at 13 50 10](https://github.com/user-attachments/assets/26dc3f20-6e6f-4da9-b203-742d128c4049)

2024-07-15 10:53 UTC, bassgeta requested changes
Awarding via MS works:
![image](https://github.com/user-attachments/assets/4a0a3b1c-0a38-4f5e-980f-01f071297160)
Removing:
![image](https://github.com/user-attachments/assets/ce89570d-fc8a-4d5d-afc4-4f06c05191c6)
Removal in a subdomain also works:
![image](https://github.com/user-attachments/assets/7e8b3004-d5c5-4bc3-ac27-5f76efaeeb43)

However, when creating a motion via voting reputation, the sidebar doesn't show up correctly
![image](https://github.com/user-attachments/assets/0322da90-94dc-4392-b04d-8034c01ff6b1)
but it's a bug on `master`, though it's easily fixable by adding these 2 lines to `CompletedAction.tsx`
![image](https://github.com/user-attachments/assets/09f3a9c8-89b4-4361-9a6f-a4ae12aa3c8b)

2024-07-15 11:52 UTC, iamsamgibbs requested changes
Nice work on this Dave! I was able to award and remove reputation via multi-sig:

<img width="1063" alt="Screenshot 2024-07-15 at 12 41 45" src="https://github.com/user-attachments/assets/de2ba184-79c1-4fe2-9d90-922746fbe0f7">

And can confirm the motions are correctly showing the sidebar now:

<img width="1062" alt="Screenshot 2024-07-15 at 12 43 21" src="https://github.com/user-attachments/assets/b3ed3b7c-f963-4677-94ed-951639abe1fe">
<img width="1053" alt="Screenshot 2024-07-15 at 12 43 49" src="https://github.com/user-attachments/assets/ab325726-4345-4f86-9b6a-07de5596b234">

The only thing missing is the multi-sig meatball on the completed action screen.

<img width="1062" alt="Screenshot 2024-07-15 at 12 42 20" src="https://github.com/user-attachments/assets/23a82020-8553-41ff-967c-fb867b002c10">

Should be:
<img width="253" alt="Screenshot 2024-07-15 at 12 45 11" src="https://github.com/user-attachments/assets/1ac2fe79-8ff1-43e9-8f61-ed1145dd4997">

2024-07-15 13:47 UTC, iamsamgibbs approved these changes
Ignore my previous comments regarding the meatball menu, it is no longer required.

2024-07-16 08:29 UTC, bassgeta approved these changes
Nice solution, awarding and removing is still working for me:
![image](https://github.com/user-attachments/assets/34c6d4af-5753-4a8e-9b8b-ac099096708f)

The sidebar for voting reputation does show up correctly now (I failed it, not an error on this branch :D ):
![image](https://github.com/user-attachments/assets/990bca35-451f-415d-b71e-59f89bb40246)

Nice one :ship: !

2024-07-16 09:23 UTC, merged