Fix: Add form validation when removing permissions
JoinColony/colonyCDapp pull request #2749
Opened 2024-07-19 18:53 UTC by rumzledz

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-07-22 16:17 UTC, arrenv requested changes
@rumzledz Great work on this, I appreciate your hard work and for working through the cases.

Everything seems to work as expected, in which the warning and confirmation modal appears in the situation whenever the `Root` permission is removed.

My only request would be to close down the modal on clicking the confirmation. That way we return to the action panel, and users can access their Userhub without having to have it float over the top.

![image](https://github.com/user-attachments/assets/26f86ebe-77e2-4898-8937-c8326ba5cfe0)

2024-07-23 09:22 UTC, iamsamgibbs requested changes
Nice work with this @rumzledz ! 🎉  This form is looking a lot nicer with these reworks. I agree with all your decisions around naming choices.

Following your testing steps everything works as expected.

<img width="682" alt="Screenshot 2024-07-23 at 09 57 04" src="https://github.com/user-attachments/assets/439b639f-df19-42db-8ac3-bf21d538b3f9">

<img width="682" alt="Screenshot 2024-07-23 at 09 57 14" src="https://github.com/user-attachments/assets/15ba08b2-90d8-4644-81f2-278c167093b2">

<img width="678" alt="Screenshot 2024-07-23 at 10 00 08" src="https://github.com/user-attachments/assets/f7fe0528-0d78-4357-bfda-8ec21f1e9be7">

<img width="548" alt="Screenshot 2024-07-23 at 10 02 34" src="https://github.com/user-attachments/assets/6216b90b-09d9-4f59-83d3-6e7c45ab5cd4">

I have found one issue with the pill here, the `Admin` set of permissions is being removed here, but the `Custom` pill shows:

<img width="1058" alt="Screenshot 2024-07-23 at 10 01 10" src="https://github.com/user-attachments/assets/25ebb59c-ba58-413a-aeb0-39ee6068080f">

There is a bigger issue with the inherited permissions. In this example, I have given custom permissions not including roles 5 or 6 in General. I have a sub domain with just role 6, another with 5 and 6 plus some other roles. With the way things are currently setup, it is impossible to remove roles 5 or 6 from the sub-domains as the form assumes they are inheriting their roles from General.

https://github.com/user-attachments/assets/927b46e8-860e-4bb0-8afe-5a0e2fd64849

2024-07-23 09:48 UTC, rumzledz commented
> There is a bigger issue with the inherited permissions. In this example, I have given custom permissions not including roles 5 or 6 in General. I have a sub domain with just role 6, another with 5 and 6 plus some other roles. With the way things are currently setup, it is impossible to remove roles 5 or 6 from the sub-domains as the form assumes they are inheriting their roles from General.

Thanks for this @iamsamgibbs , let me take a trip back to Arren's inbox to discuss this and other bits of knowledge that I haven't grasped yet!

2024-07-23 09:49 UTC, rumzledz commented
![image](https://github.com/user-attachments/assets/37badc9f-4ada-4a5e-96c6-ca4d51c63c26)
Nice catch @iamsamgibbs! I'll see what's going on here 🔎

2024-07-24 14:59 UTC, melyndav requested changes
Hey @rumzledz, nice start on this PR. A couple points of feedback that additional to @arrenv and @iamsamgibbs notes. 

1. The title font size in the removal confirmation modal is a bit bigger than what's in Figma and what's consistent with the other global modals.

**Figma:** 

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/5c0bfe94-44ab-4568-a52d-b9ed6bcd4301">

---

2. The font in the p should match Figma (gray-600)

<img width="480" alt="image" src="https://github.com/user-attachments/assets/06370e77-8efa-4b63-8af3-327833ff3520">

**Figma:**

<img width="919" alt="image" src="https://github.com/user-attachments/assets/79103a51-215f-4c0d-bef3-dfa5a414d210">

---

3. The default state of the table when the 'remove permission' option is selected should match what we've got in Figma. This will avoid the duplicate table showing in the confirmation modal. 

Link to design: https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=21336-77392&t=sxwbLXpC1zDPn27F-4 

<img width="365" alt="image" src="https://github.com/user-attachments/assets/207bc605-4c4e-4369-a370-8b78c0f25f69">

---

4. I also assigned 1 custom (admin) permission to Jasmin Jolt fromt he custom table. However the 'Mod' pill shows up in the table (I think this might have been raised).

<img width="667" alt="image" src="https://github.com/user-attachments/assets/cc76626d-b19a-481f-9dbd-d00b1f22d779">



Wanted to leave a final comment on how nicely formatted your PR's are! Really easy to follow and also visually appealing. 🙌

2024-07-24 15:22 UTC, rumzledz commented
Hey @melyndav thanks for reviewing this!
1 & 2: Whoops!
3. All right, got it now! I'll strictly reserve the new table design just for Custom permissions
4. This might be a bit tricky because just having Administration permissions is a 1:1 match for being a Mod but all right, I'll see what I can do 👌

2024-07-24 15:30 UTC, melyndav commented
> Hey @melyndav thanks for reviewing this! 1 & 2: Whoops! 3. All right, got it now! I'll strictly reserve the new table design just for Custom permissions 4. This might be a bit tricky because just having Administration permissions is a 1:1 match for being a Mod but all right, I'll see what I can do 👌

For #4 I'll super confirm this with Arren as it was a confusing UX but understand there are limitations. I will get back to you. 👍

2024-07-26 10:12 UTC, iamsamgibbs submitted a review, later dismissed
Nice work on this huge rework! Thank you for the very thorough testing steps, followed them all without issue and couldn't think of any further scenarios to test.

I only noticed one small issue, but I think it should be opened in a new issue to get this one merged in:

When redoing the action, and typing in the members dropdown it should clear the field but it doesn't, so you get the error message that member is a required field even though it appears to have a value. (This only happens when redoing the action). 

https://github.com/user-attachments/assets/707691a5-79b6-43ab-a118-38197c8970f5

Great job!

2024-07-26 10:25 UTC, melyndav requested changes
Hey @rumzledz appreciate your continued work on this one, I know it's been a big one, and I've appreciated all your Discord comms to get this one sorted. So epic effort here! 

Just some minor pick-ups:

1. In the table during the action creation, the table heading 'Remove Custom type' - type needs to say _permissions._ 

<img width="665" alt="image" src="https://github.com/user-attachments/assets/4f5398dc-07f3-4b9d-a9cb-b8d9a52a0a49">

Figma:
<img width="347" alt="image" src="https://github.com/user-attachments/assets/36a0bc0b-52a5-48cb-bb7d-c27085e3339f">


2. When it's a 'Custom' permission bundle being removed, can we show the custom pill in the confirmation modal? I feel like it was there previously, but it's not showing for me now.

<img width="482" alt="image" src="https://github.com/user-attachments/assets/45723b41-a203-4a60-b8d8-49f7d5476047">
 
Figma:

<img width="435" alt="image" src="https://github.com/user-attachments/assets/a736c812-61bd-4850-850d-ef05d3028af9">

2024-07-29 09:00 UTC, iamsamgibbs requested changes
Mel's issues appear resolved. 🎉

<img width="673" alt="Screenshot 2024-07-29 at 09 51 18" src="https://github.com/user-attachments/assets/77e1c503-e1b7-42cc-969c-fbefd07fb532">

<img width="518" alt="Screenshot 2024-07-29 at 09 52 49" src="https://github.com/user-attachments/assets/7b4758a0-0d71-43a6-b296-6cd353064267">

I've found two new issues though. The first half of this video shows the permissions table always showing the "custom" pill regardless of the selected permissions type (later in the video when I switch to Fry it does show the correct pill, so it doesn't seem to always happen). The second half shows when you switch to a user with custom permissions (Amy) then switch to a user with no permissions, the "custom" type stays selected rather than resetting the field.

https://github.com/user-attachments/assets/eb27a832-0e4d-4225-9e50-b86a70b9e38e

2024-07-29 12:52 UTC, rumzledz commented
> The second half shows when you switch to a user with custom permissions (Amy) then switch to a user with no permissions, the "custom" type stays selected rather than resetting the field

@iamsamgibbs aw man, I think this is because of the actual function we use to retrieve the user's role. The way it's written is the default role value is "custom" even if you don't have permissions 😕 but all right, I'll try to do something about that 👌

2024-07-30 09:47 UTC, iamsamgibbs submitted a review, later dismissed
Thanks for fixing the previous issue! I've followed through all the testing steps another time and all is still working as expected.

2024-07-30 14:57 UTC, melyndav submitted a review, later dismissed
Re-reviewed and all is looking good. Appreciate you picking up my previous comment and fixing the UI @rumzledz! 👍

2024-09-11 17:41 UTC, iamsamgibbs reviewed
Great work on this @rumzledz - I know there has been a ton of work put into this and it has changed about 100 times, so it's great to see this nearly closed out.

#3070 + #2967 + #2339 + #2241 + 2755 - I followed the testing steps from all of these issues without any problems when assigning both core permissions and multi-sig permissions.

Great job! I've not tested the original testing steps in this issue - I'm assuming someone else will check through those whilst reviewing, but I'm also happy to re-review and go through those specific steps too.

I ran into one issue which hasn't been mentioned anywhere before, so feel free to tackle this as a separate issue, but if you assign "Payer" permissions in "Andromeda", then assign "Admin" permissions in "General", then attempt to remove the "Payer" permissions from "Andromeda" you will get this error:

<img width="680" alt="Screenshot 2024-09-11 at 18 18 59" src="https://github.com/user-attachments/assets/3799bcb9-ec2a-4bda-b3b5-bf0645f9114d">

I think this was maybe an intentional decision at one point, but the contracts allow it so we should remove this restriction.

Here's a collection of screenshots from my testing for your enjoyment:

<img width="675" alt="Screenshot 2024-09-11 at 18 13 11" src="https://github.com/user-attachments/assets/0d8aac67-c20d-489a-a696-626cc512cca6">
<img width="676" alt="Screenshot 2024-09-11 at 18 16 37" src="https://github.com/user-attachments/assets/76a7ee39-98a0-43f2-9529-fcf549fd507f">
<img width="678" alt="Screenshot 2024-09-11 at 18 18 20" src="https://github.com/user-attachments/assets/4c061246-2565-415f-853b-a1f5ae42b59e">
<img width="680" alt="Screenshot 2024-09-11 at 18 18 59" src="https://github.com/user-attachments/assets/c9692377-dfce-4542-b322-0aa87abaae93">

2024-09-12 00:48 UTC, rumzledz commented
> I think this was maybe an intentional decision at one point, but the contracts allow it so we should remove this restriction.

Okay this will be much easier to explain in a call tomorrow but TLDR: Yes, this PR aims to have a very deliberate logic that prevents inherited permissions from being downgraded or removed. What happened here was a user already has an existing role for a subdomain which is on a lower tier compared to the one that was subsequently set on the root domain. And so the validation is getting confused 😆

I'll speak to product tomorrow to see how we can deal with this scenario 👌 Thanks for this @iamsamgibbs !

2024-09-12 15:04 UTC, rumzledz commented
@iamsamgibbs all right after speaking with Arren, here's the new issue as promised #3083. It comes with its own complexities as an edge case so as discussed, it will be dealt with separately 👌

2024-09-17 13:55 UTC, iamsamgibbs submitted a review, later dismissed
Nice job!

One small issue with testing step 6. This might be better to address as a separate PR for the sake of getting this merged. The error message appears as expected, but disappears when changing any other field.

https://github.com/user-attachments/assets/0485a37e-997b-45f9-a0a4-f22ea064265b

Otherwise I think we are maybe good?!

Proof of testing

Step 1:
<img width="543" alt="Screenshot 2024-09-17 at 14 17 47" src="https://github.com/user-attachments/assets/434f8db6-6dfe-4092-841f-c5bcc01a633f">

Step 2:
<img width="684" alt="Screenshot 2024-09-17 at 14 18 32" src="https://github.com/user-attachments/assets/54f02080-e8f1-4c1f-a27e-54e0e8af3915">

Step 3:
No screenshot

Step 4:
<img width="678" alt="Screenshot 2024-09-17 at 14 32 39" src="https://github.com/user-attachments/assets/6e12a3c1-fac8-4bc8-b785-ccbeb28619f2">

Step 5:
<img width="676" alt="Screenshot 2024-09-17 at 14 33 12" src="https://github.com/user-attachments/assets/19a3175b-53cd-478e-92fe-80b765836f4a">

Step 6:
Has an issue

Step 7:
<img width="681" alt="Screenshot 2024-09-17 at 14 34 37" src="https://github.com/user-attachments/assets/42d98786-2783-44a5-bd7f-17e87fb03a1e">

Step 8:
<img width="674" alt="Screenshot 2024-09-17 at 14 35 31" src="https://github.com/user-attachments/assets/1f7e2dd9-cc24-42c6-978e-8beca54fbe7e">

Step 9:
<img width="683" alt="Screenshot 2024-09-17 at 14 39 41" src="https://github.com/user-attachments/assets/0eb59835-c2ed-44ac-baf6-619903112552">

Step 10:
<img width="676" alt="Screenshot 2024-09-17 at 14 40 40" src="https://github.com/user-attachments/assets/ab1ddf69-aeeb-4121-90ad-84b0ee35d57f">

Step 11:
<img width="673" alt="Screenshot 2024-09-17 at 14 41 04" src="https://github.com/user-attachments/assets/e7dd524a-d0e2-4a4d-99c2-4666c9da1b6b">

Step 12:
<img width="683" alt="Screenshot 2024-09-17 at 14 41 36" src="https://github.com/user-attachments/assets/e9183878-255d-487c-ab7b-0c1b8cff03d1">
<img width="1060" alt="Screenshot 2024-09-17 at 14 41 53" src="https://github.com/user-attachments/assets/c9636f6a-150b-477d-87b8-a3f85ff02a40">

Step 13:
<img width="603" alt="Screenshot 2024-09-17 at 14 42 42" src="https://github.com/user-attachments/assets/7077f41e-e3ab-4728-8df9-66d85e3f7811">
<img width="583" alt="Screenshot 2024-09-17 at 14 42 56" src="https://github.com/user-attachments/assets/ddb5e37c-6210-4221-ac17-5f125ba9c055">
<img width="597" alt="Screenshot 2024-09-17 at 14 43 06" src="https://github.com/user-attachments/assets/464d68f2-81af-43b4-b9bd-5c5bc21e8c26">

Step 14:
<img width="1060" alt="Screenshot 2024-09-17 at 14 45 05" src="https://github.com/user-attachments/assets/fa180abe-cf8c-47dd-ae06-3087c4f4e15c">
<img width="670" alt="Screenshot 2024-09-17 at 14 45 31" src="https://github.com/user-attachments/assets/5b47cb51-7530-4c2c-ae0a-88d92793416d">
<img width="677" alt="Screenshot 2024-09-17 at 14 45 51" src="https://github.com/user-attachments/assets/39a411b2-7033-40e5-94f3-6af82007fb88">
<img width="672" alt="Screenshot 2024-09-17 at 14 52 46" src="https://github.com/user-attachments/assets/ddc648b2-4d7e-4c2e-98f4-cf7173260e2b">

2024-09-19 07:33 UTC, rdig requested changes
So codewise this is all good. You deserve praise for just having to deal with this mess of components.

I've ran the setup phase, as well as all the test steps, but cannot replicate test steps: 10, 12, 13 and 15

I suspect their parameters changed through all the subsequent changes you've made to the PR and the description was not updated.

If that's the case, just let me know, and I'll re-run those steps with the new instructions.

**Setup phase:**

![Screenshot from 2024-09-19 09-51-28](https://github.com/user-attachments/assets/68c7a134-2bd7-472c-84d0-82db231e4be9)
![Screenshot from 2024-09-19 09-52-04](https://github.com/user-attachments/assets/c539f30d-6c94-4f5e-aaa3-21083911cada)
![Screenshot from 2024-09-19 09-52-34](https://github.com/user-attachments/assets/c1946810-e36e-4f89-a623-f53001d04b9a)
![Screenshot from 2024-09-19 09-53-22](https://github.com/user-attachments/assets/bc399f85-ee3a-413a-8660-c8736f4816d4)
![Screenshot from 2024-09-19 09-54-41](https://github.com/user-attachments/assets/97985a7b-71aa-40a2-8436-a2fab3007ad9)

**Test 1:**

![Screenshot from 2024-09-19 09-56-44](https://github.com/user-attachments/assets/7a6ed6ab-573e-422e-9051-92ec19aca2fa)
![Screenshot from 2024-09-19 09-57-02](https://github.com/user-attachments/assets/ad640aab-4608-470d-a387-607b51a4b221)

**Test 2:**

![Screenshot from 2024-09-19 09-59-48](https://github.com/user-attachments/assets/abb33b77-7cac-404c-8462-50cc7b14f45b)

**Test 3:** 

![Screenshot from 2024-09-19 10-01-55](https://github.com/user-attachments/assets/c2d8d8bc-999f-4f23-8e56-ccccb76e10db)
![Screenshot from 2024-09-19 10-02-00](https://github.com/user-attachments/assets/10c16b68-adb6-4af0-8263-0bbf206e5b1f)
![Screenshot from 2024-09-19 10-02-06](https://github.com/user-attachments/assets/9c2a91e6-b938-466d-b164-d9b7b56734bd)

**Test 4:**

![image](https://github.com/user-attachments/assets/757ac139-81ae-4e9a-ab58-2e9cfddb2121)

**Test 5:**

![image](https://github.com/user-attachments/assets/044e8f6c-5833-4842-aa52-71afb1234ef7)

**Test 6:**

![image](https://github.com/user-attachments/assets/f31e2a48-74d3-4fe8-b5ef-f99c4acb20cc)

**Test 7:**

![image](https://github.com/user-attachments/assets/77f1106a-5f91-450c-a392-e498608364bd)

**Test 8:**

![image](https://github.com/user-attachments/assets/2f9e21ac-8935-47a5-96a4-ee0709d78382)

**Test 9:**

![image](https://github.com/user-attachments/assets/aa3849a2-4f6f-41c4-8b2e-0a8269a9848e)

**Test 10:**

**Cannot replicate!**: No error message shows up

![image](https://github.com/user-attachments/assets/f7a71c82-4350-4850-93a4-4ebd3556f402)

**Test 11:**

![Screenshot from 2024-09-19 10-13-05](https://github.com/user-attachments/assets/9bfacd49-edf1-459d-92a2-93c192dc8d7f)
![Screenshot from 2024-09-19 10-13-10](https://github.com/user-attachments/assets/9999b833-1f8b-4672-bc53-d0919ff135cf)

**Test 12:**

**Cannot replicate!**: Getting an error, preventing me from submitting the form

![image](https://github.com/user-attachments/assets/78085179-e8ab-4f6e-9a8e-c5a7c361d97f)

**Test 13:**

**Cannot replicate!**: I was able to submit the form / modal

![image](https://github.com/user-attachments/assets/9df71157-7032-4008-a458-f923747d5993)
![image](https://github.com/user-attachments/assets/0e99e649-dca6-4796-a1d3-9dc48e716e15)
![image](https://github.com/user-attachments/assets/83625f36-1037-4859-9481-b7b6f15e3b36)

**Test 14:**

![image](https://github.com/user-attachments/assets/5b41cefe-17bb-45bf-9019-df6a7a08a844)
![image](https://github.com/user-attachments/assets/8ed98193-924d-42e1-8914-f823e0df4b9d)
![image](https://github.com/user-attachments/assets/904abd58-ac1e-4de5-bcc8-c807905f6655)
![image](https://github.com/user-attachments/assets/5150efc6-49ef-4f2c-895c-f214709483e5)
![image](https://github.com/user-attachments/assets/b3f3d969-0ca5-4cbe-ae07-379c8f73b453)
![image](https://github.com/user-attachments/assets/1d9cd3ed-8184-4a39-97e2-1963131fa767)

**Test 15:**

**Cannot replicate**: Cannot switch off the Architecture toggle

![image](https://github.com/user-attachments/assets/7e987979-0642-44ac-83ae-02840abb59ef)

2024-10-25 10:14 UTC, rumzledz commented
Hey @rdig! I forgot to mention that I retested steps 10, 12, 13 & 15 yesterday before rebasing and I was able to do them. I've rebased yesterday, retested and I'm still able to do them. Hopefully you'll be able to see it working again when you retest 🤞

2024-10-25 12:35 UTC, iamsamgibbs submitted a review, later dismissed
Great job dealing with all of this @rumzledz ! Let's get it merged!

The only weird behaviour I've noticed is the validation on the permissions field disappearing when the title is updated, but I think this can be addressed as a separate issue.

https://github.com/user-attachments/assets/8b9edd74-45af-4d75-baa6-e29f130c7821

I did a tiny bit of multi-sig testing and it seems like there are no issues there:

https://github.com/user-attachments/assets/a298a07c-69e5-4e7f-80e6-fde91035acd2

I did screenshot and record all of the testing steps, but I won't dump them all here as it'll end up as a huge reply, but all the testing steps work as expected.

Great job! I can't believe this form will finally be fixed forever once this is merged and there will never be another issue with it again! :)

2024-10-25 16:55 UTC, Nortsova approved these changes
Hey @rumzledz 🙌  Thank you for this huge PR and really good described test cases. It was a pleasure to review this one 😃  I can't wait to have it merged 🎉  

I tested it both regular and Multi-sig. There are a tiny comments in the bottom of this review, but I would be happy if we can create separate tickets for that (if it is a bug actually). 

Thank you so much for your work 🙌 

#2 Remove permissions error:
<img width="684" alt="image" src="https://github.com/user-attachments/assets/73d6671c-bcef-4c66-9f11-0147a7395ce1">

#3. After selected fry and general "Remove permissions" selection was still present, error was there:
<img width="694" alt="image" src="https://github.com/user-attachments/assets/b276c2d1-d271-417c-83b5-ef12261203d9">
I tried the same with leela who has a permissions in general and error disapeared: 
<img width="675" alt="image" src="https://github.com/user-attachments/assets/628214b6-1a6a-4c8d-ad53-86aa96dae32d">

#4, 6 Fry is Owner in General
Here is removing permissions error in child domain: 
<img width="688" alt="image" src="https://github.com/user-attachments/assets/b034eb23-1f34-48dc-8fff-d44d488b335d">

And downgrading role:
<img width="690" alt="image" src="https://github.com/user-attachments/assets/b5aa5ae9-53e0-4fca-a091-c0abd2c17b66">

#5 Upgrading role error:
<img width="699" alt="image" src="https://github.com/user-attachments/assets/9dc28a57-0008-45e2-9b0f-a50937be8da4">

#7 The same role error:
<img width="720" alt="image" src="https://github.com/user-attachments/assets/d78060d3-c40d-4179-8ee4-0f3313756628">

#8 User have custom permissions in parent domain:
<img width="689" alt="image" src="https://github.com/user-attachments/assets/01a26bba-90a7-4726-a2f5-6188669a7e20">

#9 Downgrading when user has Custom in parent domain:
<img width="682" alt="image" src="https://github.com/user-attachments/assets/773b9746-ecf9-41f4-991f-6de0f13bdda6">

#10 The same Custom permissions in parent domain:
<img width="677" alt="image" src="https://github.com/user-attachments/assets/495576a7-1710-4126-81d9-32ad1c74b21f">

#11 Toggle tooltip: 
<img width="677" alt="image" src="https://github.com/user-attachments/assets/4fb31c85-15d2-45c4-b0ed-cee87b6707a1">

#12 removing permissions from amy who doesn't have inherited permissions
<img width="681" alt="image" src="https://github.com/user-attachments/assets/74e20649-b5ac-44c2-a198-e65341354d8a">
No "Redo" button:
<img width="993" alt="image" src="https://github.com/user-attachments/assets/cef105a4-5394-495b-afcc-4c27d897b0e2">

#13 Remove Root permission from fry by toggling off this permission in Custom:
<img width="1506" alt="image" src="https://github.com/user-attachments/assets/07f8d6a8-5824-40dc-aa87-59fe2c49bf61">
Selected Admin role (downgrade) 
<img width="1559" alt="image" src="https://github.com/user-attachments/assets/82e03de5-7d20-4f67-b2b1-9626dc84af7e">

#14 Before I submited form the copy underneath the Action title was "Assign Admin permissions for diana-dynamo in Andromeda by leela", after I submitted Action Completed form says "Assign Custom permissions for diana-dynamo in Andromeda by leela" 
<img width="721" alt="image" src="https://github.com/user-attachments/assets/6aefbf05-d358-4f08-91a9-c2ced73f7097">
p.s. Admin role is correct here because I already added "Architecture" permission to her.

Redo says Payer:
<img width="690" alt="image" src="https://github.com/user-attachments/assets/9581bc74-b4e3-40a8-aca3-6bc8da8411e2">

#15 Completed actions toggles are correct:
<img width="675" alt="image" src="https://github.com/user-attachments/assets/d718945a-fbf2-413a-af9e-245e023d1b40">





-------------
I don't know if this was intended, but here the case where Remove Permissions doesn't call modal:
Fry is Owner in General
Select Custom
Toggle off Root (submit)
Come back to this form ("Redo" button)
Select "Remove permissions"
Submit (No modal shows)

The same was happen in this case:
Fry Owner in General
Downgrade Fry to admin in General (submit) - Warning modal is shown
Press "Redo"
Downgrade to Payer - No modal

One more thing, I would propose to update styles for disabled Custom permissions: 
<img width="400" alt="image" src="https://github.com/user-attachments/assets/2c292da4-b19d-49c2-ac2b-480df58eccb9">

2024-10-28 13:51 UTC, mmioana approved these changes
Awesome work and a great deal of effort on this one @rumzledz 👏 🥇 

Went through all your well documented testing steps and can confirm everything works as expected

`Setting up the dev env`

![Screenshot 2024-10-28 at 13 58 01](https://github.com/user-attachments/assets/34344b1f-25c4-435d-970c-66a3eec8fb31)
![Screenshot 2024-10-28 at 13 58 40](https://github.com/user-attachments/assets/326ad4e4-d193-4a00-b40d-d654c303c8fd)
![Screenshot 2024-10-28 at 13 59 14](https://github.com/user-attachments/assets/ef68a700-0074-4793-a7e1-3cba89b6aae9)
![Screenshot 2024-10-28 at 13 59 53](https://github.com/user-attachments/assets/80a5610b-288a-4d86-b5e6-9a0e76d6d282)
![Screenshot 2024-10-28 at 14 00 39](https://github.com/user-attachments/assets/a7972539-f80c-4a80-8fb2-f72a0baec7b1)

1. Selecting Remove Permissions for a member who has permissions for the selected team (Fry)
![Screenshot 2024-10-28 at 14 01 57](https://github.com/user-attachments/assets/313a81f7-8a7b-4e29-9e9e-3ec584c85336)
![Screenshot 2024-10-28 at 14 02 01](https://github.com/user-attachments/assets/3b9735dc-70ad-42b5-b0b4-1cd9ac6daadc)

2. Selecting Remove Permissions for a member who does not have permissions for the selected team (jasmine-jolt)
![Screenshot 2024-10-28 at 14 03 06](https://github.com/user-attachments/assets/16246534-ba3d-4dce-8571-ca97e570d602)

3. Checking that the Remove permission option persists when changing the Team & Member fields (Fry)


https://github.com/user-attachments/assets/23f1ed55-c767-498a-9a7b-133fca694215

4. Removing permissions from someone who has inherited permissions from the Parent domain (Fry)
![Screenshot 2024-10-28 at 14 04 36](https://github.com/user-attachments/assets/2975f31e-e50c-40e6-acf2-8ea7e090b1ca)

5. Upgrading a user's role, when the user has an inherited role (alex-the-ace)
![Screenshot 2024-10-28 at 14 05 46](https://github.com/user-attachments/assets/ce10a078-22c3-441e-b2bd-f04b54b7812d)

6. Downgrading a user's role, when the user has an inherited role (alex-the-ace)
![Screenshot 2024-10-28 at 14 06 02](https://github.com/user-attachments/assets/ca851dd7-01fd-4059-82be-255433b62c40)

7. Applying the same inherited role for a user (alex-the-ace)
![Screenshot 2024-10-28 at 14 06 24](https://github.com/user-attachments/assets/3027e2cd-53ba-4af1-9bea-5c87917fe735)

8. Upgrading a user's role, when the user has inherited Custom permissions (diana-dynamo)
![Screenshot 2024-10-28 at 14 06 47](https://github.com/user-attachments/assets/97d998f6-7dbb-43c3-8a0a-b895e945818b)

9. Downgrading a user's role, when the user has inherited Custom permissions (diana-dynamo)
![Screenshot 2024-10-28 at 14 07 03](https://github.com/user-attachments/assets/f88e93af-34ff-4303-9d83-e6cd27303449)

10. Applying the same inherited permissions for a user (diana-dynamo)

https://github.com/user-attachments/assets/a5cd1af1-d350-4b57-bd48-a8febfbd9aee

11. Checking if the inherited permission toggles are disabled (diana-dynamo)

https://github.com/user-attachments/assets/f68357f4-49f1-408e-8a49-60744e526f6b


12. Removing Root permissions from someone who does not have inherited permissions from a Parent domain (Amy)
![Screenshot 2024-10-28 at 14 09 15](https://github.com/user-attachments/assets/8aaa5d88-4388-49fe-a06e-f3af37d88df4)
![Screenshot 2024-10-28 at 14 09 31](https://github.com/user-attachments/assets/85544827-0135-41b8-9e3b-2dfc4e147069)
![Screenshot 2024-10-28 at 14 09 45](https://github.com/user-attachments/assets/102cd354-2510-4154-9d11-e5d776ee8a0f)

13. Removing Root permissions from someone in a Parent domain (Fry)
![Screenshot 2024-10-28 at 14 10 29](https://github.com/user-attachments/assets/cae8990f-8895-4b8d-9036-f957d2e62163)
![Screenshot 2024-10-28 at 14 10 34](https://github.com/user-attachments/assets/4a34a62d-f34a-4aa5-9063-876880bb903b)
![Screenshot 2024-10-28 at 14 10 43](https://github.com/user-attachments/assets/2488287f-0358-42e3-a291-7fdc4b164dee)
![Screenshot 2024-10-28 at 14 11 24](https://github.com/user-attachments/assets/af021417-e015-41ed-afd3-cbc0c7bb24eb)
![Screenshot 2024-10-28 at 14 12 56](https://github.com/user-attachments/assets/15c5ad6f-cfe8-4d4e-ad84-ae0670286777)
![Screenshot 2024-10-28 at 14 13 08](https://github.com/user-attachments/assets/30f68f79-9a89-409c-b466-ec415594c869)
![Screenshot 2024-10-28 at 14 13 15](https://github.com/user-attachments/assets/eec80c95-500c-4fb1-bf08-8701e60d9f13)

14. Upgrading Custom permissions to a Role (diana-dynamo)

![Screenshot 2024-10-28 at 14 13 54](https://github.com/user-attachments/assets/c10440b9-db14-4ffd-a0bc-fc791ec57904)
![Screenshot 2024-10-28 at 14 13 59](https://github.com/user-attachments/assets/6954c8f4-edc4-48b8-a4e4-b1354ac0a109)
![Screenshot 2024-10-28 at 14 14 18](https://github.com/user-attachments/assets/1177a6bd-e206-43b2-a0da-d38ef529bf8c)
![Screenshot 2024-10-28 at 14 14 39](https://github.com/user-attachments/assets/6692e43f-5eec-4819-8987-86192cc00080)
![Screenshot 2024-10-28 at 14 14 57](https://github.com/user-attachments/assets/6006dfcd-2b4d-47d5-96d7-288909d819ad)
![Screenshot 2024-10-28 at 14 15 20](https://github.com/user-attachments/assets/d18963c5-d6d9-40cd-8a3d-7327a694da7f)

https://github.com/user-attachments/assets/738f3c19-1c2c-4b0b-ab0d-c2a02ada882d

15. Checking the disabled state of Permissions toggles in the Completed Action component (eddy-edge)
![Screenshot 2024-10-28 at 14 16 05](https://github.com/user-attachments/assets/fdd5ef24-ecb8-4bbf-94f8-174442d95efd)
![Screenshot 2024-10-28 at 14 16 53](https://github.com/user-attachments/assets/a4db8a0e-57cd-4249-b060-83e92bddbb95)


Left a small refactoring comment, but that can be treated as a separate issue/improvement 👍 @rumzledz

2024-10-28 13:51 UTC, mmioana commented on src/utils/strings.ts
I'm wondering if it would make sense to make use of `react-intl` pluralisation feature and also create a message descriptor for the `and`?

2024-10-28 16:13 UTC, mmioana commented on src/components/v5/common/ActionSidebar/hooks/useActionFormProps.ts
> +    onSuccess: () => {},
Please add `noop` here

2024-10-28 17:32 UTC, iamsamgibbs approved these changes
Gone through most of the testing steps again since the rebase and all still working well! 🚢

2024-10-28 19:57 UTC, rdig approved these changes
Retested all the steps that I couldn't before and everything now works as you laid out in your testing plan. Very nice.

Thank for your patience and determination to see this to the end.

:100: 

**Setup Phase**

![Screenshot from 2024-10-28 21-43-17](https://github.com/user-attachments/assets/0ba21925-9db9-4bf1-9981-685f338b1d0f)
![Screenshot from 2024-10-28 21-43-48](https://github.com/user-attachments/assets/6812d82f-4b21-4595-8fa3-da252071b1b1)
![Screenshot from 2024-10-28 21-44-30](https://github.com/user-attachments/assets/0b7d3f56-7f1f-488e-af69-295273df985e)
![Screenshot from 2024-10-28 21-45-13](https://github.com/user-attachments/assets/1eb8ebf0-38d9-4c84-9313-7fc13e1954ce)
![Screenshot from 2024-10-28 21-45-58](https://github.com/user-attachments/assets/24080595-500a-437d-8cf6-245df33633f2)

**Test 10**

![Screenshot from 2024-10-28 21-48-16](https://github.com/user-attachments/assets/c21d5e01-43ed-42b0-b4c8-9dc4b386b619)
![Screenshot from 2024-10-28 21-48-26](https://github.com/user-attachments/assets/24003f59-9549-4b0c-a10c-ff823df36cb5)

**Test 12**

![Screenshot from 2024-10-28 21-49-51](https://github.com/user-attachments/assets/f8754341-9e76-4147-aea0-2cd5b9ca293e)
![Screenshot from 2024-10-28 21-50-01](https://github.com/user-attachments/assets/a2170ba8-5d68-40b9-a15d-3f814005a15f)

**Test 13**

![Screenshot from 2024-10-28 21-50-47](https://github.com/user-attachments/assets/2b538490-eebf-4bd5-98d9-8b64eddb4dbe)
![Screenshot from 2024-10-28 21-51-15](https://github.com/user-attachments/assets/0fef12f4-007b-4915-b1c2-3c8050491c28)
![Screenshot from 2024-10-28 21-51-29](https://github.com/user-attachments/assets/b86b7d9a-7d8b-44da-9b09-ce65f560a79c)
![Screenshot from 2024-10-28 21-51-46](https://github.com/user-attachments/assets/794197bc-3ae0-4b12-8b62-6d13e5aed114)

**Test 15**

![Screenshot from 2024-10-28 21-54-20](https://github.com/user-attachments/assets/ae5d1a7b-e1de-43e0-b56b-cce4b08a71ff)

2024-10-28 20:41 UTC, Nortsova approved these changes
I did small retest and it seems it still working as expected 👍 

Lest merge 🎉  🥳

2024-10-29 09:48 UTC, merged