[Multi-sig] feat: allow failing multi-sig if a week has passed and realign all dates with the blockchain
JoinColony/colonyCDapp pull request #2763
Opened 2024-07-24 08:51 UTC by bassgeta

## Description

Instead of calling `executeWithoutFailure` we need to call `execute` if a week has passed since the motion was created.
Additionally, I've realigned multisig's createdAt date with the blockchain date.
[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/257)
[Figma link](https://www.figma.com/design/SaO0Zj6e7yGqLzjEsxqVhy/Permissions?node-id=22256-71198&t=2x9d7EMZkK6MCGCF-4)
![image](https://github.com/user-attachments/assets/8be9ef0a-98a8-41dc-ab2c-332db6354dc3)

## Testing

You can do all of this as just `leela` (but for testing the rejection timestamp, you need to assign `amy` the `Owner` multi-sig role, and reject the motion as both `leela` and `amy`)

1. Install the multisig extension, you can leave the threshold as is. Assign `leela` Multi-sig owner permissions
2. Go to the balances page, choose `Andromeda` and note the amount of CREDS it has
![image](https://github.com/user-attachments/assets/75dab481-c839-478d-bab8-7f426f78effa)
3. Create a transfer funds multisig motion, moving all but 20 CREDS from `Andromeda` to `General`
![image](https://github.com/user-attachments/assets/c69bf1e2-607b-4a1f-85c7-6c19f19b524e)
4. As `leela` move ~50 CREDS from Andromeda to General using permissions
![image](https://github.com/user-attachments/assets/4f96cd28-6946-4470-999f-d9cebf526261)
5. Open the previous motion from the activity table and finalize it. It should error out since the action can't complete due to a lack of funds
![image](https://github.com/user-attachments/assets/82ad7714-dd72-496c-98fc-574bd2c10ba3)
6. Now for the tricky part! Forward time for about a week by running `npm run forward-time 170`. Note that when going back to the `Approval` step, it should display the 7 days have passed disclaimer
![image](https://github.com/user-attachments/assets/ea6c21a4-a308-4452-b1d6-5d814a57a310)

7. Open up the multisig motion again from the activity table and click `Finalize`. The action should fail and this screen should show up
![image](https://github.com/user-attachments/assets/cd8139f8-9a34-40a0-af6e-8df52e89ce28)

Additionally check that when a motion is successfully passed, the blockchain timestamp appears
![image](https://github.com/user-attachments/assets/8036062e-b6ec-4abd-b6fa-2e9ccbcc3c2e)

Same for rejection
![image](https://github.com/user-attachments/assets/d40991a4-11c6-45c2-8c50-a8a0ceb7030a)

## Diffs

**New stuff** ✨

* Display new rows if motion was executed but the actions hasn't passed

**Changes** 🏗

* If motion is older than a week, we call `execute` instead of `executeWithoutFailure`

Contributes to #2658

2024-07-24 15:12 UTC, mmioana approved these changes
Rocked another one @bassgeta 🚀 

Tested the flow you described and works like a charm
![Screenshot 2024-07-24 at 17 04 52](https://github.com/user-attachments/assets/ccf7412b-2c1c-4e86-a88e-b90c309e2411)
_Ignore I didn't change the action title for the Transfer funds with Permissions_
![Screenshot 2024-07-24 at 17 04 42](https://github.com/user-attachments/assets/371c0e36-6fd1-475a-9628-a9ec282d911d)
![Screenshot 2024-07-24 at 17 06 43](https://github.com/user-attachments/assets/08aac7b3-3908-4e3f-852d-122863867e6b)
![Screenshot 2024-07-24 at 17 07 29](https://github.com/user-attachments/assets/bfd07820-7143-4be1-b562-4235157d7788)

2024-07-24 21:08 UTC, rdig approved these changes
Nice work here, went through the whole process with two users and it works as expected.

![Screenshot from 2024-07-25 00-00-50](https://github.com/user-attachments/assets/83bce918-be05-43b1-9cdc-67bb3a079988)
![Screenshot from 2024-07-25 00-01-37](https://github.com/user-attachments/assets/bff16848-fcf9-4cf4-88e4-9d1f2ca1a494)
![Screenshot from 2024-07-25 00-02-01](https://github.com/user-attachments/assets/51e2a0db-e25e-43a7-bd9d-691d639937f1)
![Screenshot from 2024-07-25 00-02-58](https://github.com/user-attachments/assets/d89eaa56-91f3-4ca5-804b-64ae107e8566)
![Screenshot from 2024-07-25 00-03-57](https://github.com/user-attachments/assets/7c2a57a3-39bd-44b0-9755-c31adada05af)
![Screenshot from 2024-07-25 00-03-54](https://github.com/user-attachments/assets/b255245a-ebe1-463e-93a3-cbd97d8ad2ca)
![Screenshot from 2024-07-25 00-04-09](https://github.com/user-attachments/assets/a80cbc30-671e-4f46-994f-2dab85836b4f)
![Screenshot from 2024-07-25 00-04-35](https://github.com/user-attachments/assets/9e41b8a2-1bd7-4718-888e-aa7f6b23b82e)
![Screenshot from 2024-07-25 00-04-59](https://github.com/user-attachments/assets/2bc11175-9979-4547-a54b-5166ea192415)

However you last step, `8` says that the action **should fail** when in fact it should succeed. Did you mean `shouldn't` instead of `should` ?

> Open up the multisig motion again from the activity table and click Finalize. The action should fail and this screen should show up

2024-07-24 22:54 UTC, jakubcolony requested changes
Cool stuff, the functionality works as expected, however I'm requesting changes because the check is using system time (through JS Date) instead of the current block time (fetched from `useCurrentBlockTime` hook). 

In prod the two timestamps will be fairly close but in dev the local block time is a few weeks/months ahead. 

It was not something introduced strictly in this PR, so if you prefer to handle it in a separate issue give me a shout and I will approve this one

2024-07-26 06:55 UTC, mmioana approved these changes
Checked again and it seems to be working properly ✨ cool work @bassgeta 

<img width="1324" alt="Screenshot 2024-07-26 at 08 46 02" src="https://github.com/user-attachments/assets/e382a847-ed99-4e0f-ad08-90bb44df2aff">
<img width="1068" alt="Screenshot 2024-07-26 at 08 46 34" src="https://github.com/user-attachments/assets/a2315f73-3d68-4fa9-820c-720379e40aaa">
<img width="1074" alt="Screenshot 2024-07-26 at 08 47 06" src="https://github.com/user-attachments/assets/26d9b4fc-477f-4aac-a8e8-32d71c69ce84">
<img width="1026" alt="Screenshot 2024-07-26 at 08 47 48" src="https://github.com/user-attachments/assets/9071e307-763b-49af-b608-a3f76e6aaf8e">
<img width="1058" alt="Screenshot 2024-07-26 at 08 48 34" src="https://github.com/user-attachments/assets/dd8721f6-9b9c-47ac-8cc4-24d564a52cbd">
<img width="358" alt="Screenshot 2024-07-26 at 08 48 43" src="https://github.com/user-attachments/assets/6c0e7bc8-9e25-4f4b-a188-d03f38736e7a">
<img width="1053" alt="Screenshot 2024-07-26 at 08 53 52" src="https://github.com/user-attachments/assets/aa36fb9e-31f1-4186-bc3d-ca86effffc0b">

2024-08-02 13:35 UTC, iamsamgibbs requested changes
Nice work on this! It's very nearly there. Good job fixing up the timestamps.

I followed the testing steps almost without issue. The only things I noticed:

This wording is incorrect, the action was approved but couldn't be executed.

<img width="1060" alt="Screenshot 2024-08-02 at 14 27 13" src="https://github.com/user-attachments/assets/457c776a-994d-4152-8d78-8f08a5b1ce05">

The 'Finalize approve' button sticks on "pending" if the transaction fails:

https://github.com/user-attachments/assets/e4be2ab1-7afb-4ef3-9c37-fc34c4a3107d

This could be addressed as a separate issue if you want to just get this merged.

2024-08-02 13:41 UTC, davecreaser requested changes
Nice work @bassgeta! Code looks all good.

Tested and it's all working as expected too. Only requesting changes for a tiny copy change, as I think it could be really confusing for users:

<img width="1920" alt="Screenshot 2024-08-02 at 14 25 34" src="https://github.com/user-attachments/assets/d9742d96-fee3-4238-883c-1c780360c357">
<img width="1920" alt="Screenshot 2024-08-02 at 14 36 06" src="https://github.com/user-attachments/assets/5aed4fef-80ac-4e44-b36a-243eae02055d">
<img width="1920" alt="Screenshot 2024-08-02 at 14 37 33" src="https://github.com/user-attachments/assets/ca235806-e188-4113-a637-75d63b75e633">

In that third screenshot, the title says `Action was approved and executed.` and then below it says not executed. I think the title should probably say something along the lines of `Action was approved but not executed.`. Other than that, all good! 📈

2024-08-02 13:42 UTC, davecreaser commented
Lol, @iamsamgibbs beat me to it 😆 Basically, what he said ^ ;)

2024-08-05 09:41 UTC, iamsamgibbs requested changes
Thanks for the changes!

Appears the issue with the 'Finalize approve' button sticking on "pending" if the transaction fails has been resolved (either by yourself or the rebase!)

The updated copy looks good:

<img width="330" alt="Screenshot 2024-08-05 at 10 32 40" src="https://github.com/user-attachments/assets/d791428a-0586-4d24-97e9-1935b0af436b">

I've got one tiny issue with a missing translation string, then it is good to go!
 
<img width="411" alt="Screenshot 2024-08-05 at 10 31 40" src="https://github.com/user-attachments/assets/9f13477a-c412-4990-9602-742f087448dc">

2024-08-05 11:02 UTC, iamsamgibbs approved these changes
I've not booted it up, but the change looks good to me!

2024-08-05 11:09 UTC, merged