fix: missing translation for UserHub
JoinColony/colonyCDapp pull request #2772
Opened 2024-07-25 11:21 UTC by Nortsova

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-07-25 11:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=2772) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=2772) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=2772) it.</sub>

2024-07-29 09:46 UTC, bassgeta approved these changes
Nice little fix, tested it out and I can see the transaction in user hub
![image](https://github.com/user-attachments/assets/d1351f33-1dc4-4a5d-a342-2925f4381cc9)
Clicking on it also redirects me to it:
![image](https://github.com/user-attachments/assets/d5ffba1b-5fa8-49e3-9044-baefa373e1b8)

Just dropped a minor comment, feel free to address it or not :)

2024-07-29 09:46 UTC, bassgeta commented on src/graphql/fragments/expenditures.graphql
> +  actions(filter: { type: { eq: CREATE_EXPENDITURE } }) {
maybe to keep consistent with how other actions are fetched we can rename this field to `creatingActions`?

2024-07-29 09:57 UTC, iamsamgibbs approved these changes
Nice work! Tested and working as expected. Both stakes open the correct transactions.

<img width="670" alt="Screenshot 2024-07-29 at 10 56 55" src="https://github.com/user-attachments/assets/9284c67a-0319-4d6e-8c9e-907ddb4f0a43">

2024-07-30 00:09 UTC, jakubcolony requested changes
Nice work @Nortsova! 

While reviewing, I spotted an apparent bug with stake statuses which I fixed in #2803.

All looks good in your PR, the only thing I noticed is this requirement that seems to got missed:
> * Should link to the "linked" motion view as of the design here - https://www.figma.com/design/5V8pr7iMwXsT9L3VAZsmUt/Colony-v5?node-id=24280-198587&t=21FkwrMm6ANcL8LC-4, or

Clicking on the fund expenditure motion stake does not open the motion view, just the relevant payment:

https://github.com/user-attachments/assets/7f5976dd-a10f-4c4f-ac09-07a640b88a1e

2024-07-30 12:58 UTC, arrenv commented
That is a great pickup and idea @jakubcolony, was not how I was thinking it needed to be implemented, and would have expected it to just go to the current active step. So, your suggestion allows the user to go to the specific motion and claim their staked funds, which makes sense.

In saying that, if it is a lot of work to make it work as you have described, then I think it should be fine to leave it as it currently is. The user is still able to claim from their Userhub. @Nortsova may be able to comment on how much work could be involved.

2024-07-30 14:00 UTC, jakubcolony approved these changes
Thanks for clarification @arrenv. 

It is a more substantial amount of work to make the stake open the relevant expenditure motion, so I think it makes sense to keep it as a separate issue.

Regarding this PR, great work @Nortsova, LGTM 👍

2024-07-30 16:20 UTC, merged