Fix: Auto-populate the Role and Permissions fields in the Manage Permissions form
JoinColony/colonyCDapp pull request #2773
Opened 2024-07-25 16:50 UTC by rumzledz

## Description

This is just a tiny fix that brings back the auto-populate behaviour for the Roles and Permissions fields in the Manage Permissions form which got affected in the recent rebase.

## Testing

> [!NOTE]
> I think the only difference now is before we can determine the role for a user, we also need to provide the Authority information.
>
> I am not very familiar with this new flow where we also take into account the Multi-Sig Authority for a user. These steps are ported over from #2565. Please let me know if my test steps needs updating.

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

> [!IMPORTANT]
> - Make sure user Leela still has Owner permissions for team General
> - Remove all permissions for user Fry from team Andromeda

### 1. Non-submitted Form Flow
| Steps | Expected Result |
| ---- | ---- |
| 1. Set Member field to leela | |
| 2. Set Team field to General | |
| 3. Set a value for the Authority field | - The permissions field is automatically set to Owner<br />- No error message is shown for permissions |
| 4. Set Permissions to Custom | - The Permission toggles are automatically set<br />- No error message is shown for permissions |
| 5. Set Member to Fry | |
| 6. Set Team to Andromeda | - No error message is shown for permissions |

###  2. Submitted Form Flow

| Steps | Expected Result |
| ---- | ---- |
| 1. Set Member to Fry | |
| 2. Set team to Andromeda | |
| 3. Set a value for the Authority field | |
| 4. Set Permissions to Custom | |
| 5. Submit the form | Error message: "You have to enable at least one permission" |
| 6. Set Permissions to Custom | - The Permission toggles are automatically set<br />- No error message is shown for permissions |
| 7. Switch on at least 1 Permission | The Permissions error message disappears |
| 8. Turn off all Permission toggles AND **do not** submit the form | Error message: "You have to enable at least one permission" |
| 9. Set Member to leela | |
| 10. Set Team to General | - The permission toggles are automatically set<br />- Error message: "This user already has these permissions" |
| 11. Switch off 1 Permission toggle | The Permissions error message disappears |
| 12. Turn on all Permission toggles AND **do not** submit the form | Error message: "This user already has these permissions" |
| 13. Set Permissions to Admin | The Permissions error message disappears |
| 14. Set Permissions to Owner | Error message: "This user already has these permissions" |

### Redo Action Flow

> [!IMPORTANT]
> 1. Give Fry the Admin role in team Andromeda and submit the form
> 2. On the Completed Action form, click the meatball icon and click "Redo action"
> 3. Confirm you can see the Manage Permissions form with auto-populated fields

| Steps | Expected Result |
| 1. Submit the form | Error message: "This user already has these permissions" |
| 2. Set Permissions to Mod AND **do not** submit the form | The Permissions error goes away |
| 3. Submit the form | The form is successfully submitted |
| 4. Bring up the Manage Permissions form | |
| 5. Set Team to Andromeda | |
| 6. Set Member to Fry | |
| 7. Set a value for the Authority field | The Permissions field is automatically set to Mod |

11. Bring up the Action form
12. Set it to Manage Permissions
13. Set Member field to Fry
14. Set Team to Andromeda
15. Verify that the Permissions field is set to Mod
## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-07-26 10:32 UTC, bassgeta approved these changes
Nice and sensible changes, thanks for the cleanup, hopefully my rebase hasn't caused you too much of a headache :D 
Before submitting flow works :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/e81de7ab-05da-4c77-b766-39de63e21468)
![image](https://github.com/user-attachments/assets/4983a565-344d-4a62-9965-97ff3d0b8124)

Fry's flow also works:
![image](https://github.com/user-attachments/assets/770d13d3-2ca5-422b-874c-21ec7294facb)
Amy:
![image](https://github.com/user-attachments/assets/36f644b7-ed67-40bd-ab3e-f16ae7ac9115)
Fry redo:
![image](https://github.com/user-attachments/assets/c7269c54-38bb-4a41-8d0e-ba8178774a4f)

2024-07-29 09:32 UTC, iamsamgibbs requested changes
This is working for core permissions, but things are a bit broken for multi-sig permissions when redoing an action. It doesn't pick up the permission type and doesn't stop you from attempting to reassign the same permissions.

https://github.com/user-attachments/assets/0181bdd4-38ec-4457-b24e-36c0f8177949

If starting the form fresh though it does work as expected, so if you'd rather get this merged we can create a new issue for it as it isn't high priority that the redo action works 100%.

2024-07-29 11:19 UTC, rumzledz commented
> This is working for core permissions, but things are a bit broken for multi-sig permissions when redoing an action

Redo action strikes again! 😂 I think I know why @iamsamgibbs

2024-07-29 12:47 UTC, rumzledz commented
I've just pushed the fixes @iamsamgibbs , I added a new Redo action test case. Thank you!

2024-07-30 08:58 UTC, mmioana reviewed
Nice job @rumzledz 👍 

However I found a couple of issue during testing

For the Non-submitted Form Flow, if I assign an user the Owner permissions and then switch to Custom the toggles are not ON by default - is this as intended?
<img width="626" alt="Screenshot 2024-07-30 at 10 40 55" src="https://github.com/user-attachments/assets/821c1e16-ac17-4bae-8565-98d599db5add">
<img width="625" alt="Screenshot 2024-07-30 at 10 41 08" src="https://github.com/user-attachments/assets/40e95354-dda6-4e28-98c7-55cc0aefe41d">


For the Redo Action Flow (Authority to take actions via Multi-Sig)
I assigned an user the Mod permissions 
<img width="619" alt="Screenshot 2024-07-30 at 10 49 16" src="https://github.com/user-attachments/assets/2b6d08d7-bb76-4aca-bf2d-4c6fec63ea0f">
I switch to Payer permissions
<img width="624" alt="Screenshot 2024-07-30 at 10 55 05" src="https://github.com/user-attachments/assets/ef5a8a22-9742-48ea-b180-e6619fa2767b">
I select Take actions via Multi-Sig as an Authority - the Permissions is cleared up
<img width="616" alt="Screenshot 2024-07-30 at 10 55 14" src="https://github.com/user-attachments/assets/e480b62f-2667-4d04-87e6-046f22c4b3ae">
I select Payer permissions
<img width="628" alt="Screenshot 2024-07-30 at 10 55 27" src="https://github.com/user-attachments/assets/d0676cf0-9c71-4464-b02c-d008f1ec7039">
Then is I select the Takes actions on their own as authority, the permissions is set back to Mod
<img width="629" alt="Screenshot 2024-07-30 at 10 55 34" src="https://github.com/user-attachments/assets/fc137eb3-cd93-44d5-9009-d044e82e215b">

Is this as intended? 🤔

2024-07-30 09:57 UTC, rumzledz commented
Thanks for reviewing this @mmioana !

**Point 1**

> For the Non-submitted Form Flow, if I assign an user the Owner permissions and then switch to Custom the toggles are not ON by default - is this as intended?

Yep! Because the user doesn't have Owner permissions at that point. This is Prod behaviour was never a requirement in both this PR and in the PR where we have to auto-populate the role field. If we want to add yet another logic that meets your expectation, let's discuss that with product and let's do that in another ticket.

**Point 2**

> 1. For the Redo Action Flow (Authority to take actions via Multi-Sig)
> 2. I assigned an user the Mod permissions (you mean, the user already has Mod permissions at that point in the DB right?)
> 3. I select Take actions via Multi-Sig as an Authority - the Permissions is cleared up

This is a side effect of us needing to distinguish a user's role when they have the "Take actions via Multi-Sig" authority versus their role when they have the "Take actions on their own" authority. First of all, an acceptance criteria was never discussed with me when it comes to auto-populating this field and I didn't work on this. The only thing I'm fixing here is to make sure that you're not supposed to be able to resubmit the same permission set and that the original logic I implemented, whereby the role field should be auto-populated when both the Team & Member fields are set, is in tact.

If we want to address another new set of auto-populate logic that includes the Authority field, that would deserve its own ticket 👌

2024-07-30 10:23 UTC, iamsamgibbs approved these changes
Thanks for fixing the previous issue I raised.

I've followed all the testing steps and it is all working without issue!

I have found this issue which I think needs addressing (ideally before multi-sig goes up onto QA), but it can be tackled as a separate issue.

When a user has multi-sig permissions in a domain, if you try to change their permission set in the same domain, the completed action will always show it as "removing permissions" even if additional permissions are being granted.

In this example, Fry already has payer multi-sig permissions in Andromeda, and I am upgrading him to Admin multi-sig permissions.

https://github.com/user-attachments/assets/dd59bc9e-e93b-4fe7-9dd3-345330310aef

This only happens with multi-sig permissions, core permissions are fine.

2024-07-30 18:41 UTC, mmioana commented
> Thanks for reviewing this @mmioana !
> 
> **Point 1**
> 
> > For the Non-submitted Form Flow, if I assign an user the Owner permissions and then switch to Custom the toggles are not ON by default - is this as intended?
> 
> Yep! Because the user doesn't have Owner permissions at that point. This is Prod behaviour was never a requirement in both this PR and in the PR where we have to auto-populate the role field. If we want to add yet another logic that meets your expectation, let's discuss that with product and let's do that in another ticket.
> 
> **Point 2**
> 
> > 1. For the Redo Action Flow (Authority to take actions via Multi-Sig)
> > 2. I assigned an user the Mod permissions (you mean, the user already has Mod permissions at that point in the DB right?)
> > 3. I select Take actions via Multi-Sig as an Authority - the Permissions is cleared up
> 
> This is a side effect of us needing to distinguish a user's role when they have the "Take actions via Multi-Sig" authority versus their role when they have the "Take actions on their own" authority. First of all, an acceptance criteria was never discussed with me when it comes to auto-populating this field and I didn't work on this. The only thing I'm fixing here is to make sure that you're not supposed to be able to resubmit the same permission set and that the original logic I implemented, whereby the role field should be auto-populated when both the Team & Member fields are set, is in tact.
> 
> If we want to address another new set of auto-populate logic that includes the Authority field, that would deserve its own ticket 👌

No, I put these questions mostly to understand the flow, so all good from my side @rumzledz 👍

2024-07-30 18:41 UTC, mmioana approved these changes

2024-07-31 09:10 UTC, bassgeta approved these changes
Changes looking great, thanks for picking this up and also solving a pesky bug alongside it!
When assigning multi sig roles, we don't see `Remove permissions` anymore :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/dd1f121e-1b2e-40bc-a37f-242eeaa10707)
Form errors on submit trigegr for missing values :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/c7292e3b-25c0-4534-bd88-1b4825382d4e)
Redo works and I can't submit the form again
![image](https://github.com/user-attachments/assets/3de5696a-262d-4a45-bda8-cdbc7b3d32b6)
![image](https://github.com/user-attachments/assets/f5d5a54e-5d87-49ea-a740-0479bc6a1af9)
And it works if I change the roles to ordinary ones instead of Multi-Sig

And I can confirm that the bug Sam pointed out is resolved here:
![image](https://github.com/user-attachments/assets/f9863a03-86d5-4694-8589-f905d6f6fd1f)


LET'S GOOOOOO :tada:

2024-07-31 12:36 UTC, merged