Fix: Crypto-to-fiat account area UI fixes
JoinColony/colonyCDapp pull request #2798
Opened 2024-07-29 10:40 UTC by mmioana

## Description

**This PR contains UI styling changes for the Crypto-to-fiat user account page**
[Figma link](https://www.figma.com/design/C2grfQysdsYXz0j4rADR6K/Crypto-to-Fiat?node-id=1-73&t=EJ9OHTuq1tQzPvMq-0)

### KYC Personal details modal

1. Additional space is required between the close X and the stepper component to not only match Figma but make this modal consistent with global modals. 

2. Padding needs to be adjusted between the last field of the form and the button row. Also, padding needs to be adjusted between the CTA's and bottom of the modal (again, to align it globally). 

<img width="755" alt="image" src="https://github.com/user-attachments/assets/7c28740c-0088-4b0d-869e-aefe9cfec07d">

3. Error states - Can we align these closer to the copy provided in Figma for a nicer UX? 

<img width="208" alt="image" src="https://github.com/user-attachments/assets/6136ae76-4379-489a-a109-bc38ee9a4b04">

Figma:

<img width="424" alt="image" src="https://github.com/user-attachments/assets/5818439c-6c2d-4f8c-861e-e9030a2dcef6">

4. The p copy after the heading should be text-gray-600

<img width="474" alt="image" src="https://github.com/user-attachments/assets/5652b5ee-268a-4fff-9ab6-d183d8692c1e">

## KYC Terms modal

Can you please kindly adjust the modal height to accommodate the Bridge embed, so the scrollbar isn't triggered inside the modal. 

<img width="469" alt="image" src="https://github.com/user-attachments/assets/f91598b9-f21c-4125-a2e2-faf41d306d8e">

## Completing the KYC modal

Upon completion of the KYC steps and after closing the bridge modal, the UI doesn't give any feedback at all about the status of my verification or that, in fact, I've completed it. This is confusing because I think I need to go back into the KYC flow because nothing is returned. Can we have a solution here that provides the issue with an update upon the bridge modal closing without making the user refresh manually. 

<img width="1357" alt="image" src="https://github.com/user-attachments/assets/a91132d3-cfd8-4dc2-9fb0-690f8ad0f781">

## C2F page 

1. Can we add a capital O to 'Optional'? This is an error in Figma, so apologises on this. 

<img width="105" alt="image" src="https://github.com/user-attachments/assets/1eee13d5-dbda-4065-a89d-fc3170a9dc21">

2. The loading indicator is no longer centre aligned in the user account area (happy for this to be raised in a sep issue)

![Export-1721379709141](https://github.com/user-attachments/assets/3e7bbbfb-df1d-4572-98db-a1d545f651bd)

3. Approved pill is using the wrong colour tokens (looks like it's using team colours and not primary colours)

<img width="148" alt="image" src="https://github.com/user-attachments/assets/dcf6138c-0299-456c-ad0b-1d7f6b0e3944">

4. 'Bank, address and currency information' title should be a medium font weight. 
<img width="389" alt="image" src="https://github.com/user-attachments/assets/a9b1eb5f-9976-408f-a663-113b7602d5da">

## Bank details modal 

1. Same issues with regards to p colour as the KYC modal, should match Figma and be text-gray-600

<img width="506" alt="image" src="https://github.com/user-attachments/assets/da670051-1aaf-4f18-ba65-ad933a276ed8">

2. Padding between inputs should align with Figma.

<img width="480" alt="image" src="https://github.com/user-attachments/assets/dc41cd60-bd26-461a-90e5-8878f87d8e86">

3. Padding between input and the bottom of the modal (same as the KYC) should also match Figma.

<img width="532" alt="image" src="https://github.com/user-attachments/assets/f9813d35-21d2-4961-a95b-b37e38579492">
 
 4. For this modal only, please remove the stepped navigation pills and match the padding between the 'X' close and the heading to this version of the modal here: https://www.figma.com/design/C2grfQysdsYXz0j4rADR6K/Crypto-to-Fiat?node-id=5245-21254&t=bCVgC5ImOijNpbQW-4
 
 
<img width="513" alt="image" src="https://github.com/user-attachments/assets/69f41df3-badd-4ac4-a45f-ebed7641cd47">

5. This selected state for the input should match the design system component (no blue text and incorrect font size)

<img width="470" alt="image" src="https://github.com/user-attachments/assets/8c3cc185-a7ed-4c29-a930-bf084ae4b96c">
 
 
 Component link: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=2706-1485&t=MkbiMKMM96kcL0sB-4
 
 6. Errors on empty states should match the Figma copy. The invalid error should show when an invalid input is provided by the user, but the empty state should tell the user the field  is required. 
 
 
<img width="454" alt="image" src="https://github.com/user-attachments/assets/6c773d58-b1e5-420f-9318-51cf631debd0">

Examples of empty inputs:

<img width="715" alt="image" src="https://github.com/user-attachments/assets/87ac710e-a284-4b21-b142-5af09b69406b">

7. Toast should not display behind the bg overlay when the modal is active

<img width="515" alt="image" src="https://github.com/user-attachments/assets/00d1b7dc-8cbb-439d-9717-ef3ecf2e3fc7">

8. Can the toast please provide more contextual information with both the toast header and text included. Please remove the :(

Heading: Something went wrong
Text: Your bank details could not be updated at this time 

## Testing

Make sure to have the `POSTHOG_` variables set in `.env.local.secrets` (if you don't have them please PING me)
Connect your wallet to `leela`
Go to `http://localhost:9091/account/crypto-to-fiat`
Check page sections and modals styling

Resolves #2741

2024-08-02 13:02 UTC, melyndav requested changes
Hey @mmioana nice start on all the UI updates. Some feedback on this one below.

1. Number 3 from my issue still requires updates - this is removing the {fieldName} and using the label for nicer copy and better UX.

<img width="231" alt="image" src="https://github.com/user-attachments/assets/68d2103a-3a85-46a4-9bad-ab15245ea938">


2. When I input an email with incorrect format, I receive no error validation error. 

<img width="497" alt="image" src="https://github.com/user-attachments/assets/28128ac5-05b0-4693-8359-6015d6be0bc7">

3. The stepped navigation should not be intractable. It's a visual indicator, with no navigation here.

<img width="539" alt="image" src="https://github.com/user-attachments/assets/fb46ed55-1bc5-4a45-a74d-ff7e41162b85">

Right now, I can skip through and bypass the terms.

<img width="605" alt="image" src="https://github.com/user-attachments/assets/7176425c-9bb7-47a7-bae9-ccd2291e0e9b">

Video:

![Export-1722603408378](https://github.com/user-attachments/assets/621b1350-8002-4bee-8b82-bbfd3af93d54)


4. Can you kindly change the 'KYC form' in the stepped pill to be 'KYC'.

<img width="559" alt="image" src="https://github.com/user-attachments/assets/f085a972-5fa8-48b0-8dee-48b7d5a452e0">

5. I can't submit the first CTA in the KYC modal. So I can't test the rest of the PR such as the bank details modal andother status pill updates. :(

![Export-1722603408378](https://github.com/user-attachments/assets/1c13b1b2-fbae-497f-8aae-d75d05d8da3f)

2024-08-05 19:17 UTC, mmioana commented
Hey @melyndav thank you for reviewing this PR 🌟 

Some of the error messages I didn't properly update, but now they should be in place ✨ 

Regarding your point 2. When I input an email with incorrect format, I receive no error validation error.
we use the same email validation function from the Yup library (as in the form from the onboarding wizard) which considers the email you have entered to be valid
<img width="647" alt="Screenshot 2024-08-05 at 20 59 43" src="https://github.com/user-attachments/assets/8329204b-cb36-43a6-8029-14f2aca37f53">
Let me know if we need to impose stricter rules when it comes to allowed emails and what format should be acceptable

For further testing the flow, you'll need to manually update a key, but let me know when you plan to re-test this PR so we can sync 🙏

2024-08-08 08:55 UTC, melyndav commented
Hey @mmioana this is fine to continue using the Yup library for this. You can ignore point 2 of my feedback.

2024-08-08 09:34 UTC, mmioana commented
Cool @melyndav! Either way if you want to enforce stricter validation, just let me know.
Otherwise this PR is ready for your review 🙏

2024-08-08 12:17 UTC, rumzledz submitted a review, later dismissed
Awesome work on this @mmioana ! ✨ 

The badge colour, font weights, spacings and most importantly, the error messages are now much more pleasant to read 😄 

![Screenshot 2024-08-08 at 13 13 02](https://github.com/user-attachments/assets/e0d1bd97-871c-4660-a897-dfd23b52af4c)
![Screenshot 2024-08-08 at 13 13 55](https://github.com/user-attachments/assets/b4f8f9cb-a45d-4e0c-b781-0fd531fd8a84)
![Screenshot 2024-08-08 at 13 14 04](https://github.com/user-attachments/assets/df98a766-67c8-4124-8338-9acd38b0ffdf)

2024-08-12 09:58 UTC, melyndav approved these changes
Hey @mmioana thanks for the further updates on this PR! Everything is looking great and all the issues have been resolved. Thanks for your effort on this one 🥇

2024-08-12 12:41 UTC, Nortsova approved these changes
Hey @mmioana ✨! Thanks for this beautiful changes 🤩

Validation and paddings looks great!

<img width="300" alt="image" src="https://github.com/user-attachments/assets/393f6379-f702-4f33-8a74-0ef237da64fd">
<img width="300" alt="image" src="https://github.com/user-attachments/assets/6f53c3f4-471d-4861-afd2-318e49c85697">


There is no scroll on Bridge embed tab:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/a2425e8d-1e97-48d7-b0c3-8f21e4ff3c5e">

Select options looks great!
<img width="300" alt="image" src="https://github.com/user-attachments/assets/b81a601c-e6f1-4e13-a852-7f66024df6b6">

"Approve" pill has correct color, "optional" has correct "O" capital, 'Bank, address and currency information' title has correct medium font weight.
<img width="870" alt="image" src="https://github.com/user-attachments/assets/eb7d0bad-0b10-4645-94c8-cff037076d10">

2024-08-12 13:45 UTC, mmioana commented on src/utils/intl.ts
> +  }
@rumzledz is the master of disaster for this 🥇

2024-08-12 16:52 UTC, merged