Use proper styling for tx paging end msg
JoinColony/colonyCDapp pull request #2865
Opened 2024-08-05 14:32 UTC by chmanie

## Description

This PR solves a little annoyance with the paging end element of the transaction list.

It looks like this now:

![image](https://github.com/user-attachments/assets/52efcda7-e0d5-4d62-bfd8-ce64bdfe3d0e)

## Testing

1) Start the CDapp
2) Go to a Colony, to the UserHub, click transactions
3) Scroll all the way down
4) You should see this little fella.

Here's the Figma: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-50890&t=oNC6Rrhij7U9pY3p-0

## Diffs

**Changes** 🏗

* Changed styling and copy of the tx end element

2024-08-05 15:47 UTC, iamsamgibbs requested changes
This looks good to me!

<img width="488" alt="Screenshot 2024-08-05 at 16 42 13" src="https://github.com/user-attachments/assets/8a41e355-b4ed-4edd-a4d6-997843389f05">

Although I definitely preferred this little guy 😎

I did find this issue with the transactions list on mobile where it is impossible to scroll to the very end and think it makes sense to fix here (although if it turns out to be a pain, let me know and I'll approve and we can handle this elsewhere.) I can see the last transaction, but not the `thisIsTheEnd` message.

<img width="388" alt="Screenshot 2024-08-05 at 16 42 38" src="https://github.com/user-attachments/assets/ac70f848-1b0f-41f8-aa56-5f2587e99ebc">

2024-08-06 08:58 UTC, melyndav commented
> Although I definitely preferred this little guy 😎

@iamsamgibbs he's the same cool guy, just lost his sunglasses along the way 😅

2024-08-06 09:00 UTC, melyndav approved these changes
I think this is the best UI update we've made so far. I'm all for more 😀 smiley guys! Thanks for updating this one @chmanie! Approved from a UI side.

2024-08-06 09:33 UTC, bassgeta approved these changes
Fs in the chat for our summer sunglasses easter egg
![image](https://github.com/user-attachments/assets/4d29daff-997a-470b-81b2-039660aee81d)

2024-08-06 09:54 UTC, chmanie commented
Hey @iamsamgibbs. I played around a bit but I'm at a loss. Maybe someone who's more present in the CSS game can take a shot at this?

2024-08-06 10:00 UTC, iamsamgibbs commented
> Hey @iamsamgibbs. I played around a bit but I'm at a loss. Maybe someone who's more present in the CSS game can take a shot at this? I guess it'd be good to open a new issue, or if this is actually simple (and I'm just stupid), add it to this one.

Let's open this as a new issue if it's not a simple fix! :)

2024-08-06 10:01 UTC, iamsamgibbs approved these changes

2024-08-06 13:44 UTC, merged