Fix: claim colony funds after mint tokens motion is finalized
JoinColony/colonyCDapp pull request #2932
Opened 2024-08-13 10:53 UTC by mmioana

## Description

- Trigger the MOTION_CLAIM_MINT_TOKENS saga after clicking the Finalize button for a Mint tokens action
- Note: Created a new saga as we might want to re-work how we're claiming incoming funds - currently the block ingestor will claim all available funds within a colony for the given token

## Testing

TODO: Incoming funds resulted from a MINT_TOKENS motion are claimed and no longer appear as funds that need to be accepted. 
![Screenshot 2024-08-13 at 12 37 00](https://github.com/user-attachments/assets/2f5e1c1d-bbbc-41b7-958c-03f39518a835)

* Step 1. Enable `Multi-sig Permissions` extension (no need to change the default settings)
* Step 2. Give `leela` Owner permissions to Take actions via Multi-sig
![Screenshot 2024-08-13 at 12 46 13](https://github.com/user-attachments/assets/844479ff-0aec-49b1-8086-78ea6cb0a2cc)
* Step 3. Create a Mint Tokens with Multi-Sig decision method
![Screenshot 2024-08-13 at 12 46 49](https://github.com/user-attachments/assets/9434fdbc-b68f-45f6-8a65-0d4c1c0e79ab)
* Step 4. Finalize motion
![Screenshot 2024-08-13 at 12 47 15](https://github.com/user-attachments/assets/9c2b186d-d14d-4137-b7b9-7bedd8146ee5)
* Step 5. Check minted tokens are already claimed in the Incoming Funds page
![Screenshot 2024-08-13 at 12 47 32](https://github.com/user-attachments/assets/8ecb30c1-6f80-44a6-8c2b-71767b18884a)
* Step 6. Enable `Reputation Weighted (Lazy Consensus method)` extension 
* Step 7. Choose `Testing governance` as extension settings and enable it
![Screenshot 2024-08-13 at 12 48 47](https://github.com/user-attachments/assets/9ad7c444-c9da-4afb-aadc-197484d44df6)
* Step 8. Create Mint Tokens with Reputation decision method
* Step 9. Support motion by staking at least 10%
![Screenshot 2024-08-13 at 12 50 10](https://github.com/user-attachments/assets/2d519db2-62dd-48f5-8a3f-a959e3937598)
* Step 10. Run `npm run forward-time 10`
* Step 11. Refresh page and finalize motion
![Screenshot 2024-08-13 at 12 51 04](https://github.com/user-attachments/assets/296d4c8b-7203-48e4-b015-814df3bdbdff)
* Step 12. Check minted tokens are already claimed in the Incoming Funds page
![Screenshot 2024-08-13 at 12 51 18](https://github.com/user-attachments/assets/69fa2f7a-bb7c-43b5-95c1-e87a10585e20)

## Diffs

**New stuff** ✨

* MOTION_CLAIM_MINT_TOKENS redux saga

Resolves [#2913](https://github.com/JoinColony/colonyCDapp/issues/2913)

2024-08-13 22:35 UTC, rdig requested changes
Very nice work! I've tested this and seems to be working as expected. Both Multisig and Motions will auto-claim the incoming funds

![Screenshot from 2024-08-14 01-27-05](https://github.com/user-attachments/assets/b338ba51-d528-4ce3-943a-20019b3b343a)
![Screenshot from 2024-08-14 01-27-38](https://github.com/user-attachments/assets/cf3367f1-4f39-4caa-ac22-201f05ff612f)
![Screenshot from 2024-08-14 01-27-45](https://github.com/user-attachments/assets/094f6f3d-c5f3-479a-98ab-163d75e56c73)
![Screenshot from 2024-08-14 01-31-46](https://github.com/user-attachments/assets/717b2052-efd7-483a-b760-623050523a3c)
![Screenshot from 2024-08-14 01-31-55](https://github.com/user-attachments/assets/5d791aba-b715-4155-97a1-1094e4f38a4f)

However I noticed a issue _(which might or might not be related to this)_. The colony balance doesn't update. No matter if it's via Multisig or via Motions, after a mint and automatic claim, the balance of the colony stays the same

![Screenshot from 2024-08-14 01-29-37](https://github.com/user-attachments/assets/d5216033-0cd3-4c7c-943b-42e813404501)
![Screenshot from 2024-08-14 01-29-49](https://github.com/user-attachments/assets/1fc676a6-72f8-4b35-80a7-8ebe7b88d9c6)

This needs to be fixed, preferably here, as it's major problem if the balance gets out of date with the chain state.

2024-08-14 06:22 UTC, mmioana commented
Thank you @rdig for reviewing it 🙏 I'll check the issue regarding the balance update

2024-08-14 06:54 UTC, mmioana commented
Hey @rdig I tried to mint a larger amount of tokens and the balance seems to be updating

https://github.com/user-attachments/assets/03480b2e-cd6a-4c11-ad0a-d2af04651b3b


I'm wondering if the balance update was not visible only because there was a too small amount of tokens minted? 🤔

2024-08-14 10:52 UTC, bassgeta requested changes
Works like a charm, maybe we can remove polling so it's a bit less API spammy :D  
Other than that, balance before:
![image](https://github.com/user-attachments/assets/1e074f8a-4a54-4ef8-831e-cc99f258dfbf)
Finalized a mint tokens Multi-sig
![image](https://github.com/user-attachments/assets/bacb8c08-c493-45aa-8be1-28a7b669f52a)
And it's updated :sunglasses: 
![image](https://github.com/user-attachments/assets/7fba0eb8-3a1b-4487-bbd7-7d3778dd41e4)

2024-08-14 10:52 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/partials/hooks.ts
> +  const { startPollingColonyData, stopPollingColonyData } = useColonyContext();
Dropped you a DM also, but I think we can do this without polling and it should work just fine :ok_hand:

2024-08-20 07:55 UTC, jakubcolony requested changes
Nice start on the PR @mmioana!

I noticed this issue is overlapping with #2506. Ideally, the solution for both multi sig and "regular" motions would be to include the claim transaction in the motion's action. However, as far as I'm aware, it is not supported by multisig (and definitely not supported by regular motions). This is great as it gets us unblocked in both cases.

The only reason for requesting changes is the saga duplication, we've always had the ability to claim funds (e.g. the "Accept all funds" button in the Incoming Funds page) via the `CLAIM_TOKEN` redux action and it should be used here as well.

2024-08-21 07:11 UTC, mmioana commented
> Nice start on the PR @mmioana!
> 
> I noticed this issue is overlapping with #2506. Ideally, the solution for both multi sig and "regular" motions would be to include the claim transaction in the motion's action. However, as far as I'm aware, it is not supported by multisig (and definitely not supported by regular motions). This is great as it gets us unblocked in both cases.
> 
> The only reason for requesting changes is the saga duplication, we've always had the ability to claim funds (e.g. the "Accept all funds" button in the Incoming Funds page) via the `CLAIM_TOKEN` redux action and it should be used here as well.

Hey @jakubcolony thank you for noticing the overlapping issue 🌟 

The reason I decided to create the new saga was due to the fact we might want to re-work how we're claiming the incoming funds, as currently we're accepting all incoming funds and not only the ones related to a specific motion/action. 

However, this actually needs to be clarified with Product (will do so) and maybe then we can create a separate issue 🙌

2024-08-21 08:02 UTC, bassgeta approved these changes
Nice solution, just a handler and stuff **just** works :D
Automatic claim of my 111 CREDS multisig
![image](https://github.com/user-attachments/assets/32cd4aa1-d70e-4482-9dbc-2bac9b0fa947)
![image](https://github.com/user-attachments/assets/9fff0038-5f0c-45d9-a454-44e0d1174c2d)

Voting reputation:
![image](https://github.com/user-attachments/assets/6581444e-c9ca-4ac7-a403-d3248bf64f1e)
![image](https://github.com/user-attachments/assets/de89c620-bc10-4ce8-9dde-4d7a9c5eb997)

2024-08-21 09:42 UTC, mmioana commented
@jakubcolony after discussing with Arren indeed it seems there is no issue in claiming all incoming funds for the same token in a colony. So I'll proceed with removing the duplicated saga 🙌

2024-08-22 09:52 UTC, jakubcolony approved these changes
> @jakubcolony after discussing with Arren indeed it seems there is no issue in claiming all incoming funds for the same token in a colony. So I'll proceed with removing the duplicated saga 🙌

Sounds good! It is actually impossible to "choose" funds you claim, you have to do it for the entire balance in given token.

Thanks for addressing my feedback, all looks good now 👍 

Before finalizing the motion:
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/8c4d76b0-7d0d-4346-84a6-e0424b3bc97a">

<img width="1081" alt="image" src="https://github.com/user-attachments/assets/37048704-58af-4f0f-bf2a-5eca4dbb1fd5">


After:
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/28e2188c-1971-48a0-a5ba-c1da1b8ae785">

2024-08-23 06:25 UTC, mmioana commented
> > @jakubcolony after discussing with Arren indeed it seems there is no issue in claiming all incoming funds for the same token in a colony. So I'll proceed with removing the duplicated saga 🙌
> 
> Sounds good! It is actually impossible to "choose" funds you claim, you have to do it for the entire balance in given token.
> 
> Thanks for addressing my feedback, all looks good now 👍
> 
> Before finalizing the motion: <img alt="image" width="1379" src="https://private-user-images.githubusercontent.com/112586815/360379865-8c4d76b0-7d0d-4346-84a6-e0424b3bc97a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTQ0NjYsIm5iZiI6MTcyNDM5NDE2NiwicGF0aCI6Ii8xMTI1ODY4MTUvMzYwMzc5ODY1LThjNGQ3NmIwLTdkMGQtNDM0Ni04NGE2LWUwNDI0YjNiYzk3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNjIyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDcxOTYxMmZkZDkyYWI2M2NmNzM1NjZkNTczYWYzZThiODMyYmU3OWFlMGQ2MmJmMDQ4ZmRlMjI1YzJjMTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-u0hbAXzGmls73YbihJDsFpLZ9ngSS0ftofg1jJGZ3c">
> 
> <img alt="image" width="1081" src="https://private-user-images.githubusercontent.com/112586815/360380555-37048704-58af-4f0f-bf2a-5eca4dbb1fd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTQ0NjYsIm5iZiI6MTcyNDM5NDE2NiwicGF0aCI6Ii8xMTI1ODY4MTUvMzYwMzgwNTU1LTM3MDQ4NzA0LTU4YWYtNGYwZi1iZjJhLTVlY2E0ZGJiMWZkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNjIyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzA1MWUxYjk1NDYwODVhNDkxZTcyNzAwZTYyYjJmZDU5OGE3MzE4YmU3MzY3ZGIwYmFiMDdmYzBmMzg1MjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SLcVJ6DFo2s0AsIbN2Zpu_hID5N6kEhNsbMyWON_WG8">
> After: <img alt="image" width="1372" src="https://private-user-images.githubusercontent.com/112586815/360380665-28e2188c-1971-48a0-a5ba-c1da1b8ae785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTQ0NjYsIm5iZiI6MTcyNDM5NDE2NiwicGF0aCI6Ii8xMTI1ODY4MTUvMzYwMzgwNjY1LTI4ZTIxODhjLTE5NzEtNDhhMC1hNWJhLWMxZGExYjhhZTc4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwNjIyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWNkYjA0MGIyZWM3ODliZTJkOWYzMzc5M2E5YWYwM2ZiOTU0MWQxZWFmN2YxMDBmMzdlZWRjZWYwNGM4YWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NpKMWU8suSRyQpT7mNWdtFPuVT_HepxDm3F-agpn5-U">

Thank you @jakubcolony for all the valuable feedback! 🌟

2024-08-23 13:59 UTC, merged