Always show chain native tokens in incoming funds table
JoinColony/colonyCDapp pull request #2975
Opened 2024-08-21 11:14 UTC by davecreaser

## Description

There was an [issue raised](https://github.com/JoinColony/colonyCDapp/issues/2787) where the chain's native token was disappearing from the Incoming Funds table after you claimed the funds. With the other tokens, the claim remains in a 'claimed' state. The problem is that the way chain native tokens are handled is very different - see the comments in the issue for more details on that.

This is a solution which will ensure there is no confusion when the chain native token is claimed and disappears from the list. In the future when financial reporting is worked on then this behaviour can be changed properly.

Here's a description of what this PR will do:

- Ensure that the chain's native token item will always be visible at the bottom of the Incoming Funds table.

Collapsed view:
- It will show a value of 0 if there is nothing to claim.
- If there are incoming funds, then it will show the value of funds to claim.

Expanded view:
- There will be an info row that always appears at the bottom of the expanded table for this token, regardless if there are funds to claim or not.
- Claimable incoming funds will appear above the notice and work as expected, allowing claiming with the claimed funds rows disappearing, keeping the note in place.

## Testing

You'll need to test that when you send ethereum to a colony, it shows up as expected. That includes before sending, after sending, and after claiming.

* Step 1. On a clean environment, go to the incoming funds page. You should see Ether at the bottom of the table with 0 Eth incoming. There should also be a warning message when you expand this row informing you that a history of claims won't be saved:

<img width="1428" alt="Screenshot 2024-08-21 at 12 07 30" src="https://github.com/user-attachments/assets/26a8e84b-45ae-43da-a708-23be99e6645c">

* Step 2. Get the colony address. I like to do this just by going to the balances page and clicking on the `Add funds to the colony` button in the top right:

<img width="1435" alt="Screenshot 2024-08-21 at 12 05 31" src="https://github.com/user-attachments/assets/8bcfe8b7-a3b3-4c77-9a5c-31630761da52">

* Step 3. Open a dev wallet in metamask, and send some ethereum to the colony. Ensure that you're on the correct network (Ganache Local) and that you're on the right account (dev wallet). If you need help setting up the network or importing a dev wallet let me know and I can help you do so. Also if this transaction fails, you may need to reset your nonces, again, just let me know and I can help you.

<img width="362" alt="Screenshot 2024-08-21 at 12 09 09" src="https://github.com/user-attachments/assets/51792306-e45a-4203-8fbb-0afacc637119">

* Step 4. Go back to the incoming funds page and refresh. You should now see some Eth available to be claimed.

<img width="1328" alt="Screenshot 2024-08-21 at 12 11 08" src="https://github.com/user-attachments/assets/f733a9fa-1d69-4cc9-8203-fcb5ccedf674">

* Step 5. Accept the Eth, and you should see it be accepted (the button will disable while this is in progress) and then go back to zero. The row should _not_ disappear from the table.

<img width="1310" alt="Screenshot 2024-08-21 at 12 12 37" src="https://github.com/user-attachments/assets/1d68072e-706d-4469-be9b-8ca37a5a86ab">

## Diffs

**Changes** 🏗

* Always return a claim from the `fetchColonyNativeFundsClaim` lambda, even if the amount is zero.
* Always show Eth at the bottom of the incoming funds table.
* Add a warning message to the incoming funds table.

Resolves #2787

2024-08-22 09:17 UTC, iamsamgibbs requested changes
Great work on this Dave, everything is working nicely!

New claims show up in the table:

<img width="1400" alt="Screenshot 2024-08-22 at 10 01 51" src="https://github.com/user-attachments/assets/8598a7c6-b24e-4f67-8fc6-f66128e5572e">

Also sanity checked they get claimed properly:

<img width="1308" alt="Screenshot 2024-08-22 at 10 02 34" src="https://github.com/user-attachments/assets/6e14b7b8-64ca-4b2f-89f4-9a880edf8b57">

I noticed when I sent two payments to the colony, they were both summed together and showed as a single claim - this looks like the intended behaviour from the code, but just wanted to check it is expected?

The only issue I noticed is this icon shrinking once you get to small screen widths on mobile:

<img width="405" alt="Screenshot 2024-08-22 at 10 06 25" src="https://github.com/user-attachments/assets/3bcad308-6cd8-46a4-b83f-0138765e107c">

Nice job!

2024-08-22 17:18 UTC, davecreaser commented on amplify/backend/function/fetchColonyNativeFundsClaim/src/index.js
> +  // If the unclaimed balance is 0, or unclaimed balance is 0, still return a claim with amount zero.
🤣 busted.

2024-08-22 17:34 UTC, davecreaser commented
@iamsamgibbs Thanks for the review! As to the behaviour you mentioned, yeah it's expected - good that you checked though. I've fixed the mobile icon shrinking and also the terribly worded comment 😆 Ready for re-review!

2024-08-23 10:45 UTC, bassgeta approved these changes
Nice and clean code changes!
Can confirm that ETH shows up
![image](https://github.com/user-attachments/assets/f92acf32-a805-4594-a292-9faba81cb3fa)
Sent over 5 ETH and it shows up:
![image](https://github.com/user-attachments/assets/8769995c-7f00-4666-9ba6-6cd98a8f7c10)
And ETH then doesn't disappear:
![image](https://github.com/user-attachments/assets/93fa5827-4a38-4e50-aa57-e72d0020ce19)

Nice job pulling that row into a function instead of inlining it :ok_hand:

2024-08-26 13:51 UTC, rdig approved these changes
Seems to be working as advertised. Nice compromise on dealing with the chain native token!

![Screenshot from 2024-08-26 16-41-24](https://github.com/user-attachments/assets/94afd782-c921-4baa-843b-01a8fbcf26ff)
![Screenshot from 2024-08-26 16-43-07](https://github.com/user-attachments/assets/28853f5e-b27e-4877-97f1-abfef4abe955)
![Screenshot from 2024-08-26 16-43-17](https://github.com/user-attachments/assets/da306c6f-43bf-4eb0-9256-cdeb79675d51)
![Screenshot from 2024-08-26 16-43-45](https://github.com/user-attachments/assets/6e79f83b-635b-41bd-8707-5f1de9dd4720)
![Screenshot from 2024-08-26 16-44-22](https://github.com/user-attachments/assets/921059ac-c78f-40be-92fc-a4bbaa1911f6)
![Screenshot from 2024-08-26 16-44-43](https://github.com/user-attachments/assets/0b488894-4e26-4fa8-a706-00af2f498809)
![Screenshot from 2024-08-26 16-45-05](https://github.com/user-attachments/assets/e41c03dd-6cc8-4148-ba60-eb606d8c82ca)
![Screenshot from 2024-08-26 16-45-56](https://github.com/user-attachments/assets/bbc4f436-6bbe-4e5e-897a-9738a4f47e2e)

2024-08-27 10:40 UTC, iamsamgibbs approved these changes
Nice one! Comment makes sense and pesky shrinking icon is resolved:

<img width="372" alt="Screenshot 2024-08-27 at 11 39 03" src="https://github.com/user-attachments/assets/7a6287c0-6268-4864-b510-c82106abcb92">

Good to go!

2024-08-27 11:26 UTC, merged