fix: show header when cancel modal is visible
JoinColony/colonyCDapp pull request #2982
Opened 2024-08-22 09:39 UTC by joanna-pagepro

## Description

You should be able to interact with the header in order to view and managed your transactions while in the modal.

## Testing

* Create a new Adv. Payment action.
* Cancel the new action.
* The cancel modal will open.
* Check if header is accesible

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* `shouldShowHeader` set to true in `CancelModal` component

**Deletions** ⚰️

* 

## TODO

- 

Resolves https://github.com/JoinColony/colonyCDapp/issues/2863

2024-08-23 00:09 UTC, rumzledz requested changes
Hey @joanna-pagepro , I think you've applied this prop on the wrong component:

![cancel_wrong](https://github.com/user-attachments/assets/8a34ab78-0251-4c61-b81e-9057b633658d)

If I understand this correctly, I believe you should apply the `shouldShowHeader` boolean to the Cancel modal component found in the `ActionSidebar.tsx` component:

![cancel_correct](https://github.com/user-attachments/assets/6dc294e4-f299-4c33-a705-0fbaa709ffe3)

2024-08-23 06:48 UTC, joanna-pagepro commented
@rumzledz screenshot from the task:
![image](https://github.com/user-attachments/assets/40f55b86-ad10-48e0-ac0f-fb5a214a7171)

2024-08-23 08:10 UTC, mmioana approved these changes
Nice and simple fix @joanna-pagepro 👏 
![Screenshot 2024-08-23 at 10 04 32](https://github.com/user-attachments/assets/1ed86d88-7b40-46e0-a87f-24d1b967fd5d)
![Screenshot 2024-08-23 at 10 05 49](https://github.com/user-attachments/assets/2b74e34e-bfd5-4e27-a3ff-22178bae1d68)

@rumzledz from the #2863 issue I think @joanna-pagepro fix tackles the right modal, even though the description mentions you only need to cancel the action, but I believe what @arrenv meant was to cancel the payment

2024-08-23 08:27 UTC, arrenv commented
@joanna-pagepro confirming that you have addressed the correct modal.

The general rule at the moment, is that if there is a transaction being performed in the modal, then the user should be able to interact with the pending button and the Userhub to manage the transaction.

Note, we are planning to improve the UX of this, although for now, this is the general rule.

2024-08-23 09:38 UTC, rumzledz commented
@joanna-pagepro @mmioana oh apologies for that, the test steps confused me. I'll re-test this!

2024-08-23 09:54 UTC, rumzledz approved these changes
Can confirm the fix works on my end @joanna-pagepro ✨ Apologies again that I misunderstood the testing steps previously!

![Screenshot 2024-08-23 at 10 53 22](https://github.com/user-attachments/assets/dd6915ae-85a9-4d60-b8ce-10d39debec6d)

2024-08-28 18:01 UTC, jakubcolony approved these changes
LGTM, working as expected:

<img width="1333" alt="image" src="https://github.com/user-attachments/assets/19e4697c-607a-455b-867c-82905aed32c5">

2024-08-29 05:38 UTC, joanna-pagepro commented
@jakubcolony can you merge it?

2024-08-29 11:37 UTC, merged