feat: split payment preview skeleton loader
JoinColony/colonyCDapp pull request #2983
Opened 2024-08-22 10:17 UTC by joanna-pagepro

## Description

Split payment preview loading state

## Testing

* Create a split payment.
* Select the Reputation percentage distribution type.
* Select users with reputation.
* Create the action.
* Note the loading state of the split payment table.

## Diffs

**New stuff** ✨

* 

**Changes** 🏗

* loading states added into missing places and members loading state added to the table to show the loader when members data is fetched

**Deletions** ⚰️

* 

## TODO

- 

Resolves https://github.com/JoinColony/colonyCDapp/issues/2843

2024-08-22 23:38 UTC, rumzledz requested changes
Nice and straightforward @joanna-pagepro ! ✨ I did leave a tiny change request regarding the `LoadingSkeleton` component but that's pretty much it 👌

2024-08-22 23:38 UTC, rumzledz commented on src/components/v5/common/CompletedAction/partials/SplitPayment/partials/SplitPaymentTable/hooks.tsx
> +              {isLoading ? (
You can use the `LoadingSkeleton` 💀  component here:

```js
// You can also pass `classNames` to use a specific border radius/width/height etc. :)
<LoadingSkeleton isLoading={isLoading}>
  {token ? (
    <div className="flex items-center justify-end gap-9 md:justify-start">
      <SplitPaymentPayoutsTotal data={data} token={token} />
      {isTablet && (
        <span className="text-md font-medium text-gray-900">100%</span>
      )}
    </div>
  ) : null}
</LoadingSkeleton>
```

2024-08-22 23:38 UTC, rumzledz commented on src/components/v5/common/CompletedAction/partials/SplitPayment/partials/SplitPaymentTable/hooks.tsx
> +          return isDataLoading ? (
Here as well 💀

2024-08-22 23:38 UTC, rumzledz commented on src/components/v5/common/CompletedAction/partials/SplitPayment/partials/SplitPaymentTable/hooks.tsx
> +                <div className="flex w-[4rem] items-center">
And here 💀

2024-08-23 07:59 UTC, mmioana approved these changes
Nice work @joanna-pagepro 🌟 

Followed your testing steps and can confirm the loading skeletons are showing up

https://github.com/user-attachments/assets/c58b37db-555b-41a0-b28a-985e90ea3635

Besides the `LoadingSkeleton` usage as @rumzledz proposed, everything looks good from my side

2024-08-23 08:15 UTC, joanna-pagepro commented
@rumzledz @mmioana updated

2024-08-23 09:58 UTC, rumzledz approved these changes
The table's loaders are looking 💯 

![loaders split](https://github.com/user-attachments/assets/f9a14eb4-1846-4efc-9a91-c65f476d9232)

2024-08-23 12:27 UTC, merged