feat: added claim delay notification
JoinColony/colonyCDapp pull request #2990
Opened 2024-08-23 06:43 UTC by CzarekDryl

## Description

- Added a delay notification to staged payments table
- For testing purpose I've added hardcoded values
<img width="511" alt="image" src="https://github.com/user-attachments/assets/013d2eb8-e83f-43b9-aa20-f6cfb315395d">

## Testing

* Create staged payments action and go to `payment` step
* After a minute, an icon with information about the delay should appear

## TODO

- Remove hardcoded variables before merging

Resolves https://github.com/JoinColony/colonyCDapp/issues/2899

2024-08-26 10:12 UTC, mmioana requested changes
Nice work on this one @CzarekDryl 👏  
If temporary claim delay is more than a month
![Screenshot 2024-08-26 at 12 08 01](https://github.com/user-attachments/assets/435dc0f8-f13a-452c-8871-1f85266d290f)
After temporary claim delay is less than a month, can confirm the tooltip is showing up
![Screenshot 2024-08-26 at 12 09 16](https://github.com/user-attachments/assets/3971f30c-3782-41c5-bd9f-d422423e498e)

However I did leave a refactoring comment, if you could please tackle it 🙏

2024-08-26 22:39 UTC, jakubcolony approved these changes
Nice work @CzarekDryl, I also think Ioana made a great suggestion regarding the hardcoded interval.

<img width="1088" alt="image" src="https://github.com/user-attachments/assets/670e7418-68ad-4c14-ba49-1933a817c764">

2024-08-27 06:59 UTC, CzarekDryl commented
@mmioana Thank you for checking, I fixed it as you suggested :)

2024-08-28 08:33 UTC, mmioana approved these changes
Thank you for doing the suggested refactoring @CzarekDryl 🙌 

Can confirm the notification still shows up 
![Screenshot 2024-08-28 at 10 31 58](https://github.com/user-attachments/assets/15de9dad-6ec5-4b9f-b444-ef9b046c0d75)

2024-08-28 08:35 UTC, merged