Fail_all_ pending txs (including `CREATED` and `READY`)
JoinColony/colonyCDapp pull request #3015
Opened 2024-08-27 14:37 UTC by chmanie

## Description

This PR adds transactions with the status `CREATED` and `READY` to the ones that are being cleared when the user refreshes the page.

I know this is not the ideal approach (we would like to retry those transactions), but with the current transaction API that's all we can do for now.

## Testing

This is quite hard to test locally, so you will have to create a transaction for your user manually:

1) Create unfinished transactions manually:

```gql
mutation CreateUnfinishedTransactions {
  tx1: createTransaction(
    input: {id: "zBtVbwKJvFhxKbJSUTbma1-createColonyForFrontend", context: NetworkClient, from: "0xb77D57F4959eAfA0339424b83FcFaf9c15407461", colonyAddress: "0x52fC5a44C7f53C42f91BB20c2C9304F046481e91", groupId: "zBtVbwKJvFhxKbJSUTbmy", group: {id: "zBtVbwKJvFhxKbJSUTbma-createColonyForFrontend", groupId: "zBtVbwKJvFhxKbJSUTbmy", index: 10, key: ""}, methodName: "createColonyForFrontend", status: CREATED, blockHash: null, blockNumber: null, createdAt: "2024-08-26T14:22:03.445Z", hash: "0xa015a493bdc50ff0488e3522ea976e8c8be3e1239f3114199f0ec35b13a34088", identifier: "0x52fC5a44C7f53C42f91BB20c2C9304F046481e91", methodContext: null, options: "{}", params: "[\"0x0000000000000000000000000000000000000000\",\"Space Credits\",\"CREDS\",18,15,\"\",\"\"]", receipt: null, title: null, titleValues: null}
  ) {
    id
  }
  tx2:createTransaction(
    input: {id: "zBtVbwKJvFhxKbJSUTbmb1-createColonyForFrontend", context: NetworkClient, from: "0xb77D57F4959eAfA0339424b83FcFaf9c15407461", colonyAddress: "0x52fC5a44C7f53C42f91BB20c2C9304F046481e91", groupId: "zBtVbwKJvFhxKbJSUTbmy", group: {id: "zBtVbwKJvFhxKbJSUTbma-createColonyForFrontend", groupId: "zBtVbwKJvFhxKbJSUTbmy", index: 10, key: ""}, methodName: "createColonyForFrontend", status: READY, blockHash: null, blockNumber: null, createdAt: "2024-08-26T14:22:03.445Z", hash: "0xa015a493bdc50ff0488e3522ea976e8c8be3e1239f3114199f0ec35b13a34088", identifier: "0x52fC5a44C7f53C42f91BB20c2C9304F046481e91", methodContext: null, options: "{}", params: "[\"0x0000000000000000000000000000000000000000\",\"Space Credits\",\"CREDS\",18,15,\"\",\"\"]", receipt: null, title: null, titleValues: null}
  ) {
    id
  }
  tx3: createTransaction(
    input: {id: "zBtVbwKJvFhxKbJSUTbmc1-createColonyForFrontend", context: NetworkClient, from: "0xb77D57F4959eAfA0339424b83FcFaf9c15407461", colonyAddress: "0x52fC5a44C7f53C42f91BB20c2C9304F046481e91", groupId: "zBtVbwKJvFhxKbJSUTbmy", group: {id: "zBtVbwKJvFhxKbJSUTbma-createColonyForFrontend", groupId: "zBtVbwKJvFhxKbJSUTbmy", index: 10, key: ""}, methodName: "createColonyForFrontend", status: PENDING, blockHash: null, blockNumber: null, createdAt: "2024-08-26T14:22:03.445Z", hash: "0xa015a493bdc50ff0488e3522ea976e8c8be3e1239f3114199f0ec35b13a34088", identifier: "0x52fC5a44C7f53C42f91BB20c2C9304F046481e91", methodContext: null, options: "{}", params: "[\"0x0000000000000000000000000000000000000000\",\"Space Credits\",\"CREDS\",18,15,\"\",\"\"]", receipt: null, title: null, titleValues: null}
  ) {
    id
  }
}
```

2. Refresh the app using the address `0xb77D57F4959eAfA0339424b83FcFaf9c15407461` (Leela) and check if all transactions are either failed or succeeded.

## Diffs

**Changes** 🏗

* Also fail transactions that are `CREATED` or `READY` on user login

Resolves #2997

2024-08-27 21:03 UTC, jakubcolony approved these changes
Approving as I can confirm the transactions were failed in the DB:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/f3654660-b2f6-45b7-8f3b-fd4e807587e4">

I was expecting to see them at the bottom of transactions in the user hub (that's how they're returned by the query), but they're not in the list:
<img width="699" alt="image" src="https://github.com/user-attachments/assets/9feaae5b-9f74-42a3-9050-69d0444964c5">

Is that expected? 

----

Most likely unrelated to this PR, but twice I got into a state where no transactions would show in the user hub for my user:
<img width="734" alt="image" src="https://github.com/user-attachments/assets/35631d9e-c2b9-4f56-a481-8a7c8256a7b1">

I had to change the fetch policy of `useGetUserTransactionsQuery` in `src/state/transactionState.ts` to network-only to see transactions for my user. Can you check if you're able to reproduce?

2024-08-27 23:05 UTC, chmanie commented
I was seeing something similar but thought it was unrelated. I'll investigate!

2024-08-28 08:54 UTC, bassgeta submitted a review, later dismissed
Nice job fixing this, I went through the steps and only got successful transactions :+1: 
![image](https://github.com/user-attachments/assets/19cf54b7-9c34-4328-88bf-c37838ba8906)

2024-08-28 11:59 UTC, chmanie commented
I will do a little change for this and add a lambda to fail the transactions

2024-08-29 14:55 UTC, chmanie commented
A LITTLE CHANGE he said

2024-09-02 19:35 UTC, chmanie commented on amplify/backend/api/colonycdapp/schema/schema.graphql
> +  Initialize user (for now only cancels pending transactions)
I gave this a bit of a more general name to be able to add more to this lambda if we so wish

2024-09-02 19:36 UTC, chmanie commented on amplify/backend/function/initializeUser/initializeUser-cloudformation-template.json
I'm not super sure if this is needed, please help, lambda-people

2024-09-02 19:37 UTC, chmanie commented on docker/colony-cdapp-dev-env-auth-proxy
> +ENV AUTH_PROXY_HASH=b83e72fd73bc676fc78872d2a646c140e521c0b3
This needs to be adjusted once https://github.com/JoinColony/colonyCDappAuthProxy/pull/25 and https://github.com/JoinColony/colonyCDappAuthProxy/pull/26/files are merged

2024-09-02 19:39 UTC, chmanie commented on src/state/transactionState.ts
> +          result.initializeUser.failedTransactions.forEach((failedTx) => {
This adjusts the Apollo cache accordingly for all failed transactions.

2024-09-16 21:48 UTC, jakubcolony requested changes
Changes look sensible, however I can't seem to be able to connect my wallet due to the mutation failing. I tried it a bunch of times and it worked once out of 10 attempts so maybe there's a race condition?


https://github.com/user-attachments/assets/90c35c3b-4f9e-4a0a-9ce4-47925d1bd240

2024-09-17 09:15 UTC, chmanie commented on amplify/backend/function/initializeUser/src/index.js
> +    );
I have absolutely no idea :D

What was I thinking? I'll change that ;)

2024-09-17 09:15 UTC, chmanie commented on amplify/backend/function/initializeUser/src/utils.js
> +};
Good catch that must have been a c&p thing

2024-09-17 09:17 UTC, chmanie commented on amplify/backend/function/initializeUser/src/utils.js
> +const graphqlRequest = async (queryOrMutation, variables, url, authKey) => {
And how did this ever work without being exported??

2024-09-17 09:28 UTC, chmanie commented
> I tried it a bunch of times and it worked once out of 10 attempts so maybe there's a race condition?

You were indeed right about the race condition. I must have been in a nebulous state of mind when I wrote this code. Please try again now :)

2024-09-17 10:59 UTC, jakubcolony requested changes
After the changes I'm still unable to connect my wallet as the mutation keeps returning 403. I think you may need to always allow it in the auth proxy so that it can make it to the lambda.


https://github.com/user-attachments/assets/ab72aa13-975d-4421-900f-bcd61cf76ea4

2024-09-17 22:17 UTC, jakubcolony reviewed
After I changed the auth proxy hash to point at [colonyCDappAuthProxy#29](https://github.com/JoinColony/colonyCDappAuthProxy/pull/29) I was able to connect wallet so that issue is resolved 👍 

As you can see on the recording, I ran the mutation with only IDs and createdAt fields changed and confirmed the transactions had been failed, however the `failedTransactions` array from the lambda is empty. I was expecting it to contain the 3 transactions I created.

Additionally, this may not be relevant to this PR, but want to confirm if it's a genuine issue. The transactions I created are not showing in the user hub transactions list despite being returned by the query. Their createdAt field is set to the future so they should be on the top of the list. 


https://github.com/user-attachments/assets/82e1419f-faea-4b8a-aa20-03afe3568723


https://github.com/user-attachments/assets/82e1419f-faea-4b8a-aa20-03afe3568723

2024-09-18 12:47 UTC, chmanie commented
Alright, I fixed the issue that the `failedTransactions` wouldn't return anything and bumped the auth proxy hash to the current master which should work.

> Additionally, this may not be relevant to this PR, but want to confirm if it's a genuine issue. The transactions I created are not showing in the user hub transactions list despite being returned by the query. Their createdAt field is set to the future so they should be on the top of the list.

Just by looking at it I can't figure out why they are not shown either, nevertheless, this is a bit of a contrived case. Try to create transactions that actually contain all required fields and see if they're not showing, still. Otherwise feel free to open an issue for this.

2024-09-18 18:23 UTC, jakubcolony approved these changes
UI initiated transactions are showing in the list correctly, so there's probably nothing to worry about.

This time I got the 3 transactions in the response array:
<img width="463" alt="image" src="https://github.com/user-attachments/assets/2828a56e-e335-49c2-b63a-6cea769359db">

Nice work @chmanie 💯

2024-09-19 08:41 UTC, iamsamgibbs approved these changes
Nice changes @chmanie ! Having this in a lambda feels quite a bit neater than what was here before. Tested and can see the transactions getting failed:

<img width="701" alt="Screenshot 2024-09-19 at 09 36 25" src="https://github.com/user-attachments/assets/67e05b4a-d9ad-4e91-bdfb-2498406a7161">

I also couldn't see them in the UI. I wonder if it's possible to create a testing scenario via the UI where a transaction is deliberately left in a created / pending / ready state and checking if it properly failed when refreshing?

2024-09-19 11:19 UTC, merged