[Dashboard] Feat: Add members and followers to colony header
JoinColony/colonyCDapp pull request #3038
Opened 2024-08-29 13:26 UTC by iamsamgibbs

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #2847

2024-08-30 10:04 UTC, Nortsova requested changes
Great work @iamsamgibbs 👏

I can confirm that after load create-data script I can see 4 members and 32 followers:
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/5fa6fd4a-3611-4dc1-9822-1c6d5fb61510">

Members was added after Step 4 and Step 9:
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/fa7691f1-db6a-4671-a969-929012fedd91">

For new colony I can see 1 member:
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/f29600e5-6ff1-408b-8a05-59d567543ba4">

After I invited amy number of followers became 2:
<img width="303" alt="image" src="https://github.com/user-attachments/assets/5dcf18d6-010d-4fe2-ac96-4c24a4aff63b">

After assigned amy permissions she became a member:
<img width="349" alt="image" src="https://github.com/user-attachments/assets/a58c36b1-fbb1-4255-9d79-a119c487e9a3">

Skeleton looks great:
<img width="432" alt="image" src="https://github.com/user-attachments/assets/56dda4a9-7b68-4209-a5e2-d80d420de3a5">

Here is a couple of comments that I observed, but please feel free to ignore if it is not related to this PR:

It seems that avatars in the design have more distance: 
<img width="122" alt="image" src="https://github.com/user-attachments/assets/ed8e3f76-5f43-44ed-a6f1-4c1a9c1da554">

And padding top should be a little bit more: 
<img width="578" alt="image" src="https://github.com/user-attachments/assets/9b812543-e82b-4510-9b50-fbe15a7b36ae">

2024-08-30 10:17 UTC, iamsamgibbs commented
Thanks for the review @Nortsova ! Good catch on the avatar overlap distance, I'll fix that up.

I also noticed the top padding but felt it was out of scope as it effects a bunch of the pages not just the dashboard header.

2024-08-30 19:14 UTC, Nortsova approved these changes
<img width="224" alt="image" src="https://github.com/user-attachments/assets/83706079-7ea9-492f-bd5e-8f28d7985d4c">

Thank you for fixing this small issue, now it works perfectly! 👏

2024-09-02 07:16 UTC, mmioana approved these changes
Thank you for picking up this issue @iamsamgibbs 🙏 Amazing work as usual 🌟 

Can confirm all the cases in the testing steps work flawlessly ✨ 

After running `create-data` script
![Screenshot 2024-09-02 at 08 36 29](https://github.com/user-attachments/assets/d97be4ce-8795-49cf-beab-b47a064d7e11)
![Screenshot 2024-09-02 at 08 38 39](https://github.com/user-attachments/assets/3de25a2f-d8c3-4000-9b3e-fd5befa32264)

Managing permissions for a member without
![Screenshot 2024-09-02 at 08 40 28](https://github.com/user-attachments/assets/2b2333f6-8518-44c2-b037-cbd5d4488b5e)
Number of members gets increased to `5`
![Screenshot 2024-09-02 at 08 40 42](https://github.com/user-attachments/assets/6f8d61fe-67fa-40d2-a96b-0b28fb01ed47)

Awarding reputation
![Screenshot 2024-09-02 at 08 41 24](https://github.com/user-attachments/assets/0e5f6f6f-fd87-4bca-adde-582a2bd5a6fc)

<img width="444" alt="Screenshot 2024-09-02 at 08 42 01" src="https://github.com/user-attachments/assets/8f93bf8e-ac99-4a41-8811-c8f3180607a6">

Number of members gets increased to `6`
![Screenshot 2024-09-02 at 08 42 21](https://github.com/user-attachments/assets/e3f24399-2469-496a-9e5a-a67486e8f2ed)


Switch to `Andromeda`
![Screenshot 2024-09-02 at 08 42 37](https://github.com/user-attachments/assets/78b920d1-c449-4ff3-95cc-ef71c4a0b0e9)

Switch to `Rocinate`

![Screenshot 2024-09-02 at 08 42 47](https://github.com/user-attachments/assets/53369867-b637-48bc-997d-fae7c86988f8)


Creating a new colony
<img width="448" alt="Screenshot 2024-09-02 at 08 43 56" src="https://github.com/user-attachments/assets/8846f53d-421f-4b68-a1fa-3dcf93ee847e">
<img width="1039" alt="Screenshot 2024-09-02 at 08 44 17" src="https://github.com/user-attachments/assets/afe10e50-4185-4058-83b9-3f437cb13aca">
`amy` joins new colony
![Screenshot 2024-09-02 at 08 45 16](https://github.com/user-attachments/assets/85887a19-818d-480b-a1ec-dbbf0ea08ad1)
![Screenshot 2024-09-02 at 08 45 46](https://github.com/user-attachments/assets/2502fe89-641f-4fdc-a701-d901e9a7648d)
Adding permissions to `amy`
![Screenshot 2024-09-02 at 08 46 53](https://github.com/user-attachments/assets/c4496e50-7cbd-4426-8792-92c1aa3ceb41)
![Screenshot 2024-09-02 at 08 47 06](https://github.com/user-attachments/assets/d7984ea9-8290-4b08-a0be-6e3adbcc75c4)
`amy` leaves the newly created colony 
![Screenshot 2024-09-02 at 08 47 52](https://github.com/user-attachments/assets/444d35cb-9af4-4d62-a88e-75d8e8e835c5)

Left a couple of refactoring comments, but feel free to tackle them if you consider they make sense

2024-09-02 07:16 UTC, mmioana commented on src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/MembersInformation/MembersInformation.tsx
> +          ) ||
Could we extract this `(role) => role?.domain.nativeId === nativeDomainId` into a more generic function

```
type EntityWithDomainNativeId = {
  domain: Pick<Domain, 'nativeId'>
};

const filterByDomainNativeId = (entity: EntityWithDomainNativeId | null, nativeDomainId) => entity?.domain.nativeId === nativeDomainId
```

And then use it `(role) => filterByDomainNativeId(role, nativeDomainId)`

2024-09-02 07:16 UTC, mmioana commented on src/components/v5/frame/ColonyHome/partials/DashboardHeader/partials/MembersInformation/MembersInformation.tsx
> +          ),
And use the generic function from above also here `(rep) => filterByDomainNativeId(rep, nativeDomainId),`

2024-09-03 17:02 UTC, rdig approved these changes
Went through the whole testing flow and it behaves as expected, nicely done!

Was on my laptop and it's slower, so the reputation based contributors would load slower (ie: you'd see 5 then immediately refresh to 6)

But all's good, so this is ready to merge!

![Screenshot from 2024-09-03 18-54-13](https://github.com/user-attachments/assets/158a2d5f-6f8e-4f6e-8297-3d4b0218efb3)
![Screenshot from 2024-09-03 18-54-36](https://github.com/user-attachments/assets/ac2e624e-26a3-4776-8fa9-f452d4ef5f12)
![Screenshot from 2024-09-03 18-56-19](https://github.com/user-attachments/assets/bf2531b1-6280-488d-ac94-870310036c15)
![Screenshot from 2024-09-03 18-56-48](https://github.com/user-attachments/assets/967fef5d-89ac-4913-a6bf-c8d022682a8b)
![Screenshot from 2024-09-03 18-57-34](https://github.com/user-attachments/assets/fabcbcab-f164-4f94-b4ea-6ca212464b62)
![Screenshot from 2024-09-03 18-58-44](https://github.com/user-attachments/assets/0cf05a50-de97-41f0-bbbf-4d1ce0fef1de)
![Screenshot from 2024-09-03 18-59-46](https://github.com/user-attachments/assets/d601ac33-9c39-491e-9741-9f86837adbb4)

2024-09-04 07:15 UTC, merged