feat: add new team filter component
JoinColony/colonyCDapp pull request #3068
Opened 2024-09-10 11:51 UTC by bassgeta

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves  #2849

2024-09-13 15:28 UTC, iamsamgibbs requested changes
Amazing work on this complicated component! It looks and works really great!

I've left one very minor comment regarding a border - which I think is the only "must fix" issue before approving. Everything else in this comment are more edge case / nice to have.

The items in the dropdown go bold on hover which is as expected, but it causes the width of the container to increase. On the figma design the container is the same size when an item is hover and not hovered, so I don't think this is desired. Although I imagine it will also be a bit of a pain to fix this.

https://github.com/user-attachments/assets/d979b4d4-81c9-432f-be17-4c1ebc6e7e4b

I found this weird edge case when the team names will fill it on a first load, but once you resize below the full screen width then they won't go back to filling up the entire space. (Probably enough of an edge case that we don't need to worry about it).

https://github.com/user-attachments/assets/859faeae-9069-4f5c-9fe3-35c76a8dfaa1

I tested adding new teams until it exceeded the width of the page without issue. 🎉

This is more of a design thing I guess, but I would expect mobile to behave it a similar way to desktop with the "active" team showing earlier in the menu on a page load. For example, navigating directly to `http://localhost:9091/planex?team=4` will have the `Rocinante` team selected, but it requires a scroll before it shows.

<img width="408" alt="Screenshot 2024-09-13 at 15 58 17" src="https://github.com/user-attachments/assets/7f434001-798b-4250-97e7-56c61e9fc6e3">

<img width="408" alt="Screenshot 2024-09-13 at 15 58 30" src="https://github.com/user-attachments/assets/7f243b4e-2cf3-44e1-8dcc-ca7a8406047b">

However, I imagine this would be a huge pain to implement and would require further discussion with product / design.

2024-09-16 08:09 UTC, bassgeta commented
> Amazing work on this complicated component! It looks and works really great!
> 
> I've left one very minor comment regarding a border - which I think is the only "must fix" issue before approving. Everything else in this comment are more edge case / nice to have.
> 
> The items in the dropdown go bold on hover which is as expected, but it causes the width of the container to increase. On the figma design the container is the same size when an item is hover and not hovered, so I don't think this is desired. Although I imagine it will also be a bit of a pain to fix this.
> Screen.Recording.2024-09-13.at.16.00.04.mov
> 
> I found this weird edge case when the team names will fill it on a first load, but once you resize below the full screen width then they won't go back to filling up the entire space. (Probably enough of an edge case that we don't need to worry about it).
> Screen.Recording.2024-09-13.at.16.06.57.mov
> 
> I tested adding new teams until it exceeded the width of the page without issue. 🎉
> 
> This is more of a design thing I guess, but I would expect mobile to behave it a similar way to desktop with the "active" team showing earlier in the menu on a page load. For example, navigating directly to `http://localhost:9091/planex?team=4` will have the `Rocinante` team selected, but it requires a scroll before it shows.
> <img alt="Screenshot 2024-09-13 at 15 58 17" width="408" src="https://private-user-images.githubusercontent.com/34915414/367355159-7f434001-798b-4250-97e7-56c61e9fc6e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzM1NDIsIm5iZiI6MTcyNjQ3MzI0MiwicGF0aCI6Ii8zNDkxNTQxNC8zNjczNTUxNTktN2Y0MzQwMDEtNzk4Yi00MjUwLTk3ZTctNTZjNjFlOWZjNmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA3NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3OWFiNzkwNzgxODMzZWRlM2ZjZGI1OThjY2M3NzU0ZTdmM2Q0ZTI5MzMxZTYyMTRhZGZmNDFjMGExNGIwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GgPwbuEupXXvTwgemsh25pDL8K7m4IDR21Xz6gfqgJA"> <img alt="Screenshot 2024-09-13 at 15 58 30" width="408" src="https://private-user-images.githubusercontent.com/34915414/367355169-7f243b4e-2cf3-44e1-8dcc-ca7a8406047b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzM1NDIsIm5iZiI6MTcyNjQ3MzI0MiwicGF0aCI6Ii8zNDkxNTQxNC8zNjczNTUxNjktN2YyNDNiNGUtMmNmMy00NGUxLThkY2MtY2E3YTg0MDYwNDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA3NTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MGY1MzI1ZmQ4MjI4Yjc2ZGUxZDZjOWE1OGQwZTY5MzRhMDVlM2UyNTkzNmNjMzQxN2YzYmI2ZmNlZTBkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kJDaboV1oZfgavlvs0Oo_Y023ayu5Wta3yPTnJG1X2s">
> 
> However, I imagine this would be a huge pain to implement and would require further discussion with product / design.

Yeah it does behave a bit weirdly when you resize the window back and forth, which would probably be a bit of a pain to fix, I was thinking of rerendering it whenever `window.width` changes and see if that would work. So I'll give it a shot if maybe that would solve it :D 

Regarding the last point for the mobile scroller, I think it's a valid point, but maybe we can do that separately since it'll involve at least **some** extra shennanigans.

2024-09-16 11:45 UTC, rdig approved these changes
This was suuuuuper complex to write, and it's going to take even more sanity away from you until you actually get to merge it.

I've tested kinda all the interactions you listed plus some more, and found it mostly acceptable _(minus all the styling issues that Sam pointed to)_

I'll first list all the testing I've done, then I'll highlight the "weird" parts of the UI I think that we should be aware of, even if we might not necessarily want to change/fix.


https://github.com/user-attachments/assets/fe92a64a-f27f-41d2-8032-e7846740c4cd

https://github.com/user-attachments/assets/d102cb23-6e72-4c74-add8-1830f1df5912

https://github.com/user-attachments/assets/3c03fffc-dc89-4d8d-b2b9-c68be8370291

https://github.com/user-attachments/assets/aaf8727a-1996-40e8-b161-dec8eb970865

If you keep clicking the ">" icon, to scroll through the domains, you can get into a pattern where it will run out of them, show the "+" and you keep clicking bringing up the _Create New Domain_ action

https://github.com/user-attachments/assets/353a913f-235f-415d-bcff-2ac649e2edf8

A selected domain which appears at the end of the list will get hidden by the UI, when the viewport is resized.

I actually don't think this is a big issue, as you can scroll to it using the ">" icon, but is more of a thing we should be aware of

https://github.com/user-attachments/assets/7716916e-0f51-4a71-8b9e-636cd4ec682e

2024-09-16 11:51 UTC, mmioana requested changes
Awesome hardcode work on this one @bassgeta 🥇 

Tested on desktop
![Screenshot 2024-09-16 at 13 46 42](https://github.com/user-attachments/assets/a510c2d4-d744-44d1-b7ad-65f6b0e78cb2)
![Screenshot 2024-09-16 at 13 46 53](https://github.com/user-attachments/assets/d93e86ac-035a-4069-b375-54fc92c8ddd2)
![Screenshot 2024-09-16 at 13 46 58](https://github.com/user-attachments/assets/e0f70ac9-1b44-4462-9b47-24f967d72559)


https://github.com/user-attachments/assets/bf426362-43e4-4b4e-b063-f994ffe87606

![Screenshot 2024-09-16 at 13 45 24](https://github.com/user-attachments/assets/682a2949-8ac1-4416-892b-ed9aecf6078a)

And on mobile

![Screenshot 2024-09-16 at 13 47 43](https://github.com/user-attachments/assets/a5c95d51-324e-4ebe-af33-315f12e25c5f)
![Screenshot 2024-09-16 at 13 47 52](https://github.com/user-attachments/assets/9ced3de4-5fa7-42a1-8fbd-2f059f8d2028)
![Screenshot 2024-09-16 at 13 47 57](https://github.com/user-attachments/assets/111ae5d4-3a1c-4d16-88fc-620d3cba5aa4)

And new colony for the empty state
![Screenshot 2024-09-16 at 13 48 37](https://github.com/user-attachments/assets/9d3255f5-f8eb-4e6c-a8c9-a63e0d1ca58c)


I left some minor refactoring comments, would highly appreciate if you can tackle them 🙏

2024-09-16 11:51 UTC, mmioana commented on src/components/v5/shared/TeamFilter/partials/AllTeamsItem.tsx
> +        'border-r border-solid border-gray-200 px-4 py-2 text-3',
By using `text-3` the `font-semibold` or `font-medium` get overridden
So either use `!font-semibold` and `!font-medium` OR replace `text-3` with `text-sm`

2024-09-16 11:51 UTC, mmioana commented on src/components/v5/shared/TeamFilter/partials/CreateNewTeamItem.tsx
> +      <Plus size={16} />
According to Figma this should be `18`

2024-09-16 11:51 UTC, mmioana commented on src/components/v5/shared/TeamFilter/partials/DesktopTeamFilter/DesktopTeamFilter.tsx
> +      <AllTeamsItem selected={selectedDomain === undefined} />
Can we extract this into a constant `const isAllTeamsFilterActive = selectedDomain === undefined` and then use it here
```suggestion
      <AllTeamsItem selected={isAllTeamsFilterActive} />
```

2024-09-16 11:51 UTC, mmioana commented on src/components/v5/shared/TeamFilter/partials/DesktopTeamFilter/DesktopTeamFilter.tsx
Would it make sense to extract all `useEffect` and `useMemo` into a separate hook?

2024-09-16 11:51 UTC, mmioana commented on src/components/v5/shared/TeamFilter/partials/LeftButton.tsx
> +      <CaretLeft size={14} />
`18` also here

2024-09-16 11:51 UTC, mmioana commented on src/components/v5/shared/TeamFilter/partials/RightButton.tsx
> +      <CaretRight size={14} />
`18` also here

2024-09-16 11:51 UTC, mmioana commented on src/components/v5/shared/TeamFilter/partials/TeamsDropdown/TeamsDropdown.tsx
> +              className="w-full text-sm font-medium text-gray-700 hover:font-semibold hover:text-gray-900"
We need to left-align the text for all items in the dropdown, so please add `text-start`

2024-09-16 11:51 UTC, mmioana commented on src/components/v5/shared/TeamFilter/partials/TeamItem.tsx
> +export default TeamItem;
We could make use of `useScrollIntoView` for mobile

```suggestion
import clsx from 'clsx';
import React, { type FC, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useMobile } from '~hooks';
import { useScrollIntoView } from '~hooks/useScrollIntoView';

import { TEAM_SEARCH_PARAM } from '~routes/index.ts';
import { type Domain } from '~types/graphql.ts';
import { getTeamColor } from '~utils/teams.ts';

const displayName = 'v5.shared.TeamFilter.partials.TeamItem';

interface TeamItemProps {
  selected: boolean;
  domain: Domain;
}

const TeamItem: FC<TeamItemProps> = ({ domain, selected }) => {
  const [searchParams, setSearchParams] = useSearchParams();
  const { ref: teamItemRef, scroll } = useScrollIntoView<HTMLButtonElement>()
  const isMobile = useMobile();

  const teamColor = getTeamColor(domain.metadata?.color);

  useEffect(() => {
    if (selected && isMobile) {
      scroll({
        block: 'end',
        inline: 'center',
        behavior: 'smooth'
      })
    }
  }, [selected, isMobile])

  const handleClick = () => {
    if (selected) {
      searchParams.delete(TEAM_SEARCH_PARAM);
      setSearchParams(searchParams);
    } else {
      searchParams.set(TEAM_SEARCH_PARAM, domain.nativeId.toString());
      setSearchParams(searchParams);
    }
  };

  return (
    <button
      type="button"
      className={clsx(
        'w-full bg-base-white px-4 py-2 text-3',
        selected ? teamColor : null,
        {
          'border-r border-solid border-gray-200 font-medium text-gray-700':
            !selected,
          'border-0 font-semibold text-base-white': selected,
        },
      )}
      onClick={handleClick}
      ref={teamItemRef}
    >
      {domain.metadata?.name ?? domain.id}
    </button>
  );
};

TeamItem.displayName = displayName;
export default TeamItem;
```

2024-09-17 15:03 UTC, mmioana approved these changes
Thank you for doing the changes @bassgeta! Stellar work on this one 🌟🥇 


https://github.com/user-attachments/assets/ac6fcff8-8863-4246-b1be-6b4c3238d291


https://github.com/user-attachments/assets/036f09c1-d15c-4910-ac65-fa7d84d1399d


https://github.com/user-attachments/assets/375d8c97-330e-4753-afe0-00fa5eb50464


And the selected filter also scrolls into view 🤩 

https://github.com/user-attachments/assets/7f8e9c38-11fc-4e95-b8ae-44b46074feb3

2024-09-18 06:56 UTC, iamsamgibbs approved these changes
Everything looks great, nice job, lets get it merged!

<img width="1163" alt="Screenshot 2024-09-18 at 07 56 25" src="https://github.com/user-attachments/assets/a094d1b3-9b31-4885-ba84-e7e5d980a0cb">

2024-09-18 08:36 UTC, merged