Feat: Update reputation chart values
JoinColony/colonyCDapp pull request #3072
Opened 2024-09-11 07:48 UTC by mmioana

## Description

- We want to update the domain reputation percentage shown in the reputation pie chart, excluding the General team from the total reputation. Based on the normalised total reputation value, we now compute the domain percentages and do not rely on the `reputationPercentage` each domain has.

**How it currently works:**
```
Total reputation: 12,500

General:     2,500 reputation (20%) (earnt specifically in General)

We show this in the chart:
Dev:         2,500 reputation (20%)
Design:      2,500 reputation (20%)
Ops:         2,500 reputation (20%)
All other:   2,500 reputation (20%)
```
**How we propose the calculation to work:**
```
Total reputation: 12,500

General:     2,500 reputation (earnt specifically in General)

Total team reputation: 12,500 - 2,500 = 10,000

We show this in the chart:
Dev:         2,500 reputation (25%)
Design:      2,500 reputation (25%)
Ops:         2,500 reputation (25%)
All other:   2,500 reputation (25%)
```
## Testing

TODO: Please ensure the domain reputation percentages are correctly computed.

* Step 1. Make sure to run the `create-data` script
* Step 2. Go to the teams page and note the reputation percentage values for the domains

![Screenshot 2024-09-11 at 09 20 15](https://github.com/user-attachments/assets/89a5e893-891e-4877-8a07-abe3c6c25c87)

* Step 3. Go to the dashboard page and check the values displayed in the `Influence by team` widget - they should be slightly increased given we exclude the General team reputation from the total reputation

![Screenshot 2024-09-11 at 09 21 31](https://github.com/user-attachments/assets/f6a667dc-a961-4a2d-8b33-f13022a6888b)

* Step 4. Now let's create a new colony by running the `create-colony-url` script
* Step 5. On the dashboard page, the `Influence by team` widget should firstly display no reputation

![Screenshot 2024-09-11 at 09 24 25](https://github.com/user-attachments/assets/f5f1290d-65a2-4637-bbd3-c5f7c3470ed7)

* Step 6. Make sure the reputation toggle is on - http://0.0.0.0:3001/reputation/monitor/toggle
* Step 7. Award `leela` some reputation 

![Screenshot 2024-09-11 at 09 28 14](https://github.com/user-attachments/assets/a890cf59-2f9e-41ff-9112-346a7b84d955)

* Step 8. Wait a bit and then refresh the dashboard page - the `Influence by team` widget should display only `General` with 100%

![Screenshot 2024-09-11 at 09 27 01](https://github.com/user-attachments/assets/e868f89c-4e0c-4c6e-a150-e2162f2f3010)

* Step 9. Create 2 more domains (even more if you feel like it)
* Step 10. Transfer some funds from `planex` to the newly created colony
* Step 11. Accept the incoming funds in the newly created colony http://localhost:9091/{COLONY_NAME}/incoming
* Step 12. Transfer some of the funds from General to each of the newly created domains
* Step 13. Make a simple payment to `leela` from the first domain
* Step 14. After a bit, the chart should update and only show the first domain

![Screenshot 2024-09-11 at 09 28 14](https://github.com/user-attachments/assets/b5f4b1c4-547d-4c73-b83f-c79a4887686f)
* Step 15. Make a simple payment to `leela` from the second domain
* Step 16. After a bit, the chart should update and display both domains

![Screenshot 2024-09-11 at 09 45 29](https://github.com/user-attachments/assets/422d8c3d-617e-4651-b953-6649887f24e6)

* Step 17. If you visit the teams page, note the values are slightly smaller than the ones displayed in the `Influence by team` widget 

![Screenshot 2024-09-11 at 09 47 12](https://github.com/user-attachments/assets/c51c06ed-2af1-448b-9235-f84ef806a9ef)

Please feel free testing some more use cases regarding the domain reputation updates and check the values 

## Diffs

**Changes** 🏗

* Update the values retrieved by `getTeamReputationChartData`

Resolves [#2656](https://github.com/JoinColony/colonyCDapp/issues/2656)

2024-09-11 15:44 UTC, bassgeta approved these changes
Nice and straight forward solution, legit :100: 
My team reputation:
![image](https://github.com/user-attachments/assets/dcd5accd-3c02-47bb-864c-569af6fe98d5)
The chart:
![image](https://github.com/user-attachments/assets/38d38c54-bb59-4760-ba61-7bad8c0ef2c3)
After giving some reputation to leela and forwarding the block time:
![image](https://github.com/user-attachments/assets/bb228801-5b56-4a42-99df-d46abbb4860e)
Making a simple payment from a new domain with 11 CREDS:
![image](https://github.com/user-attachments/assets/ceb86b16-1226-416f-a306-328b761040f4)
A simple payment from the second domain with 5 CREDS:
![image](https://github.com/user-attachments/assets/3e18dab3-2a28-402c-a474-2e606847a1ec)

Let's go :sunglasses:

2024-09-13 01:29 UTC, rumzledz commented
There's probably something going wrong on my local @mmioana but I followed your steps all the way to making a Payment for Leela from a Subdomain -- you can sort of see my actions history in the Latest activity table. But for some reason the Influence by team chart isn't updating for me. Let's jump on a call tomorrow because I need your wisdom 🧘 
![image](https://github.com/user-attachments/assets/c296f042-69ef-4913-af01-ea3bf0bd8b18)

2024-09-13 08:35 UTC, rdig requested changes
Tested this and it works exactly as your testing steps, so from that perspective all good.

The only thing that made me reject this is that _(I think)_ there's a bug in the charting software, which makes the donut chart not fill 100% of it's alloted space _(you'll see what I mean in the screenshots below)_


![Screenshot from 2024-09-13 09-52-02](https://github.com/user-attachments/assets/01d6c051-9f3b-43f2-a118-b13127f8fa0d)
![Screenshot from 2024-09-13 09-52-55](https://github.com/user-attachments/assets/1a8bc52f-0938-41d7-9289-22795109d8a2)
![Screenshot from 2024-09-13 09-55-20](https://github.com/user-attachments/assets/00f5e041-ebce-4e8a-96ee-52c3bde34b33)
![Screenshot from 2024-09-13 10-00-22](https://github.com/user-attachments/assets/0ea04336-3ea9-4f75-9153-7b35e78ef3bc)
![Screenshot from 2024-09-13 10-00-43](https://github.com/user-attachments/assets/8d3f609d-3a72-4b9a-95c2-3bff97588662)
![Screenshot from 2024-09-13 10-03-40](https://github.com/user-attachments/assets/e51d0e17-5e65-4b18-909e-e621e6ccdf1b)
![Screenshot from 2024-09-13 10-04-22](https://github.com/user-attachments/assets/506a9308-9403-48b8-808c-98dfc62b34f1)
![Screenshot from 2024-09-13 10-08-30](https://github.com/user-attachments/assets/c2587ab0-0636-431f-92c3-a91ba6ad7776)
![Screenshot from 2024-09-13 10-09-46](https://github.com/user-attachments/assets/60ac5dab-3560-4851-b833-83e1ffc58b21)
![Screenshot from 2024-09-13 10-17-18](https://github.com/user-attachments/assets/6fe65af1-2742-403c-bb46-b3c906c7e90c)
![Screenshot from 2024-09-13 10-17-59](https://github.com/user-attachments/assets/97a5ac6f-86b8-430b-847a-d58bd4ec5422)
![Screenshot from 2024-09-13 10-21-29](https://github.com/user-attachments/assets/a44c9893-0ad3-4ee9-b79b-d2d8eeedd825)
![Screenshot from 2024-09-13 10-22-05](https://github.com/user-attachments/assets/fcf2cff6-bfd1-479d-8464-30496a490f08)
![Screenshot from 2024-09-13 10-22-41](https://github.com/user-attachments/assets/3445d9fe-85c6-435e-93cf-f6ce795110ae)
![Screenshot from 2024-09-13 10-23-48](https://github.com/user-attachments/assets/b3f57b38-d0b1-411a-abb2-733908d5c8eb)
![Screenshot from 2024-09-13 10-24-11](https://github.com/user-attachments/assets/79518294-4e25-4906-bae6-3df1df306b09)
![Screenshot from 2024-09-13 10-25-30](https://github.com/user-attachments/assets/19523a02-7fc8-4b98-b289-414887b49467)

So this is the example of the chart not rendering fully in it's allotted space, both with a single domain, and with two domain's worth of reputation

![Screenshot from 2024-09-13 10-22-05](https://github.com/user-attachments/assets/fcf2cff6-bfd1-479d-8464-30496a490f08)
![Screenshot from 2024-09-13 10-22-41](https://github.com/user-attachments/assets/3445d9fe-85c6-435e-93cf-f6ce795110ae)
![Screenshot from 2024-09-13 10-23-48](https://github.com/user-attachments/assets/b3f57b38-d0b1-411a-abb2-733908d5c8eb)
![Screenshot from 2024-09-13 10-24-11](https://github.com/user-attachments/assets/79518294-4e25-4906-bae6-3df1df306b09)

The way I made it render fully was to to open the create action sidebar _(don't know why that works)_

Personally, I don't think this is an issue, but I'm sure design or product will pick up on this, so might as well fix it now.

2024-09-13 14:06 UTC, mmioana commented
@rdig thank you for testing this out 🙏 

So the issue you're mentioning regarding displaying the 0% for All teams was exactly what I treated here
https://github.com/JoinColony/colonyCDapp/compare/75130a20b3240cdc65bc07eac4f8eb30e6ffb638..41e86689b5dfdee29213ba973db7dee3252f1978

And I didn't manage to reproduce it locally anymore 😢 
I know it's a silly question, but do you have the latest branch version?

2024-09-13 19:46 UTC, Nortsova approved these changes
Hey @mmioana , great work! 🙌

After the first payment, the chart was updated and only showed the first domain:
<img width="450" alt="image" src="https://github.com/user-attachments/assets/a6f231e8-93a2-454f-baaf-5552ee68ccdf">
After the second payment, the chart showed both domains:
<img width="459" alt="image" src="https://github.com/user-attachments/assets/ef9d1084-97c0-4ebb-990d-61f64cbb62e4">
After the third payment, the chart was updated with all 3 teams:
<img width="475" alt="image" src="https://github.com/user-attachments/assets/0a0ca0d6-9230-4be8-b1f2-fee01e9ab3a8">

Team page:
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/423f3634-4eb8-47f7-b45f-607d2057a937">

Also, I am not sure that it is related to current PR, I found that the tooltip and legend values are rounded differently (the tooltip should also round to 2 decimal places):
<img width="447" alt="image" src="https://github.com/user-attachments/assets/3c671a0e-16d6-4a05-b323-f4d835db9128">

Regarding @rdig comment, we can filter chart array and if item 0 just don't push it there ✨🙌

And seems nested domain feature will be really fun 😁

2024-09-16 09:19 UTC, mmioana commented on src/components/v5/frame/ColonyHome/partials/ReputationChart/utils.ts
> +    .filter((domain) => !!domain.reputationPercentage)
@Nortsova I am wondering if this filter is not enough to omit teams having 0 reputation

2024-09-18 08:18 UTC, rdig approved these changes
Can't replicate my initial issue with the charts so I consider this now resolved. Everything seems to be rendered as expected no matter how many different reputation states I throw at it.

Nicely done!


![Screenshot from 2024-09-18 11-04-32](https://github.com/user-attachments/assets/25ca2d3d-2d7b-40b1-ba37-8c553813e523)
![Screenshot from 2024-09-18 11-04-57](https://github.com/user-attachments/assets/57f60404-ec4f-4a12-b200-50d802dc32a5)
![Screenshot from 2024-09-18 11-07-41](https://github.com/user-attachments/assets/82d9c2b2-a857-4989-9287-330b40212ea2)
![Screenshot from 2024-09-18 11-10-59](https://github.com/user-attachments/assets/af7093f4-133c-4695-b032-e7a1ed02b631)
![Screenshot from 2024-09-18 11-12-38](https://github.com/user-attachments/assets/ce416ed3-5233-4e92-b9c7-48749e85f48a)
![Screenshot from 2024-09-18 11-12-50](https://github.com/user-attachments/assets/c9788f94-8457-495a-ae5a-238d6d024f08)
![Screenshot from 2024-09-18 11-16-12](https://github.com/user-attachments/assets/81cae901-310d-4294-b004-6ae22f40c3f4)

2024-09-18 08:25 UTC, merged