[Dashboard] Weekly/monthly funds trend
JoinColony/colonyCDapp pull request #3080
Opened 2024-09-12 12:18 UTC by mmioana

Feat: Add cron lambda to cache all needed previous domain balances

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #2858

2024-09-13 13:42 UTC, mmioana commented on src/hooks/useCurrencyConversionRate.ts
> +export const useCurrencyConversionRate = ({
Need to update this to take historical data into account is date is provided

2024-09-19 09:36 UTC, bassgeta requested changes
D A M N
took me a while to get through everything, but this stuff is actually quite straight forward. Nice job with the caching per day, basically saving us a ton of compute time for subsequent requests :+1: 
Left just some minor "cosmetic" comments which we can tackle, but overall a really great job with this!
So I can confirm that batch processing happens when triggering this lambda:
![image](https://github.com/user-attachments/assets/605f7eb8-6b7c-4f79-9ab1-0df522b1e5b8)
![image](https://github.com/user-attachments/assets/3cac05e8-b353-48cc-b603-4bdac80dc9fb)
![image](https://github.com/user-attachments/assets/678eeca1-ae4b-4a7d-85f3-14bfce2384af)
Filtering over teams works like a charm too:
![image](https://github.com/user-attachments/assets/3bb8c818-799c-469b-b1ca-1839d5bbfeae)
![image](https://github.com/user-attachments/assets/bb919ba1-c734-4ce7-84f5-373c706d6571)
It also doesn't break on mobile:
![image](https://github.com/user-attachments/assets/9b4819ff-3453-463f-ab81-225fd619af4e)

So I think we're good with this implementation, we probably need to run it against large sets of data to see how many resources it's gonna hog :D

2024-09-23 21:52 UTC, jakubcolony requested changes
You've nailed it @mmioana! 🔨 

I left a couple comments but overall the code reads very nicely.

I've noticed some cache entries have `domainId` set to an empty string, if that's expected, should they be `null` instead?

<img width="536" alt="image" src="https://github.com/user-attachments/assets/97db8aa1-d7b0-4d46-8c68-7ddfca30fd1f">

Not sure if this is relevant to this PR, so I'll let you decide how to handle it, when quickly switching between teams, the value for the previously selected team replaces the current one once it loads:

https://github.com/user-attachments/assets/415ab1e1-fdf1-4df1-835d-55c32cd66ce9

Is this expected? The first screenshot shows General's payments at £2,377 yet when All teams is selected, the total is £0:
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/60f136d5-3237-48c3-a969-671648664b25">
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/f66f4de5-4ef9-45a8-9d20-23bd7288a75f">

2024-09-23 21:52 UTC, jakubcolony commented on amplify/backend/api/colonycdapp/schema/balance.graphql
> +  timeframeType: TimeframeType
Should this be nullable?

2024-09-24 16:55 UTC, mmioana commented
Thank you for your throughout review @jakubcolony 🙌 💯 
I did made some of the suggested changes and fixed the problem with the wrong data being shown, could you please re-check?

2024-09-25 12:42 UTC, Nortsova reviewed
Thank you, @mmioana! ✨ You've done an enormous amount of work!

I can confirm that trends works good with historical data: 
<img width="622" alt="image" src="https://github.com/user-attachments/assets/07d4a310-4f73-47cd-a2a4-16f93837117c">

I left a couple of small comments to this PR. Thank you again for your work! 🙌

2024-09-25 12:42 UTC, Nortsova commented on src/components/v5/frame/ColonyHome/partials/TotalInOutBalance/partials/TitledSection.tsx
> +              />
In `FundsCardsTotalDescription.tsx` we have another logic for arrow up/down. Don't you want to move that arrow in a separate component, so we can reuse it in FundsCardsTotalDescription and here?

2024-09-25 12:42 UTC, Nortsova commented on amplify/backend/api/colonycdapp/schema/balance.graphql
> +  totalUSDC: String
just a random question: is it okay that we use USDC as a constant here? shouldn't it be something like "totalBase" + "baseCurrency" so we can change it in the future? Or it is fine to have permanent conversion to USDC?

2024-09-25 12:42 UTC, Nortsova commented on amplify/backend/function/fetchDomainBalance/src/utils.js
> +const getPeriodFromNow = (timeframePeriod, timeframeType, timeframePeriodEndDate) => {
sorry, could you please explain why this is called "fromNow"? thank you ❤️

2024-09-25 12:49 UTC, Nortsova commented on amplify/backend/function/fetchDomainBalance/src/utils.js
> +const getPeriodFromNow = (timeframePeriod, timeframeType, timeframePeriodEndDate) => {
And another thing, would it be better to refactor arguments?
like this 
```suggestion
const getPeriodFromNow = (timeframeType, timeframePeriod, timeframePeriodEndDate) => {
```
or
```suggestion
const getPeriodFromNow = ({ timeframeType, timeframePeriod, timeframePeriodEndDate }) => {
```

2024-09-25 13:46 UTC, rumzledz approved these changes
@mmioana went beast mode on this beast ticket 🔥 I paired up with Ioanna over a call to go through the test steps and can confirm that changes are working as expected based on the test steps 💯 

I moved 230 CREDS from General to Andromeda and the bar charts are still working as expected:

<img width="466" alt="Screenshot 2024-09-25 at 20 55 22" src="https://github.com/user-attachments/assets/8847cd5a-71ff-4fae-b6c8-4ca573cfcbb5">

I updated the cache and the previous 30 days trend value has been updated correctly as well:

<img width="1182" alt="Screenshot 2024-09-25 at 20 51 35" src="https://github.com/user-attachments/assets/3aa4fdb4-2272-48b0-a3a8-88e29a767c5e">

2024-09-25 15:01 UTC, Nortsova approved these changes
Thank you @mmioana for your fast changes! Everything work as expected:

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/7cbe919e-ebff-43b3-8bf0-1e4e8250b948">
<img width="998" alt="image" src="https://github.com/user-attachments/assets/795f249c-ecca-4797-9472-2e108159c836">
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/49d2c568-fbb5-4506-96ab-683389d11813">

Really appreciate your work  🙌 you are a superhero 🦸‍♀️

2024-09-25 18:10 UTC, mmioana commented
Will merge this to avoid rebase conflicts ✅

2024-09-25 18:11 UTC, merged