[Dashboard] feat: reputation chart dropdown menu
JoinColony/colonyCDapp pull request #3088
Opened 2024-09-13 13:57 UTC by bassgeta

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves #3060

2024-09-17 11:38 UTC, mmioana requested changes
Awesome and simple solution @bassgeta 🎉 

![Screenshot 2024-09-17 at 13 37 19](https://github.com/user-attachments/assets/c8f88872-d81c-4625-9c97-b6bbd09fe576)
![Screenshot 2024-09-17 at 13 31 25](https://github.com/user-attachments/assets/f9e17c85-e4ff-44c1-8af7-f252d7f4b6ad)

Clicking the items navigate to the correct page or open the correct action

https://github.com/user-attachments/assets/7dd4e4f8-7765-44b8-850c-313254fe6f8f

There is a font-size mismatch compared to Figma for which I left a comment, if you can please tackle it 🙏

2024-09-17 11:38 UTC, mmioana commented on src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/TeamActionsMenu.tsx
> +const dropdownItemClassName = tw`flex w-full items-center gap-2 rounded-s px-3 py-2 text-gray-900 hover:font-medium md:hover:bg-gray-50`;
Here we should add also `text-md`

Current implementation
![Screenshot 2024-09-17 at 13 30 26](https://github.com/user-attachments/assets/e888f82d-4f6c-453f-9352-8cb5ddb164f1)

Figma
![Screenshot 2024-09-17 at 13 33 46](https://github.com/user-attachments/assets/08c91572-0c70-41b3-8b63-2a28d2d3772f)

2024-09-18 09:59 UTC, mmioana approved these changes
Thank you for the change @bassgeta 💯 now it looks perfect

![Screenshot 2024-09-18 at 11 58 11](https://github.com/user-attachments/assets/dd1af1c9-6fb8-482d-9588-9b8e8fafd6c9)

2024-09-18 19:12 UTC, rumzledz requested changes
Great work on this one @bassgeta ! 🔥 I can confirm that the buttons are doing the right thing:

![Uploading influence popover.gif…]()

I left some really minor UI comments but that's pretty much it!

2024-09-18 19:12 UTC, rumzledz commented on src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/TeamActionsMenu.tsx
> +              <Lock size={18} />
This needs to use the `LockKey` icon based on Figma:

```js
<LockKey size={18} />
```

![Screenshot 2024-09-18 at 19 59 35](https://github.com/user-attachments/assets/71162afa-b8b0-4d47-9a0e-b412503e3ae2)

2024-09-18 19:12 UTC, rumzledz commented on src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/TeamActionsMenu.tsx
> +          'text-gray-600': !visible,
This needs to be color `gray-400` in its non-hovered/non-active state based on the [Figma designs](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4878-76054&t=27Zn8LxD7w4sTlH7-4)

```js
className={clsx('text-gray-400 hover:text-blue-400', {
  '!text-blue-400': visible,
})}
```

![image](https://github.com/user-attachments/assets/2fa418e6-f402-4ca0-aced-4d2fc6c6589b)

2024-09-19 09:54 UTC, rumzledz approved these changes
Thanks for the updates @bassgeta, LGTM! 🚀

2024-09-19 15:09 UTC, davecreaser approved these changes
Nice one @bassgeta, works like a charm and code looks good and clean :)

Tested all the links funcitonalities, hover states, and mobile as you suggested:

<img width="378" alt="Screenshot 2024-09-19 at 16 03 21" src="https://github.com/user-attachments/assets/e292757b-a644-4d25-bb7d-1714d27e2511">
<img width="715" alt="Screenshot 2024-09-19 at 16 04 46" src="https://github.com/user-attachments/assets/6cc6c55d-78c4-4733-ba7f-d7f5aef09b24">

2024-09-19 15:29 UTC, merged