[Dashboard] feat: replace all teams filter in remaining pages
JoinColony/colonyCDapp pull request #3111
Opened 2024-09-17 14:18 UTC by bassgeta

## Description

Replace the old breadcrumb navigation with the new filter component!
[Figma link](https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=4870-44099&t=pWU79XSFvRIH7LiK-4)
![image](https://github.com/user-attachments/assets/f2b0786a-3c68-4ed3-a662-64caa948fd95)

## Testing

Basically go to the following pages and make sure that the filter still works and that it displays nicely
1. Activity feed
2. Balances
3. Incoming funds
4. Teams
5. Agreements
6. Members
7. Permissions

And do note there's one layout bug present but it's being fixed elsewhere
![image](https://github.com/user-attachments/assets/4315987c-d059-4e0b-ac44-45ccdce3a3a1)

When the screen gets wide, the filter is stuck with the content, but the title stays on the lefthand side.

## Diffs

**Changes** 🏗

* Added the `TeamFilter` component to the 7 pages above 

**Deletions** ⚰️

* `BreadcrumbsCardSelect` component
* `useTeamsBreadcrumbs` hook

Resolves  #2860

2024-09-18 09:39 UTC, mmioana requested changes
Smashed another one @bassgeta 💪 👏 

Tested and can confirm the new filters are present on the mentioned pages
![Screenshot 2024-09-18 at 11 21 12](https://github.com/user-attachments/assets/46e392b0-87de-4633-a17e-9974cb5f8814)
![Screenshot 2024-09-18 at 11 21 21](https://github.com/user-attachments/assets/30ad0f9a-49be-41ac-a847-070241d5fb6d)
![Screenshot 2024-09-18 at 11 21 35](https://github.com/user-attachments/assets/be7ea058-93b9-432b-b071-b056486e95b4)
![Screenshot 2024-09-18 at 11 21 39](https://github.com/user-attachments/assets/3da50ab3-077f-4cf2-827f-1744398918c2)
![Screenshot 2024-09-18 at 11 21 45](https://github.com/user-attachments/assets/6b66b67e-e01c-459b-b71c-74e475dd1caa)
![Screenshot 2024-09-18 at 11 21 51](https://github.com/user-attachments/assets/1028eab5-5680-45b3-9195-2f4fecc373fa)
![Screenshot 2024-09-18 at 11 21 58](https://github.com/user-attachments/assets/d3f12511-ee3b-4261-b180-ec1bd413f371)
![Screenshot 2024-09-18 at 11 22 03](https://github.com/user-attachments/assets/42ed083b-254c-471d-a9af-e0c4dd4aa631)

I know you didn't touch these pages, but can confirm the domain filters is not present on the Extensions or Profile pages
![Screenshot 2024-09-18 at 11 22 10](https://github.com/user-attachments/assets/1cbb9d57-283c-4818-8a2c-512980a8649a)
![Screenshot 2024-09-18 at 11 22 20](https://github.com/user-attachments/assets/50d70e45-d33a-446b-9d4f-d7415d471215)

After leaving the refactoring comments for consistency, I'm wondering if it wouldn't make sense to create a new component and just wrap the pages needing the domain filter. What do you think @bassgeta? 😁 

```
const ContentWithDomainFilter: FC<PropsWithChildren> = ({ children }) => {

  return (
    <div className="flex flex-col gap-8">
      <TeamFilter />
      {children}
    </div>
  )
}
```

2024-09-18 09:39 UTC, mmioana commented on src/components/frame/v5/pages/ActivityPage/ActivityPage.tsx
>          <FiltersContextProvider>
For consistency, would suggest to wrap the previous content as you did on the previous pages
```
<div className="flex flex-col gap-8">
      <TeamFilter />
     ...previous page content here
</div>
```

2024-09-18 09:39 UTC, mmioana commented on src/components/frame/v5/pages/AgreementsPage/AgreementsPage.tsx
>      <div>
Here as well

```
<div className="flex flex-col gap-8">
      <TeamFilter />
     ...previous page content here
</div>
```

2024-09-18 09:39 UTC, mmioana commented on src/components/frame/v5/pages/MembersPage/MembersPage.tsx
> +      <TeamFilter />
Here as well

```
<div className="flex flex-col gap-8">
      <TeamFilter />
     ...previous page content here
</div>
```

2024-09-18 09:39 UTC, mmioana commented on src/components/frame/v5/pages/TeamsPage/TeamsPage.tsx
> +      </div>
Here as well

```
<div className="flex flex-col gap-8">
      <TeamFilter />
     ...previous page content here
</div>
```

2024-09-19 11:42 UTC, mmioana approved these changes
Thank you for implementing the suggested changes @bassgeta 💪 💯 

![Screenshot 2024-09-19 at 13 40 33](https://github.com/user-attachments/assets/bca7a2df-fcfa-4c0c-81e3-e1ed5445d3f4)
![Screenshot 2024-09-19 at 13 40 41](https://github.com/user-attachments/assets/08f1f251-406b-49cf-8920-2dc13054207c)
![Screenshot 2024-09-19 at 13 40 44](https://github.com/user-attachments/assets/23c999cb-921b-4e18-902a-0c06f54e3181)
![Screenshot 2024-09-19 at 13 40 46](https://github.com/user-attachments/assets/10caa635-c46d-445f-863a-17090e1aa235)
![Screenshot 2024-09-19 at 13 40 50](https://github.com/user-attachments/assets/05371a86-0a09-43a1-8fc0-07273882fe3e)
![Screenshot 2024-09-19 at 13 40 53](https://github.com/user-attachments/assets/3e22a9d2-0778-4a2d-9591-1c172398c0da)
![Screenshot 2024-09-19 at 13 40 55](https://github.com/user-attachments/assets/c29d5c37-d280-4b0f-9535-1def9c507bcd)
![Screenshot 2024-09-19 at 13 40 58](https://github.com/user-attachments/assets/918c2318-8849-4064-a145-69e8171b3383)

Let's get this one merged 🎉

2024-09-19 16:16 UTC, davecreaser approved these changes
Nice job once again @bassgeta!

It's nice that now the breadcrumbs can just be breadcrumbs 😆 It makes it much simpler! Also agree with the approach of the reusable wrapper component, it's very nice.

It looks like you need to rebase, but I checked the code by just looking at your actual commits and it all looks good. Also tested all the pages you mentioned (including mobile) and everything is as expected! Let's gooo.

<img width="1758" alt="Screenshot 2024-09-19 at 17 12 37" src="https://github.com/user-attachments/assets/4f13c41f-59b3-43cb-a42c-b6e26558d123">
<img width="1736" alt="Screenshot 2024-09-19 at 17 12 53" src="https://github.com/user-attachments/assets/63fa5212-70e7-446e-8207-b9bb08c4963f">
<img width="1750" alt="Screenshot 2024-09-19 at 17 13 07" src="https://github.com/user-attachments/assets/16466e18-614c-414c-8bee-ebebf2cfe17d">
<img width="1791" alt="Screenshot 2024-09-19 at 17 13 18" src="https://github.com/user-attachments/assets/b30a7497-7108-40d8-ab38-da40b2a87021">
<img width="1722" alt="Screenshot 2024-09-19 at 17 13 30" src="https://github.com/user-attachments/assets/0819d42d-52cd-4140-ae77-ee777bfae4d7">
<img width="1749" alt="Screenshot 2024-09-19 at 17 13 41" src="https://github.com/user-attachments/assets/40736482-4e05-4da9-9e85-1ceba7cc4626">
<img width="1784" alt="Screenshot 2024-09-19 at 17 13 53" src="https://github.com/user-attachments/assets/e9684a53-b128-4313-8f83-b8d008a8e9bb">

2024-09-20 09:32 UTC, rdig approved these changes
Very nice team filters. Tested all pages and all seem to be behaving correctly. Stellar work!

[Screencast from 2024-09-20 12-30-38.webm](https://github.com/user-attachments/assets/553c0b3f-6473-4dc1-bce7-9be67707f8ef)

2024-09-20 09:45 UTC, merged