Feat/3003 toggle notifications
JoinColony/colonyCDapp pull request #3142
Opened 2024-09-20 11:15 UTC by bassgeta

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves  #3003

2024-09-24 08:25 UTC, rdig requested changes
Functionality wise, and even code wise this is all good, however `RpcForm` itself is still needed as it's part of the whole "D" in the CDapp which stands for Decentralized.

It's basically there to allow you to run this locally, so you're able to provide a RPC endpoint that you host yourself, and have the app run on that.

Granted, this was never properly wired up in the settings, but at some point we will _(when the focus will be less on shipping massing amount of features)_

So even if you remove it from the settings page, the `RpcForm` still needs to exist in our codebase as a component.

That's the only thing for which I rejected this, other than that, this is all good. 

Notifications disabled:


https://github.com/user-attachments/assets/f42e6054-3496-4611-b462-1362d7dc1c94

Notifications enabled:

https://github.com/user-attachments/assets/5afe310f-0cc4-4872-9455-09fe49327771

Notifications and Metatransactions Enabled:

https://github.com/user-attachments/assets/deeaac24-07bc-48d6-85fa-9edab56aaaca

2024-09-24 17:56 UTC, rdig approved these changes
'RpcForm' is back in, so I'm happy.

Thank you for reverting that! :100:

2024-09-25 08:26 UTC, iamsamgibbs approved these changes
This is working very nicely, great job @bassgeta The SettingsRow components are very nice.

Notifications are enabled by default:

<img width="774" alt="Screenshot 2024-09-25 at 09 06 20" src="https://github.com/user-attachments/assets/9c27846d-f3ab-492e-ba6d-2d0c2b19d010">

Disabling them shows the toast:

<img width="574" alt="Screenshot 2024-09-25 at 09 06 58" src="https://github.com/user-attachments/assets/892d8aeb-a8b3-4b62-a9a3-6bc4b1cdf249">

Making a new transaction does not increase the number of notifications (so no new ones were created)

<img width="1057" alt="Screenshot 2024-09-25 at 09 09 55" src="https://github.com/user-attachments/assets/3f6678c8-9542-4368-9e0e-17ce34d6b5ec">

And the correct toast is shown when reenabling:

<img width="1597" alt="Screenshot 2024-09-25 at 09 10 08" src="https://github.com/user-attachments/assets/1218e63f-c7c3-44cd-bd95-92cab9a337d7">

Then the notification count does increase:

<img width="1083" alt="Screenshot 2024-09-25 at 09 10 38" src="https://github.com/user-attachments/assets/5daf2dfb-39f7-4526-8bf2-d2b79d4d6aca">

Also tested the metatransactions are still functioning, which they are 👍 

<img width="430" alt="Screenshot 2024-09-25 at 09 11 38" src="https://github.com/user-attachments/assets/1ca10cf4-371c-4c54-a5e0-cac93fe513c4">

<img width="432" alt="Screenshot 2024-09-25 at 09 13 03" src="https://github.com/user-attachments/assets/c4940f28-94cc-468c-87d4-ed8cc8d123a2">

The only issue I have is that I believe the notifications tab should disappear entirely from the UserHub when notifications are disabled (correct me if I'm wrong @davecreaser ). The blue dot should also not show.

It should just require updating the NotificationsContext with this preference from the database. The UserHub tab already has a hardcoded `notificationsServiceIsEnabled` variable that would just need the value from the NotificationsContext, I don't recall if I setup the same for the blue dot or not, but would be a relatively simple change.

All that said I think it may be better done as it's own issue unless you fancy adding it here.

2024-09-25 13:59 UTC, davecreaser commented
Nice one @bassgeta! Works great, and the code is once again much cleaner 😆 You're really on a mission to clean up the codebase haha, every PR seems to improve something 🚀 

Tested the notifications toggle and all is good:
<img width="1561" alt="Screenshot 2024-09-25 at 14 46 45" src="https://github.com/user-attachments/assets/d529ecec-4be3-486d-aa8e-0cd550b97f33">
<img width="475" alt="Screenshot 2024-09-25 at 14 47 20" src="https://github.com/user-attachments/assets/d2920ad8-ea8e-422e-8a46-386c4ab7a3e3">
<img width="1062" alt="Screenshot 2024-09-25 at 14 51 34" src="https://github.com/user-attachments/assets/3a0cddba-f7d0-46df-9207-8e322178bd1c">
<img width="993" alt="Screenshot 2024-09-25 at 14 54 09" src="https://github.com/user-attachments/assets/5ca6d6a6-dd49-47e4-b144-aacd1dca44a4">
<img width="1062" alt="Screenshot 2024-09-25 at 14 55 11" src="https://github.com/user-attachments/assets/c5f83737-4270-4cc8-bff4-8c2d1ab3dcb7">

Metatransactions also all working, but I forgot to take screenshots 🙃 

About the comment from @iamsamgibbs about it not showing the tab, he's correct (and it also shouldn't connect to Magicbell at all in the context provider in that case). I'll make a new ticket to handle that though so we can merge this, since I didn't put it in the original ticket 👍

2024-09-25 14:00 UTC, davecreaser approved these changes

2024-09-25 14:00 UTC, davecreaser commented on src/components/v5/common/SettingsRow/index.ts
> +export default SettingsRow;
Very nice, very clean way of handling these!

2024-09-25 14:04 UTC, merged