Fix: Fund expenditure should use proper funding pot
JoinColony/colonyCDapp pull request #3145
Opened 2024-09-20 14:19 UTC by iamsamgibbs

## Description

This PR addresses an issue with the funding modal where the payload was hardcoded to fund the expenditure from the root domain.

This PR properly passes the intended domain in the payload. It also fixes a permissions issue with the saga.

I also refactored the `getMoveFundsPermissionProofs` util to use `getPermissionProofsLocal` whilst I was at it.

The important changes are in the `fundExpenditure` saga and the `FundingModal` component.

## Testing

* Step 1 - Create an action and select advanced payment
* Step 2 - Select any team other than general
* Step 3 - Add however many payment rows you like and submit (the expenditure ID will be logged to the console, copy it for later)
* Step 4 - Confirm the review stage
* Step 5 - Confirm the funding stage, select permissions as the decision method in the modal.
* Step 6 - Run this query and confirm the `nativeDomainId` and `fromPotId` are the same. (If you lost your copy from the console, the first expenditure ID on a fresh dev environment will be COLONYADDRESS_33)

```
query MyQuery {
  getActionByExpenditureId(
    expenditureId: "<EXPENDITURE_ID>"
    filter: {type: {eq: MOVE_FUNDS}}
  ) {
    items {
      type
      expenditure {
        nativeDomainId
        nativeFundingPotId
      }
      fromDomainId
      fromPotId
      toDomainId
      toPotId
    }
  }
}
```

<img width="634" alt="thispr" src="https://github.com/user-attachments/assets/3242b6ec-3d42-4690-a338-b1597b0a800b">

Compared to master where every advanced payment is funded from general.

<img width="626" alt="master" src="https://github.com/user-attachments/assets/00906e56-6019-4fc7-8f2c-5940a2fee528">

## Diffs

**Changes** 🏗

* `selectedTeam.nativeFundingPotId` is now passed in the funding expenditure payload
* Fixed permissions issue in the funding expenditure saga
* Refactored the `getMoveFundsPermissionProofs` util to use `getPermissionProofsLocal`

2024-09-23 06:56 UTC, rdig approved these changes
This work as expected. Nicely done. Thanks for the in depth testing instructions, especially the expenditure id's which might take longer for people to look up if they're not used to them.

![Screenshot from 2024-09-23 09-51-41](https://github.com/user-attachments/assets/1376c117-03e8-4158-88ba-617e1a22e8d5)
![Screenshot from 2024-09-23 09-52-01](https://github.com/user-attachments/assets/dc349dd3-0c84-4d1f-af17-bfb6455f20e1)
![Screenshot from 2024-09-23 09-52-08](https://github.com/user-attachments/assets/7ff1bb2b-e777-4f83-901a-2414b536440b)
![Screenshot from 2024-09-23 09-52-16](https://github.com/user-attachments/assets/32e4d67e-8530-4cc4-9831-11cbac12df9f)
![Screenshot from 2024-09-23 09-54-22](https://github.com/user-attachments/assets/5e5da8ff-cfb7-4d1b-87b3-c159b37e9208)

2024-09-23 10:04 UTC, mmioana approved these changes
Thank you for spotting and fixing this pesky issue @iamsamgibbs 💯🥇

Created an advanced payment from `Serenity`
![Screenshot 2024-09-23 at 11 59 50](https://github.com/user-attachments/assets/7ddc0966-270e-46e8-bdff-e992996ff7af)
![Screenshot 2024-09-23 at 11 59 56](https://github.com/user-attachments/assets/271ee745-3e74-4539-9ca3-c9cf7223230a)
![Screenshot 2024-09-23 at 12 01 29](https://github.com/user-attachments/assets/a27473d2-badc-4aea-b0b6-26fd6ce923b8)

And also one from `General`
![Screenshot 2024-09-23 at 12 02 27](https://github.com/user-attachments/assets/7dabb374-5754-4ed3-9285-7ec8ad18ff1d)
![Screenshot 2024-09-23 at 12 02 37](https://github.com/user-attachments/assets/a59403fe-ffc5-48bd-ba83-b56918846992)

And can confirm your changes work as expected 🎉 awesome job!!!

2024-09-23 10:42 UTC, bassgeta approved these changes
What a spot honestly, super nice that you found out about this.
The fix is straight forward and we've improved our sagas a bit with the local permission proofs refactor :100: 
Andromeda before:
![image](https://github.com/user-attachments/assets/7de9a2b8-55eb-4897-885f-e61d74a7b935)
Creating an action goes through nicely:
![image](https://github.com/user-attachments/assets/37afd790-2908-4151-8f77-edd71172eef0)
It has the correct pot id in the database:
![image](https://github.com/user-attachments/assets/02c8fd99-bdd1-4fc1-a9bb-446f257c87d8)
Andromeda after:
![image](https://github.com/user-attachments/assets/ffaa662b-d015-4ce2-8bfc-b65d39612351)
Moving funds:
![image](https://github.com/user-attachments/assets/c0ddb6b9-1ae9-415e-ad65-bacedd30209b)

Then I have `amy` the payer permission in `General` and it works :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/6b63cefd-30a3-44a8-8443-d214fdefda5b)

2024-09-23 10:49 UTC, davecreaser approved these changes
Nice fix, nice refactor! Works as expected for me also.

This branch:

<img width="1069" alt="Screenshot 2024-09-23 at 11 44 12" src="https://github.com/user-attachments/assets/b4383cf1-e962-4eda-961d-530ed81cd1d0">
<img width="1967" alt="Screenshot 2024-09-23 at 11 44 29" src="https://github.com/user-attachments/assets/1cead455-be98-4aa7-8de7-d97583c8f58c">

Compared to master:

<img width="715" alt="Screenshot 2024-09-23 at 11 48 41" src="https://github.com/user-attachments/assets/a287f4d2-68d8-41c5-908c-0ae6c162e2b9">

🚀

2024-09-24 08:06 UTC, iamsamgibbs commented
I've just pushed a fix to correct an incorrect assumption I had made about the move funds action only being possible in a parent domain.

It is true that if moving funds between two sub-domains, you require permissions in a shared parent of the two (currently only possible in root).

However, when moving funds between a sub-domain funding pot and an expenditure funding pot, then having permissions in the sub-domain is sufficient.

The latest commit fetches the correct userPermissionDomainId and userChildSkillIndex based on where the user has been assigned the funding permission.

To test, attempt to create an expenditure in a sub-domain as a user who has permissions only in root (Leela). Then assign funding permissions to another user in a sub-domain and attempt to create an expenditure as that user. Both should work fine.

2024-09-25 09:29 UTC, mmioana approved these changes
Really nice fix @iamsamgibbs 🎉 

Created an expenditure as `leela` from `Andromeda`
![Screenshot 2024-09-25 at 11 11 08](https://github.com/user-attachments/assets/bae0700f-0b9a-4dea-ba8a-fc8dc488ad96)
![Screenshot 2024-09-25 at 11 11 58](https://github.com/user-attachments/assets/cc92cdf5-2b00-4558-935f-d47cbdb53330)
Wanted to give `amy` only funding permissions 
![Screenshot 2024-09-25 at 11 13 08](https://github.com/user-attachments/assets/ddad0531-392d-482f-b01b-735b6bcc9043)
But realised she needs also the permissions to create an advanced payment in `General`, otherwise creating an advanced payment is not working from the action sidebar - maybe this needs to be investigated, but is not related to this PR
![Screenshot 2024-09-25 at 11 23 58](https://github.com/user-attachments/assets/c1497fc3-71f2-4c3c-b204-0c9417bb6063)
Created and funded an advanced payment as `amy`
![Screenshot 2024-09-25 at 11 18 24](https://github.com/user-attachments/assets/1cf97176-9e87-46a2-bdd4-201a8ba8e34c)
Give `fry` only funding permissions
![Screenshot 2024-09-25 at 11 22 30](https://github.com/user-attachments/assets/d552759b-468c-4d46-a334-7c77ae3e4e6e)
Create an advanced payment as `leela`
![Screenshot 2024-09-25 at 11 20 03](https://github.com/user-attachments/assets/efd3ebe6-f546-4b10-923a-0f553430209b)
`fry` can fund it
![Screenshot 2024-09-25 at 11 20 11](https://github.com/user-attachments/assets/7b8b8cbb-bffe-4abe-82ee-2aa39d8fcc84)
![Screenshot 2024-09-25 at 11 20 23](https://github.com/user-attachments/assets/cf0302ac-fc55-4ad6-bb16-c34e042645b4)
![Screenshot 2024-09-25 at 11 20 51](https://github.com/user-attachments/assets/f58c6323-0873-4898-9ff7-dea6d3ede3f2)

Amazing job once again and thank you so much for fixing this 💯 🌟

2024-09-25 10:35 UTC, rdig requested changes
I can't seem to make this work.

So the leela case works as expected:

![Screenshot from 2024-09-25 13-27-28](https://github.com/user-attachments/assets/1950f7bb-ce0b-46fb-a8d7-0ae39792a6ac)

However, with a second user, I get errors when attempting to fund the expenditure.

Gave `fry` payer permission in `andromeda` _(just funding is not enought)_

![Screenshot from 2024-09-25 13-30-25](https://github.com/user-attachments/assets/7d85aa02-5094-41c9-9a5a-069aa75b192d)

I can then create the expendinture:

![Screenshot from 2024-09-25 13-32-25](https://github.com/user-attachments/assets/dbef59a6-f330-4e33-bcfa-417f51f38bc9)

But when actually attempting to fund it, I run into the error

![Screenshot from 2024-09-25 13-32-20](https://github.com/user-attachments/assets/1e239dde-c1f5-40e8-8d98-3529a33eaff3)
![Screenshot from 2024-09-25 13-32-01](https://github.com/user-attachments/assets/010a5a4d-9aab-4fe9-9720-d8ec05770227)

2024-09-25 14:36 UTC, iamsamgibbs commented
Hmm I am unable to recreate this issue. You are correct that funding permission is not enough to create an advanced payment action - I will update the testing steps to correct this. However, it is enough to fund the expenditure, so I've tested creating an expenditure as an owner, getting it to the funding stage then switching to Fry to fund it - no issues. Also then assigned Fry payer permissions and no issue there either. I'll see if anyone else hits this issue when testing.

2024-09-27 08:05 UTC, rdig approved these changes
I've retested this and it seems I was wrong initially, as this is now working correctly, and you didn't change anything.

Honestly, the only thing I can point to as being wrong in my initial assessment is maybe I screwed something up with the initial permissions to `fry`, since I first gave him only `funding`, then the full `payer` permission group 

Anyway, here's the re-test that is indeed working

Give `fry` permissions:

https://github.com/user-attachments/assets/67c3c72a-bade-41b9-961b-eff848e96aba

As `fry`, create and fund an Adv. Payment

https://github.com/user-attachments/assets/f88dcd69-ac6d-40af-9fcb-257e28de3cfa

2024-09-27 09:35 UTC, bassgeta approved these changes
Still looking good and still working good :100: 
The new testing cases:
![image](https://github.com/user-attachments/assets/04ae3c60-d392-4eae-93c3-f44d78e549b2)
![image](https://github.com/user-attachments/assets/f2313020-e0b7-4b24-a5c4-4033ce082416)
Wen through the entire flow and managed to go through with it :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/273a4724-4af2-4165-afd7-9beeb353732b)
![image](https://github.com/user-attachments/assets/ac09fbe4-63df-40c0-a2b3-cd4259feb778)

Transfer of funds is still working as it should so let's ship this :sunglasses:

2024-09-27 09:43 UTC, merged