[Dashboard] Top contributors meatball menu
JoinColony/colonyCDapp pull request #3228
Opened 2024-09-30 19:43 UTC by mmioana

## Description

The meatball menu should change when a parent team is selected, since the same menu items are not relevant to contributors/ members. It should show 'View members' that opens up the members page with the parent team filter already selected applied. 

Currently:
<img width="470" alt="image" src="https://github.com/user-attachments/assets/27437881-31d9-481e-b19a-8879fc0c871a">

Figma:
<img width="502" alt="image" src="https://github.com/user-attachments/assets/298bd87f-74c5-4f68-ae84-efc5502ada83">

Link in Figma: https://www.figma.com/design/gac6xVgGNCAge5Bia933dp/Dashboard?node-id=6830-36359&t=cXj2gpagsBjz8b9Q-4

## Testing

* Step 1. Check for `All teams` and `General` the actions in the `Influence by team` widget remained unchanged (you can also check each item still behaves as before)
![Screenshot 2024-09-30 at 21 38 42](https://github.com/user-attachments/assets/91dd003d-d607-4327-9de1-68d8cc2e0f15)
* Step 2. Select another team/domain
* Step 3. Check only `View members` dropdown item is shown
<img width="502" alt="image" src="https://github.com/user-attachments/assets/298bd87f-74c5-4f68-ae84-efc5502ada83">
* Step 4. Clicking `View members` should navigate to http://localhost:9091/planex/members

## Diffs

**New stuff** ✨

* `useDropdown` hook
* `DropdownMenu`, `DropdownItem` and `ContributorActionsMenu` components

**Changes** 🏗

* `ReputationChart` renders either `TeamActionsMenu` or `ContributorActionsMenu`

Resolves [#3210](https://github.com/JoinColony/colonyCDapp/issues/3210)

2024-10-01 08:32 UTC, bassgeta approved these changes
Very nice and simple, I like the new dropdown component :100: 
We probably would need to hide `popper` implementation details from that component, but let's not scope creep this and let's do that down the line :D 

The teams dropdown:
![image](https://github.com/user-attachments/assets/a7f5b7ef-d656-4fbb-828f-11053f71d739)

COntributors dropdown:
![image](https://github.com/user-attachments/assets/a789799a-bc88-4946-89fd-e1ea2861e386)

2024-10-01 08:32 UTC, bassgeta commented on src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/DropdownMenu.tsx
> +const DropdownMenu: FC<DropdownMenuProps> = ({
should we maybe already extract this to a new shared component? maybe we can reuse this for the team filter too :eyes:

2024-10-01 08:32 UTC, bassgeta commented on src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/DropdownItem.tsx
> +const dropdownItemClassName = tw`flex w-full items-center gap-2 rounded-s px-3 py-2 text-md text-gray-900 hover:font-medium md:hover:bg-gray-50`;
maybe this can be used directly instead of from a variable

2024-10-01 08:32 UTC, bassgeta commented on src/components/v5/frame/ColonyHome/partials/ReputationChart/partials/DropdownItem.tsx
> +  icon: ComponentType<IconProps>;
should we make this optional so we can reuse this for the teams dropdown? 
Or maybe we can refactor that down the line and have two components like
`DropdownItem` and
`DropdownIconItem` :shrug:

2024-10-02 07:54 UTC, bassgeta approved these changes
Still looking good after the refactor, nice going :sunglasses: 
![image](https://github.com/user-attachments/assets/37b0d969-b527-4cc2-b5c0-4e10872a5fd5)
![image](https://github.com/user-attachments/assets/6a9fe3ce-d923-413c-aed2-b0ae22c3c5a0)

2024-10-03 09:38 UTC, Nortsova requested changes
Looks great! 🙌 And works perfect 😍 Thank you @mmioana ✨

<img width="566" alt="image" src="https://github.com/user-attachments/assets/1a543c73-9cf2-4d3f-af14-f67f7ab1a70f">
<img width="550" alt="image" src="https://github.com/user-attachments/assets/ad7e6ec4-eab5-491b-a1bd-28a32a5b4827">

However it would be nice to redirect to selected team members. This is the only reason why I am rejecting now ❤️

2024-10-03 11:25 UTC, iamsamgibbs requested changes
Great changes here! Love the new components.

<img width="428" alt="Screenshot 2024-10-03 at 12 19 50" src="https://github.com/user-attachments/assets/cbbb170e-d2d3-47f8-b0a8-0b1759236571">

<img width="439" alt="Screenshot 2024-10-03 at 12 20 45" src="https://github.com/user-attachments/assets/e7e05c4b-ff24-4d93-aefd-7f22cfebb212">

Only rejecting for the same reason as @Nortsova that the "View members" link should keep the selected team.

Also tested out how the new components handle not having an icon set and looks great!

<img width="424" alt="Screenshot 2024-10-03 at 12 23 47" src="https://github.com/user-attachments/assets/b0b71b74-2532-4d32-a1ba-41afc0eca958">

2024-10-03 14:24 UTC, mmioana commented
Thank you guys for your review!
I have fixed the filter when `View members` is clicked and also removing the filter when clicking on `View all teams`, as it didn't make sense to keep it.

Also, noticed there was a problem with the back navigation with the new `ColonyFiltersContext` and pushed a fix for it.
However, please keep in mind the initial route is first rendered, but if there is a domain present in the context, the route is re-rendered with the search param set. If you go back, you'll see this empty state when the initial route is rendered.
It seemed to take way too much time to also fix this now, but I'll open a new issue for it 🙌

2024-10-03 14:34 UTC, iamsamgibbs approved these changes
Nice job! This is a nice fix. I see what you mean with the back issue, but agree this can be addressed as a separate issue.

https://github.com/user-attachments/assets/117364ca-6afd-4b8c-8fe7-9b2d0180a740

2024-10-03 14:51 UTC, mmioana commented
@iamsamgibbs I opened https://github.com/JoinColony/colonyCDapp/issues/3263

2024-10-03 18:14 UTC, Nortsova approved these changes
![redirect-on-view-member](https://github.com/user-attachments/assets/b2019c0a-4834-44b9-811a-d4475d081fd1)

Perfect! Thank you for the fast fix and opened issue ✨

2024-10-04 06:51 UTC, merged