[Dashboard] fix: taem filter CSS fixes
JoinColony/colonyCDapp pull request #3233
Opened 2024-10-01 10:02 UTC by bassgeta

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-10-02 11:59 UTC, mmioana requested changes
Amazing work with the css fixes @bassgeta 🥇🎉 

Vertical alignment of the labels

![Screenshot 2024-10-02 at 13 48 00](https://github.com/user-attachments/assets/3aa1add2-d2b3-4a6f-beae-16c01e6a4680)
![Screenshot 2024-10-02 at 13 48 41](https://github.com/user-attachments/assets/5ca71119-7fa5-40ce-97d6-436dcc4ff0b8)

Filters height
![Screenshot 2024-10-02 at 13 48 24](https://github.com/user-attachments/assets/b20487af-b68f-4db4-8549-ee10e681a66a)

Hovering over a label
![Screenshot 2024-10-02 at 13 48 07](https://github.com/user-attachments/assets/1abddb74-6c01-4fcf-8e0b-d8b6a8a270c2)


No grey border for selected team 
![Screenshot 2024-10-02 at 13 50 01](https://github.com/user-attachments/assets/92707d69-4183-4408-b455-3b869293562c)

Mobile scrollbars are no longer present

https://github.com/user-attachments/assets/ae615174-49e5-4ac7-9ba7-e6c2fecfd39e

`<` and `>` have the right corners

<img width="364" alt="Screenshot 2024-10-02 at 13 51 34" src="https://github.com/user-attachments/assets/1bcca568-1e0f-43bb-bc5d-6231616541e5">

However I did notice a small issue while resizing and the labels not being horizontally centred, if you can please look into it 🥺 


https://github.com/user-attachments/assets/3b9f25f7-633b-404e-b509-5cb33509b616

2024-10-02 13:30 UTC, Nortsova requested changes
Hey @bassgeta thanks for your work! 🙌 Everything looks good now :) 

In terms of pixel-perfect perspective, these items aligned ideally! 
<img width="532" alt="image" src="https://github.com/user-attachments/assets/e3b176de-0d47-45c4-9430-9c3b7d00ec29">

Mobile behaviour works great: 
![team-filter-mobile](https://github.com/user-attachments/assets/3e60f6f8-ee38-4f28-880a-d0d0edfe01e7)

However, there is an issue with bold-on-hover behaviour:
![bold-items](https://github.com/user-attachments/assets/b1997821-e139-4870-96c4-0383105bbd7f)

Thank you 🤩

2024-10-03 14:35 UTC, mmioana approved these changes

2024-10-04 11:36 UTC, Nortsova approved these changes
Thank you! it looks great 👍

![filter-hover](https://github.com/user-attachments/assets/336c658c-258f-43a8-9cec-d93f20e308fc)

2024-10-04 12:17 UTC, iamsamgibbs requested changes
Looks like the recent changes have caused some issues unfortunately!

If I'm being really nitpicky, the selected team should have a coloured border on both the left and right. Currently the left border is always grey:
 
<img width="354" alt="Screenshot 2024-10-04 at 13 10 23" src="https://github.com/user-attachments/assets/5713a0c0-a8cf-47a8-8e6f-ac265ec016ec">

Compared to figma:
<img width="713" alt="Screenshot 2024-10-04 at 13 10 53" src="https://github.com/user-attachments/assets/60a05b48-c986-480b-a402-4c2086fda989">

No scrollbars on firefox, but I unfortunately noticed this other issue with the arrows:

<img width="449" alt="Screenshot 2024-10-04 at 13 12 56" src="https://github.com/user-attachments/assets/7311d0a9-cdba-4ed5-ac0d-37c027a629dc">

And was able to replicate it on chrome (note the missing left arrow too):

<img width="631" alt="Screenshot 2024-10-04 at 13 13 45" src="https://github.com/user-attachments/assets/5318b2b4-8385-451a-a24c-80773c156abe">

2024-10-04 14:59 UTC, mmioana commented
Hey @iamsamgibbs I pushed some changes for the issues you mentioned, if you can please be so very kind to re-check? 🙏

2024-10-07 08:53 UTC, iamsamgibbs approved these changes
Great work on this @bassgeta and @mmioana - it is working very nicely now!

Borders look great here:
<img width="397" alt="Screenshot 2024-10-07 at 09 45 11" src="https://github.com/user-attachments/assets/7907d21c-d8ad-4281-88f0-fe1279c20d2f">

And all working nicely on firefox:
<img width="466" alt="Screenshot 2024-10-07 at 09 49 33" src="https://github.com/user-attachments/assets/18acfdcb-eb49-4cef-afa4-2755008060d4">

2024-10-07 13:40 UTC, merged