[Dashboard] Recent activity table title padding fix
JoinColony/colonyCDapp pull request #3235
Opened 2024-10-01 11:18 UTC by iamsamgibbs

## Description

This PR resolves point 2 on the linked issue by reducing the padding below the recent activity table title.

## Testing

Check the spacing between the recent activity table title and the first row.

## Diffs

**Changes** 🏗

* Reduced padding below title

Contributes to #3216

2024-10-02 13:25 UTC, mmioana requested changes
Hey @iamsamgibbs really nice work on this one 👏 🥇 

Created a new colony
![Screenshot 2024-10-02 at 14 42 20](https://github.com/user-attachments/assets/35df962f-f274-4bf4-bc7d-8337bc2b1122)

Created a `Mint tokens` action
![Screenshot 2024-10-02 at 14 43 00](https://github.com/user-attachments/assets/e44c694c-28b0-47f5-b542-30969f46850f)
![Screenshot 2024-10-02 at 14 43 12](https://github.com/user-attachments/assets/cda92803-134e-4376-bb78-c58c0e651476)

On a very large desktop, the `Recent activity` table doesn't extend more than 7 rows
![Screenshot 2024-10-02 at 15 17 44](https://github.com/user-attachments/assets/b1d5f5e2-404f-4757-a479-607371c906df)

On mobile, no extra height is added
![Screenshot 2024-10-02 at 15 18 55](https://github.com/user-attachments/assets/d396cde0-d046-4c5f-81da-57c307e0e763)

The `Activity` page is unaffected
![Screenshot 2024-10-02 at 15 19 19](https://github.com/user-attachments/assets/64ee7a88-bb4f-49ea-8291-c9f935e72e51)
![Screenshot 2024-10-02 at 15 20 26](https://github.com/user-attachments/assets/f239daec-308c-4435-b570-8be96d52cfa6)

Hover state for both `light` and `dark` modes
![Screenshot 2024-10-02 at 14 44 00](https://github.com/user-attachments/assets/d90e7e26-fa31-4bbb-86b1-9affea31c6e3)
![Screenshot 2024-10-02 at 14 44 07](https://github.com/user-attachments/assets/a10adced-55c9-4630-9830-f21f0ee5974b)

Then the spacing between the table title and the first item's content is `24px`
![Screenshot 2024-10-02 at 14 45 46](https://github.com/user-attachments/assets/175110d7-71a9-4c03-888e-ecebb6bb051f)
![Screenshot 2024-10-02 at 14 45 31](https://github.com/user-attachments/assets/946cb420-8432-4b1e-84b4-febefa7b19a7)


The only issue I discovered while testing this is that on a newly created colony, once you start adding actions, only after you reach the page limit, the pagination shows up 🤔 
![Screenshot 2024-10-02 at 14 43 12](https://github.com/user-attachments/assets/364b9297-3411-47c1-823f-22f610ff43a4)
![Screenshot 2024-10-02 at 15 13 37](https://github.com/user-attachments/assets/dcd0b4ad-2bbe-46e9-9266-ee5422b7b7fe)

But if you refresh the page, the pagination will show up

https://github.com/user-attachments/assets/c1e39f7b-a0fc-4a2f-87b5-ae7ce0d867ba

From my testing, I noticed `totalActions` remains `0` in `src/components/common/ColonyActionsTable/RecentActivityTable.tsx` if it helps you @iamsamgibbs  for debugging further

2024-10-03 09:37 UTC, iamsamgibbs commented
Oh good catch @mmioana - I've added a refetch for the total actions query on a successful action and this should work as expected now.

2024-10-03 14:55 UTC, mmioana approved these changes
@iamsamgibbs your fix works like a charm 🎉 💯 

![Screenshot 2024-10-03 at 16 53 12](https://github.com/user-attachments/assets/546d95fb-75ba-419d-875a-5c054eefb139)
![Screenshot 2024-10-03 at 16 53 38](https://github.com/user-attachments/assets/88776821-5366-4d6d-bb36-39b15399aa4a)
![Screenshot 2024-10-03 at 16 53 46](https://github.com/user-attachments/assets/5fcae2fd-19ce-4c24-91ed-abaf3c63905d)

And on `planex` nothing changed
![Screenshot 2024-10-03 at 16 54 01](https://github.com/user-attachments/assets/d750dabc-6ad9-44c8-b807-c6c82f51af95)

2024-10-04 09:16 UTC, bassgeta approved these changes
Nice job adding and fixing stuff in this component full of convoluted classNames, I imagine it wasn't the easiest job :D 
1-3. The table stretches to full height on the dashboard :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/a6db1963-7f06-47ab-84fc-4f5fd6ada3bb)
4. Tallboi not mega tall :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/fe7817a4-e0cd-46dd-9deb-d78318652123)
5. Mobile is clamped down :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/03831ea6-8ab1-4ac0-a492-76dea4c58691)
6. Activity feed behaves the same as before :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/79fa4691-fbdc-4f2d-8879-54ee03ec858d)
![image](https://github.com/user-attachments/assets/1afbfc32-b3e2-4c78-b8c5-819c282c0181)

7. My dev env got wiped just before I could take screenshots of this :melting_face: But I can confirm it works on my machine :sunglasses: 

8. Hover state is full width :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/a81e5c53-92b4-4702-b8d3-2d1970936560)
9. Paddings check out :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/ec3b2329-d965-445d-b14d-a356ee1308a4)
![image](https://github.com/user-attachments/assets/992109cc-b67b-420b-9b17-d8810a769eaf)

2024-10-04 11:14 UTC, Nortsova approved these changes
Pixel perfect 👌
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/6a6b10b6-92b3-4969-a6cb-9f20c4bf5547">

Max height works great:
![max-height](https://github.com/user-attachments/assets/ffe3f660-2c1c-4622-96b3-03951247f7c3)

Mobile doesn't add any extra height:
<img width="406" alt="image" src="https://github.com/user-attachments/assets/126980b4-1313-4445-bb02-7ab1e2233cde">

Hover: 
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/4bb3c684-1c0a-4893-864e-8048f49e858b">

Spaces between elements looks perfect:
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/b4bb3d07-72c4-4080-a78a-cb85d1348b8a">

2024-10-04 11:21 UTC, merged