Send notifications on multisig actions
JoinColony/colonyCDapp pull request #3280
Opened 2024-10-08 11:15 UTC by davecreaser

## Description

- Send notifications for multisig actions. This includes creation, full approval, rejection and finalization.

Part of the work for this PR was done in the block ingestor here: https://github.com/JoinColony/block-ingestor/pull/275

## Testing

Ensure that the following is added to your .env.local.secrets and run npm run prepare.

```
MAGICBELL_API_KEY=<ask me for this>
MAGICBELL_API_SECRET=<ask me for this>
MAGICBELL_DEV_KEY=
```

Also ensure the API_KEY and SECRET are both in the .env file inside `amplify/backend/function/createUserNotificationsData`

* Log in as Leela in one browser, and Amy in another incognito browser. As Leela, install the multisig extension. Set the threshold to be fixed at "2".
<img width="1518" alt="Screenshot 2024-10-08 at 11 43 13" src="https://github.com/user-attachments/assets/bf3f1ee5-c6cb-47ca-b32d-332aa865ee00">

* Give Leela and Amy multisig owner permissions. Check that you receive notifications for these.
<img width="1049" alt="Screenshot 2024-10-08 at 11 47 57" src="https://github.com/user-attachments/assets/9e27ce8e-cab9-4881-9bef-b279f0f08e27">
<img width="1058" alt="Screenshot 2024-10-08 at 11 48 52" src="https://github.com/user-attachments/assets/835b634f-173c-4c2e-836e-282e45b8c596">
<img width="453" alt="Screenshot 2024-10-08 at 11 49 25" src="https://github.com/user-attachments/assets/d95beeac-a70e-42c2-a12c-a286917dc7c4">

* Create a multisig action. It can be any type of action as long as it is multisig. Check that you receive a notification when this is created.
<img width="1057" alt="Screenshot 2024-10-08 at 11 50 21" src="https://github.com/user-attachments/assets/1e04948f-cc8c-47f1-824d-778bc9666c0d">
<img width="447" alt="Screenshot 2024-10-08 at 11 50 39" src="https://github.com/user-attachments/assets/55da9a5a-40e5-44a7-af23-769c3e8d5831">

* As Amy, add a second approval to the multi sig action. Go back to Leela and check that she received a new notification for the approval. Then finalize the motion as Leela, and check that she also received a notification for that.
<img width="366" alt="Screenshot 2024-10-08 at 11 51 43" src="https://github.com/user-attachments/assets/4604ca89-9210-47cc-8c86-d8781c84cec2">
<img width="442" alt="Screenshot 2024-10-08 at 11 52 12" src="https://github.com/user-attachments/assets/bc129bab-01fe-48ae-9523-10257c58ef3c">
<img width="442" alt="Screenshot 2024-10-08 at 11 52 41" src="https://github.com/user-attachments/assets/7b9721bd-745a-4fe8-a17f-8f1e3da4f293">

* As Leela, make another multisig motion. Immediately go back to the approval step in the sidebar and remove her approval, then reject the motion. Check that a notification arrived for this rejection.
<img width="363" alt="Screenshot 2024-10-08 at 11 53 14" src="https://github.com/user-attachments/assets/61197f22-1f4c-413c-8494-e5552f4a8c30">
<img width="365" alt="Screenshot 2024-10-08 at 11 53 23" src="https://github.com/user-attachments/assets/9d812d41-3808-4795-9eef-d3453d472884">
<img width="440" alt="Screenshot 2024-10-08 at 11 53 51" src="https://github.com/user-attachments/assets/d6f90592-1568-4b9a-a41a-b10795d58000">

## Diffs

**New stuff** ✨

* New component: `MultisigNotificationMessage`
* New notification types

**Changes** 🏗

* Changes to some notification categories to match specs
* New block ingestor hash, and more changes there: https://github.com/JoinColony/block-ingestor/pull/275

Resolves #3221

2024-10-09 08:38 UTC, rdig requested changes
I've tested this but everything breaks when trying to approve the multisig as Amy, but the transaction never goes through

![Screenshot from 2024-10-09 11-36-01](https://github.com/user-attachments/assets/a29a6944-f4b8-4b36-b333-509b75e168f6)

This might actually be the issue that got solved in #3276 and you just need to rebase

Here's how far I got with testing:

![Screenshot from 2024-10-09 11-28-40](https://github.com/user-attachments/assets/37620a8d-2a2c-4c71-a5ee-d4b82afba455)
![Screenshot from 2024-10-09 11-29-10](https://github.com/user-attachments/assets/cad52cdf-ec58-4ba2-91bd-7bc33b8aa82e)
![Screenshot from 2024-10-09 11-29-38](https://github.com/user-attachments/assets/8cecfb89-e573-49f3-a564-90ab6a275eeb)
![Screenshot from 2024-10-09 11-29-50](https://github.com/user-attachments/assets/4235c7a2-be50-4201-be90-d6c7b6490b33)
![Screenshot from 2024-10-09 11-30-26](https://github.com/user-attachments/assets/dd215b0a-1824-4994-a635-4bdae7cdeed1)
![Screenshot from 2024-10-09 11-30-38](https://github.com/user-attachments/assets/f2fe788b-a4da-4239-a6fa-bb33b395c686)
![Screenshot from 2024-10-09 11-33-50](https://github.com/user-attachments/assets/2ce4316f-3eab-44bd-bfd7-21b336c0be03)

2024-10-09 09:03 UTC, bassgeta requested changes
Code changes super straight forward and readable, I'm loving the structure of notifications so far :100: 
Alright so creating a multisig motion does indeed send `leela` notifications:
![image](https://github.com/user-attachments/assets/137c3cb5-2821-4823-917e-0abd7e6a61aa)
But my dev env is plagued by the same issue @rdig  pointed out, so I can't enable notifications as `amy` :( maybe we should consider rebasing (and hoping everything advanced payment related won't be a headache :D )

Rejection works:
![image](https://github.com/user-attachments/assets/8ac2851f-44a7-49d6-b769-ea8d7895a1d5)

So I think this all actually works, BUT I would like to run it through all the required paces with 2 users just for sanity's sake

2024-10-09 15:06 UTC, bassgeta approved these changes
Thanks for rebasing, everything works as it should, great job finding such a slick solution to a problem that was quite a pain at first glance!
both leela and amy received notifications for multisig roles updated :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/b3c3d1e1-b5ed-4fd9-a3a0-f4d31b51fb9b)
Both got notifications when the multisig is created :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/5545ed78-765d-4118-9675-21084c678b47)
![image](https://github.com/user-attachments/assets/ce74f97d-1f2d-42c4-995a-6824ef0b1939)
Both got notifications when its threshold passed :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/4d62d70e-b492-4e27-8a9c-a649bfc6f0ec)
![image](https://github.com/user-attachments/assets/8f1f4309-447a-4038-8fb2-2800e26369ad)

Both get it for when the motion is finalized :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/d9c3d602-7d66-4b4f-b70a-a38e39e277b9)
![image](https://github.com/user-attachments/assets/4efbd647-b240-4a83-9b04-896e3d5fa3f0)

Both get it when it's rejected:
![image](https://github.com/user-attachments/assets/695045e4-0b0d-43b3-b913-63b73bab0861)
![image](https://github.com/user-attachments/assets/c9abe0ce-197c-4996-a684-4700f007bf28)

:ship:

2024-10-10 14:27 UTC, iamsamgibbs approved these changes
This looks great Dave! All very sensible code changes. I've left one comment about wording which would be nice to address here.

The only other thing missing from the spec is when a multi-sig motion is created, it should inform the user if they are required to approve. It's unclear from the specs whether this should be included in the wording for the multi-sig action created notification, or as an entirely separate notification. Either way, I think this can be addressed as it's own issue as it'll be a fairly big chunk of work with either option.

Otherwise, this all works great! I receive notifications when creating a multi-sig motion, approving and finalizing:
 
<img width="446" alt="Screenshot 2024-10-10 at 14 54 36" src="https://github.com/user-attachments/assets/3516a5d9-cf26-4db4-9aac-55219255c748">

And when rejecting:

<img width="445" alt="Screenshot 2024-10-10 at 14 52 49" src="https://github.com/user-attachments/assets/61ac78b5-073d-4c3e-b875-1139ce739f8a">

Completely unrelated, but I noticed the action type for minting via multi-sig is missing, presumably this is an issue on master:

<img width="426" alt="Screenshot 2024-10-10 at 14 50 52" src="https://github.com/user-attachments/assets/caec5683-1aef-4b2e-a200-497860295f4b">

Nice job!

2024-10-10 14:27 UTC, iamsamgibbs commented on src/components/common/Extensions/UserHub/partials/NotificationsTab/partials/Notification/Action/MultisigNotificationMessage.tsx
> +          {action.metadata?.customTitle}: {actionMetadataDescription}
Could we add something in here that makes it clear it is a multi-sig motion and not just a regular action? Currently the notification looks exactly the same whether it is a permissions action or a multi-sig motion (the custom title is the only difference here).

<img width="447" alt="Screenshot 2024-10-10 at 14 50 42" src="https://github.com/user-attachments/assets/c4d0a560-4399-4154-bc5d-9eaf27beffc6">
 
Maybe just sticking `Multi-sig motion created:` at the start or something. Might need checking with product.

2024-10-10 15:55 UTC, merged