WIP: fix: permissions inherited roles visability
JoinColony/colonyCDapp pull request #3345
Opened 2024-10-15 19:40 UTC by Nortsova

## Description

Funny thing, this bug has been fixed at least three times, but it’s still present. 😁

Here is previous fixes for reference: https://github.com/JoinColony/colonyCDapp/pull/2971 , https://github.com/JoinColony/colonyCDapp/pull/3024 , https://github.com/JoinColony/colonyCDapp/pull/2485 

<img width="1459" alt="image" src="https://github.com/user-attachments/assets/aee05995-5965-469a-9905-e00e31706ac7">

I decided to use the implementation from my last PR, but if you have any concerns, I’m open to refactoring.  🙌

## Testing

Step 1. Assign Admin permissions to fry in Andromeda
Step 2. Assign Payer permissions to fry in General
Step 3. Assign Payer permissions to amy in Andromeda
Step 4. Assign Admin permissions to amy in General
Step 5. Navigate to the permissions page to check fry's and amy's roles in Andromeda
Step 6. fry should be an admin, amy should be an admin with inherited pill

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/c8f792ec-ac9a-4708-bb95-d7dbd90c7711">

Step 7. Install multi-sig extension
Step 8. Assign Admin permissions to amy in Serenity
Step 9. Assign Payer permissions to amy in General
Step 10. Assign Payer permissions to fry in Serenity
Step 11. Assign Admin permissions to fry in General
Step 12. Navigate to the permissions page to check fry's and amy's roles in Andromeda
Step 13. amy should be an admin, fry should be an admin with inherited pill

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/9962b7d3-1631-41f7-8075-b7492bac42b2">

Resolves #2785

2024-10-16 10:06 UTC, rdig commented
Is this ready for review? Or is it still being worked on?

2024-10-16 11:10 UTC, Nortsova commented
> Is this ready for review? Or is it still being worked on?

It is ready now, sorry I spent some time on the test cases. 🙌

2024-10-16 14:03 UTC, bassgeta requested changes
I still have no idea how this disappeared, but I hope it's gonna stay in here permanently now :D  
Alright so, I think you **almost** got it, we somehow need to merge the roles here and mark them as inherited.
Lemme provide breaking steps:
1. Assign `fry` just the `Administration` role in `General`
![image](https://github.com/user-attachments/assets/1dddacfe-4bf2-4b03-b178-f4895776741d)
2. Assign `fry` `Architecture`, `Arbitration` and `Funding` in `Andromeda`
![image](https://github.com/user-attachments/assets/8e62df5b-7c81-4f51-b4cb-4747f13644c0)
3. Go to the permissions page and choose `Andromeda` as the filter, `fry` is shown as `Mod` not as an `Admin`
![image](https://github.com/user-attachments/assets/959563a2-6fe1-4e28-9757-8a5ff4f7488c)

I think the issue is with the line I've dropped a comment on, we need to merge inherited + current domain permissions, and we can still have the `isInherited` to `true`

Attaching some logs from my debug session
![image](https://github.com/user-attachments/assets/ee6ff9ed-73f2-4866-8b95-2f310f0e3af5)
Log 1 is here
![image](https://github.com/user-attachments/assets/3b685148-fce8-4bfa-bdda-d8356f29d70e)
Log 2 is here
![image](https://github.com/user-attachments/assets/3a4769d8-8f2b-458a-b1fc-84b5ae9ef6b6)

However, the popup works correctly for this, so at least we don't to fix that :sweat_smile:

2024-10-16 14:45 UTC, Nortsova commented on src/components/frame/v5/pages/MembersPage/utils.ts
> +    return { role: getRole(parentPermissions), isInherited: true };
yep, it was it, thank you so much for your finding! fixed 🥳

2024-10-17 09:13 UTC, bassgeta approved these changes
Thanks for the quick turnaround on my comment, I think we're basically ready to go :crossed_fingers:  ??
Thanks for the thorough testing steps, really helped with testing this a ton!
So I won't spam too many images I'll just note down the cases
`leela` - Owner in `General`, just `Architecture` in `Andromeda`
`amy` - `Payer` in `General`, `Admin` in `Andromeda` and just `Architecture` in `Serenity` 
`fry` - `Admin` in `General`, `Payer` in `Andromeda`
`chris-coder` (the most annoying test case)  - `Funding` and `Arbitration` in `General` and then `Administration` in `Andromeda` and `Administration` + `Architecture` in `Serenity`

 Also should we somehow save this configuration for all further permission combo testing? :D 
 
Alright so test 1, `amy` should be an admin since it's `All teams` and `chris-coder` is and admin somewhere by some combination :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/562d825f-4502-4fa6-aa3c-88d64cbeb4cb)

2. `amy` is a `Payer` in `General` and `chris-coder` is `Custom` , `leela` and `Owner`, `fry` and `Admin` :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/66981c1f-e0e2-4bc6-a8a9-305e3449adb6)
3. In `Andromeda` `fry` is an Admin still (even though we "downgraded" him in that domain, he inherits from `General`) , amy is compounded into an admin due to inheritance, chris-coder is compounded into a payer, leela inherits the owner
![image](https://github.com/user-attachments/assets/c8ac3090-b39b-40a2-8a66-ceff7932c634)

4. In `Serenity` fry is an inherited  Admin, leela an inherited Owner, chris-coder is compounded into an Admin and so is amy
![image](https://github.com/user-attachments/assets/f2c8fa8f-8224-499c-adf8-fff0a23d6dab)

so all in all, great job :sunglasses:  I've also checked Multisig, buuuuut I'm not gonna spam it with even more pictures, since the cases are the exact same :D

2024-10-17 13:41 UTC, rdig approved these changes
Pfew! This was a pain in the a to test. I can only imagine you wanting to get in done already as it's hanging about for like 3 months :)

Before I get into it I want to mention that step 12 is wrong

> Step 12. Navigate to the permissions page to check fry's and amy's roles in Andromeda

Step 12 is wrong, it should say _"Serenity"_

Another thing is that I found some bugs, but I just want you to open separate issues for them, not fix them here. (see at the bottom)

As for your PR everything seems to be working as expected, so nice job navigating the intricacies of permissions :100: 

**Direct and inherited "normal" permissions:**

![Screenshot from 2024-10-17 16-00-13](https://github.com/user-attachments/assets/bd2d7bc0-5c13-4f72-a8d4-fae90874653d)
![Screenshot from 2024-10-17 16-00-45](https://github.com/user-attachments/assets/c703ac3b-f2c7-4084-914d-ee50bfc248ff)
![Screenshot from 2024-10-17 16-01-36](https://github.com/user-attachments/assets/7d630d7a-67a5-48a6-b73a-5e9e59c99802)
![Screenshot from 2024-10-17 16-02-08](https://github.com/user-attachments/assets/3330a971-90c7-4788-97f5-d7401274657a)
![Screenshot from 2024-10-17 16-03-02](https://github.com/user-attachments/assets/4d693ac6-bea5-42f5-b1fa-c5e48a05bed5)
![Screenshot from 2024-10-17 16-03-19](https://github.com/user-attachments/assets/6e2e766a-fce9-4799-9d31-5751bd95a2c0)
![Screenshot from 2024-10-17 16-05-39](https://github.com/user-attachments/assets/18e8d85c-b96a-4acf-a76e-9d52ddb03f71)

Direct and inherited Multisig Permissions:

![Screenshot from 2024-10-17 16-04-49](https://github.com/user-attachments/assets/b54c9a31-42c8-41ba-9e67-0a757a09e8a8)
![Screenshot from 2024-10-17 16-06-48](https://github.com/user-attachments/assets/006f7315-d2bc-4b05-a49f-bd3b93231cf2)
![Screenshot from 2024-10-17 16-15-09](https://github.com/user-attachments/assets/ef36cc04-fa3f-466c-b905-5ddd539d5484)
![Screenshot from 2024-10-17 16-16-08](https://github.com/user-attachments/assets/a79e8a2a-cc6c-4e59-8f1f-962883fdc35e)
![Screenshot from 2024-10-17 16-16-35](https://github.com/user-attachments/assets/327292ae-611b-48b1-9c4e-eb805d3ef94e)
![Screenshot from 2024-10-17 16-17-20](https://github.com/user-attachments/assets/aa75c971-d8bb-495d-9c3d-5d7b2f1ebc47)

**Bella and Alex admins and owners:**

![Screenshot from 2024-10-17 16-29-16](https://github.com/user-attachments/assets/b23ee353-cf1f-498e-8dca-e6c89d44ffbe)
![Screenshot from 2024-10-17 16-29-45](https://github.com/user-attachments/assets/f93b0de9-25bf-43e6-884b-b3219632bc7e)
![Screenshot from 2024-10-17 16-30-19](https://github.com/user-attachments/assets/1042186b-3d8f-4ed3-94ec-d7107dc435d8)
![Screenshot from 2024-10-17 16-31-14](https://github.com/user-attachments/assets/200f54b9-6937-4fff-88e2-521d27cbed91)
![Screenshot from 2024-10-17 16-31-54](https://github.com/user-attachments/assets/51d3df91-c74a-4645-ba49-5d6c54483664)
![Screenshot from 2024-10-17 16-32-08](https://github.com/user-attachments/assets/62782f55-7ace-487b-a936-e1de98891a64)
![Screenshot from 2024-10-17 16-32-18](https://github.com/user-attachments/assets/b68a1a2a-2c3b-4b20-a453-900e506ea136)
![Screenshot from 2024-10-17 16-32-26](https://github.com/user-attachments/assets/c0238745-aa2a-4c47-9664-99bdd2bee954)

**Fry custom permissions:**

![Screenshot from 2024-10-17 16-34-41](https://github.com/user-attachments/assets/a7677b23-f97f-40f4-a2d0-dae6f9ba179f)
![Screenshot from 2024-10-17 16-36-46](https://github.com/user-attachments/assets/42d7b3a4-d1f3-4ba0-ad6e-5cdb34d6f301)
![Screenshot from 2024-10-17 16-37-23](https://github.com/user-attachments/assets/e44c73e9-14fa-4478-8e9e-a6604a247c29)
![Screenshot from 2024-10-17 16-37-42](https://github.com/user-attachments/assets/1b5d1c2b-b88c-49d7-ab34-539c46c5e12b)

----

While reviewing this I found two bugs, but in the spirit of getting this resolved once and for all, I'll point them out, but I'll ask you to open separate issues for each one, so that it doesn't pollute this one.

1. User popover cuts off the reputation percentage points

![Screenshot from 2024-10-17 16-03-42](https://github.com/user-attachments/assets/055649d4-0e9b-433d-824e-6033d3b2bf0b)
![Screenshot from 2024-10-17 16-03-58](https://github.com/user-attachments/assets/52c08004-24be-439b-99b3-ad1d88502996)

2. Redo-ing a **multisig permissions** actions from the list will re-do it with normal permissions, not multisig as expected (but will work correctly when re-doing from the action sidebar)

https://github.com/user-attachments/assets/76e94a7b-6ba6-4ea4-94bf-135697b14e66

2024-10-17 14:30 UTC, Nortsova commented
Thanks @rdig ! ✨ Yes, the testing steps were the most painful here 😂 

Created issues as you asked 🙌: 
https://github.com/JoinColony/colonyCDapp/issues/3381
https://github.com/JoinColony/colonyCDapp/issues/3382

I also created this bug during current tests:
https://github.com/JoinColony/colonyCDapp/issues/3344

2024-10-18 12:07 UTC, Nortsova commented
Hey, I had a call with @olgapod today, and it inspired me to simplify the testing steps so we can transfer these test cases to auto-tests.

Here are 3 cases that should be tested. (Then repeat it with multi-sig 🥲) 

1. Roles inheritance 
- user has permissions just in the parent domain
- user has permissions just in the child domain (and nothing in the parent)
- user has more permissions in the child domain
- user has more permissions in the parent domain (so we have some inherited)

2. All teams should always show the highest user role

3. Merging roles
- user has 1 permission in the child domain and 1/2 in the parent, which we need to merge
- user has 1/2 permissions in child and another 1/2 in parent, which we need to merge


Step 1. Assign amy Payer permissions in **General**
Step 2. Assign fry Admin permissions in **Andromeda**
Step 3. Navigate to the Permissions page and Verify that:
Step 4. **All teams**: amy payer, fry admin 
Step 5. **General**: amy payer, fry doesn't show up
Step 6. **Andromeda**: amy payer (**inherited**), fry admin
Step 7. **Serenity**: amy payer (**inherited**), fry doesn't show up

Step 8. Assign amy Admin permissions in **Serenity**
Step 9. Assign amy Mod permissions in **Andromeda**
Step 10. Assign fry Owner permissions in **General**
Step 11. Navigate to the Permissions page and Verify that:
Step 12. **All teams**: amy admin, and fry owner
Step 13. **General**: amy payer, fry owner
Step 14. **Andromeda**: amy payer (**inherited**), fry owner (**inherited**)
Step 15. **Serenity**: amy admin, fry onwer (**inherited**)
Step 16. **Rocinante**: amy payer (**inherited**), fry owner (**inherited**)

Let's try Custom roles now

Step 17. Assign chris Administration (Custom) permissions in **General**
Step 18. Navigate to the Permissions page and Verify that:
Step 19. **All teams**: chris has Mod role
Step 20. Assign chris Funding (Custom) permissions in **Andromeda**
Step 21. Navigate to the Permissions page and Verify that:
Step 22. **All teams**: chris has Custom role
Step 23. Assign chris Funding and Arbitration (Custom) permissions in **Serenity**
Step 24. Navigate to the Permissions page and Verify that:
Step 25. **All teams**: chris has Payer role
Step 26. Assign chris Architecture, Funding and Arbitration (Custom) permissions in ** Rocinante**
Step 27. Navigate to the Permissions page and Verify that:
Step 28. **All teams**: chris has Admin role
Step 29. **General**: chris has Mod role
Step 30. **Andromeda**: chris has Custom role (**inherited**)
Step 31. **Serenity**: chris has Payer role (**inherited**)
Step 32. **Rocinante**: chris has Admin role (**inherited**)

Sorry it is not less, but at least more structured than previous steps.

By the way, there is a bug in Step 14. fry doesn't have an inherited pill, but is located under the owner category, with an Admin role in Andromeda, I raised this question and will inform you about the solution as soon as we find one. So maybe these test steps will be updated.

@bassgeta could you please verify these test cases?

2024-10-18 14:06 UTC, Nortsova commented
Okay, so any subdomain Owners should be shown under the Admin category, so I created a ticket to avoid scope creep here: https://github.com/JoinColony/colonyCDapp/issues/3397

Thanks @bassgeta for assistance :)

2024-10-21 10:00 UTC, iamsamgibbs approved these changes
Nice work figuring this out! There are still issues with the "Owner" permissions appearing in the sub-domains as you have already noted which does through off some of the inherited permissions - but otherwise this is working great and we can fine tune it with the next PR.

I won't spam all the screenshots here, but I followed through the testing steps without issue (other than Owner appearing where it shouldn't).

Also did a tiny bit of multi-sig testing too, this is probably worth a more thorough test at some point, but seems to be working well as far as I can tell!

<img width="1092" alt="Screenshot 2024-10-21 at 10 52 59" src="https://github.com/user-attachments/assets/8d501437-39aa-4ec4-b74b-e72c2a508300">

2024-10-22 10:17 UTC, merged