fix: change loading skeleton gradient for dark mode
JoinColony/colonyCDapp pull request #3380
Opened 2024-10-17 13:17 UTC by adam-strzelec

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-10-17 13:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3380) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3380) before we can accept your contribution.<br/><hr/>**strzelec** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=3380) it.</sub>

2024-10-22 13:21 UTC, rdig approved these changes
This seems to be all good, at least as much as I've tested.

However I want to ask you to be more specific with your testing instructions.

> Open loading skeleton

This is very generic, and I can't really tell _which_ loading skeleton I need to test

![Screenshot from 2024-10-22 16-19-38](https://github.com/user-attachments/assets/ab16657c-a807-42e2-8bf0-c2456bec3bfb)
![Screenshot from 2024-10-22 16-19-57](https://github.com/user-attachments/assets/3be22a20-df39-4b73-a7a9-28be2f196c54)

2024-10-22 16:13 UTC, iamsamgibbs requested changes
I'm afraid this might be a much bigger bit of work than initially anticipated.

This fix only applies to places where the LoadingSkeleton component is used.

So it works great here:
<img width="1057" alt="Screenshot 2024-10-22 at 17 08 25" src="https://github.com/user-attachments/assets/cb839eff-6018-44e3-9b48-48ce56e4adf5">

But the fix isn't applied anywhere that just uses the `skeleton` class and not the LoadingSkeleton, such as here:

<img width="725" alt="Screenshot 2024-10-22 at 17 09 30" src="https://github.com/user-attachments/assets/7eeb2bcd-b15d-4b52-8e53-4c7b7d351ca5">

There are at least 47 places where it is used just as a class name and having to use the `usePageThemeContext` hook everywhere just to apply this change is going to be a real pain. Is there definitely no way to make this change in the tailwind config to use this background-image for the `skeleton` class when in dark mode so we can avoid adding the `skeleton-dark` class everywhere?

2024-10-22 16:23 UTC, arrenv commented
47 file changes does not seem worth the effort at all for a slight color change, so, if this cannot be unified as a part of this PR then I would suggest scrapping this issue.

2024-10-22 16:49 UTC, rdig requested changes
In light of recent changes I will rescind my approval

2024-10-23 13:54 UTC, adam-strzelec commented
@arrenv @rdig @mmioana @iamsamgibbs You're right. I didn't notice that skeleton can be called in other ways in the application than just through LoadingSkeleton. I've fixed that and it should work in the whole application now.

2024-10-24 07:39 UTC, iamsamgibbs approved these changes
Nice solution, this seems to work for me.

<img width="1141" alt="Screenshot 2024-10-24 at 08 34 56" src="https://github.com/user-attachments/assets/7cb4da64-8443-4bda-ab75-69d9ba05f9fd">

<img width="1013" alt="Screenshot 2024-10-24 at 08 35 07" src="https://github.com/user-attachments/assets/6a2cc4e5-bc0c-45b3-b4d5-63131cc6536e">

<img width="729" alt="Screenshot 2024-10-24 at 08 35 13" src="https://github.com/user-attachments/assets/a1c7f54d-3573-4259-b3d8-b2db1e753662">

Light mode is unaffected:

<img width="1146" alt="Screenshot 2024-10-24 at 08 35 57" src="https://github.com/user-attachments/assets/08250170-7fb2-47e5-bad4-ba48d13d45fd">

<img width="679" alt="Screenshot 2024-10-24 at 08 36 04" src="https://github.com/user-attachments/assets/4e0306cb-92a2-4938-b4f3-e3f8941471c2">

2024-10-24 08:34 UTC, mmioana approved these changes
Definitely a global and more clean approach to solving this issue 💯 

Nice work @adam-strzelec 🙌 

Dark mode
![Screenshot 2024-10-24 at 10 26 15](https://github.com/user-attachments/assets/f648353a-ceae-4a60-b2ce-f56cc978b981)
![Screenshot 2024-10-24 at 10 27 07](https://github.com/user-attachments/assets/ec875e25-c37f-4d95-9c68-c08508f44ed3)

Light mode
![Screenshot 2024-10-24 at 10 26 25](https://github.com/user-attachments/assets/f1a953a4-8ca6-426b-a609-23ad89ff9b7e)
![Screenshot 2024-10-24 at 10 26 50](https://github.com/user-attachments/assets/79ef96c3-826b-4b12-a3d8-40d53522667d)

2024-10-31 11:19 UTC, rumzledz approved these changes
Clean and wonderful fix @adam-strzelec !! ✨ 

![dark mode loader](https://github.com/user-attachments/assets/f734c297-c646-461a-b5d0-fa45de02f58d)

2024-10-31 11:19 UTC, rumzledz commented on tailwind.config.js
> +            'background-image': `linear-gradient(90deg,rgba(255, 255, 255, 0),${theme('colors.gradient.base')},rgba(255, 255, 255, 0))`,
Yessssss yes yes yes 💯

2024-11-04 11:20 UTC, adam-strzelec commented
@rdig I think I need your approval to merge it as now the merging is blocked.

2024-11-04 12:02 UTC, rdig approved these changes

2024-11-04 12:02 UTC, rdig commented
@adam-strzelec done! :100:

2024-11-04 12:05 UTC, merged