fix: update table for mobile view
JoinColony/colonyCDapp pull request #3401
Opened 2024-10-18 16:01 UTC by Nortsova

## Description

- [x] The status arrow should show by default, it's currently not showing, and the user do not know it's available for sorting. The table should stay by default sorted by date, so no change here. 

<img width="146" alt="image" src="https://github.com/JoinColony/colonyCDapp/assets/82127904/f0c957a3-0d7b-418f-99f6-4df72a790ea1">

- [x] Mobile table styling should match Figma designs on mobile figma: https://www.figma.com/design/C2grfQysdsYXz0j4rADR6K/Crypto-to-Fiat?node-id=4456-37629&node-type=frame&t=jlSKOZ8yTQr98oqZ-0

| **Before** | **Now** |
| ----- | ----- |
| ![Screenshot 2024-07-29 at 12 24 20](https://github.com/user-attachments/assets/8fa675b4-9ea6-4e1a-9800-a0d4d2446bef) | <img width="589" alt="image" src="https://github.com/user-attachments/assets/8d983f0b-fcdf-4ae8-a8ee-fa24a998d4a5"> |

## Testing
1. Create `.diff` file in your root direction
2. Insert this changes:
```
diff --git a/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx b/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx
index 6108cd1dc..167bc241a 100644
--- a/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx
+++ b/src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransfersTable.tsx
@@ -45,7 +45,58 @@ const FiatTransfersTable = () => {
   ]);
 
   const isMobile = useMobile();
-  const { sortedData, loading } = useFiatTransfersData(sorting);
+  const { sortedData: data, loading } = useFiatTransfersData(sorting);
+
+  const sortedData: typeof data = [
+    {
+      __typename: 'BridgeDrain',
+      id: '12343',
+      amount: '1234.22',
+      currency: 'usdc',
+      state: 'payment_processed',
+      createdAt: '2024-09-20T13:11:22.310Z',
+      receipt: {
+        __typename: 'BridgeDrainReceipt',
+        url: '#',
+      },
+    },
+    {
+      __typename: 'BridgeDrain',
+      id: '12344',
+      amount: '24689.00',
+      currency: 'usdc',
+      state: 'in_review',
+      createdAt: '2024-08-17T10:14:08.450Z',
+      receipt: {
+        __typename: 'BridgeDrainReceipt',
+        url: '#',
+      },
+    },
+    {
+      __typename: 'BridgeDrain',
+      id: '12345',
+      amount: '2230.77',
+      currency: 'usdc',
+      state: 'awaiting_funds',
+      createdAt: '2024-07-16T06:04:23.100Z',
+      receipt: {
+        __typename: 'BridgeDrainReceipt',
+        url: '#',
+      },
+    },
+    {
+      __typename: 'BridgeDrain',
+      id: '12346',
+      amount: '1200662.77',
+      currency: 'usdc',
+      state: 'awaiting_funds',
+      createdAt: '2024-07-16T06:04:23.100Z',
+      receipt: {
+        __typename: 'BridgeDrainReceipt',
+        url: '#',
+      },
+    },
+  ];
 
   const columns = useFiatTransfersTableColumns(loading);
 
```
3. `git apply .diff`
4. Navigate to Crypto to fiat tab http://localhost:9091/account/crypto-to-fiat 
5. Check that the Drain history matches the design
6. Check that the Status column has an arrow.

Resolves #2662

2024-10-21 11:45 UTC, rdig requested changes
Table itself is all good, but shouldn't it have more padding at the bottom ?

As it stands, on  my machine at least, it renders glued to the bottom of the viewport

![Screenshot from 2024-10-21 14-43-23](https://github.com/user-attachments/assets/b6e0310b-0bef-418f-bd99-58681fdc382c)
![Screenshot from 2024-10-21 14-43-32](https://github.com/user-attachments/assets/3a07ad46-e6bc-44c9-acc9-ffee6f86dd34)
![Screenshot from 2024-10-21 14-43-58](https://github.com/user-attachments/assets/fbe73e6f-b8d7-4124-ac8b-5705f63d4282)
![Screenshot from 2024-10-21 14-44-06](https://github.com/user-attachments/assets/f449fbde-b776-487a-ac7d-bde440864cf5)

2024-10-22 11:41 UTC, Nortsova commented
Thank you @rdig . I made some changes and now this table should match on both, desktop and mobile. I also added padding-bottom 🙌 

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/9f28e913-c63c-4ce2-a3ff-b17875bac0d4">

<img width="418" alt="image" src="https://github.com/user-attachments/assets/15afff72-db9e-4688-942f-6fb26413b3f7">

2024-10-23 11:55 UTC, iamsamgibbs requested changes
Great work on this so far, the styling is spot on:

<img width="644" alt="Screenshot 2024-10-23 at 12 46 34" src="https://github.com/user-attachments/assets/d3f4419c-2617-462f-a0b5-387d299dfcad">

I'm rejecting because the status sorting doesn't actually work until you sort by one of the other columns first:

https://github.com/user-attachments/assets/f2663a28-d382-4bfe-8fcf-1563eb2fb56d

It is also possible to sort by amount, so I'm not sure if that should be restricted so that it is not possible or whether the arrow needs to be visible here as the original issue states the reason for adding the arrow to the state field is to show that it can be sorted.

2024-10-28 11:54 UTC, Nortsova commented
Hey Sam! Nice catch. I think we don't have this design before with multiple arrows, I refactored a bit and now it should works fine:
![sorting](https://github.com/user-attachments/assets/d4886471-cdd5-4b7c-a04e-23c453609573)

I will message @melyndav regarding the Amount sorting! thank you :)

2024-10-29 10:46 UTC, iamsamgibbs requested changes
This is looking closer now! Unfortunately I'm experiencing this weird issue with the data not sorting and the arrow direction changing on other columns. I'm not exactly sure how this is supposed to function with multiple visible arrows.

https://github.com/user-attachments/assets/c8891733-9bd4-4e26-97ac-ad72937bff93

2024-10-30 12:57 UTC, Nortsova commented
Thank you @iamsamgibbs for your attantion to details, I spoke to @melyndav today and it seems I misunderstood the design. 

Here is updated version: 
![drain-table](https://github.com/user-attachments/assets/06970c0b-2cf2-4e1c-900a-8cfc8cd18bde)

Arrows will be hidden for all columns and visible for sorted ones, also on hover, you can see an arrow that means that the column is sortable 🙌

2024-10-31 09:53 UTC, iamsamgibbs approved these changes
Great work @Nortsova - this is working really nicely and makes a lot more sense now.

https://github.com/user-attachments/assets/4ea6ba20-5c2c-4a76-8973-c372f412c7cd

And working on mobile too:

https://github.com/user-attachments/assets/868a98e9-a2be-45c0-8146-1e8a8b37d17b

Code changes look sensible and nice to see that you got the arrow hover working too!

2024-10-31 09:53 UTC, iamsamgibbs commented on src/components/v5/common/Table/Table.tsx
> +                              'flex h-full flex-col items-start justify-center p-4 text-md',
Does this change break anything for tables elsewhere in the app? I couldn't check the activity feeds as previous actions weren't loading for me at the time of testing.

2024-11-01 15:21 UTC, rdig approved these changes
All good here! Very nice!

![Screenshot from 2024-11-01 17-19-55](https://github.com/user-attachments/assets/8b0967fc-8f92-4e78-b27a-6ff1be3f6311)
![Screenshot from 2024-11-01 17-20-07](https://github.com/user-attachments/assets/0e22715a-4086-46e7-b8fb-9ead406f771b)
![Screenshot from 2024-11-01 17-20-28](https://github.com/user-attachments/assets/c36607dd-0314-4125-b37f-a6669ca077e0)
![Screenshot from 2024-11-01 17-20-47](https://github.com/user-attachments/assets/290e52bf-7fb0-476d-81f9-4bbbb6989a80)

2024-11-05 09:32 UTC, bassgeta approved these changes
Yup looks legit and also works as it should :+1: 
Mobile:
![image](https://github.com/user-attachments/assets/a7a453cd-76b2-4b84-8da8-a33f886c32ac)
![image](https://github.com/user-attachments/assets/f0b1df8b-8cfc-42ff-8e8e-0ef00a5f944b)
Desktop:
![image](https://github.com/user-attachments/assets/01eb84d0-aa27-4972-9354-577d0cf07247)

2024-11-05 09:32 UTC, bassgeta commented on src/components/frame/v5/pages/UserCryptoToFiatPage/partials/FiatTransfersTable/FiatTransferDescriptionRow.tsx
> +  const textClassName = 'font-normal text-sm flex items-center';
I guess we can either wrap this in `tw` or just smash it down into the className directly

2024-11-05 10:35 UTC, merged