feat: add landing page carousel
JoinColony/colonyCDapp pull request #3407
Opened 2024-10-21 12:02 UTC by adam-strzelec

## Description

Create carousel for landing page

## Testing

- Run storybook
- Open `Landing Page Carousel`

## Diffs

**New stuff** ✨

https://github.com/user-attachments/assets/d4b58651-5c00-452f-9798-800d15b50b9e

Main issue - https://github.com/JoinColony/colonyCDapp/issues/3392

2024-10-21 12:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3407) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3407) before we can accept your contribution.<br/><hr/>**strzelec** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=3407) it.</sub>

2024-10-22 08:31 UTC, mmioana requested changes
Nice start on this issue @adam-strzelec 👏 

The landing page carousel adjustments look really nice 🤩 

https://github.com/user-attachments/assets/8e6221c0-c274-46f8-8362-8aa0d3f7ff1e

![Screenshot 2024-10-22 at 10 26 55](https://github.com/user-attachments/assets/4d6c8543-ffd6-4af8-b647-dadd4e8f6a9c)


I have left a few refactoring comments and would highly appreciate if you can tackle them 💯

2024-10-22 08:31 UTC, mmioana commented on src/components/frame/LandingPage/LandingPageCarousel.tsx
Nice job with this component @adam-strzelec 👍 however I would propose refactoring it as following, in order to store the messages in a single variable, then easily adjust the number of slides and their parsing. 
Also it's always better to try to define a variable for storing a check rather than repeating it (`currentSlide === index`) as if in the future there is a need to change the condition you might end up loosing track of the places this needs to be changed

```
import clsx from 'clsx';
import React, { useState } from 'react';
import { defineMessages, FormattedMessage } from 'react-intl';

import ImageCarousel from '~common/Extensions/ImageCarousel/ImageCarousel.tsx';
import Slide1 from '~images/assets/landing/slider1.png';
import Slide2 from '~images/assets/landing/slider2.png';
import Slide3 from '~images/assets/landing/slider3.png';
import SlideMobile from '~images/assets/landing/sliderMobile.png';

const displayName = 'frame.LandingPageCarousel';

const MSG = defineMessages({
  titleSlide0: {
    id: `${displayName}.titleSlide0`,
    defaultMessage: 'A powerful, all-in-one payments suite',
  },
  titleSlide1: {
    id: `${displayName}.titleSlide1`,
    defaultMessage: 'Make bulk payments your way with ease',
  },
  titleSlide2: {
    id: `${displayName}.titleSlide2`,
    defaultMessage: 'Easily track & manage shared finances',
  },
  descriptionSlide0: {
    id: `${displayName}.descriptionSlide0`,
    defaultMessage:
      'From simple transactions to complex financial operations like Streaming, Milestone based, and Split payments, you can do it with Colony.',
  },
  descriptionSlide1: {
    id: `${displayName}.descriptionSlide1`,
    defaultMessage:
      'Make bulk payments to different recipients using various tokens, amounts and scheduling. Saving time and reducing potential errors.',
  },
  descriptionSlide2: {
    id: `${displayName}.descriptionSlide2`,
    defaultMessage:
      'Transparency and clarity around shared finances is made simply with dashboard highlights, transaction history, and shared decision making. ',
  },
});

const slides = [
  {
    title: MSG.titleSlide0,
    description: MSG.descriptionSlide0,
  },
  {
    title: MSG.titleSlide1,
    description: MSG.descriptionSlide1,
  },
  {
    title: MSG.titleSlide2,
    description: MSG.descriptionSlide2,
  },
];

const LandingPageCarousel = () => {
  const [currentSlide, setCurrentSlide] = useState(0);

  return (
    <div>
      <div className="w-full max-w-[31.25rem] md:hidden">
        <img className="h-auto w-full" src={SlideMobile} alt="slider mobile" />
      </div>
      <div className="hidden w-full max-w-[31.25rem] overflow-hidden md:block">
        <div className="relative mb-9 h-[7.25rem]">
          {slides.map((slide, index) => {
            const isCurrentSlide = currentSlide === index;
            return (
              <div className="absolute left-0 top-0">
                <h1
                  className={clsx(
                    'transition-opacity duration-normal heading-2',
                    {
                      'opacity-100 delay-150': isCurrentSlide,
                      'opacity-0': !isCurrentSlide,
                    },
                  )}
                >
                  <FormattedMessage {...slide.title} />
                </h1>
                <p
                  className={clsx(
                    'mt-[.875rem] text-md font-normal transition-opacity duration-normal',
                    {
                      'opacity-100 delay-150': isCurrentSlide,
                      'opacity-0': !isCurrentSlide,
                    },
                  )}
                >
                  <FormattedMessage {...slide.description} />
                </p>
              </div>
            );
          })}
        </div>
        <ImageCarousel
          slideUrls={[Slide1, Slide2, Slide3]}
          options={{ align: 'center', loop: true }}
          isImageFullWidth
          isAutoplay
          isChangeSlideDotButton={false}
          setSelectedIndex={(currentSlideIndex) =>
            setCurrentSlide(currentSlideIndex)
          }
          className="mx-[-30px] pb-[115px]"
        />
      </div>
    </div>
  );
};

LandingPageCarousel.displayName = displayName;

export default LandingPageCarousel;

```

2024-10-22 09:43 UTC, bassgeta requested changes
Looking quite good so far! Left a few improvement suggestions, but I see @mmioana  already covered most of what I intended to drop comments on.
But overall, a nice implementation so far, seems quite extensible and I love that you've created a reusable component that doesn't do too much - `ImageCarousel` and that you've decoupled the landing page on into a new one instead of just smashing everything in the `LandingPage` component :+1:

2024-10-22 09:43 UTC, bassgeta commented on src/components/common/Extensions/ImageCarousel/ImageCarousel.tsx
> +  isImageFullWidth,
what if we rework `slideUrls` to be an array of image urls and classNames? would be a bit cleaner, since now we control all images from one variable

2024-10-22 09:43 UTC, bassgeta commented on src/components/common/Extensions/ImageCarousel/ImageCarousel.tsx
> +              'py-[10px]': !isChangeSlideDotButton,
could we just render a whole different thing if `isChangeSlideDotButton` is false?

2024-10-23 07:40 UTC, mmioana commented on src/components/common/Extensions/ImageCarousel/ImageCarousel.tsx
> +        )}
I would suggest a very small change here @adam-strzelec if you could please add a constant 
`const isSelectedIndex = index === selectedIndex` and replace the usage of `index === selectedIndex` with `isSelectedIndex`?

2024-10-23 07:43 UTC, mmioana approved these changes
Amazing work @adam-strzelec and thanks so much for your fast changes 💯 🙏 

Everything still looks good and works as expected 🎉 

https://github.com/user-attachments/assets/a0981a67-b75f-4c6a-8835-eb44d521a8c5

Left a very small refactoring suggestion, but definitely not a blocker for merging this PR, so feel free to decide whether to tackle it or not 👍

2024-10-23 12:32 UTC, bassgeta approved these changes
Thanks for the changes made, it looks good design wise and code wise and thanks again for the quick turnaround!
![Uploading image.png…]()

2024-10-24 08:41 UTC, AdrianDudko commented
Hey @rdig , I understand that 3 approvals are required to merge the PR, but if we don’t receive 3 reviews (and approvals) by the end of tomorrow, we will go ahead and merge this PR. The deadline for submitting the Landing Page Updates is around November 20th, and I know your team has a conference planned, which will likely slow down the CR process. I would like this to apply to @adam-strzelec  other PRs related to the Landing Page Updates as well, to ensure that we stay on track.

2024-10-25 10:19 UTC, arrenv requested changes
Thank you @adam-strzelec, looks and works well. I only noticed a couple of things:

1. The drop shadows are being cut off by the max width.

![image](https://github.com/user-attachments/assets/1ca21a48-b337-45ff-87ea-d873187f37fb)

![image](https://github.com/user-attachments/assets/d6d6bda9-42b4-4ddc-8214-59b637c17d7f)

![image](https://github.com/user-attachments/assets/bd665efb-fec3-4fcd-ba09-fdf50b0df1e5)

![image](https://github.com/user-attachments/assets/5dc14905-4057-49f3-a695-43d67e0ab672)

2. Can the auto timer be reset when manually navigating? It seems a little aggressive when trying to navigate back.

[time-reset.webm](https://github.com/user-attachments/assets/753a97ce-a84f-44f5-8687-87c2b200a5cc)

2024-10-25 15:38 UTC, rumzledz commented
This is a product question: CC @arrenv @melyndav 

Do we want to continue the carousel's auto paging when a user manually clicks on a slide position? I find that under some scenarios, if I clicked a slide, then the carousel automatically moves onto the next slide:

![timer](https://github.com/user-attachments/assets/2e4ad775-da01-4a4c-88bb-8296374837e7)

2024-10-25 15:51 UTC, rumzledz requested changes
Carousel's looking pretty good @adam-strzelec ! Just found some areas that need to be updated. Here's one I'd like to highlight:

According to Figma, these components need to use gray-900 when active:

<img width="536" alt="Screenshot 2024-10-25 at 23 49 29" src="https://github.com/user-attachments/assets/e42b5269-66b3-4bc1-880d-0f0a79ad4952">

Might be a good opportunity to investigate what's going on here, but that's up to you 😄 

<img width="449" alt="image" src="https://github.com/user-attachments/assets/b090ee10-f554-4ec3-95fe-b418bfe022f0">

2024-10-25 15:51 UTC, rumzledz commented on src/components/frame/LandingPage/LandingPageCarousel.tsx
> +      'Transparency and clarity around shared finances is made simply with dashboard highlights, transaction history, and shared decision making. ',
**[Nitpick alert]:** There's an extra whitespace at the end 👀

2024-10-25 15:51 UTC, rumzledz commented on src/components/frame/LandingPage/LandingPageCarousel.tsx
> +          }
**[Nitpick alert]:** Can also be simply `setSelectedIndex={setCurrentSlide}`

2024-10-25 15:51 UTC, rumzledz commented on src/components/frame/LandingPage/LandingPageCarousel.tsx
> +                    'mt-[.875rem] text-md font-normal transition-opacity duration-normal',
This should use the `text-gray-600` tailwind class according to the Figma designs:

<img width="830" alt="Screenshot 2024-10-25 at 23 47 40" src="https://github.com/user-attachments/assets/43c415c1-2d7b-4dde-997e-7265231ffe7e">

2024-10-28 09:10 UTC, adam-strzelec commented
@rumzledz done

2024-10-28 11:14 UTC, rumzledz approved these changes
Thanks for the amendments! LGTM 🚀

2024-10-28 12:07 UTC, merged