feat add invitation banner for landing page
JoinColony/colonyCDapp pull request #3431
Opened 2024-10-22 17:04 UTC by adam-strzelec

## Description

Add colony invitation banner for landing page

## Testing

- Run storybook
- Open `Colony Invitation Banner`

## Diffs

**New stuff** ✨

<img width="529" alt="Screenshot 2024-10-22 at 18 43 47" src="https://github.com/user-attachments/assets/e939085e-4f5a-47e8-8687-5516632f2032">

<img width="528" alt="Screenshot 2024-10-22 at 19 03 50" src="https://github.com/user-attachments/assets/1a8faa06-a9b9-4325-9c43-49c258c38ba9">

Main issue - https://github.com/JoinColony/colonyCDapp/issues/3392

2024-10-22 17:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3431) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3431) before we can accept your contribution.<br/><hr/>**strzelec** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=3431) it.</sub>

2024-10-24 09:02 UTC, mmioana requested changes
What a nice component @adam-strzelec 🙌 

Design wise seem to be looking as expected
![Screenshot 2024-10-24 at 10 59 48](https://github.com/user-attachments/assets/d651dd94-26e1-46a0-ba86-eb9a32d90dfb)
![Screenshot 2024-10-24 at 10 59 50](https://github.com/user-attachments/assets/47ea0014-5570-4ecf-b33e-2f249276b0e7)
![Screenshot 2024-10-24 at 10 59 53](https://github.com/user-attachments/assets/6700aae1-8c58-4726-a215-9c15fd57d4b5)

Left a veeeery tiny refactoring comment 😁 
But nice job 🎉

2024-10-24 09:10 UTC, mmioana requested changes
Sorry @adam-strzelec on a second look I found some small mismatches with Figma

2024-10-24 09:10 UTC, mmioana commented on src/components/frame/LandingPage/ColonyInvitationBanner.tsx
> +      <p className="mt-2 text-sm font-normal">
And I think we should also apply `text-gray-700`

2024-10-25 08:21 UTC, bassgeta requested changes
Another one smashed out of the park! Really nice, and a really simple component to look at.
I've just left a comment if we could move the i18n messages into this component and then we're good to go!
![image](https://github.com/user-attachments/assets/84431d05-24f0-4d8b-af8a-793167a4bd4f)

2024-10-25 08:21 UTC, bassgeta commented on src/components/frame/LandingPage/ColonyInvitationBanner.tsx
> +        {formatText(
Could we move all i18n strings into this component?

2024-10-25 08:50 UTC, arrenv requested changes
@adam-strzelec Thank you for the PR, and your work on the new landing page. Mostly looks good.

What I noticed is that the ticket icon is responsive, however, should be fixed. When using the full expected invite link, is aligns to the top and get squished. I have also exaggerated this with a really long invite link as well. 

### With the provided string
![image](https://github.com/user-attachments/assets/a2fd6c05-eaa5-48fd-a2e6-3b22468a0342)

### With the expected string
![image](https://github.com/user-attachments/assets/4da34beb-5353-412e-b055-405430ce897f)

### With an exaggerated string
![image](https://github.com/user-attachments/assets/fa9b7b22-42b4-4560-9a95-cfa51feb184e)

2024-10-25 10:27 UTC, arrenv approved these changes
@adam-strzelec Thank you, looks good now!

2024-10-25 15:18 UTC, rumzledz requested changes
Hey @adam-strzelec I've just realised that this is the first time I'm speaking to you so hello! 👋 😂 

Great job on this PR so far! I left comments in areas that need to be tweaked, but I wanted to highlight this one:

The Copy link button should follow the Figma design system. Currently, when you click it, the only thing that changes is the SVG:

![copylink](https://github.com/user-attachments/assets/7306500a-0b68-4193-b091-32b438b3ac89)

It should actually turn to green and the copy should say "Link copied". You'll find the design system here:

https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1801-464&t=jofkV0FxoYS1PGK6-4

We have a `completed` value for the `mode` prop if you wanna experiment with that:

```js
<Button mode="completed" />
```

2024-10-25 15:18 UTC, rumzledz commented on src/components/frame/LandingPage/ColonyInvitationBanner.tsx
> +        <div className="mt-2 flex flex-col gap-2 rounded-md bg-gray-50 px-3 py-3">
**[Nitpick alert]:** Instead of `px-3 py-3`, use `p-3`

2024-10-25 15:18 UTC, rumzledz commented on src/components/frame/LandingPage/ColonyInvitationBanner.tsx
> +        <div className="mt-2 flex flex-col gap-2 rounded-md bg-gray-50 px-3 py-3">
This should be `gap-4` (16px) according to the Figma designs:

![gap-4](https://github.com/user-attachments/assets/1f67b02e-c570-49c3-b830-ff595be34d37)

2024-10-25 15:18 UTC, rumzledz commented on src/components/frame/LandingPage/ColonyInvitationBanner.tsx
> +      <div className="flex h-10 w-10 items-center justify-center rounded-md border">
The border radius should be `4px`, at the moment it's `6px`

2024-10-25 15:21 UTC, rumzledz commented
Sorry one more thing, you might want to handle the pluralisation of the word "colonies" as well. Should say "1 colony remaining"

<img width="522" alt="image" src="https://github.com/user-attachments/assets/46bbe837-bf18-4bbe-a1ac-9c841e8d0438">

2024-10-25 15:24 UTC, rumzledz commented
Sorry one more thing, you might want to handle the pluralisation of the word "colonies" as well. Should say "1 colony remaining"

<img width="522" alt="image" src="https://github.com/user-attachments/assets/46bbe837-bf18-4bbe-a1ac-9c841e8d0438">

This should do the trick! 😄 

```js
defaultMessage: `{remaining} {remaining, plural, one {colony} other {colonies}} remaining`,
```

2024-10-28 08:10 UTC, adam-strzelec commented
Hello @rumzledz Nice to meet you 🙂
I already added the corrections.

2024-10-28 11:46 UTC, iamsamgibbs approved these changes
Amazing job, this all looks great. Code is nicely structured and matches figma perfectly:

<img width="539" alt="Screenshot 2024-10-28 at 11 45 08" src="https://github.com/user-attachments/assets/c136f981-6a9e-4c93-9373-9a54479b775d">
<img width="530" alt="Screenshot 2024-10-28 at 11 45 12" src="https://github.com/user-attachments/assets/dc8085d6-7714-4f50-abc2-1b514180b7bb">
<img width="189" alt="Screenshot 2024-10-28 at 11 45 42" src="https://github.com/user-attachments/assets/da9f2ac0-6eae-42b5-9d6f-ae24e1b81b04">

2024-10-28 12:04 UTC, merged