fix: disable 'Accept' incoming funds buttons when other button was clicked
JoinColony/colonyCDapp pull request #3477
Opened 2024-10-25 12:10 UTC by Nortsova

## Description

- [] Disable "Accept" buttons when "Accept all available" is loading
- [] Disable other "Accept" and "Accept all available" buttons when any "Accept" is loading

## Testing

* Step 1. Login with metamask
* Step 2. Clean Metamask history (Metamask -> Settings -> Advanced -> Clear activity tab data)
* Step 3. Navigate to Balance page
* Step 4. Click Add funds to the Colony and Copy Wallet address
* Step 5. Metamask -> send -> Paste Colony Wallet Address -> Send something to the colony (1 eth or if you choose xDai as Ganache Currency symbol choose xDai)
![send-1-etch](https://github.com/user-attachments/assets/7d507696-cd84-49d3-9b97-31b48eb00c51)

> [!TIP]
> If you don't have ETH to send try to delete Account and Import it again

* Step 6. Navigate to Wayne Enterprises
* Step 7. Create simple payment from General to Colony Wallet Address that you copied at Step 4. 
<img width="709" alt="image" src="https://github.com/user-attachments/assets/570b08d1-ce2c-4b62-a6dd-1d4a9d477376">

* Step 8. Navigate back to Planet Express
* Step 9. Navigate to Incoming funds
* Step 10. Try to Accept this funds
* Step 11. Verify that after you click "Accept" or "Accept all available" all other buttons are disabled:
![disabled-accept](https://github.com/user-attachments/assets/8f60b1f0-cc6b-44da-93af-763543ec7241)

> [!NOTE]
> I would recommend going through this flow twice: 1. Approve with the "Accept" button. 2. Approve with the "Accept all available" button. 
> I had another bug after pressing "Approve" in metamask before I started using values={getPayload} for the loading state. So, this is a weak place where something could go wrong.

Resolves #3313

2024-10-25 13:37 UTC, iamsamgibbs requested changes
Nice job fixing this up! I had a suspicion it would require a context when I was writing up the issue, so I'm glad that hunch was validated!

This works great:

https://github.com/user-attachments/assets/807dba38-5d01-4de8-a7bb-de5050c16a72

I think we could improve the accepting behaviour, the accept buttons become disabled before disappearing, but this is outside the scope of this issue:

https://github.com/user-attachments/assets/a8920454-da22-4d0b-ad96-a1bb173ff13a

I've left a minor comment regarding naming which I felt to be a bit unclear.

2024-10-25 13:37 UTC, iamsamgibbs commented on src/components/frame/v5/pages/FundsPage/partials/AcceptButton/AcceptButton.tsx
>    };
Oh in fact, on further inspection, it does require a payload, and it comes from the transform function above. Maybe we could adapt this `getPayload` function to return those values and remove the transform function?

2024-10-28 12:34 UTC, mmioana requested changes
Awesome work on this one @Nortsova and thanks for picking this issue up 🥇 🫶 

Even though I didn't manage to properly test sending tokens from Metamask to the colony, I tried other 2 test scenarios

1. Creating a simple payment from Wayne to Planex
![Screenshot 2024-10-28 at 13 25 08](https://github.com/user-attachments/assets/9c7d35d7-9a79-4ecc-9743-d8d8122f8f2b)


https://github.com/user-attachments/assets/823cede5-67a2-4a13-a87f-77d184f0698e

2. Commenting the claim funds transactions from the `mint tokens` saga


<img width="1090" alt="Screenshot 2024-10-28 at 13 27 35" src="https://github.com/user-attachments/assets/a4d28ea6-9bc4-4072-9d5c-fe095a6da1a5">

![Screenshot 2024-10-28 at 13 28 02](https://github.com/user-attachments/assets/fd47b4b1-f66d-48eb-ba9f-a7b0f3a2babb)

![Screenshot 2024-10-28 at 13 28 20](https://github.com/user-attachments/assets/09455eaf-dd96-4480-b43e-dad7cffc7775)

![Screenshot 2024-10-28 at 13 28 25](https://github.com/user-attachments/assets/6f77d17e-c9f7-47ec-b9eb-e9d3bdcc21be)

https://github.com/user-attachments/assets/e58bbc5d-d486-441e-82a9-e84e0ff56394

Did notice, just as @iamsamgibbs, the `Accept` button gets re-enabled just before disappearing, but I guess this can be treated in a separate issue. 

Left a few minor refactoring comments, if you can please have a look 🙏 

Again really nice work 💯

2024-10-28 20:26 UTC, Nortsova commented on src/components/frame/v5/pages/FundsPage/partials/AcceptButton/AcceptButton.tsx
>    };
hey, thank you so much for your comment, I removed transform and just put values here, I will double-check tomorrow to not break anything. 🙌

2024-10-29 10:11 UTC, Nortsova commented
Thank you guys for reviewing! I updated the code and created a ticket to disable the claiming button: 
https://github.com/JoinColony/colonyCDapp/issues/3502

2024-10-29 10:56 UTC, iamsamgibbs approved these changes
Thank you for the changes! This is still working great and the code reads more nicely now. 🎉

<img width="1330" alt="Screenshot 2024-10-29 at 10 56 01" src="https://github.com/user-attachments/assets/fdf0469d-5efa-4998-b63a-21b17be1b90a">

2024-10-29 11:08 UTC, mmioana approved these changes
Thanks so much for your changes @Nortsova 🫶 really nice and clean work!

All accept buttons are disabled once an incoming funds entry is accepted

https://github.com/user-attachments/assets/2a2acb97-790a-47fe-be5f-56290e490343

2024-10-29 13:26 UTC, jakubcolony approved these changes
LGTM, nice work @Nortsova 💯 

As I understand the issue of being able to click on Accept straight after Accept all will be solved in #3502. I can confirm the buttons are disabled while transactions are in progress.

https://github.com/user-attachments/assets/f0a2a290-320a-4e83-93e7-3e3cac3c0342

2024-10-30 10:15 UTC, merged