fix: always use roles passed to contract for motions
JoinColony/colonyCDapp pull request #3490
Opened 2024-10-28 13:19 UTC by bassgeta

## Description

This is just a block-ingestor hash update. Basically the solution to this was that instead of always getting the role delta in our block-ingestor handler, we just use what the contracts get called with. If we ever want to display the delta, we can get the user's latest historical roles :shrug: 

[Block ingestor PR](https://github.com/JoinColony/block-ingestor/pull/289)

## Testing

We need to test if both motions and multi-sig works for updating a member's roles. I'll mix and match multisig and voting reputation just so we cover as many cases as possible without having 20 test cases.
For sanity checks, let's use 2 browsers, `leela` and `amy`.

1. Install the voting reputation extension
2. As `leela` install the multisig extension and give `leela` the Multi-sig owner role.
3. Now let's try this out! Assign `amy` the `Payer` permissions via Multi-sig in `Andromeda`. Finalize the motion and navigate to the members page. 
![image](https://github.com/user-attachments/assets/aca9d185-e222-4a87-9129-2c1875efb63a)
4. Verify that `amy` has the payer role in Andromeda. As an extra check as `amy` try to create a simple payment action from `Andromeda` to anywhere
![image](https://github.com/user-attachments/assets/ffd5fdec-d587-4b49-8086-5fe357f6c5c7)
![image](https://github.com/user-attachments/assets/06751e62-f160-44d6-b090-0a0ee23649b7)
5. Now let's go ahead and create a voting reputation motion to assing `amy` the `Admin` role in `Andromeda`.
![image](https://github.com/user-attachments/assets/f9d2401e-08f1-44bc-90fb-97efa5c1c6b1)
6. When the action gets created, verify that you see the entire role group and not just the new `Architecture` role. 
![image](https://github.com/user-attachments/assets/92c74df6-613b-4ba2-8eb5-ebb1d466406a)
7. Fully support, `npm run forward-time 1` and finalize the motion
![image](https://github.com/user-attachments/assets/c892d7b8-f405-4939-a79b-21ce88074f20)
8. Verify that `amy` received the `Admin` bundle on the members page and try to create an action to remove reputation from somebody in Andromeda
![image](https://github.com/user-attachments/assets/52d52d36-90e5-49ad-8c8b-883205cf5b63)
![image](https://github.com/user-attachments/assets/ef592cd4-c102-4984-826c-9f7b3d5812d1)
9. As `leela` assign `amy` just the `Arbitration` role in `Andromeda` via multi-sig. Verify that the completed action view only has Arbitration checked.
![image](https://github.com/user-attachments/assets/5afc22cf-17ac-4d17-84db-3e666faa8303)
10. Finalize it and verify that she only has that role (also as `amy` try to create a simple payment action, the UI should block it)
![image](https://github.com/user-attachments/assets/f890439b-20ce-4cba-9064-92cfd060ee99)
![image](https://github.com/user-attachments/assets/1bc77913-761e-48eb-b8d7-e8ac70472c45)
![image](https://github.com/user-attachments/assets/672800ff-df0b-4a7a-9947-d09cb2c7eb9e)
11. Now as `leela` create a voting reputation motion to remove all permissions from `amy` in `Andromeda`. Finalize it and verify that `amy` doesn't have any roles anymore.
![image](https://github.com/user-attachments/assets/27b4dff4-0ca3-46b0-9ed1-c43b4f66f7a0)
![image](https://github.com/user-attachments/assets/4d72acd9-7805-4b8b-9f14-ef68c7cacccd)

This should be it, now you can take this :beer:  and do the entire flow but for Multi-sig authority instead of permissions :sweat_smile: I suggest creating a voting reputation motion for multi-sig roles first (that's the only "uncovered" case, setting initial roles via a voting reputation motion).

## Diffs

**Changes** 🏗

* `getRolesMapFromHexString` always uses the passed string as the source of truth instead of saving the diff

Resolves #2672

2024-10-29 10:15 UTC, iamsamgibbs submitted a review, later dismissed
Nice work on this! It is working very nicely.

I tested following the testing steps:

<img width="447" alt="Screenshot 2024-10-29 at 09 18 47" src="https://github.com/user-attachments/assets/f82b4f87-2235-44c8-a104-9220e058da71">
<img width="1054" alt="Screenshot 2024-10-29 at 09 24 06" src="https://github.com/user-attachments/assets/2a612e1b-c4ac-432b-a9cb-f46c58465bd2">
<img width="1069" alt="Screenshot 2024-10-29 at 09 39 25" src="https://github.com/user-attachments/assets/a2b91076-7426-485d-a0c1-15bf66414daa">
<img width="456" alt="Screenshot 2024-10-29 at 09 40 08" src="https://github.com/user-attachments/assets/176e0526-c213-41da-bd13-40f12f97fd80">
<img width="1052" alt="Screenshot 2024-10-29 at 09 41 18" src="https://github.com/user-attachments/assets/5270b17a-9525-4d66-86fe-14fb71a3ca03">
<img width="454" alt="Screenshot 2024-10-29 at 09 50 58" src="https://github.com/user-attachments/assets/0548e9b6-b63b-4992-ad52-4be9bf3bc010">
<img width="431" alt="Screenshot 2024-10-29 at 09 53 31" src="https://github.com/user-attachments/assets/17268b7b-6b93-4ad9-91c0-93da3bbc5995">

Then also tested the same with multi-sig roles (I won't spam a second set of screenshots) - all worked without issue.

Also tried creating a motion, then changing all the roles via permissions before finalizing and the roles set in the motion were still respected. Nice to have this working consistently now!

2024-10-29 10:56 UTC, mmioana submitted a review, later dismissed
Nice work on this one @bassgeta it all works as expected 💯  though I believe from your testing steps you first assigned the regular permissions and only after the multi-sig ones

In any case, the permissions changes are working flawlessly and we get the desired behaviour

![Screenshot 2024-10-29 at 11 38 19](https://github.com/user-attachments/assets/8c0f1f18-1396-4750-8153-a273708c5914)
![Screenshot 2024-10-29 at 11 38 39](https://github.com/user-attachments/assets/f95f9db6-8d3b-4ea5-afad-6667ab1fd203)
![Screenshot 2024-10-29 at 11 39 16](https://github.com/user-attachments/assets/c5b1d86e-a116-43db-beaa-a81be508a085)
![Screenshot 2024-10-29 at 11 39 52](https://github.com/user-attachments/assets/8625aaf3-78d1-464e-b790-7aae11a545ef)
![Screenshot 2024-10-29 at 11 40 02](https://github.com/user-attachments/assets/29c8f087-47e0-40fb-b9f8-24e271c67c9d)
![Screenshot 2024-10-29 at 11 40 30](https://github.com/user-attachments/assets/ab459338-4bce-4d61-a16c-2ea51ccb0db3)
<img width="1159" alt="Screenshot 2024-10-29 at 11 41 50" src="https://github.com/user-attachments/assets/3e82b938-8a92-46ab-9fda-386b2644d374">
![Screenshot 2024-10-29 at 11 42 44](https://github.com/user-attachments/assets/9258a3c8-ce15-4324-a6f5-9f33cbc742b7)
![Screenshot 2024-10-29 at 11 43 39](https://github.com/user-attachments/assets/dc271cef-8511-4509-9a46-f13ff6c9992c)
![Screenshot 2024-10-29 at 11 44 10](https://github.com/user-attachments/assets/7609871b-86c1-4183-9dab-52a9952a0b95)
<img width="1159" alt="Screenshot 2024-10-29 at 11 45 43" src="https://github.com/user-attachments/assets/b84262ad-1ac1-491c-a3fb-67f41f263662">
![Screenshot 2024-10-29 at 11 46 43](https://github.com/user-attachments/assets/c5c3bfaf-60c0-47f5-9fd3-90979fac584b)
![Screenshot 2024-10-29 at 11 47 04](https://github.com/user-attachments/assets/b9122a2d-bb28-4076-a67c-6f85568c7e11)
<img width="1159" alt="Screenshot 2024-10-29 at 11 48 54" src="https://github.com/user-attachments/assets/03153688-9ad7-407e-9e6c-987cf0581c93">
![Screenshot 2024-10-29 at 11 49 42](https://github.com/user-attachments/assets/7f0ca8f1-6ff4-4fab-a34d-6c436d027aec)
![Screenshot 2024-10-29 at 11 49 59](https://github.com/user-attachments/assets/d720e69b-db1d-4bdd-bf8d-34c097a25713)

2024-10-29 17:30 UTC, rdig submitted a review, later dismissed
Tested and confirming what everyone else already found out, as this is working as intended. Nicely done!

![Screenshot from 2024-10-29 19-03-02](https://github.com/user-attachments/assets/255fe53f-9d16-40eb-b003-d2c0c67338b5)
![Screenshot from 2024-10-29 19-03-20](https://github.com/user-attachments/assets/35c5dd37-d709-47a2-bcd7-38bf14b63669)
![Screenshot from 2024-10-29 19-03-57](https://github.com/user-attachments/assets/bdbb1c8a-0388-40f8-ad72-b136daa8fc42)
![Screenshot from 2024-10-29 19-06-57](https://github.com/user-attachments/assets/cc54f8cc-bf36-42e9-9076-401cf1b4a5d4)
![Screenshot from 2024-10-29 19-07-08](https://github.com/user-attachments/assets/e6b9b1a1-4635-4852-87d9-3ac40434b203)
![Screenshot from 2024-10-29 19-07-29](https://github.com/user-attachments/assets/45fde317-807c-4323-8898-ccaf12b02f16)
![Screenshot from 2024-10-29 19-09-56](https://github.com/user-attachments/assets/4fa6d545-d99f-4172-a8f8-4ec7e8268f21)
![Screenshot from 2024-10-29 19-10-54](https://github.com/user-attachments/assets/591968f2-451c-437d-b919-60e29127cd6d)
![Screenshot from 2024-10-29 19-11-15](https://github.com/user-attachments/assets/421f898b-ac43-4276-86f0-a02dbfd8b5dc)
![Screenshot from 2024-10-29 19-12-12](https://github.com/user-attachments/assets/0ee5261e-ab43-4c86-b8a6-ff6933438625)
![Screenshot from 2024-10-29 19-13-21](https://github.com/user-attachments/assets/7cee380f-2dbb-4367-9fb0-a9e12017b7ac)
![Screenshot from 2024-10-29 19-26-05](https://github.com/user-attachments/assets/22243fde-2dce-4bc3-9533-141d03c70e37)
![Screenshot from 2024-10-29 19-26-51](https://github.com/user-attachments/assets/93bb339f-7e77-41a1-bcf6-d85dcd0ee4af)
![Screenshot from 2024-10-29 19-29-05](https://github.com/user-attachments/assets/419ea8cd-667b-4758-90bf-a36752c40150)

2024-11-04 11:32 UTC, rdig approved these changes
Re-approved

2024-11-04 11:59 UTC, iamsamgibbs requested changes
Something isn't lining up after the rebase unfortunately! #2749 got merged recently, maybe that unintentionally changed the way the motion view works?

Assigning Fry Payer permissions:
<img width="675" alt="Screenshot 2024-11-04 at 11 56 39" src="https://github.com/user-attachments/assets/6572a414-503b-4a26-9e71-e391c26873ba">

Shows as Owner:
<img width="1053" alt="Screenshot 2024-11-04 at 11 56 59" src="https://github.com/user-attachments/assets/fcdddcf0-9f39-4986-8185-717a2f5290e9">

2024-11-06 09:17 UTC, mmioana approved these changes
Awesome, it all seems to be working as expected @bassgeta 🥇 💯 

![Screenshot 2024-11-06 at 09 23 40](https://github.com/user-attachments/assets/4e782ac2-7a73-4ce4-a9cb-c79f1b7b39e0)
![Screenshot 2024-11-06 at 09 24 08](https://github.com/user-attachments/assets/4319db22-3170-4b67-a5d4-19b0d9bd10ae)
![Screenshot 2024-11-06 at 09 24 51](https://github.com/user-attachments/assets/da31870f-2a2c-470d-9d31-b417861d7c58)
![Screenshot 2024-11-06 at 09 27 09](https://github.com/user-attachments/assets/4343132d-01b8-4651-a49a-9c21dc0f0014)
![Screenshot 2024-11-06 at 09 32 02](https://github.com/user-attachments/assets/779e10db-68ed-49f6-b802-a57b20e702ef)
![Screenshot 2024-11-06 at 09 39 30](https://github.com/user-attachments/assets/dd8175a0-cb8b-46d0-ad32-44a99cae62bc)
![Screenshot 2024-11-06 at 09 56 03](https://github.com/user-attachments/assets/67edef2c-5292-4921-90ee-d3c1d26f604c)
![Screenshot 2024-11-06 at 09 57 06](https://github.com/user-attachments/assets/7e3a656f-4d99-4580-9781-43f31109994f)
![Screenshot 2024-11-06 at 09 57 15](https://github.com/user-attachments/assets/ed332bb5-bad5-4847-a449-7d04a896eac1)
![Screenshot 2024-11-06 at 09 57 32](https://github.com/user-attachments/assets/d770d3db-42a1-4547-bccd-4bfae1c1f002)
![Screenshot 2024-11-06 at 09 59 16](https://github.com/user-attachments/assets/cc8ed41a-6a70-4442-b733-0bbc5878c374)
![Screenshot 2024-11-06 at 10 01 05](https://github.com/user-attachments/assets/5a979f1b-d327-4c15-a026-56140c0b85de)
![Screenshot 2024-11-06 at 10 01 23](https://github.com/user-attachments/assets/01c8105e-7a59-4ac7-ac0a-524ab97f6f35)
![Screenshot 2024-11-06 at 10 01 44](https://github.com/user-attachments/assets/576c7d83-8959-4a1b-ab35-918d7719f75b)
![Screenshot 2024-11-06 at 10 03 10](https://github.com/user-attachments/assets/061b41e2-29ac-4f15-8f9c-068b33cd844f)
![Screenshot 2024-11-06 at 10 07 33](https://github.com/user-attachments/assets/5db2ced3-e780-47a2-a01e-fecc0ff64f44)
![Screenshot 2024-11-06 at 10 08 42](https://github.com/user-attachments/assets/a01cd377-6e15-4e8b-b3aa-b3254764e28f)
![Screenshot 2024-11-06 at 10 08 54](https://github.com/user-attachments/assets/43a5b909-0189-480e-bb77-0bb18fa5c961)
![Screenshot 2024-11-06 at 10 16 32](https://github.com/user-attachments/assets/957f1812-277f-4f5d-99fa-9302baa23185)
![Screenshot 2024-11-06 at 10 16 50](https://github.com/user-attachments/assets/b1723253-fdd8-408a-8b37-1733b426aede)

And finally all permissions were removed for `amy`

![Screenshot 2024-11-06 at 10 16 59](https://github.com/user-attachments/assets/855b1ea5-aa36-4330-94ab-553cefc408b6)

2024-11-06 09:29 UTC, iamsamgibbs approved these changes
Nice job realigning this after the rebase! I won't spam a bunch of screenshots, but everything seems to be working nicely! Good job!

2024-11-06 11:52 UTC, rdig approved these changes

2024-11-06 11:55 UTC, merged