fix: staged payment buttons alignment
JoinColony/colonyCDapp pull request #3518
Opened 2024-10-29 14:46 UTC by adam-strzelec

## Description

Align buttons to right in staged payments action

## Testing

- Download extension for Staged payment
- Create Staged payment
- Finalize payment

## Diffs

**Changes** 🏗

Before:

![image](https://github.com/user-attachments/assets/5b1f1fbc-e83b-4ca3-9ae0-566a18d9727f)

After:

<img width="673" alt="Screenshot 2024-10-29 at 15 39 52" src="https://github.com/user-attachments/assets/e414339b-70ee-46a3-bf77-6299ee34a6bb">

Resolves - https://github.com/JoinColony/colonyCDapp/issues/3342

2024-11-04 23:12 UTC, jakubcolony requested changes
The fix looks good, nice work on that @adam-strzelec. I'm requesting changes however as there are some files that I don't think should have been removed.

<img width="669" alt="image" src="https://github.com/user-attachments/assets/3aa9e46f-17e3-4c83-99d5-c61eda9ea13c">

<img width="672" alt="image" src="https://github.com/user-attachments/assets/9c429c59-3a22-4ba0-8af1-b0adca3c1791">

2024-11-05 14:05 UTC, adam-strzelec commented
@jakubcolony I already restored them. Probably I removed them by mistake.

2024-11-05 19:31 UTC, jakubcolony approved these changes
LGTM 👍

2024-11-07 18:02 UTC, arrenv requested changes
@adam-strzelec Thank you for working on the alignment, looks all good to me.

![image](https://github.com/user-attachments/assets/f051c678-d211-4910-8650-24508f72b149)

2024-11-07 18:02 UTC, arrenv approved these changes

2024-11-07 20:30 UTC, Nortsova approved these changes
Thanks @adam-strzelec for the fix ✨ 

<img width="675" alt="image" src="https://github.com/user-attachments/assets/0aee4bfd-205d-431c-b120-eed071b34e67">

2024-11-08 07:54 UTC, merged