Fix: "Upgrade" button on Calmity Banner should be enabled for all users
JoinColony/colonyCDapp pull request #3520
Opened 2024-10-29 15:15 UTC by iamsamgibbs

## Description

This PR ensures the "Upgrade" button on the Calamity Banner is always enabled for all users when a new colony version is available.

## Testing

To save you the hassle of deploying a colony on an older version, we must first update the `canColonyBeUpgraded` function in `src/utils/checks/canColonyBeUpgraded.ts` to return true.

* Step 1 - Connect to a colony as a user with root permissions. Confirm the Calamity Banner is visible and the upgrade button is enabled.

<img width="1728" alt="Screenshot 2024-10-29 at 15 13 47" src="https://github.com/user-attachments/assets/259c52f8-54de-419c-bdc5-7a9dfb17a98e">

* Step 2 - Connect to a colony as a user without root permissions. Confirm the Calamity Banner is visible and the upgrade button is enabled.

## Diffs

**Deletions** ⚰️

* Removed `canUpgradeColony` and related uses from `useCalamityBannerInfo`

Resolves #3340

2024-10-29 16:26 UTC, arrenv commented
@iamsamgibbs Thank you for picking this up, sorry for the confusion on this issue as you have done the work already. @melyndav happened to not have Reputation enabled when running into this originally.

However, hiding the banner completely for everyone but root is not the desired behavior. As it could pose a security risk, and everyone should be informed of a new version.

We already handle permissions in the Upgrade colony version action, and we also allow a colony to be upgraded using Reputation.

So, the correct behavior here should be that the upgrade button is never disabled, and should always open the "Upgrade colony version" action.

2024-10-29 16:29 UTC, arrenv requested changes
As above.

2024-10-29 18:18 UTC, iamsamgibbs commented
No problem Arren! Updated to match the new specs.

2024-10-31 10:31 UTC, rumzledz approved these changes
Smashed it Sam! 💪 

## 1. Updated the canColonyBeUpgraded function to return true

<img width="630" alt="Screenshot 2024-10-31 at 18 28 46" src="https://github.com/user-attachments/assets/7fb5d61c-dad5-4158-bcab-f54bf9c95c0a">

## 2. Connected Leela's wallet (has root perms)

<img width="906" alt="Screenshot 2024-10-31 at 18 29 24" src="https://github.com/user-attachments/assets/43ae4e36-567b-4b1b-8d61-1a85e146899a">

## 3. Connected Amy's wallet (has no root perms)

<img width="906" alt="Screenshot 2024-10-31 at 18 29 42" src="https://github.com/user-attachments/assets/e6e99781-85cf-440f-b992-5482d51f18fb">

2024-10-31 15:21 UTC, rdig approved these changes
Nicely fixed! :100: 

As `leela` (root)

![Screenshot from 2024-10-31 17-20-15](https://github.com/user-attachments/assets/e39ac7c1-5ef5-49a8-b04b-50777954d83f)

As `fry`

![Screenshot from 2024-10-31 17-20-39](https://github.com/user-attachments/assets/016120c9-75de-4e9c-bda7-82e065aaa4fb)

2024-10-31 15:44 UTC, arrenv approved these changes
@iamsamgibbs Thank you, and sorry again for the mess around. Looks good to me :)

2024-10-31 16:03 UTC, merged