Fix/3509 user account UI fixes
JoinColony/colonyCDapp pull request #3522
Opened 2024-10-29 15:22 UTC by rumzledz

## Description

- [] TODO write description

## Testing

1. The mobile version of the Email Preferences field should follow the [Figma designs](https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=6401-11782&t=QSsB9RdPVTORnWg3-4):

<img width="550" alt="image" src="https://github.com/user-attachments/assets/b6ef71dc-3a10-4294-823f-16fd815907d1">

2. These spacings should be 24px (gap-6)

<img width="1303" alt="Screenshot 2024-10-29 at 22 26 11" src="https://github.com/user-attachments/assets/3c46bc0f-2f12-4f3d-ab24-0e14f12da2c8">

3. Rename "Advanced settings" to "Advanced"

<img width="498" alt="image" src="https://github.com/user-attachments/assets/e739e89a-ebdc-4df3-b9c8-bcab01b08d6e">

4. The H4 elements for the account pages should be brought back as per these [Figma designs](https://www.figma.com/design/0Fi3AaDlr3LAXBfsOXBGyk/User-Account?node-id=7505-8667&t=vfU0W3QeCMXUzTNU-4)

Here's Crypto to fiat's H4: https://www.figma.com/design/C2grfQysdsYXz0j4rADR6K/Crypto-to-Fiat?node-id=4441-108444&t=9p1Uvq5xWxYFmdVW-4

Resolves #3509

2024-10-30 10:04 UTC, iamsamgibbs requested changes
Thanks for the changes here!

The email address is stacked on mobile now, but the button should be full width:

<img width="422" alt="Screenshot 2024-10-30 at 09 48 44" src="https://github.com/user-attachments/assets/c5df7e53-46cf-4c52-bb59-4b0965cb42b8">

Figma:

<img width="501" alt="Screenshot 2024-10-30 at 09 49 25" src="https://github.com/user-attachments/assets/42b251f1-f8a8-4046-b69f-7fd5b11587b9">

Spacing here is good:
<img width="429" alt="Screenshot 2024-10-30 at 09 50 47" src="https://github.com/user-attachments/assets/b1330937-1270-4fb1-a365-8877ca61c6a0">

All pages have titles now:

<img width="573" alt="Screenshot 2024-10-30 at 09 56 09" src="https://github.com/user-attachments/assets/7d5c59f4-0449-490b-b022-590d7a466a71">
<img width="660" alt="Screenshot 2024-10-30 at 09 56 12" src="https://github.com/user-attachments/assets/6afbbf71-5563-43a1-beb0-5ad173f913c8">

The hr is the correct colour here now, but it is missing spacing above and below:

<img width="295" alt="Screenshot 2024-10-30 at 09 58 08" src="https://github.com/user-attachments/assets/6dc275e3-7049-4512-a7e8-dca184294989">

Figma:
<img width="368" alt="Screenshot 2024-10-30 at 10 04 39" src="https://github.com/user-attachments/assets/cca8917f-e78d-4d2c-9d5a-800d41c2329a">

2024-10-30 10:54 UTC, rumzledz commented
Thanks for spotting that @iamsamgibbs ! Pushed 🚀

2024-10-30 10:58 UTC, iamsamgibbs approved these changes
Thanks for the fix. Looks good now!

<img width="449" alt="Screenshot 2024-10-30 at 10 57 40" src="https://github.com/user-attachments/assets/4b40666f-4ee5-4886-9501-3686ba09a9c2">
<img width="347" alt="Screenshot 2024-10-30 at 10 57 58" src="https://github.com/user-attachments/assets/f04b5e30-34c8-48b0-a2c7-22d641e81a17">

2024-10-31 12:37 UTC, mmioana approved these changes
Nice work for fixing all these issues @rumzledz 🎉 

1. Email Preferences on mobile
![Screenshot 2024-10-31 at 13 30 28](https://github.com/user-attachments/assets/8d029fa0-02e6-4b2a-8e6f-a224982d97b0)

2. Paddings of `24px`
![Screenshot 2024-10-31 at 13 31 13](https://github.com/user-attachments/assets/59ec8b72-a490-4597-aedc-c301989ed628)
![Screenshot 2024-10-31 at 13 31 24](https://github.com/user-attachments/assets/cb37e6f1-aa58-460a-bad3-a7c15d6d670f)

3. `Advanced` got renamed
![Screenshot 2024-10-31 at 13 31 49](https://github.com/user-attachments/assets/26cc7dbf-0449-44c6-bde7-591d8b323e57)

4. Subtitles are back to business
![Screenshot 2024-10-31 at 13 31 49](https://github.com/user-attachments/assets/878642ab-64b5-4917-88ea-d741d4f0cdc6)
![Screenshot 2024-10-31 at 13 32 23](https://github.com/user-attachments/assets/698bc7b7-14f1-493e-8c8c-156d59b3ca18)
![Screenshot 2024-10-31 at 13 32 26](https://github.com/user-attachments/assets/e1d306a8-aa18-4ee0-9afe-35155ddfce27)
![Screenshot 2024-10-31 at 13 32 31](https://github.com/user-attachments/assets/c4102632-dd02-4e37-a6fb-278e9370a4ac)

5. The divider in the account area is the same as the one used for a colony sidebar
![Screenshot 2024-10-31 at 13 34 24](https://github.com/user-attachments/assets/7a556b6b-f08c-482a-8345-4bbb7179ac43)
![Screenshot 2024-10-31 at 13 34 29](https://github.com/user-attachments/assets/3d6b6a1d-d312-4030-84e5-e87f1941bccc)

2024-10-31 16:25 UTC, Nortsova approved these changes
Great work on this 👍  Thank you @rumzledz ✨ 

1. Preferences:
<img width="346" alt="image" src="https://github.com/user-attachments/assets/400460e6-eda5-4d56-a8cc-5d1d22fba491">

2. Gap-6 is correct
<img width="1972" alt="image" src="https://github.com/user-attachments/assets/a8e1e700-8212-4b3d-b27a-46728439a6b8">

3. Successfully renamed Advanced settings:
<img width="261" alt="image" src="https://github.com/user-attachments/assets/50d8932c-011a-48bf-897a-3562cb773b62">

4. All pages have title now:
![settings-title](https://github.com/user-attachments/assets/016a2302-b775-4902-b23c-5074def79ed5)

5. HR looks as expected:
<img width="251" alt="image" src="https://github.com/user-attachments/assets/bf05083e-9b19-4c09-b4c6-4351d9352c13">

2024-10-31 17:05 UTC, rumzledz commented
Yet another merge conflict victim @iamsamgibbs @Nortsova @mmioana 🥲 Can you please have a look again when you get the chance tomorrow? Thank you 🙏

2024-11-01 07:24 UTC, mmioana approved these changes
It still looks good after rebasing @rumzledz 🥇 👏 

![Screenshot 2024-11-01 at 08 19 34](https://github.com/user-attachments/assets/d21f2888-3db4-433c-ba32-afe2752e09c9)
![Screenshot 2024-11-01 at 08 20 33](https://github.com/user-attachments/assets/2a0398d1-d6c4-49a5-aca5-35b02326deef)
![Screenshot 2024-11-01 at 08 21 25](https://github.com/user-attachments/assets/67a98d6e-a739-4bba-af84-52be15a556fe)
![Screenshot 2024-11-01 at 08 21 28](https://github.com/user-attachments/assets/360293ae-4a86-4f34-880f-5f0e4efe366b)
![Screenshot 2024-11-01 at 08 21 30](https://github.com/user-attachments/assets/9a10fef6-f987-418b-9160-1f8d57b7bb15)
![Screenshot 2024-11-01 at 08 21 33](https://github.com/user-attachments/assets/0d02c8b7-3729-4215-b598-892feb613f2c)
![Screenshot 2024-11-01 at 08 21 52](https://github.com/user-attachments/assets/12aa1255-8e75-44f0-998d-42cf26df09fe)

2024-11-01 07:24 UTC, mmioana commented on src/components/v5/shared/Navigation/Sidebar/partials/SidebarContentDivider.tsx
Nice nice 🥇

2024-11-01 10:03 UTC, iamsamgibbs requested changes
Not sure if this is unrelated, but the Crypto to Fiat menu item has disappeared after the rebase:

<img width="391" alt="Screenshot 2024-11-01 at 09 37 31" src="https://github.com/user-attachments/assets/d668d02c-3de7-449d-b34e-e3f94ca2c6a5">

It's still here on the mobile view though:

<img width="478" alt="Screenshot 2024-11-01 at 09 37 23" src="https://github.com/user-attachments/assets/e49f22db-7bcb-4404-bdb3-555957da142e">

2024-11-01 10:37 UTC, Nortsova commented
@iamsamgibbs I still have C2F in the sidebar 😄 

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/7d1d8287-ed6e-42f6-94a3-6ffd9a8e2552">

2024-11-01 10:39 UTC, Nortsova approved these changes
It seems that it still works as expected 👍

2024-11-01 10:57 UTC, iamsamgibbs approved these changes
Hmm yeah I must not have the feature flag setup correctly locally or something, if I just manually set it to show then everything looks good:

<img width="581" alt="Screenshot 2024-11-01 at 10 56 33" src="https://github.com/user-attachments/assets/80a3f841-7275-48b8-9a70-b9b791ad4212">

All the other styling changes are still here so approving!

2024-11-01 11:10 UTC, merged