fix: set description for selected items in milestone modal
JoinColony/colonyCDapp pull request #3546
Opened 2024-10-30 10:45 UTC by adam-strzelec

## Description

set description for selected items in milestone modal

## Testing

- Create staged payments
- Go thru staged payments flow
- Open milestone modal and select one of decision method

## Diffs

**New stuff** ✨

![Screenshot 2024-10-30 at 11 39 01](https://github.com/user-attachments/assets/d761f38b-ca4d-4608-9b84-1136bbb12ec1)

![Screenshot 2024-10-30 at 11 39 14](https://github.com/user-attachments/assets/db651910-9e06-4c86-b27c-afe6beb034a0)

**Changes** 🏗

Change translations for milestone modal

## TODO

Add translations for `Multi-sig` once they will be available

Resolves https://github.com/JoinColony/colonyCDapp/issues/3341

2024-10-30 10:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3546) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3546) before we can accept your contribution.<br/><hr/>**strzelec** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=3546) it.</sub>

2024-10-31 10:27 UTC, mmioana requested changes
All good here @adam-strzelec 💯 

The correct copy text is shown in the `Payment` modal for the selected decision method

`Permissions`
![Screenshot 2024-10-31 at 11 23 51](https://github.com/user-attachments/assets/11615460-f3cd-48aa-ace9-cdc3e99648f7)
`Payment creator`
![Screenshot 2024-10-31 at 11 23 57](https://github.com/user-attachments/assets/de5f6b4a-64f2-45fb-be4a-0c5b093022d9)
`Reputation`
![Screenshot 2024-10-31 at 11 24 27](https://github.com/user-attachments/assets/1726b60b-74d5-4521-9b11-ddc3cf60398b)

I'm requesting changes only because it would be nice to add already the needed copy and code for `Multi-Sig`, even if we comment it out for the moment

Also a side-note, it would be good to add in the testing steps that the `Staged payment` extension needs to be installed 💯

2024-10-31 10:27 UTC, mmioana commented on src/i18n/en.json
> +    "milestoneModal.paymentCreatorDescription": "This will use your temporary permissions as the payment creator to immediately make the selected milestone payments.",
Can we also add the copy needed for `Multi-sig`?

2024-10-31 10:27 UTC, mmioana commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentStep/partials/MilestoneReleaseModal/consts.ts
Can we please add also the `DecisionMethod.MultiSig` and comment it our for the moment?

2024-11-06 10:09 UTC, mmioana approved these changes
Thank you for adding these changes @adam-strzelec 💯 

The copy is showing up correctly for all decision methods
![Screenshot 2024-11-06 at 11 07 33](https://github.com/user-attachments/assets/953ede13-8a98-40da-a6af-62833c72fca4)
![Screenshot 2024-11-06 at 11 07 38](https://github.com/user-attachments/assets/43df35c8-6847-4b0a-bbba-56ad08fe6466)
![Screenshot 2024-11-06 at 11 07 42](https://github.com/user-attachments/assets/83db176b-8806-49bb-8a46-2ae8113aade1)
![Screenshot 2024-11-06 at 11 07 46](https://github.com/user-attachments/assets/5acb15a8-f7d9-482b-9453-6bef459981c0)

2024-11-06 10:09 UTC, mmioana commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/StagedPaymentStep/partials/MilestoneReleaseModal/consts.ts
> +  // [DecisionMethod.PaymentCreator]: formatText({
Here we should use `DecisionMethod.MultiSig` - but either way as it's disabled for the moment you can leave it as it is

2024-11-06 10:31 UTC, bassgeta approved these changes
Nice and simple :ok_hand: 
![image](https://github.com/user-attachments/assets/cb1b1c31-a865-404a-9aaf-22287c4e5d3a)
![image](https://github.com/user-attachments/assets/4eb5ba39-88a6-4f65-8d9b-25d6d7270e28)

2024-11-07 20:40 UTC, Nortsova approved these changes
Great work on this 👏 Thank you 

<img width="719" alt="image" src="https://github.com/user-attachments/assets/8dc82b5b-f1da-4b5f-9e3d-c5b6aa762040">
<img width="549" alt="image" src="https://github.com/user-attachments/assets/264e7df0-3b06-4a30-bc5b-029b03a555d0">
<img width="557" alt="image" src="https://github.com/user-attachments/assets/4d2226f1-9511-493a-9707-76b4b3f7b7ab">
<img width="559" alt="image" src="https://github.com/user-attachments/assets/fd097683-5fd5-4c04-81cc-671eb82fd7f6">

2024-11-08 07:55 UTC, merged