wip: funding step multisig
JoinColony/colonyCDapp pull request #3553
Opened 2024-10-30 11:46 UTC by bassgeta

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-11-07 15:40 UTC, iamsamgibbs requested changes
Great work on this so far! These components seem like a real pain to deal with, so nice work getting this implemented so well!

I've found a few issues which I'll detail as best I can. My dev environment seemed to get more and more unstable the more testing I did (I think mostly related to this issue I just opened: #3673)

Multi-Sig option appears as expected:

<img width="518" alt="Screenshot 2024-11-07 at 14 20 50" src="https://github.com/user-attachments/assets/b28b8880-7cb8-44ab-a12a-deb08097a1c5">

And does not appear when extension is not installed:

<img width="591" alt="Screenshot 2024-11-07 at 15 06 51" src="https://github.com/user-attachments/assets/2e713124-74d4-41d5-b9a7-e1ffc1b52460">

Signatures component shows as expected:

<img width="1066" alt="Screenshot 2024-11-07 at 14 21 19" src="https://github.com/user-attachments/assets/c87c3e5f-6b73-49bd-bc26-adbf8f7ee305">

<img width="353" alt="Screenshot 2024-11-07 at 14 22 29" src="https://github.com/user-attachments/assets/522df63f-f48c-4c76-873a-c96b101095c8">

I can approve, reject as either user without issue.

I did get stuck with this "Pending" button on multiple occasions though when confirming a rejection:
 
<img width="567" alt="Screenshot 2024-11-07 at 14 22 49" src="https://github.com/user-attachments/assets/3f2d16d3-298d-4f24-89b2-3bfbdb9d01d0">

https://github.com/user-attachments/assets/e54b5a3b-8a1a-4dcf-964e-967ad853cdea

I was unable to get a funding in a sub-domain to work though as either user:

As Fry:
<img width="1728" alt="Screenshot 2024-11-07 at 14 27 29" src="https://github.com/user-attachments/assets/965a8029-9b42-4c82-af2e-3f0f4f683615">

<img width="471" alt="Screenshot 2024-11-07 at 14 29 11" src="https://github.com/user-attachments/assets/eda04bea-e79d-4db7-b61c-c6e58d2bb09a">

As Leela:
<img width="1728" alt="Screenshot 2024-11-07 at 14 30 16" src="https://github.com/user-attachments/assets/c3d6338b-64eb-4659-a59e-52ab7006d407">

Notifications also aren't showing the correct information:
 
<img width="770" alt="Screenshot 2024-11-07 at 14 31 00" src="https://github.com/user-attachments/assets/146e21c8-cd58-4588-bad9-10b694f40a42">

I tested that your MoveFunds change on block-ingestor didn't break the notification there which still seems okay!

<img width="749" alt="Screenshot 2024-11-07 at 14 31 53" src="https://github.com/user-attachments/assets/46c69892-1a0e-4c3b-97a9-2091c090d64d">

Tested looking at failed motions / multi-sigs which works great:
https://github.com/user-attachments/assets/029970a7-e7ad-4e02-9b20-a8ed7b1ab294

There is an `Invalid threshold` message that is shown when the extension is uninstalled though. I didn't test this, but I suspect if the extension was re-installed, it would try and update based on the new extension settings. So this should be hidden if multi-sig being loaded has been uninstalled.
 
<img width="1056" alt="Screenshot 2024-11-07 at 15 28 07" src="https://github.com/user-attachments/assets/6c74f733-d383-46b6-aa82-e36e325c3ff3">

There is no check on the modal that you actually have permissions to create the multi-sig (this is in Wayne where no user has multi-sig permissions at all)

<img width="1728" alt="Screenshot 2024-11-07 at 15 28 36" src="https://github.com/user-attachments/assets/a651e2a2-2b32-4ed7-8df2-37d709e42ea1">

Also doesn't check if there are enough eligible signees:

<img width="1348" alt="Screenshot 2024-11-07 at 15 30 18" src="https://github.com/user-attachments/assets/d3ed53ea-3d9a-4bea-a2e1-6c9730ef819e">

Appreciate there is a lot there! I'm not sure how much of this would make sense to handle in this issue or as separate issues. Nice job on getting it hooked up so well this far though. The actual core multi-sig aspect of it is all working nicely.

2024-11-15 11:53 UTC, iamsamgibbs reviewed
Nice job getting the multi-sig working in a sub-domain!

I'm now able to fund an expenditure in Andromeda as Fry with payer permissions only in Andromeda:

https://github.com/user-attachments/assets/b7bcf248-602b-4a71-a435-6dde128d3465

I had quite a few issues with the stepper not progressing to the next step. In the above video you can see it doesn't progress to review and seems like it would let me start another funding multi-sig / permissions action if I wanted.

Also found similar issue here where the multi-sig widget didn't load after starting funding:

https://github.com/user-attachments/assets/467c3ee3-e518-4120-9e52-6e882f3beb00

Also got stuck removing here:

<img width="1085" alt="Screenshot 2024-11-15 at 11 42 59" src="https://github.com/user-attachments/assets/b01ad88d-8d3e-4929-99cd-1062e9d195c0">

Also found that the multi-sig widget wasn't updating for Leela when Amy / Fry would approval and finalise.

I'll let someone else give it a review and see if it's just issues with my environment.

2024-11-25 09:54 UTC, mmioana requested changes
Lots of sweat and tears must have been shed for this issue, but really awesome work @bassgeta 👏 

I'll start with the things that have been working when reviewing this PR and then will leave the points that still need work on 

`Installed the multi-sig extension`
![Screenshot 2024-11-25 at 09 48 00](https://github.com/user-attachments/assets/5626a020-0eac-4702-aa4d-867f25ef1a92)

And gave `leela`, `amy` and `fry` the suggested permissions
![Screenshot 2024-11-25 at 09 48 49](https://github.com/user-attachments/assets/9640a233-9abc-4e6b-bb10-a136b2b1ad25)
![Screenshot 2024-11-25 at 09 49 16](https://github.com/user-attachments/assets/5326b0d3-dcea-4f35-a421-540835663f9d)
![Screenshot 2024-11-25 at 09 49 42](https://github.com/user-attachments/assets/6dd98f59-c985-4479-bba9-9d43270a8e2e)

Created an advanced payment as `leela` and used `Multi-sig` for funding 
![Screenshot 2024-11-25 at 09 51 02](https://github.com/user-attachments/assets/7acfff55-f227-4f45-86f4-222f762af810)
![Screenshot 2024-11-25 at 09 51 21](https://github.com/user-attachments/assets/73d77a68-25c6-4363-af6b-b7ce8754620e)

The `Multi-sig` funding notification is shown
![Screenshot 2024-11-25 at 09 51 48](https://github.com/user-attachments/assets/2ff2ef24-f173-401f-85f2-18d0d91d4f42)

The proper skeleton is shown upon refresh
![Screenshot 2024-11-25 at 09 52 17](https://github.com/user-attachments/assets/41dbce63-5c79-4040-bedc-a64f09fb9575)

Removed `leela`s approval
![Screenshot 2024-11-25 at 09 52 37](https://github.com/user-attachments/assets/b47df72e-681c-4fae-90c0-4fe441c99774)

Rejected as `leela`
![Screenshot 2024-11-25 at 09 53 05](https://github.com/user-attachments/assets/78b508f1-8bc1-43dd-9860-925064650449)
![Screenshot 2024-11-25 at 09 53 10](https://github.com/user-attachments/assets/3e7c6d24-b1d8-4cbd-bafc-c529a38d2ba3)
![Screenshot 2024-11-25 at 09 53 30](https://github.com/user-attachments/assets/1da91ff6-dd8e-4c24-acec-d737573231be)
Then funded again the payment using `Multi-sig`
![Screenshot 2024-11-25 at 09 54 00](https://github.com/user-attachments/assets/98411c03-f52d-4494-b03f-70ba15cad1b2)

Can switch between the current and previous funding actions

https://github.com/user-attachments/assets/639ca2ed-c812-4cfa-85df-a29b3f11fae6

`amy` can interact with the `Multi-sig` widget
![Screenshot 2024-11-25 at 09 55 10](https://github.com/user-attachments/assets/6c77e314-96d0-4ff7-b461-c4ecc21fbffe)

While `fry` is only in viewer-mode 👓 
![Screenshot 2024-11-25 at 09 55 58](https://github.com/user-attachments/assets/67d02deb-84ed-439e-aec0-2309550c9a5a)

Approved as `amy`
![Screenshot 2024-11-25 at 09 56 17](https://github.com/user-attachments/assets/0bc0f2bb-66aa-47eb-a93e-abad71d3fec8)
![Screenshot 2024-11-25 at 09 56 33](https://github.com/user-attachments/assets/1f239fac-3fa8-4d22-8c7c-4c89f81874fb)
![Screenshot 2024-11-25 at 09 56 40](https://github.com/user-attachments/assets/7b7913da-b506-4b49-bf87-7aab9fd95e59)

Payment has been released
![Screenshot 2024-11-25 at 09 57 17](https://github.com/user-attachments/assets/99a9a660-b1ef-4a1b-96cb-addc73eef45f)
![Screenshot 2024-11-25 at 09 57 34](https://github.com/user-attachments/assets/780db6eb-0e22-427a-b763-9a18c5dbd4ee)

Now creating and advanced payment in `Andromeda`
![Screenshot 2024-11-25 at 09 59 05](https://github.com/user-attachments/assets/be788e60-0c0e-4aea-b3e1-efd95860a515)

`fry` can fund using `Multi-sig`
![Screenshot 2024-11-25 at 10 00 17](https://github.com/user-attachments/assets/0fd28fde-9209-4a79-afb8-39712a8565d1)
`Approved` by default
![Screenshot 2024-11-25 at 10 00 36](https://github.com/user-attachments/assets/53474818-017c-4a84-8f6b-debc67b3ef1b)

Remove `fry`'s approval
![Screenshot 2024-11-25 at 10 00 46](https://github.com/user-attachments/assets/59e6bf7f-dab5-4740-8638-49e05540c6ba)

And approve again
![Screenshot 2024-11-25 at 10 01 03](https://github.com/user-attachments/assets/a8ea9945-bc46-488f-aa1d-f73372c5c426)

Remove approval again and then reject 
![Screenshot 2024-11-25 at 10 01 18](https://github.com/user-attachments/assets/44b114e6-f677-4f69-9e3a-e27a1ba2382f)
![Screenshot 2024-11-25 at 10 01 38](https://github.com/user-attachments/assets/eee4a094-370a-483f-ae1b-bb2a0ceca9bb)

Now moving some funds using `Permissions`
![Screenshot 2024-11-25 at 10 04 21](https://github.com/user-attachments/assets/98d02f93-780f-49a4-a0d7-04b86bb16bb3)

Advanced payment using `Permissions` as funding
![Screenshot 2024-11-25 at 10 05 14](https://github.com/user-attachments/assets/c9aae044-551b-4961-acb9-0a4930d82547)


Updating the `Multi-sig` threshold to a higher value than existing permission holders
![Screenshot 2024-11-25 at 10 05 28](https://github.com/user-attachments/assets/b746ffb0-f867-4294-9368-0208136b6ac3)
The error message is shown
![Screenshot 2024-11-25 at 10 07 36](https://github.com/user-attachments/assets/b6132205-4025-4280-a9a3-7b7c3dcff17c)

Trying to fund a payment in `Rocinate` as `fry`, the `Multi-sig` option is not displayed 💯 
![Screenshot 2024-11-25 at 10 09 39](https://github.com/user-attachments/assets/8b6b206b-eb4f-4ed9-af4e-a42d962b208f)

Now the issues part 😢 

## Issues

1. The `Manage permissions` completed action screen
It seems the wrong `Owner` permissions table is shown after assigning permissions to `amy` and `fry` - **however this should be treated in a separate issue**
![Screenshot 2024-11-25 at 09 49 16](https://github.com/user-attachments/assets/5326b0d3-dcea-4f35-a421-540835663f9d)
![Screenshot 2024-11-25 at 09 49 23](https://github.com/user-attachments/assets/1e2c24da-c7d1-4cfa-9f94-cdcf547ade5f)
![Screenshot 2024-11-25 at 09 49 42](https://github.com/user-attachments/assets/6dd98f59-c985-4479-bba9-9d43270a8e2e)
![Screenshot 2024-11-25 at 09 49 47](https://github.com/user-attachments/assets/0bb60d66-a66b-46a7-8d2c-bc5fd68da138)
2. Remove `fry` approval and then reject gets into an always pending state before page refresh, while `leela` can already see the `Fund` button
![Screenshot 2024-11-25 at 10 01 18](https://github.com/user-attachments/assets/44b114e6-f677-4f69-9e3a-e27a1ba2382f)
![Screenshot 2024-11-25 at 10 01 38](https://github.com/user-attachments/assets/eee4a094-370a-483f-ae1b-bb2a0ceca9bb)
![Screenshot 2024-11-25 at 10 03 50](https://github.com/user-attachments/assets/d295f489-ebf3-403d-b9d4-aebe413a8e21)

3. While updating the `Multi-sig` threshold to a higher value than existing permission holders, the error box for the funding step is shown only after page refresh
![Screenshot 2024-11-25 at 10 05 28](https://github.com/user-attachments/assets/b746ffb0-f867-4294-9368-0208136b6ac3)
![Screenshot 2024-11-25 at 10 06 53](https://github.com/user-attachments/assets/6b2c4014-1950-43b9-8cd9-e80189a08b9b)
![Screenshot 2024-11-25 at 10 07 36](https://github.com/user-attachments/assets/b6132205-4025-4280-a9a3-7b7c3dcff17c)

Nonetheless, amazing effort @bassgeta 🥇

2024-11-25 09:54 UTC, mmioana commented on src/components/v5/common/ActionSidebar/partials/forms/PaymentBuilderForm/utils.ts
> +    values.decisionMethod === 'Permissions'
Can we use here the following check?
```suggestion
    values.decisionMethod === DecisionMethod.Permissions
```

2024-11-25 09:54 UTC, mmioana commented on src/components/v5/common/ActionSidebar/partials/forms/SplitPaymentForm/utils.ts
> +    decisionMethod === 'Permissions'
Also here
```suggestion
    decisionMethod === DecisionMethod.Permissions
```

2024-11-25 10:24 UTC, mmioana approved these changes
Awesome, 2nd point has been resolved with light-speed 💪 

Thanks for the fast change @bassgeta 
<img width="1165" alt="Screenshot 2024-11-25 at 11 21 03" src="https://github.com/user-attachments/assets/1e0f0f6d-a4e4-4b78-a086-841ad069c767">
<img width="1165" alt="Screenshot 2024-11-25 at 11 21 57" src="https://github.com/user-attachments/assets/70fc32ef-8ece-42fe-81b9-bd7a7c15b81b">
<img width="1165" alt="Screenshot 2024-11-25 at 11 22 06" src="https://github.com/user-attachments/assets/0e0e2ce6-5099-4163-ad5a-abd837949765">
<img width="1165" alt="Screenshot 2024-11-25 at 11 22 12" src="https://github.com/user-attachments/assets/2a37de71-ade2-4bfe-afb6-f2717af7230f">
<img width="1165" alt="Screenshot 2024-11-25 at 11 22 20" src="https://github.com/user-attachments/assets/d7830c9c-2083-449a-9891-610ab629b1a7">
<img width="1165" alt="Screenshot 2024-11-25 at 11 22 29" src="https://github.com/user-attachments/assets/fac976c8-ad5d-4a83-9673-ddf151075d3a">

I will approve this PR and create a new issue for the 1st point 💯

2024-11-26 17:25 UTC, mmioana approved these changes
Stellar work @bassgeta 🥇 

Re-tested the main testing flow and it all worked as expected
![Screenshot 2024-11-26 at 18 06 47](https://github.com/user-attachments/assets/f9bc167e-abdb-47bc-b9a7-b041eb528109)
![Screenshot 2024-11-26 at 18 07 16](https://github.com/user-attachments/assets/46be142b-2d5f-48ba-9704-55c021189398)
![Screenshot 2024-11-26 at 18 07 37](https://github.com/user-attachments/assets/3c9e3f8b-3aca-453f-962e-c953d700336a)
![Screenshot 2024-11-26 at 18 08 04](https://github.com/user-attachments/assets/bc76f5f0-406c-48be-82be-a2f339b7e60a)
![Screenshot 2024-11-26 at 18 08 46](https://github.com/user-attachments/assets/df617f90-5e75-4fe0-8075-1ee031077f0c)
![Screenshot 2024-11-26 at 18 09 03](https://github.com/user-attachments/assets/ca265d6e-fb60-4a4c-b878-e54ab92f7b01)
![Screenshot 2024-11-26 at 18 09 17](https://github.com/user-attachments/assets/0288d459-a2cb-42ca-9017-aec3746571ef)
![Screenshot 2024-11-26 at 18 09 36](https://github.com/user-attachments/assets/4c1292d8-c70b-4611-bf13-2594d5a141d5)
![Screenshot 2024-11-26 at 18 09 54](https://github.com/user-attachments/assets/b62ec267-f39e-4579-a2a6-75cba5fd184d)
<img width="1075" alt="Screenshot 2024-11-26 at 18 11 11" src="https://github.com/user-attachments/assets/e045e3c0-9c0c-4d65-b0b1-2838014cf9f6">
![Screenshot 2024-11-26 at 18 11 53](https://github.com/user-attachments/assets/6f2ab0a2-593f-4c7d-a40b-dc89c7928236)
![Screenshot 2024-11-26 at 18 12 08](https://github.com/user-attachments/assets/57adb837-782f-404f-b731-f7a054d902a7)
![Screenshot 2024-11-26 at 18 12 26](https://github.com/user-attachments/assets/72f93445-047d-446e-ba07-21abaa120709)
<img width="1227" alt="Screenshot 2024-11-26 at 18 13 31" src="https://github.com/user-attachments/assets/3676bfce-d097-4244-8618-f4f2ad2b26d4">
<img width="1085" alt="Screenshot 2024-11-26 at 18 14 06" src="https://github.com/user-attachments/assets/8a9970c1-9734-4967-9ba8-12b012356d0b">
![Screenshot 2024-11-26 at 18 15 21](https://github.com/user-attachments/assets/4b9b0437-8a10-458b-81b5-170daea33588)


Tested the `Advanced payment` funding for multiple tokens and it all looks good from my side 🥇 
![Screenshot 2024-11-26 at 18 18 00](https://github.com/user-attachments/assets/66ea9a6a-7c4f-4509-8b62-3440ee0bdb37)
![Screenshot 2024-11-26 at 18 18 18](https://github.com/user-attachments/assets/d2664e95-7235-405c-8d41-abacef29176b)
![Screenshot 2024-11-26 at 18 19 04](https://github.com/user-attachments/assets/4918892b-c144-4693-832e-4f48ba768cf5)
![Screenshot 2024-11-26 at 18 19 44](https://github.com/user-attachments/assets/4512dc21-9d09-4350-ab88-4eb07e5c65d4)
![Screenshot 2024-11-26 at 18 20 41](https://github.com/user-attachments/assets/6adf9fac-0213-4b86-8fe1-d93cf9ca997d)

Thank you for the huge effort on this issue 💯 let's get it merged!

2024-11-26 21:52 UTC, jakubcolony approved these changes
Can confirm `expenditureFunding` is now showing all the tokens being funded 👍 

<img width="564" alt="image" src="https://github.com/user-attachments/assets/7155e145-4848-4bf3-ab18-0503f5353afe">

Nice one, let's get this merged! 💯

2024-11-27 11:35 UTC, iamsamgibbs approved these changes
Nice job handling the case with multiple tokens. Tested and all working as expected!

<img width="477" alt="Screenshot 2024-11-27 at 11 33 41" src="https://github.com/user-attachments/assets/4af7405c-9c49-44d5-8b96-8c770ac50dc1">

<img width="1027" alt="Screenshot 2024-11-27 at 11 34 56" src="https://github.com/user-attachments/assets/2e5a71b2-8f30-420d-bcd9-4a772358de80">

2024-11-27 12:40 UTC, merged