Fix: Remove Pie Chart's black box background
JoinColony/colonyCDapp pull request #3575
Opened 2024-10-31 11:46 UTC by rumzledz

## Description

It simply removes Pie Chart's boxy black background:

![loader bg fix](https://github.com/user-attachments/assets/8f3067af-d416-452c-9686-ff75987f9cfd)

## Testing

1. Go to a Colony Dashboard
2. Reload the page and just observe the Pie Chart as it loads
3. Verify that it doesn't have a black box background for both light and dark themes:

![image](https://github.com/user-attachments/assets/9db49aef-a1c3-44ea-a0db-1a954f9e916d)
![image](https://github.com/user-attachments/assets/21b8cf97-e309-47d9-ae8c-51073c803353)

Resolves #3570

2024-10-31 14:20 UTC, iamsamgibbs requested changes
Still showing on mobile I'm afraid!

<img width="610" alt="Screenshot 2024-10-31 at 14 19 17" src="https://github.com/user-attachments/assets/54481303-f3d0-4e16-9dce-023bc056e882">

Also this fun thing:

https://github.com/user-attachments/assets/6bb3a4db-1817-46bb-bea7-1954d245f235

2024-10-31 15:55 UTC, rumzledz commented
@iamsamgibbs oh wow, all right I'll try a different approach 🤔

2024-10-31 15:57 UTC, rumzledz commented
Can you try this one please @iamsamgibbs ? I swear on my local, with the previous fix by just setting the bg colour to transparent, it "works" 🤔

2024-10-31 16:09 UTC, iamsamgibbs requested changes
Still seeing it on mobile screen width in Safari, lets see if it is an issue for anyone else

<img width="555" alt="Screenshot 2024-10-31 at 16 07 29" src="https://github.com/user-attachments/assets/0b51ec0d-8b52-4747-97f9-95e82b3301f7">

2024-10-31 16:27 UTC, rumzledz commented
@iamsamgibbs all right if that latest push doesn't fix it, I don't know what will!

2024-11-01 07:31 UTC, mmioana approved these changes
Lovely, the pie chart no longer has a black box background. Thanks for fixing this issue @rumzledz 🎉 


https://github.com/user-attachments/assets/03e190b8-708d-486f-aec4-9dfeb9659255

2024-11-01 09:36 UTC, iamsamgibbs approved these changes
All looking good now!

<img width="563" alt="Screenshot 2024-11-01 at 09 35 29" src="https://github.com/user-attachments/assets/9ea6bfe6-5eb0-4db5-8fc2-54abfe0d29ef">

2024-11-04 09:56 UTC, bassgeta approved these changes
Nice stuff, tested it out on a linux webkit browser and the bg is now indeed transparent!
![image](https://github.com/user-attachments/assets/3494fc5b-3c37-4a31-99e0-7b6355175b76)

2024-11-04 15:08 UTC, merged