Fix: Enable Dashboard Activity Table Item Redo Functionality
JoinColony/colonyCDapp pull request #3587
Opened 2024-10-31 15:45 UTC by rumzledz

## Description

This PR aligns the action redo logic of the Dashboard Activity Table with the Activity page's Activity Table.

![Redo action](https://github.com/user-attachments/assets/77ca196b-b556-4ecf-923b-75f8235093f1)

## Testing

1. Make a simple payment
2. Once it shows up on the Recent Activity table, click its kebab button
3. Click Redo action
4. Verify that the Action Form comes up and the details are filled in
5. Visit the Activity page http://localhost:9091/planex/activity
6. Look for the same action on the table and redo it
7. Verify that the result is consistent as step 4
 
## Diffs

**New stuff** ✨

* I centralised this "Redo action" behaviour for the Actions Table items in a new hook called `useRedoAction` so it's shared consistently between the Action Tables found with the Dashboard & Activity pages.

Resolves #3551

2024-11-01 08:17 UTC, mmioana submitted a review, later dismissed
Nice, now we're able to redo an action from both the `Recent activity` table on `Dashboard` and from the table on the `Activity` page @rumzledz 🎉 

https://github.com/user-attachments/assets/211d2639-0899-4267-81d9-8a0e39a93650


https://github.com/user-attachments/assets/d0011bfd-1637-4eac-86b8-c432c3c34101

2024-11-01 08:17 UTC, mmioana commented on src/components/common/ColonyActionsTable/hooks/useRedoAction.ts
Really nice 🙌

2024-11-01 17:21 UTC, rumzledz commented
Hey @rdig @iamsamgibbs all right noted. This seems to be a wider bug since the Colony Actions have had this Redo Action for all actions for the past 2 months and no one noticed. I'll see what actions are allowed to have this Redo button, will amend the logic for both the Dashboard and Activity page's actions table and will update the issue's dev hours field 👌

2024-11-02 19:52 UTC, rumzledz commented
Hey @iamsamgibbs @rdig I've pushed the required changes. Catch you both on Monday! 👋

2024-11-04 10:40 UTC, iamsamgibbs submitted a review, later dismissed
Great job with this!

<img width="1405" alt="Screenshot 2024-11-04 at 10 31 17" src="https://github.com/user-attachments/assets/b24c7f99-8b19-4a0c-af98-0f0913d272f0">

<img width="1407" alt="Screenshot 2024-11-04 at 10 31 24" src="https://github.com/user-attachments/assets/ee6a37c4-6487-435d-be97-43cc0f0cbbb1">

Nice implementation. I agree with your comments that it would be nice to rework the completed action component so that there is a single source of truth for this. I was actually thinking earlier about how spread out everything to do with actions is, and that we could either benefit with unifying aspects of it (I believe the work Chris is doing will help with this), or at the very least, the next time we add a new action we could document everywhere new code is needed as it is so spread out.

Thanks for adding the new functionality around when to show / not show the redo action, appreciate it was outside of the original scope, but you've got it working very nicely.

2024-11-05 10:13 UTC, bassgeta submitted a review, later dismissed
Really nice solution with the map, it's much nicer and much more unified this way
Create a new team doesn't have Redo :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/93e30917-6e8f-449f-b0e8-6e221cb31a8b)
Transfer funds works :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/4b373540-58b7-4793-a84e-80f1e726ed11)
Simple payment :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/1582ab98-29df-405c-9ae9-c23b85ca7dca)
![image](https://github.com/user-attachments/assets/6c3cc355-0858-4e36-8ea3-d4c5444bf7fa)
Permissions also work :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/17512511-c9a4-4323-a59e-9b9a582c3ade)
![image](https://github.com/user-attachments/assets/83464301-1a70-4765-b10c-57f005bdbf04)
Activity feed also works :100: 
Nice work with solving this, it's quite a simple hook which does one thing only, super legit :muscle:

2024-11-05 17:42 UTC, rumzledz commented
Hey @bassgeta @iamsamgibbs! @rdig has just helped me uncover that the Activity table cannot currently redo Reputation-related actions. So I had to push that which got rid of your reviews 😅 

The latest commit also includes a fix for preventing the app to crash when redoing Reputation-related actions, which is an issue raised in #3593 

I thought it made sense to combine these fixes because they intertwine.

I will be updating the test steps shortly so you can verify that the app doesn't crash when redoing a Reputation action 👌

2024-11-05 17:45 UTC, rdig submitted a review, later dismissed

2024-11-06 09:54 UTC, iamsamgibbs submitted a review, later dismissed
Nice job! Awarding reputation can be redone:

https://github.com/user-attachments/assets/cf402d90-376f-4711-bbcb-75e307e26215

Redo option is being conditionally rendered as expected:

<img width="1416" alt="Screenshot 2024-11-06 at 09 52 21" src="https://github.com/user-attachments/assets/3f3c81ab-a7fb-4fbe-9f49-a2a73d5cf909">

2024-11-06 15:36 UTC, rdig approved these changes
Nice turnaround of this. Tested and everything works as expected.

Also, nice job in centralizing the redo actions.

Redo simple payment

https://github.com/user-attachments/assets/b68f7726-b50c-4a48-b277-c3c8f6865397

No redo on a "Create Team" action

https://github.com/user-attachments/assets/3993ab80-655c-4802-b188-2c86e17e660f

Award reputation redo does not crash the app

https://github.com/user-attachments/assets/9f6558d5-4520-4b7a-ab04-4009e7152c54

2024-11-06 20:42 UTC, rumzledz commented
@iamsamgibbs @rdig @iamsamgibbs apologies guys, I had to resolve some merge conflicts in `SetUserRoles.tsx`, the reviews got wiped 😅

2024-11-07 08:35 UTC, rdig approved these changes
Reapproved

2024-11-07 09:29 UTC, bassgeta approved these changes
Reapproving :+1:

2024-11-07 13:58 UTC, iamsamgibbs reviewed
I just went to test this and make sure redoing Manage Permissions was still working, but it's suffering from the action form not working issue. Can you rebase it @rumzledz ?

2024-11-07 16:38 UTC, rumzledz commented
> I just went to test this and make sure redoing Manage Permissions was still working, but it's suffering from the action form not working issue. Can you rebase it @rumzledz ?

Ah right of course, new fixes were added to `master` this morning 🥲 Will rebase!

2024-11-07 16:39 UTC, rumzledz commented
@iamsamgibbs rebased! 🚀

2024-11-08 16:41 UTC, iamsamgibbs requested changes
Really minor issue, but when redoing a manage permissions action, the authority type is not properly set. Here is an example where it should be multi-sig:

https://github.com/user-attachments/assets/363fac58-e52a-4e87-ba7d-a767d7c3c6ac

Works fine when redoing from the completed action, but not the activity table.

I also noticed this fun behaviour. Seems to only happen on the manage permissions form:

https://github.com/user-attachments/assets/529c06a4-a9fd-4362-9742-fee2809d23a9

And this is happening when redoing via either method:

https://github.com/user-attachments/assets/91ade709-ea73-4a67-b462-c661cf2947a5

Could always open this as a new issue for the sake of getting it merged. Not sure if any of these are specifically introduced by this PR.

2024-11-12 08:50 UTC, iamsamgibbs approved these changes
Approving so we can get this merged and we can open a new issue for the last little bits

2024-11-12 11:16 UTC, merged