fix: userhub styling adjustments
JoinColony/colonyCDapp pull request #3618
Opened 2024-11-04 16:27 UTC by rumzledz

## Description

Just some styling updates to follow the Figma designs:

1. Our fonts have a default line height which causes them to have extra vertical spacing. On Figma, you'll find that the Avatar has compensated for this by having a top spacing of 4px from the container. So I just added it:

![avatar alignment](https://github.com/user-attachments/assets/6b7b1540-9dca-44dd-8737-6b854fdd2bd4)

2. Then made a little style update for the UserHub tabs to sort of align the Balance icon's top edge with the notification title's top edge as shown in #3578 

![image](https://github.com/user-attachments/assets/3b513fbe-d6ca-4e6c-9a48-5566ba75f116)

So yeah, here's the result:

<img width="686" alt="image" src="https://github.com/user-attachments/assets/fdaf277c-90a8-426a-8994-0f027ff54247">

## Testing

1. Create a Simple Payment
2. Wait for the notification to arrive
3. Open the UserHub
4. Go to the Notifications tab
5. Verify that the issue raised on #3678 is addressed by referring to these designs: https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1782-51509&t=9BgEXHLnQiK6dmp0-4

Resolves #3578

2024-11-05 11:02 UTC, mmioana requested changes
Pixel-perfect job on this one @rumzledz 

Now the icon for a notification is properly aligned
![Screenshot 2024-11-05 at 12 00 00](https://github.com/user-attachments/assets/5e517c23-b2c6-4544-a7fa-de3bd79e2293)

And the items from the user hub navigation have the same spacing between the icon and title
![Screenshot 2024-11-05 at 12 00 12](https://github.com/user-attachments/assets/4f20546b-df9f-4e50-b243-b7cfcf186b02)
![Screenshot 2024-11-05 at 12 00 20](https://github.com/user-attachments/assets/1e830006-ee6e-490c-b9cd-8867fd665f5d)

However I'm requesting changes because after checking the designs I believe we still need the `pt-4` for the notification list

2024-11-05 12:45 UTC, mmioana submitted a review, later dismissed
Thanks for the amazingly fast change, actually `pt-0.5` was needed 💪 
You're the pixel master of disaster ✨

2024-11-05 18:01 UTC, rdig approved these changes
All good now. Nicely fixed! :+1: 

![Screenshot from 2024-11-05 20-00-15](https://github.com/user-attachments/assets/dc19ce90-e900-4cfd-962f-801ec5028360)
![Screenshot from 2024-11-05 20-00-24](https://github.com/user-attachments/assets/8d6efc50-8be5-44b8-8968-fce08e8e36a4)

2024-11-06 09:25 UTC, mmioana approved these changes
Awesome @rumzledz, not also the colony logo is perfectly rounded 🥇 

![Screenshot 2024-11-06 at 10 23 32](https://github.com/user-attachments/assets/fcade9be-39f0-494e-8f82-819dac6e0a6f)

And the spacing is as expected 💯 

![Screenshot 2024-11-06 at 10 24 19](https://github.com/user-attachments/assets/2a12cd6a-834a-4b0c-9c24-52f525102cee)
![Screenshot 2024-11-06 at 10 24 28](https://github.com/user-attachments/assets/d8075487-05cb-4942-ba2b-2701c4bba398)

2024-11-07 19:58 UTC, Nortsova approved these changes
Great work on this @rumzledz ✨ 

Checked it with my PixelPerfect tool and it seems it aligns perfectly: 
<img width="745" alt="image" src="https://github.com/user-attachments/assets/671fdc49-0a53-4419-a894-10389b911af1">

Tested with a ruler as well 👍 
<img width="441" alt="image" src="https://github.com/user-attachments/assets/ab713003-593d-43db-b0c1-e102be5a81fe">

2024-11-08 19:12 UTC, merged