feat: add redo to streaming payment
JoinColony/colonyCDapp pull request #3648
Opened 2024-11-06 10:40 UTC by CzarekDryl

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-11-13 14:49 UTC, iamsamgibbs requested changes
Nice work on this! I tested every scenario with different start / end conditions I could think of and it is handling them all fine.

<img width="1728" alt="Screenshot 2024-11-13 at 14 40 47" src="https://github.com/user-attachments/assets/e07bfa7d-d919-4bbc-9621-225495981a2d">

<img width="1728" alt="Screenshot 2024-11-13 at 14 40 54" src="https://github.com/user-attachments/assets/1392febc-e470-4086-8e57-258023bffc50">

The only reason I'm rejecting, is because of this recent PR #3587 which re-enables the redo option from the activity table. Currently here it isn't possible to redo via the activity table. It would be great if the `feat/streaming-payments-ui` feature branch could be rebased onto master and make sure the redo via activity table functionality is working here. Especially as there is some custom logic in getting the correct values to show.

2024-11-13 14:49 UTC, iamsamgibbs commented on src/components/v5/common/CompletedAction/partials/StreamingPayment/StreamingPayment.tsx
> +  // console.log({isStartImmediately, startTimeDate, createdAt});
Left over console log

2024-11-14 10:09 UTC, iamsamgibbs approved these changes
Switching this to an approval and we can handle the redo via activity table as a separate issue after the branches have been rebased.

2024-11-22 14:27 UTC, bassgeta approved these changes
Works nice and the solution is very simple :+1: 
Tried out a few cases, got 2 on video too :eyes: 

https://github.com/user-attachments/assets/da782647-db5f-442b-aed6-29489192270d

2024-11-22 14:27 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/hooks/useActionFormBaseHook.ts
> +    transform,
nice catch!

2024-11-22 16:29 UTC, rdig requested changes
I've tested this but can only redo the streaming payment action from the sidebar menu, not from activity feed menu.

I believe redo-ing from the activity feed should also be included in this PR

From the sidebar:

![Screenshot from 2024-11-22 18-24-51](https://github.com/user-attachments/assets/caa58889-6dce-446b-b2d5-4e84925e94d9)
![Screenshot from 2024-11-22 18-25-53](https://github.com/user-attachments/assets/7308ce9e-2ec9-4f6d-ab39-6b1299d5bb4a)
![image](https://github.com/user-attachments/assets/ff6783d6-c49c-4d81-a09f-82a4e4f40950)
![Screenshot from 2024-11-22 18-26-39](https://github.com/user-attachments/assets/17a88b72-ad70-4e3e-92fb-fea9bd0b19d6)

From the activity feed:

![Screenshot from 2024-11-22 18-27-00](https://github.com/user-attachments/assets/6bf1aeae-19aa-4e77-ad9e-d5d48542430b)

2024-11-28 14:23 UTC, CzarekDryl commented
@rdig Can we make it in other PR? `feat/streaming-payments` branch needs to be rebased to have changes from https://github.com/JoinColony/colonyCDapp/pull/3587

2024-11-29 13:44 UTC, rdig commented
Sure, another PR is fine

2024-11-29 13:44 UTC, rdig approved these changes
All good here

2024-12-02 08:38 UTC, merged