fix: add only numeric values and remove tokens validation
JoinColony/colonyCDapp pull request #3689
Opened 2024-11-08 16:52 UTC by adam-strzelec

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

Resolves  [#31415](https://github.com/JoinColony/colonyCDapp/issues/3647)

2024-11-08 16:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3689) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3689) before we can accept your contribution.<br/><hr/>**strzelec** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=3689) it.</sub>

2024-11-12 12:53 UTC, iamsamgibbs requested changes
Thanks for your work on this Adam. The validation is removed as expected.

However, I'm still experiencing the console error mentioned in the original issue:

<img width="1142" alt="Screenshot 2024-11-12 at 12 49 36" src="https://github.com/user-attachments/assets/63199e7f-dd0d-470f-8a24-4415ad625203">

The comma separation for the amount has also disappeared (although I can see your changes are unrelated to this).

<img width="549" alt="Screenshot 2024-11-12 at 12 50 35" src="https://github.com/user-attachments/assets/d86c6697-5ea6-45b5-bcbc-94d4b69af390">

2024-11-13 14:28 UTC, iamsamgibbs approved these changes
Thanks for resolving the console error. The commas seem to have reappeared for me too.

<img width="1140" alt="Screenshot 2024-11-13 at 14 19 12" src="https://github.com/user-attachments/assets/6e90e01b-6cad-4312-b17d-a2e90c3b816e">

I did find this bug specifically when switching from staged payments to streaming payments then interacting with the amount field. But it is also happening on the feature branch, so won't stop this from getting merged.

https://github.com/user-attachments/assets/afc8ac47-815a-4c05-9ba0-54c623556557

2024-11-19 12:46 UTC, Nortsova approved these changes
Nice work on this, no error in console, no validation ✨ : 

<img width="1295" alt="image" src="https://github.com/user-attachments/assets/54544fb4-7ed3-484d-9a0c-0e7eb67f3bdf">

2024-11-21 09:10 UTC, merged