test: e2e tests for manage account page
JoinColony/colonyCDapp pull request #3710
Opened 2024-11-14 13:32 UTC by olgapod

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-11-21 11:44 UTC, rdig approved these changes
The preview logic works well, it just doesn't need the `ulimit` as you don't have as many files needed to be watched by `vite` anymore _(since they're bundled now)_

However I do want to note that while this is very close to the production build, it's still not 100% the same as production, as due to internal routing and cors issues we're running in our infrastructure, locally this cannot function exactly the same.

But this is as close as it gets, so I think it'll be of great help.

2024-11-21 11:44 UTC, rdig commented on package.json
> +    "preview": "ulimit -n 2048 && NODE_ENV=development npm run build && npx import-meta-env -x .env && vite preview --port=9091",
```suggestion
    "preview": "NODE_ENV=development npm run build && npx import-meta-env -x .env && vite preview --port=9091",
```

2024-11-22 11:27 UTC, iamsamgibbs requested changes
Nice job on this @olgapod ! All tests are passing 🎉 

<img width="1103" alt="Screenshot 2024-11-22 at 11 02 20" src="https://github.com/user-attachments/assets/2e48a7a0-c228-461f-84f7-cca1f133b91e">

I've left a few small comments, some are personal opinion, I think removing the unneeded awaits in the spec file is the only one that should be fixed before merging.

Another personal opinion thing, but it feels like the spec files end up being quite long and these are some of the simpler sections of the site, so it will only get worse with more complicated sections. I'm not sure if it's possible to break them up into smaller chunks?

It might also be worth adding extra tests to the avatar upload that the file type restrictions are respected, and the minimum resolution.

2024-11-22 15:08 UTC, olgapod commented on src/components/frame/v5/pages/UserAdvancedPage/partials/NotificationsSection/NotificationsSection.tsx
> +    >
Thanks for spotting this. Performance-wise, isn’t it better to keep such things outside ? The toggleButton has no dependency on anything from inside the NotificationsSection , so why reassign it on every render? But if it isn’t a concern, and looks neater to the team I’m happy to move it back.

2024-11-22 15:21 UTC, olgapod commented on playwright/e2e/manage-account.spec.ts
> +      await expect(displayNameInput.inputValue).toBeTruthy();
hey, thanks a lot for this one, although this is not really the case that the await is not needed here, but I should have called it as it's a function returning promise. 
<img width="439" alt="image" src="https://github.com/user-attachments/assets/6309bd1c-dc67-4c3e-892f-7ee8a3b7cb67">

2024-11-22 16:28 UTC, olgapod commented
> Another personal opinion thing, but it feels like the spec files end up being quite long and these are some of the simpler sections of the site, so it will only get worse with more complicated sections. I'm not sure if it's possible to break them up into smaller chunks?

> It might also be worth adding extra tests to the avatar upload that the file type restrictions are respected, and the minimum resolution.

Hey @iamsamgibbs , thanks for the thorough review!

Regarding the test files being lengthy - these two actually are likely to be the largest ones due to the features being a multi-tab page and a multi-step form. I'll aim to keep upcoming tests shorter moving forward.

As for adding tests for the missing cases of file uploader validation, I will definitely do that, thanks for noticig. However, I was also thinking whether adding detailed e2e tests for input validations would be the best approach, I don't mean this particular case but in general. It might be more effective to cover such validation in unit tests since they run much faster.  What are your thoughts?

2024-11-28 14:10 UTC, Nortsova submitted a review, later dismissed
Thank you @olgapod for your work, it seems that tests are passed successfully 🎉 

<img width="359" alt="image" src="https://github.com/user-attachments/assets/78285ca1-64c9-48bf-b3b7-b37ca4f5231e">

2024-11-29 11:38 UTC, iamsamgibbs approved these changes
Thanks for the changes! All the tests are still passing.

<img width="434" alt="Screenshot 2024-11-29 at 11 33 11" src="https://github.com/user-attachments/assets/dee9441b-6b24-4bae-9c3f-4a9aff83c5ba">

VSCode is still bugging me about this, but happy to leave it as everything is working fine.

<img width="610" alt="Screenshot 2024-11-29 at 11 25 03" src="https://github.com/user-attachments/assets/bde41b08-6c28-401f-ae2a-a2f72b62033b">

Also still think it would be beneficial to add the extra tests to the avatar upload that the file type restrictions are respected, and the minimum resolution. But this can always come in a later PR.

2024-11-29 13:05 UTC, Nortsova approved these changes
Thanks, tests are passing:

<img width="364" alt="image" src="https://github.com/user-attachments/assets/daeed944-e485-49d8-9a92-f5d717f1ce76">

2024-11-29 19:23 UTC, merged