fix: description in release step
JoinColony/colonyCDapp pull request #3726
Opened 2024-11-18 12:22 UTC by adam-strzelec

## Description

Display accurate description for Advanced payment in release step

## Testing

- Create advanced payment
- Go thru entire flow
- Go back to release step

## Diffs

**Changes** 🏗

<img width="368" alt="Screenshot 2024-11-18 at 12 56 27" src="https://github.com/user-attachments/assets/9a055819-fc2a-4120-959f-4109d98d0f2e">

Resolves 3334

2024-11-18 12:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3726) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3726) before we can accept your contribution.<br/><hr/>**strzelec** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=3726) it.</sub>

2024-11-19 09:42 UTC, bassgeta requested changes
Well it does in fact do the job, but if we always want to display this, I think we should remove `FinalizeByPaymentCreator` info so we get rid of some extra lines :sunglasses:

2024-11-19 09:42 UTC, bassgeta commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
> +                <ActionWithPermissionsInfo
Hmmm? :D Alright so we always display that the payment was released via permissions, if that's what we always need to do (even if the user used their temporary payment creator permissions), we can safely remove `FinalizeByPaymentCreatorInfo`

2024-11-21 16:37 UTC, mmioana requested changes
Hey @adam-strzelec thanks for picking this issue up 🙌 

However, I believe this is not working as intended.

If I release the advanced payment using `Permissions` the right information is displayed
![Screenshot 2024-11-21 at 17 32 10](https://github.com/user-attachments/assets/7d6c91c8-4ce8-43ba-871c-261b2e9e1a7c)

However, releasing the advanced payment using `Payment creator` the same details as for the previously used decision method (`Permissions`) is shown, which is not correct
![Screenshot 2024-11-21 at 17 33 11](https://github.com/user-attachments/assets/c63974d0-e59f-4758-a07b-cc8e3979a95d)

2024-12-03 00:25 UTC, jakubcolony commented
The permissions vs payment creator selection never worked properly - the saga always uses payment creator if user is such:

<img width="550" alt="image" src="https://github.com/user-attachments/assets/ff8aafdf-2ecf-4c0f-b409-1bd1c92cf1c9">

While we can tell if permissions or reputation was used, we lack details to tell if permissions were specifically chosen over payment creator.

@arrenv How should we proceed with this one?
- We could add a separate payment creator finalization action (but this might be overkill just for history tracking).
- Simply prevent payment creators from selecting permissions (assuming there's no real need for them to use permissions). This lets us keep using the existing expenditure owner address check.

2024-12-06 10:14 UTC, arrenv commented
@adam-strzelec @jakubcolony 

Thank you for the input on this. I think it is useful to be able to communicate the difference of how the payment was released. So, out of the two options provided, I would opt for the second one.

> Simply prevent payment creators from selecting permissions (assuming there's no real need for them to use permissions). This lets us keep using the existing expenditure owner address check.

To add to that, I feel it would also be good to have the select field to auto select the option if there is only one. I do think a new issue should be created for this update.

2024-12-13 00:53 UTC, jakubcolony requested changes
It looks like there was a copy change that was not specified in the issue. I think this should still read "Payment creator released this payment."

<img width="377" alt="image" src="https://github.com/user-attachments/assets/46854bbc-81cb-4757-b79b-f6b5b2afd6dc" />

----

The info is also incorrectly showing payment creator decision method when the payment was finalized by a different user via permissions.
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/924d2ab5-efdc-480a-a0bd-63615d7ec129" />

2024-12-13 00:53 UTC, jakubcolony commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/PaymentBuilderWidget.tsx
> +                  statusText="action.executed.creator.description"
This needs to show payment creator/permissions depending on the decision method used

2024-12-20 10:45 UTC, mmioana reviewed
Thank you for your continuous effort on this one @adam-strzelec 🙌 

Now the copy is the correct one for the `Release` step as the `Payment creator`
![Screenshot 2024-12-20 at 11 38 36](https://github.com/user-attachments/assets/490a662f-3207-43a3-b04c-02f974d9eb0c)

Created another `Advanced payment`
![Screenshot 2024-12-20 at 11 40 51](https://github.com/user-attachments/assets/d334026b-5782-429e-806a-e2898e6c906e)

And tried to finalise it as `amy`, but it seems I can no longer do that. Is this as intended?
![Screenshot 2024-12-20 at 11 41 06](https://github.com/user-attachments/assets/ca77e4bf-4aa3-4c44-bd22-db3d17ca0037)

2025-01-02 08:40 UTC, adam-strzelec commented
@mmioana I have no idea. @arrenv If I am a person who did not create the action, should I receive such information?

2025-01-02 09:17 UTC, arrenv commented
> @mmioana I have no idea. @arrenv If I am a person who did not create the action, should I receive such information?

Yes, this is intended, the has to be an available decision method for a non-creator of the Payment to be able to release it.

So, amy would need either the right permissions ("Payer" bundled or Arbitration), or, the Lazy consensus extension would need to be installed and there would need to be reputation in the domain.

2025-01-13 08:38 UTC, mmioana requested changes
Hey @adam-strzelec @arrenv thanks for the clarification 🙌 

The description correctly updates when releasing as a payment creator
![Screenshot 2025-01-13 at 09 18 33](https://github.com/user-attachments/assets/796a3496-6175-4e12-be8f-1d25e280106b)
![Screenshot 2025-01-13 at 09 18 43](https://github.com/user-attachments/assets/3c915475-464e-4f6b-a53c-27a4c6784657)

Created another `Advanced payment`
![Screenshot 2025-01-13 at 09 19 28](https://github.com/user-attachments/assets/9f57eef2-4a13-4e40-a5cd-df9fceaa6378)

Then after installing the `Reputation` extension
![Screenshot 2025-01-13 at 09 21 53](https://github.com/user-attachments/assets/27515208-b620-4b40-95e4-c1e527323f25)

And tried to release it as `amy`, the `Reputation` decision method was available in the dropdown
![Screenshot 2025-01-13 at 09 21 49](https://github.com/user-attachments/assets/8c3f7d33-ac90-403e-8b68-cc82bd402644)

However @arrenv @adam-strzelec, if I assign `amy` the `Payer` bundled permissions, the permissions is not available to `Release` the advanced payment ❌ 
![Screenshot 2025-01-13 at 09 16 20](https://github.com/user-attachments/assets/890d2b52-e0d8-49d3-bbba-7e5682a2a679)
![Screenshot 2025-01-13 at 09 20 56](https://github.com/user-attachments/assets/c2659b7e-093c-404e-a02f-c66806536dc1)

2025-01-14 16:48 UTC, adam-strzelec commented
@mmioana done 🙂

2025-01-15 07:21 UTC, jakubcolony requested changes
Thanks for another round of changes @adam-strzelec

As leela (who created the payment), I can correctly see Payment creator as the only available decision method:
<img width="958" alt="image" src="https://github.com/user-attachments/assets/b0a93dcf-71fb-4a94-a44b-9083dd38af8b" />

As a user without arbitration permission, I get an error as expected:
<img width="801" alt="image" src="https://github.com/user-attachments/assets/b2b3c7f9-ac11-4ba0-96d0-bef6a8e868d0" />

However, after being assigned Payer role, the newly available method reads "Payment creator" instead of "Permissions":
<img width="804" alt="image" src="https://github.com/user-attachments/assets/fe54f526-ba54-4b13-abae-33c7f107937d" />

2025-01-16 08:03 UTC, mmioana requested changes
Thanks for your continuous efforts on this issue @adam-strzelec 🙌 

Released a payment as `Payment creator` ✅ 
![Screenshot 2025-01-16 at 08 34 15](https://github.com/user-attachments/assets/e7189fb0-f639-480e-a870-f1abd370b376)

Gave `amy` payer permissions
![Screenshot 2025-01-16 at 08 35 00](https://github.com/user-attachments/assets/964053ed-813d-4768-a524-eb38aa5ea9a6)

Released payment using `Payer` permissions ✅ 
![Screenshot 2025-01-16 at 08 36 47](https://github.com/user-attachments/assets/410c48a6-d781-4825-ad5c-5196632ff291)
However the widget from the `Release` step showed the payment was released as `Payment creator`, which is not correct ❌ 
![Screenshot 2025-01-16 at 08 37 09](https://github.com/user-attachments/assets/15e86942-2057-4d9b-b5ae-501ac0e5a9d7)

Gave `fry` `Custom-Arbitration` permissions
![Screenshot 2025-01-16 at 08 38 55](https://github.com/user-attachments/assets/86b1aee8-57c1-4fb7-ad04-ac2838710fda)
Released payment using `Custom-Arbitration` permissions ✅ 
![Screenshot 2025-01-16 at 08 40 39](https://github.com/user-attachments/assets/21caa105-fd4e-436b-b7ab-52a162d00905)
However, also here the same problem with the widget showing the payment was released as `Payment creator`, which is not correct ❌ 
![Screenshot 2025-01-16 at 08 40 49](https://github.com/user-attachments/assets/43e61461-d9a3-46fc-98b9-f94d5b7b47bc)

2025-01-16 08:03 UTC, mmioana commented on src/components/v5/common/CompletedAction/partials/PaymentBuilder/partials/PaymentBuilderWidget/hooks.tsx
>              )}
Here we should perform a similar check for `userIsCreator` to decide which description to actually show

2025-01-24 11:09 UTC, adam-strzelec commented
@mmioana Do we have any designs for how it should look like when the user uses permissions? The main issue only says very generally that `The history of decisions should accurately show what happened and how the decision was made.` Should it be `Member used permissions to create this action.`?

2025-01-27 23:36 UTC, jakubcolony commented
@adam-strzelec I believe that's the copy that should be used in case of permissions, it would be consistent with the cancel step:
<img width="379" alt="image" src="https://github.com/user-attachments/assets/fdb7d37d-8ed9-4660-a38a-1e59b7fe0efd" />

2025-01-28 19:20 UTC, mmioana approved these changes
Thanks a lot for all the changes @adam-strzelec it all works as expected now 🥇 

Released the payment as `Payment creator`
![Screenshot 2025-01-28 at 20 04 14](https://github.com/user-attachments/assets/232e2e8a-f1a2-4bdf-9d40-0460d7310ba8)
![Screenshot 2025-01-28 at 20 04 30](https://github.com/user-attachments/assets/df9382b1-86e2-4504-b13b-606a0f4beaec)

Gave `amy` `Payer` permissions and released the payment using `Permissions`
![Screenshot 2025-01-28 at 20 06 13](https://github.com/user-attachments/assets/0cc9db14-73cf-4d2f-8940-e3344a9e709f)
![Screenshot 2025-01-28 at 20 07 34](https://github.com/user-attachments/assets/58b34232-e5fb-417c-96e5-f7606192b2c7)

Now gave `fry` `Custom-Arbitration` permissions
![Screenshot 2025-01-28 at 20 07 41](https://github.com/user-attachments/assets/0a3fa656-9453-4679-a2b8-9701bd56dfb8)
And released the payment using `Permissions`
![Screenshot 2025-01-28 at 20 08 36](https://github.com/user-attachments/assets/9aa084ce-86ae-4ddb-a368-bbb713a13d21)
![Screenshot 2025-01-28 at 20 08 46](https://github.com/user-attachments/assets/d582adac-6017-4e36-88be-ce2a85617d2a)

Removed `fry`'s permissions and installed the `Reputation` extension
![Screenshot 2025-01-28 at 20 11 51](https://github.com/user-attachments/assets/89757069-806e-4c18-95ea-4d5448706184)
Created another payment as `fry` and used the `Reputation` decision method for releasing the payment
![Screenshot 2025-01-28 at 20 11 57](https://github.com/user-attachments/assets/99f9247d-728a-47ea-b37e-ea42993bd77d)
![Screenshot 2025-01-28 at 20 14 01](https://github.com/user-attachments/assets/ecf2fc16-3f49-47e3-8741-6e96a826b9cc)

@adam-strzelec Regarding the wording I think @arrenv is best to provide an input to when releasing a payment using `Permissions` we should use `Member used permissions to create this action.`. Personally, I believe `Member used permissions to release this payment.` would be a better fit. Either way, I'm happy to approve your PR 💯 

Really nice work and thanks again for all the changes! 🎉

2025-01-29 10:04 UTC, bassgeta approved these changes
Thanks for all the hard work on this, looking real good right now :muscle: 
As payment creator :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/5947bfc1-09dc-43ba-8472-79a22d3f13d5)
As member with permissions :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/896d1b85-4af1-44c3-a4a8-b15215f1cbe2)
With reputation :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/558837e9-22f3-4d50-9c73-dcf538ffee06)

2025-01-29 11:47 UTC, arrenv commented
@adam-strzelec Regarding wording as @mmioana has raised, this is definitely the desired behavior, we want these descriptions to be as accurate as possible so, if it can be `Member used permissions to release this payment.` in this case, that would be preferred.

2025-01-30 09:56 UTC, adam-strzelec commented
@arrenv @mmioana I already changed the copy 🙂

2025-01-31 00:02 UTC, jakubcolony approved these changes
Nice work on this PR, looks good to be merged. Thank you @adam-strzelec 👍 

Releasing as payment creator:
<img width="501" alt="image" src="https://github.com/user-attachments/assets/03f18f0c-e104-461e-ae06-7d049a1d34f7" />
<img width="385" alt="image" src="https://github.com/user-attachments/assets/819d6979-8c24-4018-9709-47aa30e257f4" />

Releasing as another user with permissions:
<img width="508" alt="image" src="https://github.com/user-attachments/assets/0f6e37d3-29fa-4603-963a-8a9bb5148b46" />
<img width="385" alt="image" src="https://github.com/user-attachments/assets/76987227-5cb7-437a-8a64-e9fddd2840a8" />

Trying to release as a user without permissions:
<img width="512" alt="image" src="https://github.com/user-attachments/assets/0303f4e1-2ced-4d43-a654-9609e22ea4cc" />

Releasing using reputation:
<img width="387" alt="image" src="https://github.com/user-attachments/assets/4869d568-0d5d-4216-bb63-4035f0c63594" />

2025-02-04 09:15 UTC, AdrianDudko commented
@bassgeta Can you please take a look at this PR? We have 2 approvals already :)

2025-02-05 09:38 UTC, iamsamgibbs approved these changes
Great job getting to the bottom of this issue. All working nicely now.

Releasing as creator:
![Screenshot 2025-02-05 at 09 32 46](https://github.com/user-attachments/assets/358ce341-353d-45b1-a242-f22590adbd55)

Releasing with permissions:
![Screenshot 2025-02-05 at 09 36 51](https://github.com/user-attachments/assets/54a99d0d-6937-4dcf-82fc-ee990449ce17)

Releasing with reputation:
![Screenshot 2025-02-05 at 09 34 33](https://github.com/user-attachments/assets/ac11c261-0535-45e3-ab1b-f39059c68ea0)

🎉

2025-02-05 10:15 UTC, merged