fix: add info about opposed agreement
JoinColony/colonyCDapp pull request #3745
Opened 2024-11-20 15:01 UTC by adam-strzelec

## Description

Display badge about opposed greeement

## Testing

- create agreement
- fully oppose the agreement
- display item in `Recent activity`

## Diffs

**Changes** 🏗

![Screenshot 2024-11-20 at 15 54 38](https://github.com/user-attachments/assets/326924f3-1673-4ca7-91c7-e2132de327ee)

Resolves https://github.com/JoinColony/colonyCDapp/issues/3463

2024-11-20 15:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3745) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/JoinColony/colonyCDapp?pullRequest=3745) before we can accept your contribution.<br/><hr/>**strzelec** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/JoinColony/colonyCDapp?pullRequest=3745) it.</sub>

2024-11-20 15:56 UTC, Nortsova approved these changes
Thank you, @adam-strzelec , for your work! This fix seems to be working great. I also tested the 99% oppose scenario, and it correctly shows "Staking." Only 100% oppose displays the "Opposed" status.

<img width="1368" alt="image" src="https://github.com/user-attachments/assets/86290efb-9a4f-421f-8d0e-c7163832b08c">

2024-11-21 10:50 UTC, rdig requested changes
So either I am misunderstanding the purpose of this PR or the testing steps are vague.

If you full oppose an agreement, the status is "Failed", not "Opposed"

![Screenshot from 2024-11-21 12-48-42](https://github.com/user-attachments/assets/02f7c115-892b-4a7e-9d05-18beb285626e)
![Screenshot from 2024-11-21 12-48-57](https://github.com/user-attachments/assets/adc7fee6-c86a-4657-88b6-0d4f6ffece2b)
![Screenshot from 2024-11-21 12-49-37](https://github.com/user-attachments/assets/419cef2c-59b0-4370-965c-8424c128478a)

2024-11-26 10:32 UTC, adam-strzelec commented
@rdig It displays as opposed when you fully oppose during `Staking` step.

2024-11-27 16:47 UTC, rdig approved these changes
Re-checked, all good now.

Nicely done!

2024-11-28 11:12 UTC, merged