Fix: Activity table fixes and table refactoring
JoinColony/colonyCDapp pull request #3757
Opened 2024-11-22 15:12 UTC by mmioana

## Description

This PR aims to refactor (a tiny bit) the `Table` component and addresses the following issues

- [X] The pagination should be displayed inside the table container and not outside for all tables
[Figma link](https://www.figma.com/design/l1dOM5qiQYwF0ElvKDqqjg/Design-System---Colony-v3?node-id=1776-8565&t=JazItdUIdCedG0rv-4)
- [X] When there are not enough items for there to be more than 1 page, the recent activity table should go as tall as it can until it either fills the bottom of the dashboard area, or reaches the max height it would be with 7 items.
- [X] For activity tables, the content - namely the `metadata` and `status pill` - is moving upon expanding a row

**Tabs closed (note the position of the pill, title and metadata):**
<img width="391" alt="image" src="https://github.com/user-attachments/assets/3ec1aa80-57d8-440d-ba20-474b6dd36721">
**With one tab open (again, note the position of the pill, title and metadata):**
<img width="404" alt="image" src="https://github.com/user-attachments/assets/b63d0d98-762f-4910-a5d8-8cfc07c1bcf3">

- [X] For the recent activity table, the status pills should have only `16px` between the expandable icon
<img width="466" alt="image" src="https://github.com/user-attachments/assets/27243d17-006a-4a4f-97af-f20cce378b7b">

## Testing

TODO: Please test the above mentioned issues have been resolved, as well as the `Table` component refactoring didn't introduce bugs. 

* Step 1. Visit http://localhost:9091/planex
* Step 2. Set your viewport to mobile
* Step 3. Try expanding an existing action

https://github.com/user-attachments/assets/f4844621-3029-4b7c-8c87-a36e37623b37

* Step 4. Ensure the description and status pills of the other actions doesn't change their position
* Step 5. Check the spacing between the status pill and expandable icon is `16px`
 
![Screenshot 2024-11-22 at 16 03 44](https://github.com/user-attachments/assets/9bbf2df6-358a-4888-8a11-d8172bc043af)

* Step 6. Now go to http://localhost:9091/planex/activity
* Step 7. Check the table pagination is displayed inside the table
![Screenshot 2024-11-22 at 16 05 45](https://github.com/user-attachments/assets/d326c65c-f7e2-4916-beeb-f1becce2f5e3)

* Step 8. Run `node scripts/create-colony-url.js` and complete creating a colony
* Step 9. Create a `Mint tokens` action
![Screenshot 2024-11-22 at 16 07 19](https://github.com/user-attachments/assets/aab992ad-a240-45ce-8f78-4d3ea0d8ee18)

* Step 10. Go to the newly created colony `Dashboard` page
* Step 11. Check the height of the `Recent activity` table - it should occupy the whole available page height
![Screenshot 2024-11-22 at 16 09 01](https://github.com/user-attachments/assets/7fbd9fe1-9d65-4e3b-b86f-3159b4f52d17)

### Further testing
Please check the tables from 
http://localhost:9091/planex/balances
http://localhost:9091/planex/incoming
http://localhost:9091/account/crypto-to-fiat

Also please try creating an `Advanced payment` or `Manage tokens` action and check the tables there for both `mobile` and `desktop`

Any further testing ideas are highly welcomed 🙌  and thanks a lot for reaching this far in the testing 🥇 

## Diffs

**Changes** 🏗

* The `Table` component has been split up into more manageable partial components 

Resolves #2695 
Resolves #3550 
Resolves #3668

2024-11-25 19:34 UTC, rdig approved these changes
Very nice, all 3 cases I tested, mobile, desktop, and single action in the list, work as described.

Nicely done!


https://github.com/user-attachments/assets/6b554c05-8886-46a8-be15-886d0d2ac8b1


https://github.com/user-attachments/assets/dedf752a-a4d6-4331-926a-e730e1a5ee2d


https://github.com/user-attachments/assets/17c2f4b7-7701-447a-a64a-a881d74411e3

2024-11-27 10:26 UTC, iamsamgibbs approved these changes
Thanks for the change, looks perfect now!

<img width="1351" alt="Screenshot 2024-11-27 at 10 25 36" src="https://github.com/user-attachments/assets/3606e12e-4de2-4cc5-a6c9-b96d16c972ba">

<img width="497" alt="Screenshot 2024-11-27 at 10 25 43" src="https://github.com/user-attachments/assets/b7ce6380-94e9-4bdd-8b51-04afbccec19e">

2024-11-27 13:06 UTC, bassgeta submitted a review, later dismissed
Definitely a step in the right direction with the table, it was about time we took everythin out into separate components.
Love that we have 2 different layouts now, it was quite confusing before :') 
Overall, super happy with the foundations laid in this PR, let's hope we can get to refactoring that beast into something manageable in the future :crossed_fingers: 
1. Expanding an existing action :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/96cdde2e-d1d3-4908-9802-d89ebf1c4fb7)
2. Padding is 16px :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/b4655f19-e57e-40e3-9c39-d7803ce07621)
3. No pagination on latest activity when only 1 action :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/41a07db3-f55c-4ad6-9dbe-93f3e1728594)
4. Tallboi recent activity table :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/2e4041e4-03a9-4877-8f36-a4c355e8cf22)

2024-11-28 09:13 UTC, rumzledz requested changes
Almost at the finish line @mmioana ! All the test cases you mentioned are looking good on my end but I just noticed one wee problem. The error state for the table seems to be slightly off:

## Manage permissions form

| Master | Your branch |
| ---- | ---- |
| <img width="692" alt="Screenshot 2024-11-28 at 17 11 14" src="https://github.com/user-attachments/assets/0eb29cf6-41b0-4164-b021-9ce49729318d"> | <img width="692" alt="Screenshot 2024-11-28 at 17 10 51" src="https://github.com/user-attachments/assets/9e699451-9ae4-48a2-a6e3-8a303afce58a"> |

## Manage Tokens

| Master | Your branch |
| ---- | ---- |
| <img width="693" alt="Screenshot 2024-11-28 at 17 12 00" src="https://github.com/user-attachments/assets/57b1861e-9057-40b6-a371-8de589a17292"> | <img width="684" alt="Screenshot 2024-11-28 at 17 09 21" src="https://github.com/user-attachments/assets/8d7d9521-c64d-42e3-89f9-45acbd32e76f"> |

2024-11-28 12:02 UTC, mmioana commented
Thanks so much for finding this issue @rumzledz 🙌 

I pushed a fix, so could you guys @iamsamgibbs @bassgeta @rumzledz please re-check? 🙏

2024-11-28 16:07 UTC, mmioana commented
@rumzledz found an issue with duplicated borders for table shown on the http://localhost:9091/planex/incoming page when expanding a token, but now it should be fixed

![Screenshot 2024-11-28 at 17 06 38](https://github.com/user-attachments/assets/5468e24d-635c-4b9d-8e92-fba654eb754f)

2024-11-29 10:28 UTC, iamsamgibbs approved these changes
Nice job @mmioana this is all looking good!
 
<img width="1343" alt="Screenshot 2024-11-29 at 10 24 50" src="https://github.com/user-attachments/assets/6cd2561e-07a3-4ff5-a894-cfbffd12a866">

Error states

<img width="671" alt="Screenshot 2024-11-29 at 10 25 22" src="https://github.com/user-attachments/assets/1511fece-0441-4631-a63f-a37f62f0f95d">

<img width="661" alt="Screenshot 2024-11-29 at 10 26 44" src="https://github.com/user-attachments/assets/2e345f3b-4004-41ba-8f96-c53134e10422">

Still looking good:

<img width="1371" alt="Screenshot 2024-11-29 at 10 27 06" src="https://github.com/user-attachments/assets/e0477430-96e8-4bda-ada5-df39344e482d">

<img width="1318" alt="Screenshot 2024-11-29 at 10 27 30" src="https://github.com/user-attachments/assets/9de0b37f-2978-402f-b623-abe247293314">

2024-11-29 10:36 UTC, bassgeta approved these changes
Nice job fixing the error border too, now let's merge this badboi :ship: 
![image](https://github.com/user-attachments/assets/bb25d698-02be-41b8-a2a2-31a429de46a7)
Errors now look correct :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/ad1bb836-d58c-4c7b-87f2-d55604f7b895)
![image](https://github.com/user-attachments/assets/0dab3198-dfb1-4cd8-b99a-d53c13ffdb7e)

2024-12-02 11:03 UTC, rumzledz approved these changes

2024-12-02 11:04 UTC, rumzledz commented
Thanks for your patience Ioana! All good on my end! Merge merge mergeeee 🚀

2024-12-02 11:08 UTC, merged