Fix: Split payment action form has pre-selected team filled
JoinColony/colonyCDapp pull request #3772
Opened 2024-11-25 14:13 UTC by mmioana

## Description

- The issue was caused by the fact the other two payment action forms (`Simple Payment` and `Advanced Payment`) were relying on the team field to be called `from`, while `Split payment` was using `team` as the field id.

## Testing

TODO: Please check opening the action sidebar by clicking `Pay` and having a team filter in place will populate the `Simple payment`/`Advanced payment`/`Split payment` with the active team filter. 

* Step 1. Go to http://localhost:9091/planex
* Step 2. Select `Andromeda` from the team filters
![Screenshot 2024-11-25 at 15 11 11](https://github.com/user-attachments/assets/f387bfba-d9bc-4f62-aed3-9f2b34094ef7)

* Step 3. Click `Pay` from the `Total in and out` card
![Screenshot 2024-11-25 at 15 11 25](https://github.com/user-attachments/assets/bf24c71d-643c-4f08-9bbc-df821f553c62)

* Step 4. The `Payments` actions sidebar should open
![Screenshot 2024-11-25 at 15 12 39](https://github.com/user-attachments/assets/379c7f73-ac38-4ed7-af86-ce24bc1e5f1e)

* Step 5. Check for each individual action - `Simple`, `Advanced` and `Split` - that `Andromeda` is pre-filled
* Step 6. Now let's move to checking the actions sidebar triggered from the **navigation sidebar**
* Step 7. Click on `Make payment` and check for each individual action - `Simple`, `Advanced` and `Split` - that `Andromeda` is prefilled
![Screenshot 2024-11-26 at 15 08 39](https://github.com/user-attachments/assets/2e06fbd5-7a83-4f51-9c5f-9b9de68de184)

* Step 8. Click on `Manage colony` and check for the following actions that `Andromeda` is pre-filled: `Transfer funds`, `Edit a team`, `Manage reputation` and `Manage permissions`
![Screenshot 2024-11-26 at 15 06 12](https://github.com/user-attachments/assets/542e4dc2-46c3-4cfd-bf83-c4993402fdf1)
![Screenshot 2024-11-26 at 15 12 03](https://github.com/user-attachments/assets/41aec632-0d29-41bc-b397-8433bfa995d3)
![Screenshot 2024-11-26 at 15 12 11](https://github.com/user-attachments/assets/ec85fc45-2d8f-4473-a5d2-b26900c340f0)
![Screenshot 2024-11-26 at 15 12 19](https://github.com/user-attachments/assets/11ab15d4-81b3-4e3a-ab9e-d41dd8a08efb)
![Screenshot 2024-11-26 at 15 12 26](https://github.com/user-attachments/assets/d112cafc-774d-4991-99b4-9b72c7124f9b)

https://github.com/user-attachments/assets/69447a9b-b1aa-4b1d-9426-dc17a439fa1c

Resolves #3674

2024-11-25 20:34 UTC, rdig requested changes
Can't get this to work on my end, and I doing something wrong ?


https://github.com/user-attachments/assets/6f46c6ae-3900-4e86-8452-ec13d9866222

I also checked the commit to ensure I was running the latest

![Screenshot from 2024-11-25 22-33-28](https://github.com/user-attachments/assets/8750d6f6-cfbd-47b7-a9c3-12f8846ffabe)

2024-11-26 00:32 UTC, arrenv commented
@mmioana Yes, while the team filter is active, all actions with a team election should be prefilled with the filtered team.

2024-11-27 10:30 UTC, iamsamgibbs approved these changes
Very nice, great solution and works across the board.

https://github.com/user-attachments/assets/fdd32d14-046b-4406-9d62-4d9fbd750eb4

https://github.com/user-attachments/assets/e16e6fd8-6668-4198-a63b-30b2ad342fa1

2024-11-27 11:44 UTC, davecreaser approved these changes
Nice work @mmioana, all working as expected in all places mentioned in the testing steps.


https://github.com/user-attachments/assets/a8b641d8-0c60-45d1-92f6-5bb71ba3ba0f


https://github.com/user-attachments/assets/222c0bae-724c-4f2c-b815-f4574bdb88d0


https://github.com/user-attachments/assets/1469040c-c49f-41b6-882a-8a6c8054d02c

2024-11-28 09:33 UTC, rdig approved these changes

2024-11-28 09:35 UTC, merged