fix: long activity title overflow issue
JoinColony/colonyCDapp pull request #3773
Opened 2024-11-25 15:13 UTC by Nortsova

## Description
![image](https://github.com/user-attachments/assets/4b018249-5448-4777-8ce7-a5920303a0c5)

## Testing
Step 1. Create any motion with the title: `12312321312312312312312312312313123123123123412341234124312`
Step 2. Open Activity page
Step 3. Change the screen size to Mobile and check that the title is truncated 🎉 
<img width="412" alt="image" src="https://github.com/user-attachments/assets/e610632c-1058-4a04-ad3a-2fdbd5492746">

Resolves #3433

2024-11-26 09:53 UTC, iamsamgibbs reviewed
Thanks for the fix here! It does indeed truncate long words without spaces.

<img width="398" alt="Screenshot 2024-11-26 at 09 46 52" src="https://github.com/user-attachments/assets/58f34583-ac13-430f-bd00-ad5f15943b9c">

However, I'm not sure what is the expected behaviour for long titles which have spaces. On master they currently drop to a new line, and if they are still too long it will truncate at the end of the second line, like this:

<img width="379" alt="Screenshot 2024-11-26 at 09 51 36" src="https://github.com/user-attachments/assets/57b45457-d936-4f0f-9c45-888082d12dcc">

On this branch it gets truncated off on the first line (as shown in the first image).

Might just need some clarification on how we should expect these titles with spaces to look.

2024-11-27 10:33 UTC, davecreaser commented
Just to add some more spice to the mix here:

On master there's currently two different behaviours between desktop and mobile for the issue @iamsamgibbs raised (what should happen when there's spaces).

Desktop truncates on one line:
<img width="1308" alt="Screenshot 2024-11-27 at 10 26 49" src="https://github.com/user-attachments/assets/193d5cee-4916-40e5-89a8-1a1b9f9b480a">

Mobile truncates on two lines:
<img width="359" alt="Screenshot 2024-11-27 at 10 27 27" src="https://github.com/user-attachments/assets/aa565f98-bba8-4118-813a-a68c7c781f48">

In my opinion the way it's handled with this fix is the best solution, since then everything is aligned (all devices, and spaces / no spaces). It's also then aligned with the loading skeleton which shows only one line, and I think it works UX wise since this is really just an overview table and if you need to see the full title you can open the action. Having said all that, I agree that it's probably best to check with the design powers that be.

BUT since I like this solution, I'm going to approve it 🙃

2024-11-27 10:33 UTC, davecreaser approved these changes

2024-11-27 17:17 UTC, rdig approved these changes
The long title is now truncated on the activity list

![Screenshot from 2024-11-27 19-11-12](https://github.com/user-attachments/assets/35684d34-a07a-4c7f-90ae-e8419bdb94bb)

However, I still see on the action sidebar, after the action has been completed:

![Screenshot from 2024-11-27 19-10-51](https://github.com/user-attachments/assets/82cf40a4-59fc-4df0-8fc9-15ee28b16fd3)
![Screenshot from 2024-11-27 19-11-05](https://github.com/user-attachments/assets/766350e6-1a65-4ab6-a185-eb68c43f207a)

While I know it's not part of the PR, since it's a small change, I'd say you can do it in here.

Thanks

2024-11-27 17:17 UTC, rdig requested changes
Sorry, meant to reject the other review

2024-11-29 13:49 UTC, Nortsova commented
Thank you, guys, for the review, 🙌  I made an update:

The completed action title should be good now:
<img width="361" alt="image" src="https://github.com/user-attachments/assets/d158b387-1e54-455c-b9e3-33de68b0752a">

Two lines for activity feed 🎉 : 
<img width="351" alt="image" src="https://github.com/user-attachments/assets/0e7be5eb-05c1-4b94-b8a0-fce2cd7864d6">

2024-11-29 13:51 UTC, rdig approved these changes

2024-12-02 10:15 UTC, davecreaser approved these changes
All looking good @Nortsova 

Desktop:
<img width="751" alt="Screenshot 2024-12-02 at 10 14 09" src="https://github.com/user-attachments/assets/b05502bb-051f-4b17-9dd2-f69027c987d7">

Mobile:
<img width="358" alt="Screenshot 2024-12-02 at 10 14 22" src="https://github.com/user-attachments/assets/233a9640-1ba8-48ca-a86d-156ed97f0a0f">

Completed actions too!

2024-12-02 10:48 UTC, iamsamgibbs approved these changes
Amazing, great job making these changes.

<img width="1096" alt="Screenshot 2024-12-02 at 10 47 38" src="https://github.com/user-attachments/assets/25bdafc3-3b56-433d-a177-8397d55cba59">

<img width="428" alt="Screenshot 2024-12-02 at 10 48 00" src="https://github.com/user-attachments/assets/e1c85b62-1e14-46be-9aea-0ffd13c46fcc">

2024-12-04 09:53 UTC, merged