Fix: Gracefully close the saved draft agreement form
JoinColony/colonyCDapp pull request #3834
Opened 2024-12-03 16:42 UTC by rumzledz

## Description

Current behaviour is when you save a draft agreement and you click outside the form, then the form closes without prompting you. The problem is that when you click the close button of the form then it will still show you the "Do you wish to cancel the action creation" modal. So this PR just aligns the behaviour between clicking outside the form component and clicking the close form button.

![agreement-form](https://github.com/user-attachments/assets/b979b934-6f70-4b95-9b74-7664ecbb53c7)

## Testing

1. Install the Reputation extension
2. Set the viewport to mobile
3. Bring up the Create agreement form
4. Fill in all required fields
5. Click the close button

<img width="621" alt="Screenshot 2024-12-04 at 00 41 14" src="https://github.com/user-attachments/assets/e2feece9-a3e5-4f5d-9b8c-259cc96f210c">

6. Verify that the "Do you wish to cancel the action creation" modal is shown
7. Click the Save draft button
8. Click the close button
9. Verify that the form just closes

Resolves #2933

2024-12-04 12:09 UTC, davecreaser approved these changes
Nice work @rumzledz, looks good to me! Neat little refactor too with the hook etc.

Tested both mobile and desktop:
https://github.com/user-attachments/assets/857bcf08-1a82-45d7-8b39-b2ef96df2926


https://github.com/user-attachments/assets/73253c3b-4938-4c4c-b384-5855b31c4e8b

2024-12-05 10:06 UTC, iamsamgibbs requested changes
This does work as expected when following the testing steps:

https://github.com/user-attachments/assets/a29780b9-c8fd-40a4-9a4d-6dbfadc3ef52

However, if you make a save, then make some changes, the close modal doesn't show (seems the isDirty check isn't working as expected?)

https://github.com/user-attachments/assets/c2cc8620-a3ab-44d0-8e36-2f8c4659e49a

2024-12-05 10:14 UTC, bassgeta approved these changes
Not gonna lie, our `ActionForm` is getting so absurdly complex and filled with proprietary logic, we definitely should rethink how it's structured.
It needs to check permissions, multisig permissions, now if it's a draft agreement too :melting_face: 
But nonetheless, a pretty straightforward solution given how complex everything is :100: 
![image](https://github.com/user-attachments/assets/67f54550-2d88-487e-9eb1-8e4a8b804a3c)
![image](https://github.com/user-attachments/assets/63c65aee-97bb-4862-907d-57b98e557dd2)
Saving the draft beforehand:
![image](https://github.com/user-attachments/assets/ba62ba47-7ece-426d-9c74-eb32fc6509ff)
just closes it :heavy_check_mark: 

:ship:

2024-12-09 11:09 UTC, mmioana approved these changes
Nice work figuring your way through all this components and hooks @rumzledz 🥇 

It works as expected 🙌 

https://github.com/user-attachments/assets/03cb71db-9d7a-4132-892b-2480ea6fc77a

2024-12-13 10:01 UTC, mmioana approved these changes
All good @rumzledz, the modal no longer shows after the draft is being saved 🥇 


https://github.com/user-attachments/assets/0b84e7a4-665e-4c13-aaec-545f8989bb02


https://github.com/user-attachments/assets/f717c0bf-a6ff-484e-af56-dfcaa38f15b8

2024-12-13 14:25 UTC, iamsamgibbs approved these changes
All still working as intended!

![Screenshot 2024-12-13 at 14 24 51](https://github.com/user-attachments/assets/1d30e1a4-c4c9-4007-8e9c-51357dcb1e82)

2025-01-17 14:04 UTC, davecreaser approved these changes
Still all looking good and working well @rumzledz!

Modal is shown:
<img width="439" alt="Screenshot 2025-01-17 at 14 01 27" src="https://github.com/user-attachments/assets/c57109ba-1a8a-4ea3-a08a-6ac4cb60635e" />

And after saving the draft the modal isn't shown. Nice work 👍

2025-01-17 14:25 UTC, merged