Fix: Do not overscroll the Teams filter
JoinColony/colonyCDapp pull request #3951
Opened 2024-12-16 15:21 UTC by rumzledz

## Description

The left scroll's distance multiplier was somehow causing the team filter to shift way beyond the boundaries so I set it to match the right scroll's distance multiplier, `0.5`.

| Before | After |
| ---- | ---- |
| ![team-filter-scroll-bug](https://github.com/user-attachments/assets/7fa86a75-2e5c-4bd5-8796-8b6e7804b7cd) | ![team-filter-scroll-fix](https://github.com/user-attachments/assets/6f779f6c-bafc-450b-aa1b-39eaf269e3b9) |

## Testing

> [!NOTE]
> I don't know any other way for anyone to test this apart from doing this in a Simulator.

1. Open the app on an iOS simulator
2. Go to the Planex colony dashboard
3. Click the right arrow for the Teams filter
4. Click the left arrow for the Teams filter
5. Verify that the Team filter is not overly scrolled to the point that there is an empty space to its left
6. To compare, simply checkout to the `master` branch and redo steps 2 to 4

Resolves #3540

2024-12-16 19:35 UTC, bassgeta approved these changes
Hahahah I am sorry for this <3 
But thanks for the simple fix, nice one :sunglasses: 
Tried scrolling, dragging, everything seems to work as intended :ok_hand: 

https://github.com/user-attachments/assets/f33641e9-be62-43ea-bf4d-c57c43318433

2024-12-16 22:58 UTC, Nortsova approved these changes
Nice catch, @rumzledz 😄

![mobile-filter](https://github.com/user-attachments/assets/e2e6183b-d17c-4453-be80-3ee4ae7c4183)

2024-12-18 21:43 UTC, mmioana requested changes
Nice start on this issue @rumzledz 🙌 

However, I still experience some issues if I select `Andromeda` for eg. and then try to scroll left

https://github.com/user-attachments/assets/f51864ea-ccfb-46d3-aaa6-93d2f87e091d

I'm leaving my thoughts on how we should maybe refactor the `scrollLeft` and possibly also the `scrollRight` functions to properly work

For `scrollLeft`, we need to ensure the scroll value stays within the available scrollable space. Since `-clientWidth * 0.5` could exceed the remaining scrollable space, we should first calculate the remaining space. If the remaining space is smaller than `clientWidth * 0.5`, we use the remaining space as the scroll offset instead of scrolling by half the width of the container.

Thus this should do the trick
```
const scrollLeft = () => {
    if (!containerRef.current) {
      return;
    }

    const { clientWidth, scrollLeft: currentScrollLeft } = containerRef.current;
    const boundedScrollLeft = Math.min(clientWidth * 0.5, currentScrollLeft);
    containerRef?.current.scrollBy({
      left: -boundedScrollLeft,
      behavior: 'smooth',
    });
  };
```

Pretty similar logic also for the `scrollRight` - which I know is not intended in this PR, but I did notice the right overscroll

```
const scrollRight = () => {
    if (!containerRef.current) {
      return;
    }

    const {
      clientWidth,
      scrollLeft: currentScrollLeft,
      scrollWidth,
    } = containerRef.current;
    const remainingScroll = scrollWidth - currentScrollLeft - clientWidth;
    const boundedScrollLeft = Math.min(clientWidth * 0.5, remainingScroll);
    containerRef?.current.scrollBy({
      left: boundedScrollLeft,
      behavior: 'smooth',
    });
  };
```

🙌

2025-01-07 13:03 UTC, mmioana approved these changes
Thanks for the changes @rumzledz 🥇 I'll approve given I've already tested them 💯

2025-01-07 14:35 UTC, bassgeta approved these changes
Another day, another dollar
Another year, another overscroll issue solved :sunglasses: 

https://github.com/user-attachments/assets/a99f2a3f-bf38-42ad-bbc7-39411265aabd

:ship:

2025-01-09 14:18 UTC, iamsamgibbs approved these changes
Perfect! All working very nicely.

https://github.com/user-attachments/assets/ed17be64-25a1-415b-90e4-eb322ceca8d8

2025-01-09 19:14 UTC, merged