test: split payment e2e tests
JoinColony/colonyCDapp pull request #3994
Opened 2024-12-19 23:16 UTC by olgapod

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2025-01-21 12:42 UTC, iamsamgibbs approved these changes
Nice job setting this all up! Tests are passing no problem. I think there is room for further tests here, the reputation distribution method is unused for example, and confirming the form returns the correct values for equal distribution etc.

![Screenshot 2025-01-21 at 12 41 59](https://github.com/user-attachments/assets/4b7c068d-4bbb-46bb-ad34-0ae454a956d0)

2025-01-21 12:44 UTC, iamsamgibbs requested changes
Actually, my comment about being curious actually needs addressing I think. By manually updating the amounts and percentages it forcibly changes the distribution type to "Unequal"

![Screenshot 2025-01-21 at 12 43 26](https://github.com/user-attachments/assets/75255e95-7a67-4465-b4d1-a37ef008b16c)

2025-01-22 10:21 UTC, olgapod commented on playwright/e2e/split-payment.spec.ts
> +      ],
Yes, it does calculate the amount and percentage fields automatically in that case (thanks for bringing this up, I've added a test case for that). But,  If you start manually filling in the table then the Distribution is set to Unequal, and this is expected behavior (I've double-checked with Arren)

2025-01-27 09:17 UTC, iamsamgibbs approved these changes
Discussed this with @olgapod and didn't realise that the equal checks are only done before submitting, so makes sense why the resulting action shows as unequal.

2025-01-27 16:17 UTC, mmioana approved these changes
A lot of work to now have some cool tests for the `Split payment` action 🎉 really nicely done @olgapod!

The tests have passed for me, but only after setting back the timeout to `9000` in `playwright.config.ts`

<img width="1114" alt="Screenshot 2025-01-27 at 17 09 14" src="https://github.com/user-attachments/assets/350dbca5-7baf-4ad1-b528-075269d106bf" />

I will approve your PR nonetheless!

2025-01-27 16:17 UTC, mmioana commented on playwright/e2e/manage-account-profile.spec.ts
> +    await page
@olgapod would it make sense to refactor the code from lines `13-23` into an utility function, given this piece is repeating across all the manage account e2e tests?

2025-01-29 07:53 UTC, olgapod commented on playwright/e2e/manage-account-profile.spec.ts
> +    await page
I will add this refactoring  in the following PR

2025-01-29 07:54 UTC, merged