Feat/landing page
JoinColony/colonyCDapp pull request #4001
Opened 2024-12-20 14:32 UTC by adam-strzelec

## Description

Create Landing Page with all subpages

## Testing

- Open landing page as not connected user:

![Screenshot 2024-11-05 at 13 37 54](https://github.com/user-attachments/assets/ffdca734-7160-41c2-9619-3908eb0ff5a1)

- Open landing page as connected user with access:

![Screenshot 2024-11-05 at 14 20 40](https://github.com/user-attachments/assets/bc5491b0-5e58-4790-baa9-bfb9018e7389)
![Screenshot 2024-11-05 at 14 33 38](https://github.com/user-attachments/assets/2f30bc58-0e39-4477-b379-d05a8c982a54)

- Open landing page as connected user without access:

![Screenshot 2024-11-05 at 13 37 32](https://github.com/user-attachments/assets/28e70ae2-97d5-4b44-b337-146c4a80ae1e)

### Invite page

- generate invite code and open invite page

<img width="1722" alt="Screenshot 2024-11-13 at 15 35 33" src="https://github.com/user-attachments/assets/a81a101f-75ff-419c-a22f-a0ed6c82c629">

<img width="1720" alt="Screenshot 2024-11-13 at 15 35 52" src="https://github.com/user-attachments/assets/e6a5b8b9-2fea-4947-abc6-eddf9b35abe6">

### Go page

- Open `/go` page

<img width="1720" alt="Screenshot 2024-11-13 at 15 36 25" src="https://github.com/user-attachments/assets/3e9f8f61-42d2-4833-b3ef-43be7c73f16e">

### Invite to colony flow:

https://github.com/user-attachments/assets/11343718-e6e2-4325-b2f0-06b271bd375d

### invite to create colony flow

https://github.com/user-attachments/assets/fdef2e9f-6b0b-4591-8652-1fc969cd5eee

## Diffs

**New stuff** ✨

- Add new layout for landing page
- Implement new components for landing page
- Connect existing logic
- Add new logic for Members count
- Implement new invite page
- Implement new Go page

Main issues https://github.com/JoinColony/colonyCDapp/issues/3392 https://github.com/JoinColony/colonyCDapp/issues/3895 https://github.com/JoinColony/colonyCDapp/issues/3894

2024-12-27 12:27 UTC, mmioana requested changes
Really nice work on this @adam-strzelec 💯 

I've followed your testing steps and we're almost there. I'll leave the 2 small issues at the bottom of the review.

Accessing the landing page with no wallet connected ✅

https://github.com/user-attachments/assets/919379db-2a52-46a7-bcff-c2d1ecd5ff5c

![Screenshot 2024-12-27 at 12 30 07](https://github.com/user-attachments/assets/498e28ba-e550-4335-b7e5-0c434b02c0ef)

With connected wallet and access ✅

![Screenshot 2024-12-27 at 12 54 57](https://github.com/user-attachments/assets/095f3be2-f695-40ca-9fda-69295e2e17db)
![Screenshot 2024-12-27 at 12 56 05](https://github.com/user-attachments/assets/7a066d6a-6080-4efd-84fb-ef5bead2a2f4)

Landing page with connected wallet but no access ✅
![Screenshot 2024-12-27 at 12 57 05](https://github.com/user-attachments/assets/f90f15df-480e-41c8-8bb0-ba3881b49291)

Invitation page ✅
![Screenshot 2024-12-27 at 12 59 38](https://github.com/user-attachments/assets/1ec09577-903e-4daf-8d40-6689830f12d1)
![Screenshot 2024-12-27 at 12 59 49](https://github.com/user-attachments/assets/62ed5f68-8f45-4777-a1c3-92848a07062c)

Opened `/go` page ✅
![Screenshot 2024-12-27 at 13 00 21](https://github.com/user-attachments/assets/09ddf311-63b1-428c-8489-e38b114a19f3)

Invite flow ✅

https://github.com/user-attachments/assets/b8f49d39-7104-4cce-a9cd-102c78320fe5

Create colony flow ✅ 

https://github.com/user-attachments/assets/ad80c2af-27a5-49aa-a287-ded1b58201fa


### Issues
1. If you set the screen width between `920px`-`1024px` on the landing page with no wallet connected, the copy text is no longer visible. Maybe we should set a max-height?
However this should not be a blocker from merging this PR 👍 
![Screenshot 2024-12-27 at 12 30 49](https://github.com/user-attachments/assets/a0b7a0be-d483-4d61-94fd-0a6d7c7c9c84)
2. However, the 2nd issue is related to having the feedback popover being hidden behind the call to action and this would be nice to be fixed in this PR

https://github.com/user-attachments/assets/11c9f1af-62ec-4506-86c1-4d1f78559eaf

Also I left a couple of refactoring comments, if you can please tackle them 🙌 
Either way really nice work on this one 🎉

2024-12-27 12:27 UTC, mmioana commented on src/components/frame/v5/pages/ColonyPreviewPage/ColonyPreviewPage.tsx
> +          )}
Can we extract this into a constant for eg.
```
const actions = !wallet ? (
    <Button isFullSize onClick={connectWallet}>
      {formatText(MSG.connectWalletButton)}
    </Button>
  ) : (
    <>
      {inviteIsValid && (
        <Button isFullSize onClick={validateInviteCode}>
          {formatText(MSG.joinColonyButton)}
        </Button>
      )}
      {inviteIsInvalid && (
        <a href={REQUEST_ACCESS} target="_blank" rel="noreferrer">
          <Button isFullSize>{formatText(MSG.requestAccessButton)}</Button>
        </a>
      )}
    </>
  ); 
```
and use it here 
```
<LandingPageLayout
      bottomComponent={
        <div className="w-full px-6 pb-6 md:hidden">{actions}</div>
      }
    >
```

2024-12-27 12:27 UTC, mmioana commented on src/components/frame/v5/pages/ColonyPreviewPage/ColonyPreviewPage.tsx
>            </div>
And then we can also use it here 
`<div className="hidden w-full md:block">{actions}</div>`

2024-12-27 12:27 UTC, mmioana commented on src/components/frame/Extensions/layouts/LandingPageLayout.tsx
Very nice work on creating this component @adam-strzelec 🙌 
How ever I'm thinking if it wouldn't make sense to have a clear separation between the 2 types of layout we support as it will make the code easier to follow. What do you think?

2024-12-31 11:21 UTC, adam-strzelec commented on src/components/frame/Extensions/layouts/LandingPageLayout.tsx
@mmioana Do you mean separating the layout into a connected and disconnected wallet?

2025-01-02 13:36 UTC, davecreaser requested changes
Really nice work here @adam-strzelec, the page is looking great and the code nicely done too overall, thank you!

I've left a couple of small comments in the code to address, mostly just covering lint warnings and some small code cleanup things.

Also during my testing I uncovered a couple of minor issues which should be looked into.

The first one is that on this page, it looks like the vertical alignment of the left hand side is off. It is different also from the screenshot that you posted in the testing steps, is it supposed to be centre aligned?
<img width="2557" alt="Screenshot 2025-01-02 at 13 01 41 - weird vertical alignment" src="https://github.com/user-attachments/assets/17c250d8-a70b-4e59-b752-76582f94c6a3" />

The second one is on this page. The issue is with the text where it says `Connect your wallet below to join the colony`. I find this wording strange since it is shown when my wallet is already connected. It should instead say something along the lines of `click the button below to join the colony`.
<img width="2557" alt="Screenshot 2025-01-02 at 13 09 59 - awkward text connect your wallet (already connected)" src="https://github.com/user-attachments/assets/fbcd7ec0-fb11-4790-a9dc-5b4e01a42dee" />

All the other testing I did worked well though, here's some screenshots and recordings from it for reference:


https://github.com/user-attachments/assets/896fa8f7-668f-4b45-9ee1-cf84409e094f


https://github.com/user-attachments/assets/24d85dd7-e85f-4060-8b13-57741a8d6c58

<img width="2557" alt="Screenshot 2025-01-02 at 13 01 09" src="https://github.com/user-attachments/assets/2a75e222-8b1b-4b00-9b0c-c42e50920939" />
<img width="2557" alt="Screenshot 2025-01-02 at 13 01 42" src="https://github.com/user-attachments/assets/e299f285-b082-464e-8776-49c52e196f00" />
<img width="2557" alt="Screenshot 2025-01-02 at 13 09 01" src="https://github.com/user-attachments/assets/1b6d06b6-943b-403d-9e13-ab793c25a338" />
<img width="2557" alt="Screenshot 2025-01-02 at 13 16 29" src="https://github.com/user-attachments/assets/5cfd24eb-7edd-41b1-8559-9e33b7818b33" />

2025-01-02 13:36 UTC, davecreaser commented on src/components/common/Extensions/ImageCarousel/ImageCarousel.tsx
> +  }, [selectedIndex]);
Can we add `setSelectedIndex` to the dependency array here to fix the warning?

2025-01-02 13:36 UTC, davecreaser commented on src/components/common/Extensions/ImageCarousel/hooks.ts
> +    [emblaApi?.plugins().autoplay],
Would be great to also resolve these warnings 🧹

2025-01-02 13:36 UTC, davecreaser commented on src/components/common/Extensions/ImageCarousel/hooks.ts
> +export const useEmblaCarouselSettings = (options, autoplay) => {
Could we add some types to these function parameters please?

2025-01-02 13:36 UTC, davecreaser commented on src/components/frame/LandingPage/partials/ShareInvitationButton/ShareInvitationButton.tsx
> +  ) : null;
Instead of having a component which potentially renders nothing and has no logic depending on a prop, I think it's better to just always render the contents inside this component and remove the prop entirely, but in the parent component just check `hasShareableInvitationCode` and render this component conditionally.

So instead of:
```ts
<ShareInvitationButton hasShareableInvitationCode={hasShareableInvitationCode} onCreateColony={onCreateColony} />
```

you would have:
```ts
{hasShareableInvitationCode &&
<ShareInvitationButton onCreateColony={onCreateColony} />
}
```

In the parent component. I think it's better because it avoids rendering a component which can potentially have zero impact (in fact, a negative impact overall performance wise).

2025-01-03 09:06 UTC, adam-strzelec commented
@davecreaser I already improved code.
The list on designs, is also positioned on top of the screen. What in case if i have `Create new Colony` button visible?
<img width="767" alt="Screenshot 2024-12-16 at 12 49 58" src="https://github.com/user-attachments/assets/8d37f0f4-0c3f-4cca-9829-989f4d538118" />

`Connect your wallet below to join the colony` is on designs. Maybe we should ask the designer what exactly copy should be?

2025-01-03 09:59 UTC, davecreaser commented
Thanks for the quick changes @adam-strzelec!

Ah, I didn't realise it was like that in the design, I should've checked that first, my bad!

@melyndav if you get a chance, maybe you could have a quick look at those two things? First being whether the left hand side of the screen with the colony list looks okay as is (I assume yes since it follows the design), and second whether my suggestion for the copy change should go ahead.

Since it's all following designs though and the code changes you made are good, I'm happy to approve. Nice one @adam-strzelec!

2025-01-03 10:00 UTC, davecreaser submitted a review, later dismissed

2025-01-03 10:14 UTC, melyndav commented
Hey @adam-strzelec @davecreaser the correct text is here for the connected state

**Desktop:** https://www.figma.com/design/j0VEfFryOkmjrVVq2PItso/Landing-page-%2B-Beta-Launch?node-id=17073-59822&t=aKDM0JFeY6Lxd6og-4 

**Mobile:** https://www.figma.com/design/j0VEfFryOkmjrVVq2PItso/Landing-page-%2B-Beta-Launch?node-id=16638-16649&t=aKDM0JFeY6Lxd6og-4

**Main component:** https://www.figma.com/design/j0VEfFryOkmjrVVq2PItso/Landing-page-%2B-Beta-Launch?node-id=17720-22596&t=aKDM0JFeY6Lxd6og-4

2025-01-03 11:36 UTC, melyndav requested changes
Hey @adam-strzelec 

Great work on this big PR. A lot of work has been put into this, so thank you for your effort!

After reviewing @davecreaser screenshots during his testing, I've picked up some issues that need addressing to help align it closer to Figma and was intended. 


 **1. The right side panel content shouldn't float in the centre** 

As Per Figma, the content was specifically positioned to have top padding and the slider navigation to be positioned towards the bottom of the browser, as you can see here in this example when a wallet is not connected.

<img width="646" alt="image" src="https://github.com/user-attachments/assets/981c98eb-7137-480d-975b-0e28ab39aa1c" />

When a wallet is connected, the content **should remain** in the same position and not change where the slider navigation is not shown.

<img width="669" alt="image" src="https://github.com/user-attachments/assets/4eb72a3f-3c16-4f03-8215-79eea3683256" />

**2. In Figma in both the disconnected and connect states, the padding on the left side of this right panel should be 100px to match the left side. Currently, the two paddings are different.** 

Figma paddings for each panel:

Right panel:
<img width="371" alt="image" src="https://github.com/user-attachments/assets/092d6f93-b9d4-433a-885f-7953d861b811" />

Left panel:
<img width="140" alt="image" src="https://github.com/user-attachments/assets/99a1ef28-0563-45fc-b7e1-5ce02ab0b922" />


**3. Once a wallet is connected, can we please fix the height of the 'Explore your colonies' heading to the right side panel as shown here with the red line in Figma:**

<img width="1284" alt="image" src="https://github.com/user-attachments/assets/a78c1ffe-2ff3-40ae-a0ca-7aa6e73b8c69" />

This means that the list of joined colonies will increase down the page, but the content will remain fixed to the top.

<img width="1363" alt="image" src="https://github.com/user-attachments/assets/e5efc684-c915-49b2-9eb5-1de428b8c69b" />

When the list exceeds 5 colonies or the verticle height is reduced, scrollbar is triggered, the main CTA button should remain visible on the page. No changes to mobile. 

Note, this will change the skeleton state positioning: https://www.figma.com/design/j0VEfFryOkmjrVVq2PItso/Landing-page-%2B-Beta-Launch?node-id=17073-75135&t=aKDM0JFeY6Lxd6og-4

**4. Please add drop shadows to the two cards that are shown on the right panel in the connected state.**

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/066e3bfd-60f7-4cfd-bd10-d97f29e5ccbd" />


**5. On mobile, the icons are not aligned to the top in the promo call out cards:** 
![image](https://github.com/user-attachments/assets/5dff2ff1-ce46-429c-9e9b-a2e534a57d1b)


**6. I had a new user with 0 invites available to create a colony. I then used an invite code with 12 invites, then created a colony successfulyl. However, when I returned to the landing page to create a Colony. It showed I had '0 invited remaining'. I had to reload the page, and then it correctly showed 11 remaining. Can this value be updated with reloading?** 

![image](https://github.com/user-attachments/assets/00d83ccf-ad3c-4da0-a1ed-71854134f1ad)


**7. On mobile, there is no padding at the bottom of the content across all connected and disconnected states, the content gets lost behind the CTA.** 

![image](https://github.com/user-attachments/assets/f11f9823-1750-43ee-a10a-4ba56ecb5c1c)


---

**In addition to the above feedback** - can we update the hover state for the individual colonies card? They now should retain the gray-200 border, but have a gray-25 background upon hover.

Figma component: https://www.figma.com/design/j0VEfFryOkmjrVVq2PItso/Landing-page-%2B-Beta-Launch?node-id=16596-34186&t=aKDM0JFeY6Lxd6og-4

https://www.figma.com/design/j0VEfFryOkmjrVVq2PItso/Landing-page-%2B-Beta-Launch?node-id=17183-5015&t=aKDM0JFeY6Lxd6og-4 

Link to the design: https://www.figma.com/design/j0VEfFryOkmjrVVq2PItso/Landing-page-%2B-Beta-Launch?node-id=17073-60889&t=aKDM0JFeY6Lxd6og-4

2025-01-03 16:51 UTC, adam-strzelec commented
@melyndav done. Regarding 6 point i have no idea why on your device `remaining colonies` is not displaying properly. On my device everything works perfect.

2025-01-07 16:50 UTC, melyndav requested changes
Hey @adam-strzelec,

Appreciate all your effort on the requested updates. 🙌 A few more minor fixes are needed. 

**1. The drop shadows behind the right side images don't match Figma. Please check all images to ensure they are correct and consistent. Please check all images on mobile as well as some are missing shadows.** 

Figma values:

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/1bc71d1d-6403-45f0-b727-d82cce2389e2" />

Currently:
![image](https://github.com/user-attachments/assets/b7c53787-dd96-4f2d-ac9d-cec09a981852)

**2. The main content container should have a left and right padding of 24px matching Figma and also match this top header section. This is causing the icons in the invite call out boxes to not align to the content.** 

Figma:
<img width="289" alt="image" src="https://github.com/user-attachments/assets/76e2ee8f-f286-49af-ace5-df1034a58593" />

Currently at the top:
![image](https://github.com/user-attachments/assets/da2f2396-e445-486e-a03e-c6443376f900)

What it is below:
![image](https://github.com/user-attachments/assets/af0e8d34-b3c7-4dbb-9cc1-9f5fec7d835e)

**3. Can we position the scrollbar in the following screenshot away from the cards so it does not overlap UI elements?**

![image](https://github.com/user-attachments/assets/7772960d-c295-49a1-bf08-111ebf2c52fd)

**4. Can we increase the whole height of the 'Explore your colonies' container so there is a preview of the 6th colony card like the screenshot below?**

![image](https://github.com/user-attachments/assets/c26d9589-7dbe-48ae-93b7-9c1906733877)

**5. Due to the image in the slider loading, you get a flash of a broken UI when the page is loading or disconnecting your wallet. Can we have the slider fixed so it doesn't result in a broken layout during load?**

![image](https://github.com/user-attachments/assets/2d16aef1-453d-477c-aa74-e85cd73ec1f7)

2025-01-09 10:56 UTC, melyndav requested changes
Hey @adam-strzelec!

Another round of great updates, thanks again for your continued work on this. 

Just one minor feedback and then I think we're good to MERGE! :)  

1. On mobile, the gray background behind the top image is missing. And the image is missing the drop shadow as per Figma:

<img width="857" alt="image" src="https://github.com/user-attachments/assets/286cc379-dd48-4dc8-93bd-0391df0e2f70" />

Currently, with the missing gray background and missing drop shadow:

https://media.discordapp.net/attachments/822372628525744178/1326865164300976188/image.png?ex=6780fafb&is=677fa97b&hm=4c99ce23c78d4f1c98ff3f4f9a8296168de6bef74843e3d3933fd34bc719eb28&=&format=webp&quality=lossless&width=814&height=1366

2025-01-09 10:57 UTC, arrenv approved these changes
@adam-strzelec Everything is looking and working great from everything I tested, nice work! A minor UI element from @melyndav, otherwise, I am approving.

2025-01-10 11:01 UTC, adam-strzelec commented
@melyndav done

2025-01-10 11:17 UTC, melyndav approved these changes
Hey @adam-strzelec thanks for the final update on this, everything is looking correct on mobile with the gray background and dropshadow. Thanks again for all your effort on this one, let's get this MERGED! 

![image](https://github.com/user-attachments/assets/6b0c9fce-2a69-4c24-ae01-c0c728b57634)

2025-01-10 11:17 UTC, arrenv submitted a review, later dismissed
Thank you @adam-strzelec, I can see the background added in now and everything else looks good.

2025-01-10 13:30 UTC, adam-strzelec commented
@mmioana @davecreaser I need your approval to merge it 🙂

2025-01-10 14:26 UTC, davecreaser commented
@adam-strzelec Reviewing now! I'll get back to you asap :)

2025-01-10 15:00 UTC, davecreaser submitted a review, later dismissed
Nice work @adam-strzelec 🎉 

I'm happy with all the changes since my last approval, and after retesting the basic flows (mobile too) everything looks good from my end.

Let's merge!

<img width="2557" alt="Screenshot 2025-01-10 at 14 53 12" src="https://github.com/user-attachments/assets/33f99c7e-5b08-4282-a228-1f1763535973" />
<img width="2557" alt="Screenshot 2025-01-10 at 14 54 40" src="https://github.com/user-attachments/assets/ece326ba-700c-432e-9000-5604ea3968f3" />
<img width="2557" alt="Screenshot 2025-01-10 at 14 54 59" src="https://github.com/user-attachments/assets/cafc5a16-dac1-41fe-8f39-f5625ee61258" />
<img width="2557" alt="Screenshot 2025-01-10 at 14 56 14" src="https://github.com/user-attachments/assets/c07de016-c6c6-45e0-9f99-e67fb9a25404" />
<img width="2557" alt="Screenshot 2025-01-10 at 14 56 23" src="https://github.com/user-attachments/assets/148ff555-5003-4398-a104-58a3a536b4a1" />
<img width="2557" alt="Screenshot 2025-01-10 at 14 57 14" src="https://github.com/user-attachments/assets/edbdbd19-d887-499f-8d58-417356718cb5" />
<img width="2557" alt="Screenshot 2025-01-10 at 14 57 25" src="https://github.com/user-attachments/assets/8eb55897-d724-4bd2-8ec1-b760a7f3dcff" />

2025-01-10 15:09 UTC, adam-strzelec commented
@mmioana I need only your approval to merge it 🙃

2025-01-13 08:11 UTC, mmioana submitted a review, later dismissed
Thank you for all the changes @adam-strzelec! 

Looks good from my side, so let's merge it 🎉 

![Screenshot 2025-01-13 at 09 07 44](https://github.com/user-attachments/assets/091317b8-9838-4af5-a379-4077a2863bab)
![Screenshot 2025-01-13 at 09 08 06](https://github.com/user-attachments/assets/e6fa8052-587c-4b49-9613-5a07d9c42d88)
![Screenshot 2025-01-13 at 09 09 15](https://github.com/user-attachments/assets/defbb270-726b-4bdc-9db0-2e17f845db41)
![Screenshot 2025-01-13 at 09 10 18](https://github.com/user-attachments/assets/332cb317-c594-4369-b667-464bdb17d457)

![Screenshot 2025-01-13 at 09 09 42](https://github.com/user-attachments/assets/bcdec354-040b-4d08-b756-c375d5a86f8f)
![Screenshot 2025-01-13 at 09 09 54](https://github.com/user-attachments/assets/5444d364-f7c2-459a-80e6-fb45a6ef4420)
![Screenshot 2025-01-13 at 09 10 01](https://github.com/user-attachments/assets/3e269f58-fd46-4ac2-87f7-dbe43f143e6f)
![Screenshot 2025-01-13 at 09 10 13](https://github.com/user-attachments/assets/40924b63-8529-46cd-88d6-6a9da1214dd7)

2025-01-13 09:09 UTC, adam-strzelec commented
@arrenv @mmioana @davecreaser I had to fix one issue related to eslint, because the pipeline was broken and I was not able to merge the PR. Can I ask you one more time for approval? 😅

2025-01-13 09:14 UTC, arrenv approved these changes
@adam-strzelec Quick test, all looks good, thank you!

2025-01-13 09:41 UTC, melyndav approved these changes
@adam-strzelec all good from my end after a quick UI sanity check. Thanks again for your work!

2025-01-13 09:42 UTC, mmioana approved these changes

2025-01-13 09:58 UTC, merged

2025-01-13 10:13 UTC, melyndav commented
Yesss @adam-strzelec finally merged! Nice work on this!! 💯