Feat: Add manage supported chain action
JoinColony/colonyCDapp pull request #4006
Opened 2024-12-23 19:45 UTC by mmioana

Feat: Add manage supported chain action

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2025-01-07 13:39 UTC, bassgeta requested changes
Holy moly, this is an absolutely huge amount of work, and during the holidays to top it off. Seems like Santa brought managing supported chains via UI as a present :christmas_tree: 
Commendable code, everything reads quite nicely and makes sense, no head scratching while checking it :D 

1. Manage supported chains shows up in the sidebar :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/a574439e-a6e8-4a3e-be57-cb68e77b8c9a)
2. The form has a bug due to `SearchSelect` and how it works... we need to disable it, I've managed to just add this to `ChainSelect` line 94 and it works
![image](https://github.com/user-attachments/assets/ac549a35-5662-4226-87f8-bc528867701d)

https://github.com/user-attachments/assets/43ce0948-da67-40ae-a689-c16618891458

Nonetheless, next!
3. The form works, submits and the completed action is rendered :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/0a422aa0-6896-4eb4-8838-ec27fab45b4c)
![image](https://github.com/user-attachments/assets/533351df-042f-443d-8be0-429615bd8a9c)
4. Redoing works and Ethereum isn't in the dropdown anymore :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/fba5c391-8fd3-4225-b8a4-5d863135ca12)
![image](https://github.com/user-attachments/assets/314e9a05-5534-45c7-a99e-bba18d878a61)
5. Removing Ethereum works like a charm too :heavy_check_mark: (note that this form has the same bug as above)
![image](https://github.com/user-attachments/assets/af27a4ba-c2e0-48ae-aa8d-056166f7f1af)
![image](https://github.com/user-attachments/assets/b897e59a-15f4-4888-909c-78353611a80a)

2025-01-07 13:39 UTC, bassgeta commented on src/components/v5/common/ActionSidebar/partials/hooks.ts
> +    return selectedAction && SUBMIT_BUTTON_TEXT_MAP[selectedAction];
since this is the only action which clearly discerns between `Add` and `Remove` instead of just doing `Submit`, should we keep it the same way here?
and maybe down the line make it work for other actions too

2025-01-07 13:39 UTC, bassgeta commented on src/components/v5/frame/ColonyHome/ColonyHome.tsx
> -      <TmpProxyColonyDeploy />
rip `TmpProxyColonyDeploy` you have been a great one :saluting_face:

2025-01-07 13:39 UTC, bassgeta commented on src/redux/sagas/proxyColonies/disableProxyColony.ts
> +    console.log('PROXY COLONY DISABLE TXHASH', txHash, customActionTitle);
can we remove this one :eye:

2025-01-08 17:22 UTC, mmioana commented on src/components/v5/common/ActionSidebar/partials/hooks.ts
> +    return selectedAction && SUBMIT_BUTTON_TEXT_MAP[selectedAction];
If you don't feel strongly against it, I would propose to leave this given that we know we want to differentiate between the action submit button text

2025-01-08 17:22 UTC, mmioana commented on src/redux/sagas/proxyColonies/disableProxyColony.ts
> +    console.log('PROXY COLONY DISABLE TXHASH', txHash, customActionTitle);
Done 🚀

2025-01-08 17:25 UTC, mmioana commented
@bassgeta regarding 
`The form has a bug due to SearchSelect and how it works... we need to disable it, I've managed to just add this to ChainSelect line 94 and it works` I have fixed it in #4008 by adding `showSearchValueAsOption` flag so we explicitly set where we want to use the search value as a fallback

https://github.com/JoinColony/colonyCDapp/pull/4008/commits/f9b1b69e11a55fec03fb8d493d2e251cc57a64be

Also noticed this was a problem occurring for the `Teams` select in the `Edit domain` action

2025-01-09 08:58 UTC, bassgeta approved these changes
Approving since that search select thing is a form bug present on `master` too :ok_hand:

2025-01-13 22:04 UTC, rdig requested changes
Besides the feature flag, everything works! :100: 

![Screenshot from 2025-01-13 23-54-27](https://github.com/user-attachments/assets/35fd7092-b816-4c84-a28f-2f733c92f1c3)
![Screenshot from 2025-01-13 23-58-23](https://github.com/user-attachments/assets/2d9fbd54-7fc7-49a1-aa85-10462052e010)
![Screenshot from 2025-01-13 23-58-32](https://github.com/user-attachments/assets/3f6a9365-ff10-48fc-be9f-8cd85156d18d)
![Screenshot from 2025-01-13 23-59-55](https://github.com/user-attachments/assets/c7dd4064-6526-4185-b47d-754efb1093a0)
![Screenshot from 2025-01-14 00-00-10](https://github.com/user-attachments/assets/ab0f039f-907e-498b-abb2-2758d1d9af8b)
![Screenshot from 2025-01-14 00-00-14](https://github.com/user-attachments/assets/faa29ba3-c370-44ae-818e-3a1f509b5373)
![Screenshot from 2025-01-14 00-00-24](https://github.com/user-attachments/assets/db4456c0-91e8-4a85-92d6-4458daa89a49)
![Screenshot from 2025-01-14 00-00-33](https://github.com/user-attachments/assets/a4855c38-7160-41fc-9344-599d36b3f4e4)
![Screenshot from 2025-01-14 00-00-43](https://github.com/user-attachments/assets/5a707363-2e1e-446e-8692-93d88644d825)

I do have all the required Posthog API keys locally, however the action did not show in my actions list, until I manually added the bypass for the feature flag

![Screenshot from 2025-01-13 23-55-54](https://github.com/user-attachments/assets/e62beb4e-6fc1-4b11-9025-46aa18d8788f)
![Screenshot from 2025-01-13 23-57-42](https://github.com/user-attachments/assets/80bcba03-6a96-414d-83fc-74539c836f53)
![Screenshot from 2025-01-13 23-56-23](https://github.com/user-attachments/assets/2cef06e3-5f2a-4f4f-878e-1bcc45a1d4ca)

2025-01-14 08:33 UTC, mmioana commented
@rdig I have checked the feature flags config and it **should** be working

This is the response from PostHog for a request I have just made
![Screenshot 2025-01-14 at 09 25 28](https://github.com/user-attachments/assets/6ca9599e-c5e9-45b7-b21f-8205e904098e)

And I have just checked the `Usage` tab for this feature in PostHog and I haven't seen any issues - there might not yet be data available from `last 24 hours`
![Screenshot 2025-01-14 at 09 32 50](https://github.com/user-attachments/assets/85b9e9e1-08fb-4e75-9f16-55a72437db44)

Anyway let's debug it together

2025-01-14 17:08 UTC, iamsamgibbs approved these changes
Nice job! I've found a few issues, but still approving this as I think it makes more sense to get this merged and fix up issues afterwards unless you disagree.

The main issue I encountered is that the action table will show that the action was created successfully:

![Screenshot 2025-01-14 at 16 53 42](https://github.com/user-attachments/assets/8a5c763e-91c5-400d-94d1-5cde92d6999c)

But the transactions list shows that the "Add chain support" transaction failed. I'm guessing this is an issue with the transactions list rather than the transaction actually failing:

![Screenshot 2025-01-14 at 16 54 07](https://github.com/user-attachments/assets/a753b071-f347-4d73-9f26-35db2358906e)

Removing doesn't have this issue (seeing as it calls edit colony instead) but if it's possible to rename this transaction here to make it clearer that would be better (although I think Manage Verified Members, Manage Tokens, etc probably also show Edit Colony)

![Screenshot 2025-01-14 at 16 54 37](https://github.com/user-attachments/assets/42a4005b-87e5-4ed4-8399-b520f1f1141a)

There is also this issue if you select a chain before selecting add / remove then it gets wiped even if it is a valid option.

https://github.com/user-attachments/assets/7a400fb4-661b-4f54-a689-d4361b534300

Also just noting that notifications still need to be handled:

![Screenshot 2025-01-14 at 16 53 51](https://github.com/user-attachments/assets/132777e1-9cf2-4504-967d-cc9ba183b4ce)

Otherwise this is all great and clearly a lot has been added here so great job!

2025-01-15 07:35 UTC, mmioana commented
Thanks @iamsamgibbs for your review 🙌 I will add your findings into a separate issue ✨

2025-01-15 07:36 UTC, merged