feat: add invite modal
JoinColony/colonyCDapp pull request #4009
Opened 2024-12-27 11:07 UTC by CzarekDryl

## Description

- [] TODO write description

## Testing

TODO: High level overview of what reviewers are testing with your pr. 

TODO: Followed by step-by-step instructions for testing your branch so reviewers can easily jump straight in and start testing. 

* Step 1. E.g. add reputation
* Step 2. E.g. install Governance extension
* Step 3. E.g. Create motion

## Diffs

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2024-12-31 12:41 UTC, arrenv requested changes
@CzarekDryl Nice work, thank you for the PR, working as expected. Just a couple of points of feedback.

1. Can we have the hover state consistent with the other header buttons with the blue border:
![image](https://github.com/user-attachments/assets/50a2eb89-6ade-4a3a-ac1b-7372bc3c7e60)

![image](https://github.com/user-attachments/assets/0578d6a9-5557-4a4f-b684-d2f838b9f33b)

2. The "Up to 100 people can join" is hard coded, can the number `100` be dynamic based on the actual invites available.

2024-12-31 12:41 UTC, arrenv commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
> +      'Up to 100 people can join to follow and be apart of this colony during early access. If you exceed the limit, you can request more.',
Can the 100 be dynamic based on actual limit returned from DB.

2024-12-31 12:41 UTC, arrenv commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
> +              to={`https://colony.io/request-member-invites?colony=${colonyName}`}
Can this be added to the const file with all other URLs so that it can easily be updated.

2025-01-07 07:58 UTC, CzarekDryl commented
@arrenv All the things have been fixed and are it's ready for review again

2025-01-07 11:32 UTC, mmioana requested changes
Hey @CzarekDryl really nice start on this issue 💯 

The modal is working as expected

https://github.com/user-attachments/assets/5113f0f5-155f-4fa8-bf56-b684150e6332

![Screenshot 2025-01-07 at 12 24 10](https://github.com/user-attachments/assets/09eb8c18-f4f5-4d8f-b44e-cf5757c84fb6)

However I left some refactoring comments and found a couple of misalignments with `Figma` if you could please be so kind to tackle them 🙌

2025-01-07 11:32 UTC, mmioana commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
> +  const isOutOfInvites = invitesUsed >= invitesAvailable;
I think we could make use of the `const { totalMemberCount } = useMemberContext();` here to compute how many invites are used and `colonyMemberInvite?.invitesRemaining` for deciding how many invites are available, thus replacing lines `74-79` with
```
  const inviteLink = useBaseUrl(
    `/invite/${colonyName}/${colonyMemberInvite?.id}`,
  );
  const { totalMemberCount } = useMemberContext();
  const invitesAvailable = colonyMemberInvite?.invitesRemaining || 0;
  const invitesUsed = totalMemberCount;
  const isOutOfInvites = invitesUsed >= invitesAvailable;
```

2025-01-07 11:32 UTC, mmioana commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
Actually let's please refactor this component a bit, given we have lots of conditional content based on the `isOutOfInvites` flag

So my proposal would be the following

```
const InviteMembersModal = ({ isOpen, onClose }: Props) => {
  const {
    colony: { colonyMemberInvite, name: colonyName },
  } = useColonyContext();
  const inviteLink = useBaseUrl(
    `/invite/${colonyName}/${colonyMemberInvite?.id}`,
  );
  const { totalMemberCount } = useMemberContext();
  const invitesAvailable = colonyMemberInvite?.invitesRemaining || 0;
  const invitesUsed = totalMemberCount;
  const isOutOfInvites = invitesUsed >= invitesAvailable;

  const { handleClipboardCopy, isCopied } = useCopyToClipboard();

  const commonClassName = 'rounded-lg p-2 text-sm font-medium';

  const getModalSubtitle = () => {
    if (isOutOfInvites) {
      <FormattedMessage
        {...MSG.modalDescriptionReached}
        values={{ invitesAvailable }}
      />;
    }

    return (
      <FormattedMessage
        {...MSG.modalDescription}
        values={{ invitesAvailable }}
      />
    );
  };

  const getModalContent = () => {
    if (isOutOfInvites) {
      return (
        <CardWithCallout
          title={
            <span
              className={clsx(
                commonClassName,
                'bg-negative-100 text-negative-400',
              )}
            >
              <FormattedMessage
                {...MSG.invitesUsed}
                values={{ invitesAvailable }}
              />
            </span>
          }
          subtitle={<FormattedMessage {...MSG.limitReached} />}
          button={
            <Link
              to={getRequestInvitesLink(colonyName)}
              target="_blank"
              className="flex min-h-8.5 items-center justify-center gap-2 whitespace-nowrap 
              rounded-lg border border-gray-900 bg-base-white px-2.5 py-1.5 text-sm font-medium text-gray-900 
              transition-all duration-normal disabled:border-gray-300 disabled:text-gray-300 md:hover:border-gray-900 
              md:hover:bg-gray-900 md:hover:!text-base-white"
            >
              {formatText(MSG.requestInvites)}
            </Link>
          }
        >
          <FormattedMessage {...MSG.requestMoreInvites} />
        </CardWithCallout>
      );
    }

    return (
      <CardWithCallout
        title={
          <span className={clsx(commonClassName, 'bg-blue-100 text-blue-400')}>
            <FormattedMessage
              {...MSG.invitesUsed}
              values={{ invitesAvailable }}
            />
          </span>
        }
        subtitle={<FormattedMessage {...MSG.inviteLinkHeading} />}
        button={
          <Button
            text={MSG.buttonText}
            mode={isCopied ? 'completed' : 'quinary'}
            icon={isCopied ? undefined : CopySimple}
            onClick={() => handleClipboardCopy(inviteLink)}
            size="small"
            textValues={{ isCopied }}
          />
        }
      >
        {inviteLink}
      </CardWithCallout>
    );
  };

  return (
    <Modal isOpen={isOpen} onClose={() => onClose()}>
      <div className="mb-8 mt-10 flex flex-col items-center">
        <SmileySticker size={42} className="mb-3" />
        <Heading3
          appearance={{ theme: 'dark' }}
          className="font-semibold text-gray-900"
          text={MSG.modalTitle}
        />
        <p className="mt-1 text-center text-sm text-gray-600">
          {getModalSubtitle()}
        </p>
      </div>
      {getModalContent()}
    </Modal>
  );
};
```

Of course, bonus points if you feel like splitting the code up into partial components 💯

2025-01-07 11:37 UTC, mmioana commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
> +  const isOutOfInvites = invitesUsed >= invitesAvailable;
@arrenv do we want to hardcode the invites limit to `100`?
I think it would be best to actually use the stored remaining invites, as well as the number of existing followers and decide based on that if we are or are not out of invites

2025-01-07 12:19 UTC, arrenv commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
> +  const isOutOfInvites = invitesUsed >= invitesAvailable;
@CzarekDryl no, I was not aware this was hardcoded, this is a value that can be increased in the database. As a result of this and to minimise impact on the database, we updated the design last week to remove the need to show the upper limit and just show the remaining available.

2025-01-18 15:02 UTC, CzarekDryl commented
@mmioana Fixed :)

2025-01-20 10:18 UTC, arrenv approved these changes
@CzarekDryl Thank you for the updates, looks to be working well!


### Modal working well

![image](https://github.com/user-attachments/assets/083e2875-f2bb-4dea-a425-e83d48f4673a)


### Hover state updated

![image](https://github.com/user-attachments/assets/a0a2fd79-e359-4d01-867a-9f86ea04f39a)


### Invite works

![image](https://github.com/user-attachments/assets/c2339ce7-e84a-4ecf-a770-e904d358a5fa)


### Count updates

![image](https://github.com/user-attachments/assets/5051fd89-ac1e-4555-9d75-13347cb61ddd)


### No invites remaining

![image](https://github.com/user-attachments/assets/23113f7f-7fb6-4fb0-978e-72a63188a118)

Goes to the correct link and populates the form:

![image](https://github.com/user-attachments/assets/3c457da6-5468-4a7d-bf52-36df9998a81b)

2025-01-20 10:40 UTC, mmioana requested changes
Hey @CzarekDryl really nice work, now it behaves properly 🙌 

With `100` invites available
![Screenshot 2025-01-20 at 11 31 16](https://github.com/user-attachments/assets/2eae22e2-bac5-4094-9286-3b015eb13790)
With `12` invites available
![Screenshot 2025-01-20 at 11 32 45](https://github.com/user-attachments/assets/09155c66-0aa8-47b5-afa6-3b10b928cfa1)
With no invites available
![Screenshot 2025-01-20 at 11 33 06](https://github.com/user-attachments/assets/f76dcca0-61f4-4a96-b2c4-5ad7c89b4db4)
Got redirected to the proper page when requesting more invites
![Screenshot 2025-01-20 at 11 33 13](https://github.com/user-attachments/assets/a97396a5-3ec0-4a41-96d6-4dec50f34a06)
The copy-link functionality works as expected
![Screenshot 2025-01-20 at 11 33 35](https://github.com/user-attachments/assets/6d98dc76-130a-49d0-a275-2b25973659ae)

However @CzarekDryl I did find some mismatches according to `Figma` for the `mobile` version
1. The copy link action is on a new line
![Screenshot 2025-01-20 at 11 34 27](https://github.com/user-attachments/assets/1d1f67f1-5f81-4aea-84aa-608eb398ef28)
While in `Figma`
![Screenshot 2025-01-20 at 11 34 41](https://github.com/user-attachments/assets/9cc95f32-5927-4b14-b4c5-adc0e2bc2bf3)
2. Same for `Request invites`
![Screenshot 2025-01-20 at 11 35 09](https://github.com/user-attachments/assets/d0209b79-0635-4475-bcd7-09532e48098e)
While in `Figma`
![Screenshot 2025-01-20 at 11 35 19](https://github.com/user-attachments/assets/450fec93-bfa6-4418-8bc4-e8b987b2eef9)
3. The invite button is fully rounded
![Screenshot 2025-01-20 at 11 36 06](https://github.com/user-attachments/assets/5f817a68-1683-4304-a1f0-2df594c85556)
While in `Figma` there is some horizontal padding
![Screenshot 2025-01-20 at 11 36 12](https://github.com/user-attachments/assets/ea8dd910-8e02-41c4-a9ed-002453853ee2)

After these issues are fixed, we're good to go 🎉

2025-01-20 13:29 UTC, CzarekDryl commented
@mmioana 

Button unified with others so it's 46px width now:
<img width="412" alt="image" src="https://github.com/user-attachments/assets/7a7dfd65-115a-4b12-83b9-1095e0caab57" />

Moved button to the side of texts in both cases:
<img width="407" alt="image" src="https://github.com/user-attachments/assets/29a0fbff-df63-4832-ad7a-52edb5383746" />

2025-01-20 21:14 UTC, mmioana submitted a review, later dismissed
Nice work @CzarekDryl 🥇 

Everything looks good also on `mobile` now 💯 
![Screenshot 2025-01-20 at 22 09 15](https://github.com/user-attachments/assets/1d78cf27-0c78-447b-b648-0f47cef05241)
![Screenshot 2025-01-20 at 22 10 17](https://github.com/user-attachments/assets/78aba20a-85be-45e1-9921-5b7ba4a80aa1)
![Screenshot 2025-01-20 at 22 12 25](https://github.com/user-attachments/assets/735d4149-ee68-458b-ab64-dc6ae80d0d6f)

2025-01-21 17:36 UTC, rumzledz requested changes
Great start on this PR @CzarekDryl ! I left bits and bobs on your PR about areas of improvement. Give me a shout when you want me to re-test this PR! 👌

2025-01-21 17:36 UTC, rumzledz commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
> +      'You can invite {invitesAvailable} more people to join and follow this colony during early access. If you run out, you will be able to request more.',
Checking with @JoinColony/product  if you want "person" to be "person" if there's only 1 invite available

2025-01-21 17:36 UTC, rumzledz commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
> +      '{invitesAvailable} {invitesAvailable, plural, one {invite} other {invites}} remaining',
✨

2025-01-21 17:36 UTC, rumzledz commented on src/components/v5/common/Modals/InviteMembersModal/partials/ModalContent.tsx
> +      'You can invite {invitesAvailable} more people to join and follow this colony during early access. If you run out, you will be able to request more.',
Same question about "people" pluralisation here @JoinColony/product

2025-01-21 17:36 UTC, rumzledz commented on src/components/v5/common/Modals/InviteMembersModal/partials/ModalContent.tsx
> +      other {Copy link}
Noice ✨

2025-01-21 17:36 UTC, rumzledz commented on src/components/v5/common/Modals/InviteMembersModal/partials/ModalContent.tsx
> +  const commonClassName = 'rounded-lg p-2 text-sm font-medium';
You can write this outside the component since it's just a constant, so it's not part of the re-render cycle

2025-01-21 17:36 UTC, rumzledz commented on src/components/common/Extensions/UserNavigation/UserNavigation.tsx
> +      {!isActionSidebarOpen && isWalletConnected && user && isInColony ? (
I see that this `isInColony` boolean is prop drilled at least 3 levels deep. I think it's better if you just use the context within this component:

```js
const colonyContext = useColonyContext({ nullableContext: true });

const isInColony = !!colonyContext;

...

{!isActionSidebarOpen && isWalletConnected && user && isInColony ? (
```

2025-01-21 17:36 UTC, rumzledz commented on src/components/common/Extensions/UserNavigation/UserNavigation.tsx
> +          className="gap-1 px-[0.875rem] sm:px-2.5 md:hover:!border-blue-400"
I think it's cleaner if you just do `px-3.5`

2025-01-22 16:57 UTC, CzarekDryl commented
@rumzledz Thanks for checking, I've made changes with description pluralisation - for better UX. Please check it again :)

2025-01-23 09:53 UTC, mmioana requested changes
Hey @CzarekDryl thanks for your latest changes. It all looks good 💯 

![Screenshot 2025-01-23 at 10 45 44](https://github.com/user-attachments/assets/50a8dec2-4b4d-4943-8014-89492b2c29eb)
![Screenshot 2025-01-23 at 10 46 04](https://github.com/user-attachments/assets/f2ddfb7d-5cb6-45fa-a3a4-0d55ab3478b0)
![Screenshot 2025-01-23 at 10 53 28](https://github.com/user-attachments/assets/df536a97-6420-4d94-8b2e-f08aa67390fb)

However, after @rumzledz pointed out the messages pluralisation, realised we have unused translations in both `ModalContent` and `InviteMembersModal`. I left a few comments about what needs to be removed. Once this is done, I'll be more than happy to approve your PR 🙌  Thanks for your hard and continuous work on this issue! ✨

2025-01-23 09:53 UTC, mmioana commented on src/components/v5/common/Modals/InviteMembersModal/partials/ModalContent.tsx
> +  },
Please remove these unused translations

2025-01-23 09:53 UTC, mmioana commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
> +    defaultMessage: 'Request more invites for your colony',
Please remove these unused descriptions

2025-01-23 09:53 UTC, mmioana commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
>    buttonText: {
Also this one

2025-01-23 18:48 UTC, CzarekDryl commented
@mmioana Unused messages removed

2025-01-23 19:30 UTC, mmioana submitted a review, later dismissed
Thanks a lot @CzarekDryl for all your work! Good to go from my side! 🎉

2025-01-24 15:35 UTC, bassgeta requested changes
Nice job, code looks good and everything works :sunglasses: 
1. The header button shows up to logged in users :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/12dcdd08-d7cb-483a-afc9-3549c361f5e1)
![image](https://github.com/user-attachments/assets/fb5928a9-e933-4fe0-8435-f4131e6029fc)
2. The modal shows up and looks like expected :heavy_check_mark: 
![image](https://github.com/user-attachments/assets/d5b8d4fc-d3cb-45ce-bb1d-5e6fdaee75f3)
![image](https://github.com/user-attachments/assets/72aa50f0-80d5-4402-af24-1f41f6418148)
3. THe only issue is that when we have 0 invites remaining, the if condition doesn't work :/
![image](https://github.com/user-attachments/assets/8e5bdc6e-2512-4153-b289-a838a7d0e0a4)

2025-01-24 15:35 UTC, bassgeta commented on src/components/v5/common/Modals/InviteMembersModal/InviteMemberModal.tsx
> +      <FormattedMessage
dropped a `return` here, we have a tiny bug because of it :eyes:

2025-01-27 15:06 UTC, arrenv approved these changes
Thank you @CzarekDryl everything still looks to be working well. After fixing the bug @bassgeta raised, let's get it merged.

![image](https://github.com/user-attachments/assets/5477cb67-7c57-40fb-8add-108d7ac93085)

![image](https://github.com/user-attachments/assets/8a4b0c44-9d4f-472a-897a-f70cff3a620d)

![image](https://github.com/user-attachments/assets/a08a09a1-7b45-484e-9c5a-354693d6b9d6)

![image](https://github.com/user-attachments/assets/9294ee21-0fc4-4b4c-b3dc-0c841004792c)

2025-01-28 12:59 UTC, rumzledz approved these changes
Thanks for the making the changes @CzarekDryl ! All good on my side 😄

2025-01-31 09:25 UTC, arrenv requested changes
Fix still required as of @bassgeta's comment.

2025-02-06 08:32 UTC, mmioana commented
@adam-strzelec can you please fix the bug @bassgeta mentioned?

2025-02-12 09:19 UTC, arrenv approved these changes
Thank you @adam-strzelec, all looks good now!

2025-02-18 12:29 UTC, adam-strzelec commented
@mmioana @rumzledz @bassgeta done 🙂

2025-03-17 10:47 UTC, merged