feat: add back button to action sidebar
JoinColony/colonyCDapp pull request #4016
Opened 2024-12-30 14:32 UTC by CzarekDryl

## Description

- Added back button to action sidebar

<img width="742" alt="image" src="https://github.com/user-attachments/assets/f4422bff-7e1b-4062-9126-af99e6ec4d58" />

## Testing

1. Back Arrow:

- Appears only after an action is selected.
- Navigates to the relevant action list view category.
- Not visible on the main action list view.

2. Completed Actions:
- Navigates to the relevant list view category.

3. Browser Back Button:
- Returns to the previous action transaction if clicked after navigating away.

4. Hover State:
- On desktop, matches other action header icons and uses the blue-400 color.

(Resolves | Contributes to) #31415

2024-12-31 11:58 UTC, arrenv requested changes
@CzarekDryl Nice work, it works great.

The only thing not working as expected is the browser back button requires two clicks before the sidepanel opens up.

**All back arrow buttons working as of spec:**

![working-back-button](https://github.com/user-attachments/assets/60e47741-a59e-4d5d-a233-8fbde118c10c)

2025-01-03 10:57 UTC, CzarekDryl commented
@arrenv Browser back button is working fine now

https://github.com/user-attachments/assets/4a0a2566-f7c1-443b-9bc5-d76b55a93dc6

2025-01-07 12:54 UTC, mmioana requested changes
Hey @CzarekDryl nice start on this issue 💯 

The back navigation on the action sidebar seems to be working as expected


https://github.com/user-attachments/assets/43024676-7098-45f5-887c-06642012a4f7

However, I did leave some refactoring comments if you could be so kind to tackle them 🥇

2025-01-07 12:54 UTC, mmioana commented on src/components/v5/common/ActionSidebar/ActionSidebar.tsx
> +            )}
Seems the `ActionSidebar` is increasing more and more, so let's clean this up a bit.

Let's create a partial component - for eg. `GoBackButton`

```
import { ArrowLeft } from '@phosphor-icons/react';
import React, { type FC } from 'react';

import { useActionSidebarContext } from '~context/ActionSidebarContext/ActionSidebarContext.ts';
import { type ColonyAction } from '~types/graphql.ts';

import { ACTION_TYPE_FIELD_NAME } from '../consts.ts';
import { getActionGroup, mapActionTypeToAction } from '../utils.ts';

interface GoBackButtonProps {
  action?: ColonyAction | null;
  onClick?: () => void;
}

export const GoBackButton: FC<GoBackButtonProps> = ({ action, onClick }) => {
  const { actionSidebarToggle, actionSidebarInitialValues } =
    useActionSidebarContext();
  const { toggleOn: toggleActionSidebarOn } = actionSidebarToggle[1];
  const actionType = mapActionTypeToAction(action);
  const actionGroupType = getActionGroup(
    actionSidebarInitialValues?.[ACTION_TYPE_FIELD_NAME] || actionType,
  );

  const openGroupedAction = () => {
    toggleActionSidebarOn({
      [ACTION_TYPE_FIELD_NAME]: actionGroupType,
    });
  };

  if (!actionGroupType) {
    return null;
  }

  return (
    <button
      type="button"
      className="flex items-center justify-center py-2.5 text-gray-400 transition sm:hover:text-blue-400"
      onClick={() => {
        if (onClick) {
          onClick();

          setTimeout(openGroupedAction, 500);

          return;
        }

        openGroupedAction();
      }}
    >
      <ArrowLeft size={18} />
    </button>
  );
};

```

and then use it here as 
```
           <GoBackButton
              action={action}
              onClick={transactionId ? closeSidebarClick : undefined}
            />
```

2025-01-07 12:54 UTC, mmioana commented on src/components/common/ColonyActionsTable/hooks/useGetMenuProps.tsx
> -              },
Are we sure this doesn't have any unintended side-effects?

2025-01-15 15:37 UTC, CzarekDryl commented on src/components/common/ColonyActionsTable/hooks/useGetMenuProps.tsx
> -              },
At the moment, after testing, I haven't noticed anything wrong

2025-01-16 18:31 UTC, mmioana approved these changes
Thanks for implementing my suggestions @CzarekDryl 🙌 

The back button for the action sidebar works very nice 🥇 

https://github.com/user-attachments/assets/c1adf8dc-8253-4615-b078-a254880065d2

I did notice an issue with the browser back navigation. If you select a completed action, use the browser back navigation, an empty action sidebar is shown. However, this issue is also present on `master` and is unrelated with your changes, so I'll create a separate issue 👍

https://github.com/user-attachments/assets/c35a1908-e8cc-42d0-af11-dac5bb51731a

2025-01-17 15:34 UTC, arrenv approved these changes
@CzarekDryl Thank you, nice addition, approving!

2025-01-18 15:00 UTC, merged