Clean up Colony Home
JoinColony/colonyCDapp pull request #56
Opened 2022-11-01 14:51 UTC by jakubcolony

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2022-11-01 17:56 UTC, jakubcolony commented
I created additional issues which are related to this ticket but currently blocked by something else: #57, #58, #59 and #60.

2022-11-02 10:28 UTC, rdig reviewed
Am I doing something wrong?

When I try to run this, webpack is missing to styles files

![Screenshot from 2022-11-02 12-26-43](https://user-images.githubusercontent.com/1193222/199466544-7e30aa91-88bb-427b-891f-2860a408f12a.png)

Were they moved? Or not commited ?

2022-11-02 12:12 UTC, jakubcolony commented
>Am I doing something wrong?

Nope, that's on me. Should be fixed now

2022-11-02 17:08 UTC, rdig requested changes
Mostly what I expected, but there's still some ts errors / leftover imports that need to be addressed

2022-11-02 17:08 UTC, rdig commented on src/components/common/NewActionButton/NewActionButton.tsx
> +const NewActionButton = ({ colony, ethDomainId }: Props) => {
colony / ethdomain are not being used, please either comment them out or make sure they are used

2022-11-03 13:28 UTC, rdig approved these changes
Looks serviceable for now, but we did end up with a lot of commented out code.

I guess we'll fix it when get to each individual component.

2022-11-03 13:28 UTC, rdig commented on src/components/common/ColonyHome/ColonyFundingWidget/TokenItem.tsx
> +const displayName = 'common.ColonyHome.ColonyFundingWidget.TokenItem';
This is not something you did here, it's just something I ran into so I'm leaving it for future reference.

We have two files named `TokenItem`. This one, and another one in `shared/TokenEditDialog/TokenItem`

We should rename one of them to keep things less confusing

2022-11-04 18:54 UTC, rdig approved these changes
All good from my end! :tada:

2022-11-06 01:01 UTC, Julianahlk approved these changes
LGMT 👍

2022-11-06 15:26 UTC, danbr approved these changes
LGTM well done.

2022-11-07 07:40 UTC, chinins approved these changes
Very good - I like the renaming part :)

2022-11-07 10:00 UTC, merged