Add `useUserByNameOrAddress` hook
JoinColony/colonyCDapp pull request #577
Opened 2023-05-22 23:04 UTC by Julianahlk

## Description

* Adds userUserByNameOrAddress hook that only makes one query depending if the input is a username or an address

## Testing

Make sure a user can be loaded by both username or address in the route:

`/user/0x9dF24e73f40b2a911Eb254A8825103723E13209C`
`/user/a`

Resolves #512

2023-05-23 13:18 UTC, ArmandoGraterol commented on src/hooks/useUserByNameOrAddress.ts
> +const useUserByNameOrAddress = (username: string) => {
Same here

2023-05-23 13:20 UTC, ArmandoGraterol commented on src/components/common/UserProfile/UserProfile.tsx
> +  const { user, loading, error } = useUserByNameOrAddress(username || '');
I would also change the name of this param to something more general as with this PR now this could not be just a username.

2023-05-23 20:32 UTC, jakubcolony requested changes
Nice work but I think we can avoid all the overheads of calling the queries "manually" by using the generated hooks with `skip` option

```ts
const isAddress = isAddress(username);
const { } = useUserByAddressQuery({
  skip: !isAddress,
});
const { } = useUserByNameQuery({
  skip: isAddress,
});
```

2023-06-14 17:18 UTC, Julianahlk commented
> Nice work but I think we can avoid all the overheads of calling the queries "manually" by using the generated hooks with `skip` option

@jakubcolony Thanks for the suggestion, updated.

2023-06-14 21:24 UTC, jakubcolony approved these changes
LGTM, thanks for making the changes 👍

2023-06-14 21:51 UTC, merged