Add remove safes dialog
JoinColony/colonyCDapp pull request #799
Opened 2023-07-12 11:24 UTC by alicjakujawa

Add RemoveSafeDialog to config

Add pink checkbox variant

Add hardcoded safes to dialog

Parse safe object when passing to Checkbox

Fix additional border on checkbox

## Description

- [] TODO write description

**New stuff** ✨

* New stuff goes here

**Changes** 🏗

* Changes go here

**Deletions** ⚰️

* Deletions go here

## TODO

- [ ] Add TODOs

(Resolves | Contributes to) #31415

2023-07-12 19:23 UTC, ArmandoGraterol requested changes
Good start! Overall looks good, we just need to address some small stuff and this should be good to go.

- When I get to the dialog, the submit button is already enabled. Also, it stays enabled if I select and then unselect safes. We should check if the form is dirty and has a value before we allow the user to submit it.
![FireShot Capture 120 - Colony CDapp - localhost](https://github.com/JoinColony/colonyCDapp/assets/18473896/1e8af3f4-8ffd-4388-a157-7ed5466192a9)

2023-07-12 19:23 UTC, ArmandoGraterol commented on src/components/common/Dialogs/RemoveSafeDialog/RemoveSafeDialog.tsx
> +import { ActionTypes } from '~redux/index';
You can shorten this import by removing the `index`

2023-07-12 19:23 UTC, ArmandoGraterol commented on src/components/common/Dialogs/RemoveSafeDialog/SafeListItem.tsx
> +    <div className={`${styles.main} ${isChecked && styles.checked}`}>
We could use the `classnames` library here and write this in a more readable way:
```
classnames(styles.main, { [styles.checked]: isChecked })
```

2023-07-12 19:23 UTC, ArmandoGraterol commented on src/components/common/Dialogs/RemoveSafeDialog/SafeListItem.tsx
> +      <span className={`${isChecked ? styles.selectedLabel : styles.label}`}>
Same here

2023-07-12 19:23 UTC, ArmandoGraterol commented on src/components/common/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.tsx
> +import DialogSection from '~shared/Dialog/DialogSection';
You can also export this section like this `import { DialogSection } from '~shared/Dialog';`, that way we avoid repeating the `DialogSection` at the end of the import route

2023-07-12 19:23 UTC, ArmandoGraterol commented on src/components/common/Dialogs/RemoveSafeDialog/RemoveSafeDialog.tsx
> +    }),
Normally we extract this function that gets the payload for readability's sake. You can check out the other action dialogs for an example

2023-07-12 19:23 UTC, ArmandoGraterol commented on src/components/common/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.tsx
> +                        ,
I'm getting lint errors from this snippet of code

2023-07-13 22:29 UTC, ArmandoGraterol approved these changes
Looks good to me! Nice job Alicja 💯

2023-07-14 09:43 UTC, thomassdk approved these changes
Works well for me too, nice work Alicija

2023-07-14 09:45 UTC, merged